### ISSUE TITLE
Possibility of adding Basic Authentication?

### ISSUE THREAD

**Issue by nprovencher** [domaindrivendev/Swashbuckle#10]
Is there any way of adding basic authentication header beside modifying index.html from swagger-ui directly?

**Comment by mgibas** [comment]
@domaindrivendev is there any chance that you will paste here js file that you've mentioned above ?
I have exactly same scenario.

**Comment by milanmalkani** [comment]
Check this out. Works great. http://stevemichelotti.com/customize-authentication-header-in-swaggerui-using-swashbuckle/
