### ISSUE TITLE
Does Swashbuckle support OData?

### ISSUE THREAD

**Issue by xhhha** [domaindrivendev/Swashbuckle#101]
I created a WebAPI with Odata, then installed Swashbuckle. I attempt to run this application but got nothing with odatacontroller name.

So does that mean Swashbuckle doesn't support Odata?

If this doesn't support, which tools will support the odata auto documentations?

Thanks.

**Comment by rbeauchamp** [comment]
Borrowing code from [Microsoft.AspNet.OData](https://github.com/OData/WebApi), I have added support for OData v4.0. I created a custom ISwaggerProvider that converts an IEdmModel to a SwaggerDocument. Try out [Swashbuckle.OData](https://github.com/rbeauchamp/Swashbuckle.OData) and let me know what you think.

**Comment by satishsomani** [comment]
@rbeauchamp  can you please share sample code as I see sample code on multiple places but not able to make it work. As I'm using **odata with asp.net core 2.1** the error which I'm getting "customProvider". can you please help me on this.
