### ISSUE TITLE
Swashbuckle own Index.page not rendering properly no javascript no css  .Net Mvc Web Api

### ISSUE THREAD

**Issue by MurtuzaTravadi** [domaindrivendev/Swashbuckle#1011]
i making my own index page in swashbuckle in .net mvc web api. i  copied source code from this link

https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html

and when i run this web api i get this output

![image](https://cloud.githubusercontent.com/assets/22894409/23113288/2970cc16-f75d-11e6-9bc6-6b04e977e8fb.png)

i am using Swashbuckle.Core  1.0.0.0  
Run-time version v4.0.30319

Please help me out 
@fffej @skoon @AnneTheAgile @kvarv @svickers @urig @domaindrivendev  @ManuelRauber @estiller 

i more thing do i  have put static CSS and JS file?

**Comment by aaronralls** [comment]
Are you asking where are the CSS and JS files for the original or where do you put your custom files to go with your custom index page?

**Comment by MurtuzaTravadi** [comment]
thank you so much for replaying @aaronralls  as you can see in screen shot default css and java script is not rendering properly on custom index page load event.  i have set in Route.config file that first load swagger page i have used custom index page from this url

https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html

and i injected in swagger.config file like this

c.CustomAsset("index", thisAssembly, "YourWebApiProject.SwaggerExtensions.index.html");

but its not render properly.
