### ISSUE TITLE
how we can change tab bar image in swashbuckle?

### ISSUE THREAD

**Issue by MurtuzaTravadi** [domaindrivendev/Swashbuckle#1016]
I have try this in custom index page But its not working.
`<link rel="shortcut icon" href="icon" />`
is there any solution 
plz let me know as soon as possible 

@fffej @skoon @AnneTheAgile @kvarv @svickers @DavidDeSloovere @domaindrivendev 

@gliljas @smichtch @mharen

**Comment by DavidDeSloovere** [comment]
Did you put a favicon.ico in the root of the site?

**Comment by heldersepu** [comment]
Yes you could include your own custom CSS that transforms the UI to your liking 
see InjectStylesheet in the file ...\app_start\swaggerconfig.cs

**Comment by heldersepu** [comment]
Here is an example using InjectStylesheet:
https://github.com/heldersepu/csharp-proj/commit/0029dbfb26588de077002db320108b9346016ccd#diff-c7fc1ace1fc5e348dc9d61c1e701471d

And here is how the UI looks like now:
http://swashbuckletest.azurewebsites.net/swagger/ui/index

**Comment by MurtuzaTravadi** [comment]
Thank you so much  for replaying back  i ll check let you know..in case i have query @DavidDeSloovere  & @heldersepu

**Comment by heldersepu** [comment]
Please close this issue...
You can contact me directly if you need help
