### ISSUE TITLE
How to set paramType and required for a parameter?

### ISSUE THREAD

**Issue by PeterZong** [domaindrivendev/Swashbuckle#102]
We can use [FromUri] and [FromBody] to indicates if the paramType is Path or Body. Actually Swagger supports 5 paramType: "path", "query", "body", "header", "form". I know we can use IOperationFilter to change the paramType dynamically. But I am wondering if there is any better solutions - E.g.:
/// <param name="id" paramType="path" required="false">

Same, how can we set if the parameter is required or optional?

Thanks.

**Comment by Stefan-Z-Camilleri** [comment]
Do note that this does not work currently, at least with dotnet core

Having a parameter like so:
![screen shot 2017-08-16 at 13 41 20](https://user-images.githubusercontent.com/20099218/29361595-a0fa1f88-8288-11e7-9b31-209323a9bf09.png)

Results in the following:
![screen shot 2017-08-16 at 13 43 57](https://user-images.githubusercontent.com/20099218/29361688-020e745e-8289-11e7-8c12-6f4a18804a5e.png)

i.e. AspNet parses it correctly... but Swashbuckle on the other hand...
![screen shot 2017-08-16 at 13 45 24](https://user-images.githubusercontent.com/20099218/29361731-317edc7e-8289-11e7-927b-1b9a5cdd3bb3.png)

This can be patched of course using an `IOperationFilter`... yet it would be nice if it were fixed.

**Comment by heldersepu** [comment]
@Stefan-Z-Camilleri what you are reporting is not related to this issue, it is actually a duplicate of #1161 ...

Ant that specific issue makes it all the way to the OpenAPI-Specification:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7

**Comment by Stefan-Z-Camilleri** [comment]
Thank you for the clarification @heldersepu 

In that case, this makes sense and I wouldn't fix it either.  A workaround is totally possible (and already done in my case) via an `IOperationFilter`, so nothing to do here.

**Comment by tomglenn** [comment]
Sorry to necro an old issue, but this is still the case in dot net core.
@Stefan-Z-Camilleri you mentioned it can be worked around with an `IOperationFilter`. Are you able to share how this can be done?

**Comment by Stefan-Z-Camilleri** [comment]
Hey @tomglenn ... sadly I have moved on to other pastures since this and no longer have access to this code... and in fact, am currently not even touching the .NET world.

That said, IIRC, I had used an `IOperationFilter` to intercept the call and modify the data before it actually gets to the rendering pipeline.

My suggestion for you is to create a basic `IOperationFilter`, register it and then place a breakpoint there to investigate what the object tree looks like at that point and modify it accordingly.

**Comment by tomglenn** [comment]
Hi @Stefan-Z-Camilleri, thanks for such a quick reply after all these years of the issue being closed!

I actually did just that and I'm posting the solution below for anyone else who may be experiencing the same issue in dot net core.

```
/// <summary>
/// Fixes issue with optional parameters not being generated correctly by Swashbuckle in .NET Core
/// </summary>
public class OptionalParameterOperationFilter : IOperationFilter
{
    /// <summary>
    /// Sets appropriate Required status of parameters
    /// </summary>
    /// <param name="operation">The Swagger operation</param>
    /// <param name="context">The Swagger operation context</param>
    public void Apply(Operation operation, OperationFilterContext context)
    {
        if (operation.Parameters == null)
        {
            return;
        }

        var parameters = context.ApiDescription.ParameterDescriptions;
        foreach (var parameter in parameters)
        {
            var param = operation.Parameters.FirstOrDefault(x => x.Name.ToLowerInvariant() == parameter.Name.ToLowerInvariant());
            if (param == null)
            {
                continue;
            }

            param.Required = parameter.ModelMetadata.IsRequired;
        }
    }
}
```
