### ISSUE TITLE
WebAPI 5.2.2

### ISSUE THREAD

**Issue by FabienDehopre** [domaindrivendev/Swashbuckle#104]
The install of the nuget package fails when using web api 5.2.2
Here is the error message:

```
Updating 'Microsoft.AspNet.WebApi.Core 5.2.2' to 'Microsoft.AspNet.WebApi.Core 4.0.20710.0' failed.
Unable to find versions of 'Microsoft.AspNet.WebApi.Owin, Thinktecture.IdentityModel.Owin.ResourceAuthorization.WebApi' that are compatible with 'Microsoft.AspNet.WebApi.Core 4.0.20710.0'.
```

**Comment by gabrielweyer** [comment]
I just had the same issue and I think this is due to the fact on how NuGet is working.

VS 2013 Update 4
NuGet 2.8.50926.663
Swashbuckle 5.0.4

This is what I typed in the _Package Manager Console_: `Install-Package Swashbuckle`

This is the output I got:

```
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.WebHost (≥ 4.0.20710)'.
Attempting to resolve dependency 'Microsoft.Web.Infrastructure (≥ 1.0.0.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Core (≥ 4.0.20710.0 && < 4.1)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Client (≥ 4.0.20710.0 && < 4.1)'.
Attempting to resolve dependency 'Microsoft.Net.Http (≥ 2.0.20710.0 && < 2.1)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 4.5.6)'.
Attempting to resolve dependency 'WebActivatorEx'.
Attempting to resolve dependency 'Swashbuckle.Core (≥ 5.0.4)'.
Installing 'Microsoft.Web.Infrastructure 1.0.0.0'.
Successfully installed 'Microsoft.Web.Infrastructure 1.0.0.0'.
Installing 'Microsoft.Net.Http 2.0.20710.0'.
You are downloading Microsoft.Net.Http from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/MVC_4_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.Net.Http 2.0.20710.0'.
Installing 'Microsoft.AspNet.WebApi.Client 4.0.20710.0'.
You are downloading Microsoft.AspNet.WebApi.Client from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/MVC_4_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.WebApi.Client 4.0.20710.0'.
Installing 'Microsoft.AspNet.WebApi.Core 4.0.20710.0'.
You are downloading Microsoft.AspNet.WebApi.Core from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/MVC_4_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.WebApi.Core 4.0.20710.0'.
Installing 'Microsoft.AspNet.WebApi.WebHost 4.0.20710.0'.
You are downloading Microsoft.AspNet.WebApi.WebHost from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/MVC_4_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.WebApi.WebHost 4.0.20710.0'.
Installing 'WebActivatorEx 2.0.6'.
Successfully installed 'WebActivatorEx 2.0.6'.
Installing 'Swashbuckle.Core 5.0.4'.
Successfully installed 'Swashbuckle.Core 5.0.4'.
Installing 'Swashbuckle 5.0.4'.
Successfully installed 'Swashbuckle 5.0.4'.
Install failed. Rolling back...
Install-Package : Updating 'Microsoft.AspNet.WebApi.Core 5.2.3' to 'Microsoft.AspNet.WebApi.Core 4.0.20710.0' failed. Unable to find a version of 'Microsoft.AspNet.WebApi.Owin' that is compatible with 'Microsoft.AspNet.WebApi.Core 4.0.20710.0'.
```

I did not have `Microsoft.AspNet.WebApi.WebHost` installed. As you can see from above NuGet tried to install the lowest version satisfying the requirements (4.0.20710) instead of the latest version (5.2.3).

This [version](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.WebHost/4.0.20710) explicitly states this as a dependency:

`Microsoft.AspNet.WebApi.Core (≥ 4.0.20710.0 && < 4.1)`

And this is where the upper limit is coming from.

Instead of hacking the project by hand you should install the required dependencies first:

```
Install-Package Microsoft.AspNet.WebApi.WebHost
Install-Package Microsoft.Web.Infrastructure
Install-Package Microsoft.Net.Http
```

This way you'll get the latest version of everything and when you'll issue the `Install-Package Swashbuckle` command again it'll work.

**Comment by ChristianWeyer** [comment]
Nice finding! From Weyer to Weyer ;)

**Comment by gabrielweyer** [comment]
Indeed quite an uncommon name :smile: 

I did a bit more digging and this is the way NuGet is supposed to work but if you're using NuGet 2.8 you can instruct NuGet to [get the highest version](http://docs.nuget.org/release-notes/nuget-2.8#-dependencyversion-switch):

`Install-Package Swashbuckle -DependencyVersion Highest`

If you want to do this when installing any packages in the current project you can use the [DependencyVersion Attribute](http://docs.nuget.org/release-notes/nuget-2.8#dependencyversion-attribute)

**Comment by malclear** [comment]
Thank you Gabriel Weyer. This solved my problem.

**Comment by vLGrok** [comment]
VS2015 new ASP.NET Web Application > Web API
PM> Install-Package Microsoft.AspNet.WebApi.WebHost
Package 'Microsoft.AspNet.WebApi.WebHost.5.2.3' already exists in project 'WebApp1'
PM> Install-Package Microsoft.Web.Infrastructure
Package 'Microsoft.Web.Infrastructure.1.0.0' already exists in project 'WebApp1'
PM> Install-Package Microsoft.Net.Http
... package installs successfully ... then ..
PM> Install-Package Swashbuckle
Attempting to gather dependencies information for package 'Swashbuckle.5.3.2' with respect to project 'WebApp1', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Swashbuckle.5.3.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Swashbuckle.5.3.2'
Resolved actions to install package 'Swashbuckle.5.3.2'
Install failed. Rolling back...
Package 'Swashbuckle.Core.5.3.2 : Microsoft.AspNet.WebApi.Core [4.0.20710, )' does not exist in project 'WebApp1'
Package 'Swashbuckle.Core.5.3.2 : Microsoft.AspNet.WebApi.Core [4.0.20710, )' does not exist in folder 'c:\src\local\WebApp1\packages'
Install-Package : An error occurred while downloading package 'Swashbuckle.Core.5.3.2 : Microsoft.AspNet.WebApi.Core [4.0.20710, )' from source 'https://www.nuget.org/api/v2/'.
At line:1 char:1
+ Install-Package Swashbuckle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM>
