### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by cryo75** [domaindrivendev/Swashbuckle#1041]
I'm getting the following exception when before everything was working fine:

`500 : {"ClassName":"System.MissingMethodException","Message":"Method not found: \"System.Func`2<System.String,System.String> Newtonsoft.Json.Serialization.JsonDictionaryContract.get_PropertyNameResolver()\".","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" bei Swashbuckle.Swagger.SchemaRegistry.<>c__DisplayClass18.<CreateDictionarySchema>b__14(String name)\r\n bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n bei Swashbuckle.Swagger.SchemaRegistry.CreateDictionarySchema(JsonDictionaryContract dictionaryContract)\r\n bei Swashbuckle.Swagger.SchemaRegistry.CreateInlineSchema(Type type)\r\n bei Swashbuckle.Swagger.SchemaRegistry.<CreateObjectSchema>b__1f(JsonProperty prop)\r\n bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n bei Swashbuckle.Swagger.SchemaRegistry.CreateObjectSchema(JsonObjectContract jsonContract)\r\n bei Swashbuckle.Swagger.SchemaRegistry.CreateDefinitionSchema(Type type)\r\n bei Swashbuckle.Swagger.SchemaRegistry.GetOrRegister(Type type)\r\n bei Swashbuckle.Swagger.Annotations.ApplySwaggerResponseAttributes.Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)\r\n bei Swashbuckle.Swagger.SwaggerGenerator.CreateOperation(ApiDescription apiDesc, SchemaRegistry schemaRegistry)\r\n bei Swashbuckle.Swagger.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)\r\n bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n bei Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)\r\n bei System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n bei AboServer.API.Config.SwaggerCachingProvider.GetSwagger(String rootUrl, String apiVersion)\r\n bei Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n bei System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n bei System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n bei System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n bei AboServer.API.Handlers.SessionHandler.<SendAsync>d__1.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\n<CreateDictionarySchema>b__14\nSwashbuckle.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cd1bb07a5ac7c7bc\nSwashbuckle.Swagger.SchemaRegistry+<>c__DisplayClass18\nSystem.String <CreateDictionarySchema>b__14(System.String)","HResult":-2146233069,"Source":"Swashbuckle.Core","WatsonBuckets":null,"MMClassName":null,"MMMemberName":null,"MMSignature":null} http://myserver:80/myapp/swagger/docs/v1`

**Comment by iHateCode** [comment]
Set Newtonsoft.Json package to version 9.0.1 and the error will go. Just a temp fix for now.

**Comment by metallserge** [comment]
also dealt with same issue after updating Newtonsoft to 10.x.x, since they removed Obsolete PropertyNameResolver
and also reverted Newtonsoft back for now

**Comment by tomasfalt** [comment]
I know that the focus is on the .Net core version of Swashbuckle but is there any possibility to correct this? It is really critical for me and probably for a lot of more people since I can't revert to version 9 of Newtonsoft.

**Comment by mehyaa** [comment]
I've added a pull request for fixing this issue: #1063

**Comment by tomasfalt** [comment]
Great! But I think it's #1062 I'm looking for. Is it possible to have a release of this?

**Comment by heldersepu** [comment]
Possible? sure it is!
When? that is the real question, seem that the pull request are piling up...
...And we have a call out for maintainers #1053

**Comment by eatfrog** [comment]
this is reaallly becoming more and more of a problem as time goes.. reverting to v9 is starting to look impossible here now.

**Comment by heldersepu** [comment]
@eatfrog 
Come on man, you know how it is...
We all have full time jobs, this is a hobby for us, no SLA or dedicated support team.
Until we can turn this project into something like: https://www.mashery.com/api/products and start getting thousands flowing in, I think development/release will be slow.

But if you want to contribute your time answer the call for maintainers: #1053

**Comment by lluismontero** [comment]
Hi!
Now that the fix have been merged, do you have any plan to release a new version? Obviously, an ETA would be great! Thanks for your good work!

**Comment by lakario** [comment]
Sorry for the +1 post, but really hoping this gets some visibility. We depend on Swashbuckle and this bug is causing major problems.

**Comment by heldersepu** [comment]
I'm working on my own fork that uses the latest and greatest, anyone intrested can get from:
https://www.myget.org/gallery/swashbuckle

And here is a demo:
http://swashbuckletest.azurewebsites.net/swagger

**Comment by domaindrivendev** [comment]
@lakario - if you hang tight I'll try push out a new release this evening

**Comment by domaindrivendev** [comment]
@heldersepu - any chance you could use a different name for your myget package? It's going to be confusing to have different packages with the same name. Plus it means you can publish yours to Nuget also.

**Comment by heldersepu** [comment]
@domaindrivendev 
Yes I've been thinking about renaming the package/project.
Will probably do it next week

**Comment by paul3291** [comment]
It would make things clearer..

**Comment by domaindrivendev** [comment]
@cryo75, @lakario - just pushed v5.6.0 to Nuget which should have the fix for this issue. Please check it out and let me know

**Comment by lakario** [comment]
@domaindrivendev Just tested 5.6.0, looks good. Thanks!
