### ISSUE TITLE
Enum value names

### ISSUE THREAD

**Issue by stuartbloom** [domaindrivendev/Swashbuckle#1068]
I have the following enum:

```
namespace WebApi.Logic.CustomPages.Dtos
{
    public enum CustomPageFieldType
    {
        Text = 1,
        Numeric,
        Date,
        Numeric_Function,
        Dropdown_List,
        Checkbox
    }
}
```
However, when a class includes this as a property it is shown as `type (integer, optional) = ['1', '2', '3', '4', '5', '6']integerEnum:1, 2, 3, 4, 5, 6,`, and when exported using NSwag as a Typescript enum it has the following definition:
```
export enum CustomPageFieldResponseDtoType {
    _1 = 1, 
    _2 = 2, 
    _3 = 3, 
    _4 = 4, 
    _5 = 5, 
    _6 = 6, 
}
```
How can i get it so that the enum is exported as:
```
export enum CustomPageFieldResponseDtoType {
    Text = 1, 
    Numeric = 2, 
    Date = 3, 
    Numeric_Function = 4, 
    Dropdown_List = 5, 
    Checkbox = 6, 
}
```

Thanks

**Comment by heldersepu** [comment]
This goes beyond a "class includes this as a property" ...
Here is a test controller I created:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#!/TestEnum/TestEnum_Get

That takes an enum as a parameter and returns it:
```c#
    public class TestEnumController : ApiController
    {
        public enum CustomEnum
        {
            Text = 1,
            Numeric = 2,
            Date = 4,
            Numeric_Function = 8,
            Dropdown_List = 16,
            Checkbox = 32
        }

        public CustomEnum Get(CustomEnum value)
        {
            return value;
        }
```

What I find interesting/weird is that the response changes when we change the Response Content Type, with JSON it give us the numeric value, but with XML it show the name.

**Comment by heldersepu** [comment]
@stuartbloom  maybe what you need is to enable:
```c.DescribeAllEnumsAsStrings();```
that is on the ...App_Start\SwaggerConfig.cs file.
Try it out and let me know.

**Comment by stuartbloom** [comment]
@heldersepu 
Thanks, I did try that, but then my enums are set as strings.  I was hoping to keep the values going between api and client as integers/numbers, but in my ts reference them as `MyEnum.Enumeration` rather than `MyEnum._0`

**Comment by heldersepu** [comment]
@stuartbloom
there is nothing wrong with enums set as strings is it?

**Comment by stuartbloom** [comment]
no, I guess not; i suppose it will make it easier for other consumers to make sense of what is going on :)  Thanks

**Comment by heldersepu** [comment]
I do see your point ...
and I think we are limited by the swagger definitions of enums:
http://swagger.io/docs/specification/enums/
there is no place for the actual value of the ```MyEnum.Enumeration``` 
In my CustomEnum the values are not sequential, if I wanted to inform that to the final consumer I will have to create an SDK or point them to my code.

**Comment by stuartbloom** [comment]
Yes, this is an issue.

The data coming from the API has the enumeration, however, the swagger does not document it as an integer if you call DescribeAllEnumsAsStrings().

Surely there is a way to have the enumeration to contain the Name with its actual value rather than its name and the string representation of the name?

**Comment by heldersepu** [comment]
I mentioned on my previous comment...
This is not a Swashbuckle issue, we are limited by the swagger definitions of enums:
http://swagger.io/docs/specification/enums/

You should open an issue with them:
https://github.com/OAI/OpenAPI-Specification

**Comment by stuartbloom** [comment]
@heldersepu my apologies, thanks :)
