### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by shaunparsloe** [domaindrivendev/Swashbuckle#107]
I can't get Swagger to work.  I keep getting the An item with the same key has already been added error message.  I have tried to ensure that everything is working, but I just can't get Swagger to work.  The default /help page seems to work, just not swagger.

To replicate this, I have created a repository at https://github.com/shaunparsloe/SwashBuckleIssues.git

Clone that repository and then open it (I used Visual Studio 2013 express)

Run it (it should restore the Nuget packages on first build)

https://localhost:44305/help - works correctly
https://localhost:44305/swagger - shows errors on loading

https://localhost:44305/swagger/api-docs/Customers returns the following error:
An error has occurred.
An item with the same key has already been added.
System.ArgumentException

**Comment by somdeepgniyogi** [comment]
Hi I am using IDocumentFilter to create my Odata definitions
public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
            {
                var thisAssemblyTypes = Assembly.GetExecutingAssembly().GetTypes().ToList();

                var odatacontrollers = thisAssemblyTypes.Where(t => t.IsSubclassOf(typeof(ODataController))).ToList();
                var odataRoutes = GlobalConfiguration.Configuration.Routes.Where(a => a.GetType() == typeof(ODataRoute)).ToList();

                if (!odatacontrollers.Any()) return;
                var odatamethods = new[] { "Get", "Put", "Post", "Delete" };
                var opProducers= new List<string> { "application/atom+xml", "application/json" };
                var route = "odata";

                foreach (var odataContoller in odatacontrollers)  // this is all of the OData controllers in your API
                {
                    var methods = odataContoller.GetMethods().Where(a => odatamethods.Contains(a.Name)).ToList();
                    if (!methods.Any())
                        continue; // next controller -- this one doesn't have any applicable methods

                    foreach (var method in methods)  // this is all of the methods for a SINGLE controller (e.g. GET, POST, PUT, etc)
                    {
                        var path = $"/{route}/{odataContoller.Name.Replace("Controller", string.Empty)}";
                        var odataPathItem = new PathItem();
                        var op = new Operation();

                        // This is assuming that all of the odata methods will be listed under a heading called OData in the swagger doc
                        op.tags = new List<string> { odataContoller.Name };
                        op.operationId = $"OData_{odataContoller.Name.Replace("Controller",string.Empty)}";

                        // This should probably be retrieved from XML code comments....
                        op.summary = "Summary for your method / data";
                        //op.description = "Here is where we go deep into the description and options for the call.";
                        
                        op.consumes = new List<string>();
                        op.produces = opProducers;
                        op.deprecated = false;

                        var response = new Response() { description = "OK" };
                        response.schema = new Schema { type = "array", items = schemaRegistry.GetOrRegister(method.ReturnType) };
                        op.responses = new Dictionary<string, Response> { { "200", response } };

                        //var security = GetSecurityForOperation(odataContoller);
                        //if (security != null)
                        //    op.security = new List<IDictionary<string, IEnumerable<string>>> { security };
                    if(method.Name=="Get")
                        odataPathItem.get = op;   // this needs to be a switch based on the method name
                    if (method.Name == "Post")
                        odataPathItem.post = op;
                    if (method.Name == "Put")
                        odataPathItem.put = op;
                    swaggerDoc.paths.Add(path, odataPathItem);
                    }
                }
            }

however swaggerDoc.paths.Add(path, odataPathItem) being a dictionary fails as the path for get,put and patch are same please suggest any solution
