### ISSUE TITLE
Error : "Could not find comment file"

### ISSUE THREAD

**Issue by heldersepu** [domaindrivendev/Swashbuckle#1070]
```
"Message": "An error has occurred.", 
"ExceptionMessage": "Could not find file '...\\Swagger_Test\\XmlCom.xml'.",
```

Users get that error if the xml file is not found...
 I think we should ignore the error and keep business the xml comments are not critical to the Swashbuckle operations

**Comment by domaindrivendev** [comment]
I disagree - if a dev has wired up SB, including XML comments then the only reason you would see this error is if they made a mistake or missed something during deployment. For me, this is an exception and should be raised regardless of feature criticality so the mistake can be fixed promptly

**Comment by heldersepu** [comment]
I raised this because in our case it work on our dev environments ...
but once we deployed to production Azure it crashed, that completely rendered Swagger useless for an optional feature that we can live without.

**Comment by heldersepu** [comment]
In case anyone is running into this same issue it could be handled in the config, with something like:

```c#
if (System.IO.File.Exists("XmlComments.xml"))
    c.IncludeXmlComments("XmlComments.xml");
```

**Comment by heldersepu** [comment]
I was doing some more research on this and when the crash happens on azure we don't get an ExceptionMessage only the generic "An error has occurred".
At least we should improve the message

**Comment by paul3291** [comment]
it is in the docs?

![image](https://cloud.githubusercontent.com/assets/2818069/26085846/63526f10-3a2a-11e7-9a9e-aaf93594a02a.png)

**Comment by heldersepu** [comment]
@paul3291 
Don't you think a more descriptive message could be helpful?

**Comment by paul3291** [comment]
I'm happy with making error messages more meaningful for sure, didn't know if you knew that Trouble Shooting item was there.
