### ISSUE TITLE
Question: Hide all but specific routes

### ISSUE THREAD

**Issue by coderangerdan** [domaindrivendev/Swashbuckle#1072]
I couldnt find an answer to this anywhere, but I want to hide all controller routes except just a few which will be 'public'.

All my controllers inherit from a BaseApiController which i have setup with the attribute:
`[ApiExplorerSettings( IgnoreApi = true )]`

This correctly hides everything; but I now want to just include a handful of specific routes again, but adding an IgnoreApi=false to those routes doesnt un-hide them

Is my requirement possible, or do i have to write an IDocumentFilter.

**Comment by paul3291** [comment]
From memory we just apply the Ignore=true to any api within the controller that needs hiding, not at the top level of the controller.

**Comment by heldersepu** [comment]
@coderangerdan 
Yes I think an IDocumentFilter will be your best bet...
I was just discussing that this morning on a different issue:
https://github.com/domaindrivendev/Swashbuckle/issues/153#issuecomment-302100184
If you follow that sample code you probably won't need that ApiExplorerSettings at all

**Comment by paul3291** [comment]
We tend to keep things simple and not go into custom document filters if we can help it. If you don't want it present in the first place you can use Ignore=true, but if you have a lot of things to show/not show within a controller then that might be a move to the document filter, you just have to be able to find what you need to hide via another bit of logic/information as mentioned above by @heldersepu .

**Comment by coderangerdan** [comment]
Yeah I have tens of controllers with lots of routes and I only want to document half a dozen which will be 'publicly open' by a separate 'role' and route. So it seems the filter is my option for this. Was hoping to use something out the box but never mind. Thanks guys
