### ISSUE TITLE
swagger-ui-min-js Access Denied

### ISSUE THREAD

**Issue by Ustes** [domaindrivendev/Swashbuckle#1074]
I am facing a issue where my API is behind a load balancer that is https but then the server redirects to http internally.  Swagger UI loads on my dev box with no problems but when I publish to our server I get the following js errors:
SCRIPT5: Access is denied.
swagger-ui-min-js (13,711)

This happens in my custom index.html as well on this line:
<script src='swagger-ui-min-js' type='text/javascript' ></script>

Any help is greatly appreciated.

**Comment by heldersepu** [comment]
I think that if we load all those from a CDN that will not be a problem...
it was suggested on Issue #532 

@Ustes 
Can you load the swagger docs OK?
The URL should be something like: 
http://swashbuckletest.azurewebsites.net/swagger/docs/v1

Can you share a link to your API?

**Comment by Ustes** [comment]
@heldersepu Sorry for the delay.  Whenever I tried to load swagger-ui-js from CDN I would get SwaggerUI is undefined.  I have since resorted to styling the generic help pages to get it out.  Thanks for taking the time to assist.
