### ISSUE TITLE
Updated NuGet package?

### ISSUE THREAD

**Issue by tkallevik** [domaindrivendev/Swashbuckle#1075]
I upgraded Swashbuckle into version 5.5.3 and suddenly expanding single operations stopped working (Expand all still works). If I downgrade to 5.4.0 it works again, but that has some other issues that caused me to upgrade in the first place.

I found out that this issue was due to a bug in Swagger UI, which has been fixed. And I noticed a pull request in this project for upgrading Swagger UI, that is merged (https://github.com/domaindrivendev/Swashbuckle/pull/974). So what I am wondering about is if it is possible to get an updated NuGet package as well, so that I am able to upgrade my project?

Thanks in advance :)

**Comment by heldersepu** [comment]
I use the latest version (v5.5.3) and I have not seen that issue that you are describing...
http://swashbuckletest.azurewebsites.net/swagger/ui/index
http://offleaseonly.azurewebsites.net/swagger/ui/index
Can you elaborate a bit more on this issue?

**Comment by tkallevik** [comment]
I think it might be the sort of the same as https://github.com/domaindrivendev/Swashbuckle/issues/932. I can't really say that I have any ampersands in my path, but still when I click the header of an endpoint it won't expand. When I say endpoint I mean a header of for example /api/ApiExplorer under the ApiExplorer group in your http://swashbuckletest.azurewebsites.net/swagger/ui/index example, only in my API. Your examples are working for me as well, so it shouldn't be my browser (have also tried multiple browsers).

But as I have understood it the fix is already in the master branch of Swashbuckle, so a release of a new version (e.g. 5.5.4) should hopefully fix my problems :)

**Comment by heldersepu** [comment]
is sound like you have done your research ... 
but what you say (should hopefully fix) does not sound very promising 

Can you get latest of Swashbuckle compile and include that in your WebApi to confirm that it fixes the issue?
Another option could be: You create a sample project to reproduce your issue, and I can test with latest

**Comment by tkallevik** [comment]
Sorry about the slow response. I have now cloned the Swashbuckle-repo, compiled and included it in my WebApi and it fixes the problem. With the latest version all expanding and collapsing works as it should.

**Comment by jmsvl** [comment]
Good afternoon and thanks in advance for this project :)

Can you tell me if the swagger-ui included in swashbuckle is the latest 3.0.11, I think? https://github.com/swagger-api/swagger-ui/blob/master/README.md

Thank you

**Comment by heldersepu** [comment]
@jmsvl 
No, the swagger-ui is not the latest, we still at 2.x

**Comment by jmsvl** [comment]
And is there any estimated date for the swagger-ui upgrade?

**Comment by heldersepu** [comment]
@jmsvl 
There are a lot of bugs on 3x ... are you sure you want to upgrade soon?

**Comment by heldersepu** [comment]
I've been working on my fork, I updated to the latest Swagger-UI (3.x), here is how it looks on one of my projects:
http://turoapi.azurewebsites.net/swagger/ui/index

If you have time I could use your help testing it, you can get my version from MyGet:
https://www.myget.org/gallery/swashbuckle

**Comment by jmsvl** [comment]
Great! I'll give it a try and come back to you.

**Comment by jmsvl** [comment]
On a first try I see that the drop down on the top of the page when there are multiple Api Versions is not showing but it works if I change the Url manually.

![image](https://user-images.githubusercontent.com/6940508/27789752-8e970ba0-5fe5-11e7-9a7b-d217d65244e8.png)

![image](https://user-images.githubusercontent.com/6940508/27789777-a563fc26-5fe5-11e7-8466-94e733745871.png)

I can also confirm that this version of the UI javascript doesn't have the excessive loading time issue I experience with the current javascript version.

**Comment by heldersepu** [comment]
@jmsvl
can you email me directly ? I'm not sure what should be a dropdown...

**Comment by domaindrivendev** [comment]
Just released v5.6.0 which includes version 2.2.10 of the swagger-ui. Should fix the original issue - @tkallevik let me know if this isn't the case

**Comment by jmsvl** [comment]
Hello,

Your version in MyGet vanished?

**Comment by heldersepu** [comment]
Nope it still there, The package name just changed:
https://www.myget.org/feed/heldersepu/package/nuget/Swagger-Net
I changed the name so I could later publish to NuGet
