### ISSUE TITLE
Suggestion: Upgrade to latest Swagger UI to fix Inline Model problem

### ISSUE THREAD

**Issue by coderangerdan** [domaindrivendev/Swashbuckle#1080]
As per these issues in AspnetCore repro, is there a possibility we can get an updrade to Swagger UI:
[Any plans on updating to latest swagger ui 3.x](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/349)
[Use of actual model name instead of Inline Model](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/179)

**Comment by heldersepu** [comment]
See my comment in #1064
