### ISSUE TITLE
Running Swashbuckle.OData in VS 2017 - IISExpress.exe - Precondition failed

### ISSUE THREAD

**Issue by rohitiscancerian** [domaindrivendev/Swashbuckle#1082]
![image](https://cloud.githubusercontent.com/assets/13632788/26309738/139707f8-3ef6-11e7-92a8-919325849b2e.png)

**Comment by heldersepu** [comment]
I think you are reporting this issue on the wrong project...
See: https://github.com/rbeauchamp/Swashbuckle.OData

**Comment by rohitiscancerian** [comment]
sorry my bad

**Comment by heldersepu** [comment]
no worries, just close it and open your issue on that other project.
