### ISSUE TITLE
Question: How do i build and debug

### ISSUE THREAD

**Issue by coderangerdan** [domaindrivendev/Swashbuckle#1084]
How do i set this project up for testing and hopefully contributing? When i tried, the UI folder is empty, if i copied resources from Swagger UI that didnt work; but then how do i test and debug it?

**Comment by heldersepu** [comment]
Can you take some screenshots of you Visual Studio solution and post it here

**Comment by heldersepu** [comment]
Here is how mine looks like, showing TestExplorer and SolutionExplorer
![image](https://cloud.githubusercontent.com/assets/545474/26372480/1e86719a-3fcc-11e7-913f-ad0313ba19fd.png)

**Comment by coderangerdan** [comment]
I was more wondering about how you debug it; where does it show the information i need to determine if it works or not:
![VisualStudio2017](https://cloud.githubusercontent.com/assets/1733292/26422555/46a3aea8-40c2-11e7-9305-c97f365093b4.png)

I tried making changes, building and then pointing my actual API project to the nuget package but i just got a UI with missing assets and all a bit messed up.

**Comment by heldersepu** [comment]
Your test explorer is empty I will start focusing there...

**Comment by bkwdesign** [comment]
@coderangerdan - I have this same question. I'd also like to know how to build Swashbuckle from the ground up.

I know when I'm looking at it, sitting in my Windows Explorer after checkout, there's a `swagger-ui` folder that is empty.. and there's a corresponding `gitmodules` file that targets that directory.

If I run this `git` command, it will properly hydrate that sub-directory...
`git submodule update --init`

I'm curious to know how these `swagger-ui` files get incorporated as assets in the final `Swashbuckle.Core.DLL` assembly - I don't see how it's mapped into it at all
