### ISSUE TITLE
Cant get injected resources to work

### ISSUE THREAD

**Issue by coderangerdan** [domaindrivendev/Swashbuckle#1088]
I have tried changing my project to force a logical name:
```XML
    <EmbeddedResource Include="Content\swagger-overrides.css">
        <LogicalName>MyAppNamespace.Content.swagger-overrides.css</LogicalName>
    </EmbeddedResource>

```
I can confirm that the resource is embedded with the right name by looking at: `System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceNames()`; that returns:
```
MyAppNamespace.Content.swagger-overrides.css
```
I have called SwaggerUI with:
```
c.InjectStylesheet( typeof( SwaggerDocsConfig ).Assembly, "MyAppNamespace.Content.swagger-overrides.css" );
```

Yet the UI is returning a 404 loading css with following address:
```
https://localhost:5000/swagger/ui/ext/MyAppNamespace-Content-swagger-overrides-css
```
I am now a bit stuck, can someone point me in right direction please

**Comment by heldersepu** [comment]
You mentioned in Issue #1086 
```hide the APIKey ... using a custom CSS injection```
Is this different?

**Comment by heldersepu** [comment]
Here is a fully functional example:
http://swashbuckletest.azurewebsites.net/swagger/ui/index

And here is the source code:
https://github.com/heldersepu/csharp-proj/tree/master/Swagger_Test/Swagger_Test

**Comment by coderangerdan** [comment]
Finally got it working by getting the assembly from the actual current class where i was setting the config instead of 'any' class which was in my project. Event though they are all in the same project and assembly it clearly wasnt working. Thanks though.
