### ISSUE TITLE
Default parameter values

### ISSUE THREAD

**Issue by heldersepu** [domaindrivendev/Swashbuckle#1089]
Methods with default parameters are not showing the value
http://offleaseonly.azurewebsites.net/swagger/ui/index#!/Cars/Cars_Get

Here is the code for that method:
https://github.com/heldersepu/OffLeaseOnly/blob/master/OffLeaseOnly/Controllers/CarsController.cs#L13

In the docs the parameters can have a default
```json
		"/api/Cars": {
			"get": {
				"tags": ["Cars"],
				"operationId": "Cars_Get",
				"consumes": [],
				"produces": ["application/json",
				"text/json",
				"application/xml",
				"text/xml",
				"text/html"],
				"parameters": [{
					"name": "query",
					"in": "query",
					"required": true,
					"type": "string"
				},
				{
					"name": "skip",
					"in": "query",
					"required": false,
                    **"default": "0",**
					"type": "integer",
					"format": "int32"
				},
				{
					"name": "take",
					"in": "query",
					"required": false,
					"type": "integer",
					"format": "int32"
				}],
```

**Comment by commonsensesoftware** [comment]
You're correct.  The default value from the schema is overwriting the default value defined by the parameter descriptor. I saw your PR and it looks mostly correctly. The default value of the parameter descriptor, however, should not be used when it's `null`. To do so just reverses the problem. The `null` default value from the parameter descriptor will overwrite a non-null default value assigned by the schema. A simple null check before updating the operation parameter default value with the parameter descriptor default value should do the trick.
