### ISSUE TITLE
Two response types, one for code 202 accepted, other for real response

### ISSUE THREAD

**Issue by isvaljek** [domaindrivendev/Swashbuckle#1093]
Is it possible to specify two response types?
I have some long running tasks for which the endpoints return an intermediate result with response code 202 and a value "location" with some URL like "/queue/id", then when the user gets this URL it returns the required data (if ready).

This is how it's currently attributed:
[SwaggerResponse(HttpStatusCode.OK, "OK", typeof(SomeResponseType))]

But it forces me to show either the intermediate 202 response type that only holds the queued location or the real data response type, both of them is currently not an option.

**Comment by heldersepu** [comment]
Can you please create a sample project to reproduce your issue, and post it here.

**Comment by heldersepu** [comment]
I'm not quite sure what you are asking here...
But you can use multiple SwaggerResponse in your actions
```c#
[SwaggerResponse(HttpStatusCode.OK, Type = typeof(abc), Description = "a b c")]
[SwaggerResponse(HttpStatusCode.Accepted, Type = typeof(a12), Description = "a 1 2")]
[SwaggerResponse(HttpStatusCode.BadRequest, Type = typeof(def), Description = "d e f")]
[SwaggerResponse(HttpStatusCode.InternalServerError, Type = typeof(ghi), Description = "g h i")]
```
there are a lot of StatusCodes:
https://msdn.microsoft.com/en-us/library/system.net.httpstatuscode(v=vs.110).aspx

**Comment by isvaljek** [comment]
Nice, didn't thought about stacking them, thanks.
