### ISSUE TITLE
Swashbuckle.Core reference to System.Web.Http

### ISSUE THREAD

**Issue by mskvorcovs** [domaindrivendev/Swashbuckle#1096]
I've written Windows Service application, which acts as my Web Api Owin Self Host.
I've also written some PowerShell script to install the service using installutil.exe.
As soon as I add Swashbuckle.Core reference using NuGet, I start getting "System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types..." error. As soon as I perform NuGet remove Swashbuckle.Core package from the project and rebuild - service can be installed ok.

I've used FusionLog utility to investigate, and the only suspicious thing was:
```
*** Assembly Binder Log Entry  (31.05.2017 @ 14:06:11) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/WINDOWS/Microsoft.NET/Framework/v4.0.30319/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = InstallUtil.exe
Calling assembly : Swashbuckle.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cd1bb07a5ac7c7bc.
===
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
WRN: No matching native image found.
```

But at the same time I have this binding in my config:
```
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
```
And definately have System.Web.Http.dll file in my build output folder.

Does Swashbuckle try to load System.Web.Http assembly from other place or it requires another assembly (not the one coming in the bundle with Web Api packages)?

Thank you in advance!

**Comment by mskvorcovs** [comment]
I'm sorry, probably I missed something in my description.
I am integrating Swashbuckle to the OWIN Hosted WebApi 2 project, and as readme states, it should be possible and working.

By the way, I've found a workaround - now I'm installing the service without installutil.exe, and everything works like a charm. I guess there's an unused reference somewhere inside Swashbuckle.Core, which cannot be ignored by installutil.exe

**Comment by ZhilinYang** [comment]
Observed the same issue. Sound like theSwashbuckle.core.dll has a reference of System.Web.Http.

*** Assembly Binder Log Entry  (9/11/2019 @ 10:06:04 AM) ***
The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.
Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Windows\syswow64\MsiExec.exe
--- A detailed error log follows.
=== Pre-bind state information ===
LOG: DisplayName = System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
(Fully-specified)
LOG: Appbase = file:///C:/Windows/syswow64/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = MsiExec.exe
Calling assembly : Swashbuckle.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cd1bb07a5ac7c7bc.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: No application configuration file found.
LOG: Using host configuration file: C:\Program Files\Citrix\SessionRecording\Server\Bin\Installer.dll.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Windows/syswow64/System.Web.Http.DLL.
LOG: Attempting download of new URL file:///C:/Windows/syswow64/System.Web.Http/System.Web.Http.DLL.
LOG: Attempting download of new URL file:///C:/Windows/syswow64/System.Web.Http.EXE.
LOG: Attempting download of new URL file:///C:/Windows/syswow64/System.Web.Http/System.Web.Http.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Citrix/SessionRecording/RestApiService/Bin/System.Web.Http.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Program Files\Citrix\SessionRecording\RestApiService\Bin\System.Web.Http.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
LOG: Attempting download of new URL file:///C:/Program Files/Citrix/SessionRecording/RestApiService/Bin/System.Web.Http/System.Web.Http.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Citrix/SessionRecording/RestApiService/Bin/System.Web.Http.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Citrix/SessionRecording/RestApiService/Bin/System.Web.Http/System.Web.Http.EXE.
LOG: All probing URLs attempted and failed.

**Comment by riyaztalikoti** [comment]
Hi, check these steps.  https://stackoverflow.com/a/47923538/5028108
