### ISSUE TITLE
How to sort methods by path?

### ISSUE THREAD

**Issue by djem3000** [domaindrivendev/Swashbuckle#11]
Hi
Is it possible to add functionality to sort methods by path. For example: I have a lot of methods and it is not easy to search the method.(see attached image).

![methods_path](https://f.cloud.github.com/assets/2162631/1397577/239957c2-3c8a-11e3-9c00-3bf6941c808f.png)

Many thanks
Maksim

**Comment by pallu** [comment]
I finally did it by creating a document filter with this code:
```csharp
public class CustomDocumentFilter : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, System.Web.Http.Description.IApiExplorer apiExplorer)
        {
            //make operations alphabetic
            var paths = swaggerDoc.paths.OrderBy(e => e.Key).ToList();
            swaggerDoc.paths = paths.ToDictionary(e => e.Key, e => e.Value);

            
        }
    }
```
and then in `SwaggerConfig.cs`, I included this:
```csharp
c.DocumentFilter<CustomDocumentFilter>();
```

**Comment by monobjorn** [comment]
pallu's code works fine (thanks by the way, I use it). Though it seems as it will be unsupported in the next major version, see: https://github.com/domaindrivendev/Swashbuckle/issues/416
