### ISSUE TITLE
no schema in response

### ISSUE THREAD

**Issue by M2Key** [domaindrivendev/Swashbuckle#1106]
I'm using asp net core 1.1.2 and Swashbuckle 6.0.0-beta902

I have a simple action in my asp net core controller

```
        [HttpGet("{id}")]
        public IActionResult GetById(int id)
        {
            var couponing = _couponingService.GetById(id);
            return couponing == null ? (IActionResult)NotFound(CouponingNotFound()) : new OkObjectResult(couponing);
        }
```

Where the result returned is an object.

Here's my startup.cs file

```
public void ConfigureServices(IServiceCollection services)
{



    // Add framework services.
    services.AddMvc();

    services.AddSwaggerGen(options => {
        options.SingleApiVersion(new Info
        {
            Version = "v1",
            Title = "Microservice service design",
            Description = "Manage design for services",
            TermsOfService = "Copyright, " + DateTime.Now.Year.ToString() + " M2Key, Inc. All Rights Reserved. For authorized use only.",
        });
        options.AddSecurityDefinition("apikey", new ApiKeyScheme
        {
            Name = "apikey",
            In = "header",
            Type = "apiKey"

        });

    });

}
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.UseSwagger();
    app.UseSwaggerUi("apidoc", "/servicedesign/swagger/v1/swagger.json");

    app.UseMvc();
}
```

So, in the api doc i should see this object in "Response class" section. but I have not this section at all. And if I look the json file of this action, there is no "schema" in "response"

`{"/Couponing/{id}":{"get":{"tags":["Couponing"],"operationId":"CouponingByIdGet","consumes":[],"produces":[],"parameters":[{"name":"id","in":"path","required":true,"type":"integer","format":"int32"}],"responses":{"200":{"description":"Success"}},"deprecated":false}`

What i'm doing wrong? Did I miss something

**Comment by heldersepu** [comment]
asp net core?
I think you are on the wrong project, take a look at:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by M2Key** [comment]
You're right, sorry

**Comment by heldersepu** [comment]
please close this issue
