### ISSUE TITLE
RoutePrefix attribute ignored when method does not have Route attribute

### ISSUE THREAD

**Issue by manuelsalvatori** [domaindrivendev/Swashbuckle#1108]
**Current result**
POST /api/Account
GET /api/accounts/{id}

**Expected result**
POST /api/accounts
GET /api/accounts/{id}

**Code**
```
    [RoutePrefix("api/accounts")]
    public class AccountController : BaseApiController
    {

        [HttpGet]
        [Route("{id:int}")]
        public IHttpActionResult Get(int id)
        {
            return NotFound();
        }

        [HttpPut]
        public IHttpActionResult Put(AccountDTO accountDto)
        {
            return null;
        }
    }
```

**Work around**
```
    [RoutePrefix("api/accounts")]
    public class AccountController : ApiController
    {

        [HttpGet]
        [Route("{id:int}")]
        public IHttpActionResult Get(int id)
        {
            return NotFound();
        }

        [HttpPut]
        [Route("")]
        public IHttpActionResult Put(AccountDTO accountDto)
        {
            return null;
        }
    }
```

**Considerations**
It looks like that when there is a RoutePrefix attribute in the controller class, when I don't use a Route attribute in a method, the api url is generated using the controller name suffix.

**Comment by heldersepu** [comment]
I don't think this is a Swashbuckle issue, that might be the way the WebAPI are designed...

**Comment by heldersepu** [comment]
Without the ```[Route("")]``` as in your sample code the path ```/api/accounts``` will not resolve you will get a 404 error!


Here is a working sample:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/Controllers/RoutesController.cs
Here is the swaggerui for that project:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Routes

This one OK:
http://swashbuckletest.azurewebsites.net/api/Routes/
This other is 404:
http://swashbuckletest.azurewebsites.net/faux/RoutePrefix/

On this case Swashbuckle is working correctly.
Please close this issue.

**Comment by manuelsalvatori** [comment]
Thanks for the reply, I can close the ticket but I'm not sure this should be the behaviour (I don't decide anyway).
Checking the test you linked I noticed that the behaviour is different compared with mine, possibly because I use [HttpPut] attribute. The above api was used already and I'm retrofitting swagger.
The PUT method was accessible via _api/accounts_ and not _api/Account_, again, this might be affected not just by the Route attribute but also verb specification attributes such HttpGet/HttoPost and so on.

**Comment by heldersepu** [comment]
Yes you should close this ticket, this is not a Swashbuckle issue.

That same question has been raised in stackoverflow:
https://stackoverflow.com/questions/20116362/using-route-instead-of-routeprefix-at-controller-level-in-net-web-api-attribute
