### ISSUE TITLE
Is there any library to generate Swagger.json from a .net core console application and store it in a specific location?

### ISSUE THREAD

**Issue by hydanjan** [domaindrivendev/Swashbuckle#1109]
I was wondering if there is a way to generate Swagger.json manually instead of loading it from http://host:port/swagger/v1/swagger.json.

**Comment by heldersepu** [comment]
This is not an issue, please close it.
You might want to post this question in [StackOverflow](https://stackoverflow.com/)

**Comment by hydanjan** [comment]
Closing it as it is not related. Thanks!
