### ISSUE TITLE
ASP CORE Injecting Custom Content

### ISSUE THREAD

**Issue by Astimus** [domaindrivendev/Swashbuckle#1111]
Injecting custom content in ASP CORE (.net 4.6.1) not working.
1) Added new file
2) Build action = Embedded resource
3) c.InjectJavaScript("{Default project namespace}.{path to file}.{file name}.{file extension}");

I receive 404 for js file.

**Comment by heldersepu** [comment]
It works for me:
https://github.com/heldersepu/SwashbuckleTest/commit/88c909b6e672b115f0ed5b10a33dce3b4922aaef

And here is the JS file:
http://swashbuckletest.azurewebsites.net/swagger/ui/ext/Swagger_Test-custom-js

Maybe your path is incorrect?

**Comment by Astimus** [comment]
I've added folder swagger to wwwroot and added file to that folder.

c.InjectJavascript("myjsfile.js");

All works great.

**Comment by heldersepu** [comment]
If it works for you ... please close this issue
