### ISSUE TITLE
HTML markup stripped out

### ISSUE THREAD

**Issue by pallu** [domaindrivendev/Swashbuckle#1115]
I have some HTML like <ul><li></li></ul> in the remarks section and the json is coming through fine. However, the final markup strips out all those elements. When I use the same json in the swagger.io editor, the list is shown. 
The same happens to a <table> too. This started happening when I upgraded to the newest swashbuckle on nuget. Any reason why the tags are getting stripped out?

**Comment by heldersepu** [comment]
I guess some of your code got lost...
Do you have a sample project that reproduces the issue?

**Comment by pallu** [comment]
Oh let me rewrite it. I have some sample remarks like this:
`/// <remarks>`
`/// <ul>`
`/// <li><b>Item 1</b> - description 1</li>`
`/// <li><b>Item 2</b> - description 2</li>`
`/// </ul>`
`/// </remarks>`

and the JSON comes through faithfully like this:
`description: "<ul><li><b>Item 1</b> - description 1</li><li><b>Item 2</b> - description 2</li></ul>"`

However the rendered HTML has all the list elements stripped out and renders like this:
`<p><b>Item 1</b> - description 1<b>Item 2</b> - description 2</p>` 
or in essence

<p><b>Item 1</b> - description 1<b>Item 2</b> - description 2</p>

The same happens with a `<table></table>` tag. It used to work till I upgraded to the newest nuget package.

**Comment by heldersepu** [comment]
Can you create a sample project that reproduces this issue?

**Comment by heldersepu** [comment]
I think this is what you are doing: https://github.com/heldersepu/SwashbuckleTest/commit/c275fbe1fc97b1e9730ec12218c65aed7f5f8230
I added remarks to a Post, we can see that the XML has the right data, and just like you mentioned the JSON has the correct data...

The problem is on the Swagger-UI, you can try sending them a bug, but we are using an old version, I don't think they will spend any time on this.

**Comment by pallu** [comment]
Ahh thanks. Event the `<list>` XML documentation tag does not work. Oddly enough the entire json works in the new swagger.io editor.

**Comment by paul3291** [comment]
Sounds like what I logged last year.

https://github.com/swagger-api/swagger-ui/issues/2478#issuecomment-263390710

**Comment by paul3291** [comment]
https://github.com/domaindrivendev/Swashbuckle/issues/920

**Comment by pallu** [comment]
I managed a workaround.
I created an operation filter like this:
```
public class FormatXmlComments : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, System.Web.Http.Description.ApiDescription apiDescription)
        {
            operation.description = Formatted(operation.description);
            operation.summary = Formatted(operation.summary);
        }

        private string Formatted(string text)
        {
            if (String.IsNullOrWhiteSpace(text))
                return text;
            else
            {
                return (HttpUtility.HtmlEncode(text));
            }
        }
    }
```
Then I created a site.js with the following code:
```
$(document).ready(function () {
    //all the xml html formatting from FormatXmlComments now decode back
    $(".markdown p").each(function (idx, el) {
        var text = $(el).text();
        $(el).html(text);
    })
))
```
Finally I added this line to `SwaggerConfig.js`:
```
GlobalConfiguration.Configuration 
                .EnableSwagger(c =>
                {
                       c.OperationFilter<PortalWebAPI.Swagger.Extensions.FormatXmlComments>();
                })
                .EnableSwaggerUi(c =>
                {
                       c.InjectJavaScript(thisAssembly, "MyWebAPI.Swagger.site.js");
                })
)
```
And it works fine! In essence, the `OperationFilter` encodes the html and the js decodes it back reinserts it back in the element.
