### ISSUE TITLE
Documentation Missing in UI, Swagger-UI Update

### ISSUE THREAD

**Issue by matthewrhoden1** [domaindrivendev/Swashbuckle#1125]
I am getting the same "inlineModel" issue outlined here: 
https://github.com/domaindrivendev/Swashbuckle/issues/1065

It seems to be a problem in swagger-ui; see last comment by owner:
https://github.com/swagger-api/swagger-ui/issues/2325

which he included a fix for in this release:
https://github.com/swagger-api/swagger-ui/releases/tag/v3.0.0

I tried to fork and update it myself but I can't understand how the resource paths are resolved. If you get a chance to update swagger-ui I'd really appreciate it; or if you can point me in the right direction I can try to contribute myself.

**Comment by bjornharrtell** [comment]
Working on it in https://github.com/domaindrivendev/Swashbuckle/pull/1132. It finds the resources without problems but there is quite a bit of bundled JavaScript that connects Swashbuckle config to Swagger UI that needs updating.

**Comment by heldersepu** [comment]
@matthewrhoden1 & @bjornharrtell If you guys have time please try:
https://www.nuget.org/packages/Swagger-Net/
That should be fixed there...

**Comment by matthewrhoden1** [comment]
@heldersepu works great, really appreciate the help!

**Comment by freeranger** [comment]
Hi @heldersepu - you reference a different package so I am wondering how that would help with this swashbuckle issue? Is there a way to use that package with swashbuckle (which I thought embeds the swagger ui?)?
Also, will this work with .NET Core?

thanks

**Comment by heldersepu** [comment]
@freeranger  Swagger-Net is a fork of swashbuckle, configuration is very similar (no  .NET Core yet)

**Comment by freeranger** [comment]
@heldersepu - thanks for getting back to me so quickly.  It's Core I need unfortunately :(
Thanks anyway!
