### ISSUE TITLE
Display Model Info section

### ISSUE THREAD

**Issue by AlexHedley** [domaindrivendev/Swashbuckle#1127]
In the Swagger demo [petstore](http://petstore.swagger.io) there is a section for 'Models' at the bottom of the page.

In the readme [Including XML Comments](https://github.com/domaindrivendev/Swashbuckle#including-xml-comments) it mentions adding the following

```
c.IncludeXmlComments(GetXmlCommentsPathForControllers());
c.IncludeXmlComments(GetXmlCommentsPathForModels());
```

I've already setup a single `GetXmlCommentsPath()` which is using the auto generated file.
SO: https://stackoverflow.com/questions/24284413/webapi-help-page-description

What is the difference between `ForControllers()` and `ForModels()` methods, do they point to different auto generated XML files?

Is there a config setting I need to enable in 'SwaggerConfig.cs' to show the Models?

**Comment by AlexHedley** [comment]
![swagger_models](https://user-images.githubusercontent.com/1573469/27856456-1ffc43e0-6166-11e7-96e8-c204c4971379.png)

**Comment by heldersepu** [comment]
You screenshot looks like swagger-ui version 3.x !
This project does not yet support that version, but I've been working on my own fork and now it offers  3.x:

Please try it out if you can:
https://www.myget.org/gallery/swashbuckle

**Comment by AlexHedley** [comment]
Thanks, I'll take a look, are you looking to merge it into this project?

**Comment by heldersepu** [comment]
@AlexHedley 
Right now my branch is 164 commits ahead, merge will be very very difficult

**Comment by domaindrivendev** [comment]
This is related to swagger-ui 3.x and this is captured by #1064

**Comment by calvin998** [comment]
Just want to check the status of upgrading to Swagger UI 3. I'm waiting for this fix: https://github.com/domaindrivendev/Swashbuckle/issues/1127
