### ISSUE TITLE
Defining Schema for ExpandoObject as response

### ISSUE THREAD

**Issue by springerarthur** [domaindrivendev/Swashbuckle#1129]
I have a WebApi Method that returns a ExpandoObject.

```
public dynamic GetUsers(string filter, int pageSize, int pageIndex) {
    ...
    dynamic result = new ExpandoObject();
    result.total_results = 100;
    result.page_count = 0;
    result.user_list = GetUsers();
    
    return result;
}
```

So Swashbuckle generate a swagger-file that looks like this:
```
"/v1/user/users":{  
    "get":{  
        ...
        "responses":{  
            "200":{ 
                "schema":{  
                    "type":"object"
                }
            }
        }
    }
```

In the swagger ui I'll only see a empty "Inline Model {}" as a model definition. This isn't very useful.

Is there any smart solution to describe the dynamic return object?

**Comment by heldersepu** [comment]
Use SwaggerResponse, here is an example:
https://github.com/heldersepu/TuroApi/blob/master/TuroApi/Controllers/SearchController.cs

**Comment by springerarthur** [comment]
I've already use SwaggerResponse for some other methods that return a model or an array of a model. Like: public Order GetOrder(...).

But in my other case I have a API-Method which didn't return a known model. The method returns a dynamic object like in the example above.

Is there a way to define a dynamic response with the SwaggerResponse?

**Comment by heldersepu** [comment]
What's the purpose of a dynamic object?  
a dynamic object is just that:  ```"schema":{  "type":"object" }``` and that does not help anyone...
 
The purpose of a swagger documentation is to provide details about your API so other developers that consume your API know exactly what to expect. 

My recommendation refactor your API, create your model object and add it to your SwaggerResponse.

**Comment by springerarthur** [comment]
Yes, It's true that a dynamic object is just a simple object. 

But it is an old existing API, which is still in use. It isn't possible to refactor the API and change the returned object.

I need a way to describe the dynamic returned object manually in the swagger documentation

**Comment by heldersepu** [comment]
You don't have to change the returned object in your API all you need is to add the SwaggerResponse with the correct model object:
```c#
[SwaggerResponse(HttpStatusCode.OK, Type = typeof(UserObject))]
public dynamic GetUsers(string filter, int pageSize, int pageIndex) {
    ...
    dynamic result = new ExpandoObject();
    result.total_results = 100;
    result.page_count = 0;
    result.user_list = GetUsers();
    
    return result;
}
```
In that example ```UserObject``` that matches your response

**Comment by domaindrivendev** [comment]
I'm going to close this as I agree with @heldersepu's comments and think his suggestion is your best option.
