### ISSUE TITLE
Automatically generate default 200 OK response while specifying other response types

### ISSUE THREAD

**Issue by emsiu** [domaindrivendev/Swashbuckle#1138]
According to [#216](https://github.com/domaindrivendev/Swashbuckle/issues/216), Swashbuckle will automatically generate a 200 success response as the default behavior, or otherwise expects all response types to be specified.

I'd like to be able to add a 404/400 error response to some endpoints in the XML comments while keeping the 200 success responses for all endpoints, including those with a 404/400 error response.

Is it possible to make Swashbuckle continue to automatically generate a 200 success response for all endpoints even when an error response is specified?

**Comment by emsiu** [comment]
I added an operation filter to programmatically add the missing 200 responses, which resolved the missing model schemas.

`class CustomOperationFilter : IOperationFilter
{
    public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
    {
        var responses = operation.responses;
        if (responses.ContainsKey("404") || responses.ContainsKey("400"))
        {
            responses.Add("200", new Response()
            {
                description = "OK",
                schema = (schemaRegistry.GetOrRegister(apiDescription.ActionDescriptor.ReturnType))
            });
        }
    }
}`

But I still wonder if there's a way to keep Swashbuckle's automatic generation of 200 success responses while explicitly specifying other responses

**Comment by domaindrivendev** [comment]
Yes - you can use one or more `SwaggerResponseAttribute`s to specify additional responses
