### ISSUE TITLE
Question: What is the official way of documenting a QueryParam for a function?

### ISSUE THREAD

**Issue by Kapulara** [domaindrivendev/Swashbuckle#1151]
So lets say I have this function below.

```cs
/// <summary>
/// gets foo from a given fooName
/// </summary>
/// <param name="fooName">gets foo with fooName</param>
/// <returns> foo with a given fooName </returns>
[HttpGet]
[Route("api/getFoo)]
[HMACAuthorization]
[Swashbuckle.Swagger.Annotations.SwaggerResponse(HttpStatusCode.NotFound)]
[Swashbuckle.Swagger.Annotations.SwaggerResponse(HttpStatusCode.OK, Description = "Foo retrieved", Type = typeof(string))]
[Swashbuckle.Swagger.Annotations.SwaggerResponse(HttpStatusCode.InternalServerError)]
public HttpResponseMessage getFoo(string fooName) {}
```

Now I add some query parameter parsing in the function, That will get "pageLimit" and "pageOffset" to add pagination to this function.

So those are not arguments to the getFoo function. But instead received from the request parameters directly.

How would I document this? (so this parses correctly)

It's no option to go over each function we have for our API and add new parameters. Since that is more than 150 different API routes. That would need testing again. So we need a way to define it in the documentation for the function.

**Comment by heldersepu** [comment]
You add some query parameters ("pageLimit" and "pageOffset") to add pagination to the function.
But those are not arguments to the getFoo function. Instead received from the request parameters directly.

This sounds a lot like an anti-pattern! I will recommend against that
Can't you just do a global replace to add the new params properly(as args to the functions) ?

You should post this question to [Stackoverflow](https://stackoverflow.com/questions/tagged/SWASHBUCKLE) that way you can get feedback from the community

**Comment by Kapulara** [comment]
@heldersepu Yeah, That's not really what my question is. 

Let me ellaborate:
I added pagination inside of the function. Which gets it directly from the query parameters. 

Now I don't seem to find anywhere how I can document this function so the Swagger specification parses it and adds it to the route. 

For example this route:
https://gist.github.com/Kapulara/a141a515b8855fa82396700898daeaab#file-questionnaire-json-L13-L26

Those parameters were added by parsing the function arguments.

Lets say I have a few other parameters but they are not function arguments, How would I go and document those?

**Comment by heldersepu** [comment]
I think I understood your question just fine...

Getting the query parameters directly is a bad ***BAD*** practice! 
do it the proper way(as args to the functions) and the documentation will work as it should

**Comment by Kapulara** [comment]
Allright, Thanks for the help anyway @heldersepu 

I get why this is an anti-pattern but it's not something I can change. Almost all of the functions are written with this method.  

Just to verify, There is no other way than to rewrite all of the functions?

**Comment by heldersepu** [comment]
Ways there are...
If you want to modify the resulting swagger document you can add an IDocumentFilter 
You should work to untangle the spaghetti code not add more to the pile.

**Comment by heldersepu** [comment]
... and what you call a rewrite, that could be a few simple global replacements, maybe need to use some Regex, but the resulting code will be significantly better

**Comment by heldersepu** [comment]
Post this question to Stackoverflow see the feedback from the community...

**Comment by Kapulara** [comment]
Allright thanks @heldersepu 😄
