### ISSUE TITLE
How to implement filter bar?

### ISSUE THREAD

**Issue by akaylh** [domaindrivendev/Swashbuckle#1153]
How to implement filter bar?

**Comment by zdarovka** [comment]
What do you mean by filter bar?

**Comment by akaylh** [comment]
like this:
![tmp5c15e4cc](https://user-images.githubusercontent.com/437330/28900487-2aca869a-7824-11e7-8209-0037acb74ff5.png)

**Comment by domaindrivendev** [comment]
Dup of #1064. That's swagger-ui 3.x
