### ISSUE TITLE
I want to hide ODataQueryOptions from swagger UI

### ISSUE THREAD

**Issue by akshaybheda** [domaindrivendev/Swashbuckle#1160]
I dont want to display ODataQueryOptions in swagger ui, how can i remove that?

**Comment by akshaybheda** [comment]
For removing the autogenerated ODataQueryOptions parameter from swagger documentation we need to create a new .cs file and insert the following code.

`public class IgnoreODataQueryOptionOperationFilter : IOperationFilter
{
public void Apply (Operation operation, SchemaRegistry schemaRegistry
,ApiDescription apiDescription)
            		{
            		apiDescription.ParameterDescriptions
.Where(desc => desc.ParameterDescriptor.ParameterType == typeof(ODataQueryOptions<BUSINESSOBJECT OF MODEL>)).ToList().ForEach(param =>
                	{
                    var toRemove = operation.parameters.SingleOrDefault(p => p.name == param.Name);
                    if ( null != toRemove )
                        operation.parameters.Remove(toRemove);
                	});
        }`

And in SwaggerConfig.cs we need to add

`c.OperationFilter<THE ABOVE CREATED FILE>();`

**Comment by drmcclelland** [comment]
Thank you @akshaybheda!

Here is a updated version of `IgnoreODataQueryOptionsOperationFilter` for .NET Core which excludes all `ODataQueryOptions` parameters from the generated Swagger document without having to specify the type of model being used:

```
using Microsoft.AspNetCore.OData.Query;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace ECommerce.API.OpenApiFilters;

public class IgnoreODataQueryOptionsOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        context.ApiDescription.ParameterDescriptions
            .Where(desc => desc?.ParameterDescriptor?.ParameterType?.BaseType == typeof(ODataQueryOptions)).ToList()
            .ForEach(param =>
            {
                var toRemove = operation.Parameters.SingleOrDefault(p => p.Name == param.Name);
                if (null != toRemove)
                {
                    _ = operation.Parameters.Remove(toRemove);
                }
            });
    }
}
```

Usage:

```
services.AddSwaggerGen(
    c=>
    {
        c.OperationFilter<IgnoreODataQueryOptionsOperationFilter>();
    });
```
