### ISSUE TITLE
path was wrong

### ISSUE THREAD

**Issue by lth1040240425** [domaindrivendev/Swashbuckle#1161]
[HttpGet, Route("payments/{payId}/{requester?}")]
 public ApiResponse GetPayInfoSingle(Guid payId, int requester = 8)
 
i set the requester is not required   
but  when  i click 'try it now '  the url  was   xxxx/payments2/8d3f40bc-36b4-4197-9c70-a988293b0c55/{requester} 

i want the url is   xxxx/payments2/8d3f40bc-36b4-4197-9c70-a988293b0c55/

**Comment by heldersepu** [comment]
See here: 
https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Swagger/SwaggerGenerator.cs#L190

```c#
 parameter.required = location == "path" || !paramDesc.ParameterDescriptor.IsOptional;
```

**Comment by domaindrivendev** [comment]
in Swagger, you can't have optional path parameters. Therefore, SB does not support it either

**Comment by heldersepu** [comment]
Yep the OpenAPI states:
```
If the parameter is in "path", this property is required and its value MUST be true.
```
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7


<br>
...but it seems that swagger is quite forgiven, create an IDocumentFilter to change the required flag:

```c#
private class OptionalPathParamDocumentFilter : IDocumentFilter
{
private class OptionalPathParamDocumentFilter : IDocumentFilter
{
    public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
    {
        string actionPath = "/attrib/{payId}";
        swaggerDoc.paths[actionPath].get.parameters[0].required = false;
    }
}
```

that seems to work, at least on my test:
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Attribute#/Attribute/Attribute_Get
