### ISSUE TITLE
Not applicable to dotnet core 2.0 application

### ISSUE THREAD

**Issue by cnstevenwang** [domaindrivendev/Swashbuckle#1168]
Is there any planning to support dotnet core 2.0 application?

**Comment by Young717** [comment]
The version of mvc needs to be update. You would update all packge if it has new version.

**Comment by domaindrivendev** [comment]
This project is specifically for WebAPI. If you're looking to incorporate Swashbuckle into an ASP.NET Core project, please refer to the following project - https://github.com/domaindrivendev/Swashbuckle.AspNetCore
