### ISSUE TITLE
Include / Ignore controller based on namespace

### ISSUE THREAD

**Issue by maxmantz** [domaindrivendev/Swashbuckle#1174]
Hi,

first of all this is an amazing library. It makes my life just so much easier documenting my APIs as well as implementing them.

As I'm expanding my API I would like to be able to filter out certain controllers based on their namepsace. 
I have a public API which should be visible in the swagger docs, but also some private endpoints which should be hidden. The controllers for the private endpoints are in a separate namespace than the public controllers. Can I include or exclude controllers based on their namespace?

Cheers!

**Comment by domaindrivendev** [comment]
There's improved support for arbitrary selection of API descriptions in the [newer version of Swashbuckle that targets ASP.NET Core](https://github.com/domaindrivendev/Swashbuckle.AspNetCore). But, unless you're on or moving to ASP.NET Core, this won't help much.

For the traditional WebAPI version, you do have some options though ...

One potential approach you could try is to use the __MultipleVersions__ option in your SwaggerConfig.cs. This method accepts a Func for indicating which ApiDescriptions are relevant to each specified version. You could still just specify one version but also provide the Func which only includes the ApiDescriptions you're interested in. I think this should get you what you need - let me know how it goes?

Alternatively, you could inject your own implementation of IApiExplorer, the built-in metadata service that ships with WebAPI:

```csharp
var apiExplorer = httpConfig.Services.GetApiExplorer();
httpConfig.Services.Replace(typeof(IApiExplorer), new FilteredApiExplorer(apiExplorer));
```

Swashbuckle uses the _ApiDescriptions_ property to generate it's docs so _FilteredApiExplorer_ could provide an implementation of this property that filters out items according to the underlying controller namespace.
