### ISSUE TITLE
Swagger-UI doesn't response with plenty of controllers

### ISSUE THREAD

**Issue by sonphnt** [domaindrivendev/Swashbuckle#1177]
Hi

My WebAPI have around 30 controllers. And it seems Swagger taking a lot of times to render UI on browser. I always get timeout exception after waiting for a long time.

Is this a bug?

Thanks

**Comment by heldersepu** [comment]
Can you post a link to your Api?

**Comment by sonphnt** [comment]
@heldersepu This is internal API, Have we had any issues involving to this?

**Comment by heldersepu** [comment]
I remember one case that with a large class (2000+ properties) generated by Entity Framework that was causing slowdowns, but nothing just by the amount of controllers...

Can you remove or replace what ever is private property from your internal API and add it to GitHub, without that it will be impossible to help you out.

**Comment by sonphnt** [comment]
@heldersepu I think I have found a bug that crashed swaggerUI by being stuck at "fetching resource list......Please wait"

`        [HttpPost]
        [Route("importarray")]
        public IActionResult ImportArray([FromBody]Account[] value)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                var data = value;
                return Ok();
            }
        }`

Account[] is entity model that is scaffolded from database. FromBody should be a Viewmodel or DTO model.
Hope this will help others.

**Comment by heldersepu** [comment]
@sonphnt I can NOT troubleshoot with that...
Were are the other classes (Contact, SupplyAgreement) ?

**Comment by heldersepu** [comment]
@sonphnt Please create a project that reproduces your bug.

**Comment by sonphnt** [comment]
Hi @heldersepu I will try to create a project later. But I can give you other classes. The problem I guess is Navigation Property in classes. That will create a circle loop. In this case is Account - Contact - Account


>     public partial class Contact
>     {
>         public int Id { get; set; }
>         public int? AccountId { get; set; }
>         public string FirstName { get; set; }
>         public string LastName { get; set; }
>         public string JobTitle { get; set; }
>         public string Email { get; set; }
>         public string BusinessPhone { get; set; }
>         public string MobilePhone { get; set; }
>         public string Fax { get; set; }
>         public DateTime? Updated { get; set; }
> 
>         **public Account Account { get; set; }**
>     }


>     public partial class SupplyAgreement
>     {
>         public SupplyAgreement()
>         {
>         }
> 
>         public int Id { get; set; }
>         public int EntityId { get; set; }
>         public int? AccountId { get; set; }
>         public string Name { get; set; }
>         public int? Slaid { get; set; }
> 
>         public Account Account { get; set; }
>     }

**Comment by heldersepu** [comment]
@sonphnt Here I created a controller very similar to yours:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/Controllers/ImportArrayController.cs

And the UI loads just fine:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/ImportArray/ImportArray_Post

**Comment by sonphnt** [comment]
@heldersepu I am using .net core 2.0. Is it a difference? but I will download your project and try to add some more to test.

**Comment by heldersepu** [comment]
Yes big difference you are reporting this on the wrong project!

**Comment by sonphnt** [comment]
@heldersepu sorry for missing that information. Can we give it a test in .net core 2.0 ?

**Comment by heldersepu** [comment]
Sure you can, report it here: 
https://github.com/domaindrivendev/Swashbuckle.AspNetCore
But I'm not doing net core

**Comment by sonphnt** [comment]
Thanks @heldersepu  Once again, sorry about this confusion. I will report there.
