### ISSUE TITLE
ActionName attribute is not handled in ApplyActionXmlComments

### ISSUE THREAD

**Issue by robpex** [domaindrivendev/Swashbuckle#118]
If the ActionName attribute is used to change action name, Swagger documentation will not be generated for that action.  For example, if you have the following action:

```
    [ActionName("MyAction")]
    [HttpDelete]
    public void DeleteMyAction(int Id)
    {
    } 
```

The .NET XML documentation generates using 'DeleteMyAction' whether or not you have the ActionName attribute.  I guess it could be argued that this is a .NET bug too, but Swashbuckle could handle this by doing something like the following in ApplyActionXMLComments GetXPathFor method:

```
        string actionName = actionDescriptor.ActionName;
        if (actionDescriptor.GetCustomAttributes<ActionNameAttribute>().Any())
        {
            var reflected = actionDescriptor as ReflectedHttpActionDescriptor;
            actionName = reflected.MethodInfo.Name;
        }
```

Right now, I'm handling this by adding a custom OperationFilter that's basically a copy of ApplyActionXmlComments.

**Comment by domaindrivendev** [comment]
Just released version 4.2.0 with these changes. Please try it out and provide feedback if you get a chance.

FYI, bar any serious bugs, this will be the last release of the 4.x line. All future development and features will be targeted to the next major version 5.x, which makes the transition from Swagger 1.2 to Swagger 2.0.
