### ISSUE TITLE
No XML documentation for properties from dependent assemby

### ISSUE THREAD

**Issue by PaulDotNet** [domaindrivendev/Swashbuckle#1182]
Swagger spec generated by swashbuckle contains descriptions of classes from dependent assembly but all properties have no descriptions. 

## VERSION: ##
1.0.0 for .Net Core. Project is .Net Core 2.0 console application referencing .Net Standard 2.0 DLLs.

## STEPS TO REPRODUCE: ##
Here is the code that adds swagger generator and specifies Data.XML file with XML documentation for the objects.
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Version = "v1",
                    Title = "API"
                });
                c.IncludeXmlComments(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Data.xml"));
            });

## EXPECTED RESULT: ##
Swagger JSON file should contain descriptions of classes and their properties.
Swagger UI should contain descriptions of classes and their properties.

## ACTUAL RESULT: ##
Swagger JSON file contains descriptions for classes but no descriptions of any properties.
Swagger UI has no descriptions of classes and their properties.

**Comment by heldersepu** [comment]
This works fine for me, there are even UnitTests checking that functionality.
Can you create a minimal project reproducing your issue?

**Comment by PaulDotNet** [comment]
Created projects from scratch and got the same result. Here are the steps:

1. Created Server project using **dotnet new webapi**
2. Opened Server project in VS2017 and added .Net Standard 2.0 class library project called **Data** to the solution.
3. In **Data** project implemented Class1 with one data member and added XML descriptions for class and data member.
4. Enabled XML comments in **Data** project build settings.
5. Added **Data** as dependency of **Server** project.
6. In **Server** project added Nuget Swashbuckle.AspNetCore 1.0.0
7. Added code to Startup.cs file for swagger generation and XML comments
8. Ran the app and checked Swagger JSON file. Description was present for Data.Class1 but not for data member of that class. Description existed in Data.XML file.

Where are my member comments? Did I miss something?

**Comment by heldersepu** [comment]
You are reporting this on the wrong project...

**Comment by PaulDotNet** [comment]
Which project is the right one?

**Comment by heldersepu** [comment]
Swashbuckle.AspNetCore

**Comment by PaulDotNet** [comment]
That was unexpected.
