### ISSUE TITLE
how to read custom header field in Swagger

### ISSUE THREAD

**Issue by osmanrahimi** [domaindrivendev/Swashbuckle#1185]
I used below code to Add custom value to header : 

```
public class RequestIdParameter : IOperationFilter
    {
        public void Apply(Swashbuckle.Swagger.Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            if (operation == null) return;
```
            if (operation.parameters == null)
            {
                operation.parameters = new List<Parameter>();
            }

            var requestParameter = new Parameter
            {
                description = "RequestId",
                @in = "header",
                name = "RequestId",
                required = true,
                type = "string"
            };

            operation.parameters.Add(requestParameter);
        }
    }`

but now I need to read that vlaue . I used this Code but it does not exists in Header: 
`System.Web.HttpContext.Current.Items`

**Comment by heldersepu** [comment]
This is completely unrelated to Swashbuckle, please close it.

...but here is a starting point to your header issues:
```c#
        public Dictionary<string, string> Put()
        {
            var dict = new Dictionary<string, string>();
            foreach (var header in Request.Headers)
                if (header.Key.EndsWith("id"))
                    dict.Add(header.Key, header.Value.First());
            return dict;
        }
```

http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Val#/ValueProvider/ValueProvider_Put
and the code behind is here:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L385
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/Controllers/ValueProviderController.cs#L22
