### ISSUE TITLE
I can't config SwaggerUi anything

### ISSUE THREAD

**Issue by zhaokuohaha** [domaindrivendev/Swashbuckle#1192]
\*\* As per the [contributing guidelines](CONTRIBUTING.md), please restrict the creation of issues to reproducible bug reports and feature requests that align to the project's goals. If you have general questions or feedback around the use of Swashbuckle, PLEASE DON'T CREATE AN ISSUE AND POST TO STACKOVERFLOW INSTEAD.

Also note that Swashbuckle leverages the [swagger-ui project](https://github.com/swagger-api/swagger-ui) but doesn't actually implement any UI code. If you've discovered a UI-specific issue, PLEASE DON'T CREATE AN ISSUE HERE AND POST TO THE SWAGGER-UI REPO INSTEAD \*\*

## VERSION: ##
Swagger/SwaggerUI : 6.0.0 beta902
ASP.NET Core 1.1

## STEPS TO REPRODUCE: ##
in `Startup.cs` , I config swagger as follow:

```csharp
using Swashbuckle.Swagger.Model;
 // ...
public void ConfigureServices(IServiceCollection services)
 {
 services.AddSwaggerGen(c =>
            {
                c.SingleApiVersion(new Info()
                {
                    Version = "v1",
                    Title = "my api doc"
                });
                c.DescribeAllEnumsAsStrings();
                // I can config something about swagge here , like add filter
            });
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
        app.UseSwagger();
        app.UseSwaggerUi();
// But I can't do anyting here ??
}
```

the question is : how can I do for config swaggerui  like this : 
```csharp
httpConfiguration
    .EnableSwagger(c => c.SingleApiVersion("v1", "A title for your API"))
    .EnableSwaggerUi(c =>
        {
            c.InjectStylesheet(containingAssembly, "Swashbuckle.Dummy.SwaggerExtensions.testStyles1.css");
            c.InjectJavaScript(containingAssembly, "Swashbuckle.Dummy.SwaggerExtensions.testScript1.js");
            c.SetValidatorUrl("http://localhost/validator");
            c.DisableValidator();
            c.DocExpansion(DocExpansion.List);
            c.SupportedSubmitMethods("GET", "HEAD")
        });
```

In Startup.cs ??

**Comment by heldersepu** [comment]
You are reporting this on the wrong project, see:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by zhaokuohaha** [comment]
thx ! I upgrade the dependence to Swashbuckle.Asp.NetCore and solved the issue
