### ISSUE TITLE
Not showing status code 201,400,403,404 on swagger ui in .Net

### ISSUE THREAD

**Issue by jitsingh89** [domaindrivendev/Swashbuckle#1194]
I am not able to show status code 201,400,500,404  etc on swagger ui page Like (Response class (Status 200). It's always showing  "Status 200". I have to show status code for created 201,Forbidden 403, BadRequest 400. I have also used swashbuckle.example dll.

This is my class
public class EmployeeExample: IExamplesProvider
{
public object GetExamples()
{
return new Employee(){
ID=0,
Name="Jitu",
City="Noida"
}
}

This is my method in controller:-

[HttpPost
[SwaggerResponse(HttpStatusCode.Creted, Type = typeof(IEnumerable<EmployeeExample>))]
public  HttpResponseMessage  Get(string lang) 
{
Return Request,CreateResponse(HttpStatusCode.Created, objectyofresponse);
}

I want to shwo like this.
![222](https://user-images.githubusercontent.com/9546697/33207331-450b92a2-d133-11e7-97f9-cc12ef463626.PNG)

is the below issue closed ?
https://github.com/swagger-api/swagger-ui/issues/1117
https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/issues/9

Please let me know how can i show status code with example value.

**Comment by Marusyk** [comment]
Use `SwaggerResponseRemoveDefaultsAttribute`
```C#
[HttpPost]
[SwaggerResponseRemoveDefaults]
[SwaggerResponse(HttpStatusCode.Creted, Type = typeof(IEnumerable))]
public HttpResponseMessage Get(string lang)
{
     Return Request,CreateResponse(HttpStatusCode.Created, objectyofresponse);
}
```

**Comment by mattfrear** [comment]
I think you can close this issue
