### ISSUE TITLE
Swashbuckle stucks on loading after setting CustomSchemaIds

### ISSUE THREAD

**Issue by SchneMa** [domaindrivendev/Swashbuckle#1196]
## VERSION: ##
1.1.0

## ACTUAL RESULT: ##
After solving the issue with "Conflicting schemaIds: Duplicate schemaIds detected " by adding the ConfigureSwaggerGen the Swashbuckle/Swagger page seems to stuck on Building.
When I route to `http://localhost:60737/swagger/` the Page stucks and causes the browser to wait for page or stop the script.
Sounds like theres something wrong on building the Config or something like that with a endless loop.

The only Swagger/Swashbuckle depending Code I use is the following:

```
services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("0.0.1", new Info { Title = "SAnywhereAPI", Version = "0.0.1" });
                var filePath = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "SAnywhereAPI.xml");
                c.IncludeXmlComments(filePath);
            });
services.ConfigureSwaggerGen(options =>
            {
                options.CustomSchemaIds(x => x.FullName);
            });
```
Without setting the CustomSchemaIds I got the ` Duplicate schemaIds` Error.
After solving it like mentioned in multiple solutions by setting the `CustomSchemaIds` the page will stuck on loading.

I checked all Controllers by commenting them out but even when there is no controller the Swagger Page is going to stuck on loading.

Would be great to hear if I'm missing something or that this is a Bug.

**Comment by heldersepu** [comment]
It will be nearly imposible to troubleshoot your issue without and actual API sample.
You should create a minimal API reproducing your issue and add it to your post...
But looking at the version you post it looks like you are on the wrong project

**Comment by SchneMa** [comment]
Hard to reproduce as minimal as possible because of big dependecy libaries ...
Hm I don't know if this is the wrong Project beause of the version. The Version is the NuGet Version from VisualStudio's Swashbuckle.AspNetCore ( 1.1.0). Which would be the right project instead @heldersepu ?

**Comment by heldersepu** [comment]
Swashbuckle.AspNetCore
https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by SchneMa** [comment]
@heldersepu Thx seems like I missed that git Project...
I'll close this and open an Issue in that Project.
