### ISSUE TITLE
Swagger-UI 3.x update?

### ISSUE THREAD

**Issue by Kizmar** [domaindrivendev/Swashbuckle#1203]
What are the chances of this getting updated to use Swagger UI 3.x? There are some [known issues](https://github.com/swagger-api/swagger-ui/issues/2132) with response type encoding that should be fixed in newer versions.

**Comment by Kizmar** [comment]
[Dupilcate](https://github.com/domaindrivendev/Swashbuckle/issues/1064)

**Comment by heldersepu** [comment]
If you are in urgent need try my fork:
https://www.nuget.org/packages/Swagger-Net/
