### ISSUE TITLE
Possibility to add additional custom pages to documentation

### ISSUE THREAD

**Issue by Marusyk** [domaindrivendev/Swashbuckle#1209]
It would be greate to have possibility to add additional custom pages to documentation. 
Let's say I wanna describe rules for consumers of my Webapi (rules for integration). So, it should be a new html page. 

I created the page "integration.html" and add to the project as embaded resourse. Then 

```
.EnableSwaggerUi("docs/{*assetPath}", c => {
     c.CustomAsset("index", Assembly.GetExecutingAssembly(), "Web.API.Swagger.UI.index.html");
     c.CustomAsset("integration", Assembly.GetExecutingAssembly(), "Web.API.Swagger.UI.integration.html");
});
```

How can I specify the link to this page from index without hardcoding?

```
<div><a href="%(RootUrl)/docs/integration">Integration</a></div>
```

There is a class `SwaggerUiConfig` with private field
```
private readonly Dictionary<string, string> _templateParams;
```
Why not create setter to add custom template parameter like
```
c.CustomParam("%(IntergatioPageUrl)", "Web.API.Swagger.UI.integration.html");
```
and use it

```
<div><a href="%(IntergatioPageUrl)">Integration</a></div>
```
What do you think about that? Thanks

**Comment by stormaref** [comment]
@Marusyk did u succeed?
