### ISSUE TITLE
All parameters show as 'optionall

### ISSUE THREAD

**Issue by richard-parker** [domaindrivendev/Swashbuckle#121]
Hi guys,

First off - awesome project, I'm loving using it already!

I do have a quick question, perhaps an issue, but also perhaps because I'm new to using Swagger/Swashbuckle. 

In a nutshell, I notice that in the documentation generated, for both the Response Class and each parameter, every field is marked as optional, despite the fact none of them (in my code) are nullable. I have hunted for quite some time and can't seem to find an attribute that marks them as 'required', and I'm wondering what the proper way to go about fixing this is.

Here's an example of a Response Class:

RegistrationResult {
Status (string, _optional_) = ['Registered' or 'AlreadyRegistered' or 'Bad'],
ExpiresUtc (string, _optional_),
PrimaryRegionId (string, _optional_),
SecondaryRegionIds (array[string], _optional_)
} 

The italic sections, "optional", really aren't :)

Many thanks,

Richard.

**Comment by WhatIsHeDoing** [comment]
Shame it doesn't pick up the required state from JSON.NET, i.e. `[JsonProperty(Required = Required.Always)]`.
