### ISSUE TITLE
SwaggerUI not properly constructing URL to API

### ISSUE THREAD

**Issue by JtrPerficient** [domaindrivendev/Swashbuckle#1212]
## VERSION: ##
v5.6

## STEPS TO REPRODUCE: ##
We access the SwaggerUI via a load-balanced site (URL).  The load-balancer redirects to the physical server(s) on port 8060.  

## EXPECTED RESULT: ##
The calculated URL should match the inbound URL.

## ACTUAL RESULT: ##
The calculated URL for the JSON document includes the redirect port.

## ADDITIONAL DETAILS ##
The generated documentation and SwaggerUI work correctly on developer workstations.  When we publish the APIs to our test environment, which is behind a load balancer, the SwaggerUI will render correctly but the documentation URL (e.g., http://test:8060/product/swagger/docs/v1) is not formed correctly.  The load balancer is redirecting the virtual IP to the physical server on port 8060. 

I have tried several solutions found on the GitHub site - setting RootUrl, custom IDocumentFilter, interrogating the HTTP headers - but i have not been successful.  How do i go about solving this problem?

**Comment by domaindrivendev** [comment]
RootUrl is the way to go here. Can you elaborate on what you tried? The implementation will depend on the load balancer and specifically which headers it injects to identify the “outer” hostname and port

**Comment by JtrPerficient** [comment]
I tried different ideas using "RootUrl".  Was able to get more input from the network engineers on how the load balancer is configured - i.e., there are no headers present.  Will add headers for original host/port and then update the "GetRootUrl()" implementation.
