### ISSUE TITLE
Any way to set the collectionFormat of array properties in viewmodels?

### ISSUE THREAD

**Issue by hades200082** [domaindrivendev/Swashbuckle#1214]
I have a number of array properties but they always get displayed as collectionFormat multi.  I'd like to use collectionFormat csv.

Can this be set in .NET?

**Comment by domaindrivendev** [comment]
I can’t try it out right now but you should be able to do this fairly easily with a SchemaFilter (see read me for usage). The filter gets applied to every Schema after it’s been initially generated. So, you could check for Schema’s of type array and update collectionFormat to the value you want

**Comment by JoryUK** [comment]
If only the Schema had collectionFormat as a property

**Comment by bchuecosrincon** [comment]
Can we reopen this? This isn't possible right now since collectionFormat isn't part of Schema

**Comment by bchuecosrincon** [comment]
@domaindrivendev Can we reopen this? This isn't possible right now since collectionFormat isn't part of Schema
