### ISSUE TITLE
Hiding Properties in swagger ui example

### ISSUE THREAD

**Issue by mvakili** [domaindrivendev/Swashbuckle#1217]
Hi, I'm using swagger, beside dotnet standard 2.0 web api.

It's a sample model that i used in my application. most of them are common between database entities and controllers input and return values
```
public class Grade
{
    public int Id { get; set; }

    public virtual ICollection<Student> Students {get; set;}
    public virtual ICollection<Class> Classes {get; set;}
    public virtual ICollection<LessonTitle> LessonTitles {get; set;}
    
    [Timestamp]
    public byte[] RowVersion { get; set; }
}
```

I want to hide virtual properties and RowVersion property just in swagger example.
It is possible for dotnet core 2.0 ?

**Comment by matzheng** [comment]
Just Try [Ignore] annotation.

**Comment by mvakili** [comment]
[Ignore] Annotation is not working for me, I couldn't find reference for it.
I found my solution here:
[`Exclude properties from being listed in Swagger UI`](https://stackoverflow.com/questions/44644782/exclude-properties-from-being-listed-in-swagger-ui?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) 

It works fine for me when I use use [JsonIgnore]

@matzheng

**Comment by syaifulnizamyahya** [comment]
@mvakili Be aware that JsonIgnore wont allow you to seriealize/deserialize

**Comment by Sandeep321** [comment]
[JsonIgnore]
        internal string Id { get; set; }

This works for me

**Comment by abaslam** [comment]
[JsonIgnore] from System.Text.Json.Serialization namespace will work as Swashbuckle uses System.Text.Json by default.
