### ISSUE TITLE
IIS Rewrite and Swagger

### ISSUE THREAD

**Issue by ranouf** [domaindrivendev/Swashbuckle#1219]
Hi,

I m sorry, I know it s not completely related to Swagger, but It could help other people like me who are looking for the answer there too.

I have a WebApp with and AspNetCore WebAPI + AngularApp on Azure with IIS rewrite rules in my Web.Config based on this article: https://weblog.west-wind.com/posts/2017/Apr/27/IIS-and-ASPNET-Core-Rewrite-Rules-for-AspNetCoreModule

I would like to avoid rewriting on Swagger, so I added this rule as the first rule:
        <rule name="swagger" enabled="true" stopProcessing="true">
          <match url="swagger/.*" />
          <action type="None" />
        </rule>

Based on this website: https://www.regextester.com/

The rules is supposed to swagger/ but all the subfolders and files too. But It s not the case.
![image](https://user-images.githubusercontent.com/1764519/36435270-35cb8554-162f-11e8-830b-007f73a2bff8.png)

This is what I can see when I open http://[MYWEBSITE]/swagger/
![image](https://user-images.githubusercontent.com/1764519/36435366-7741a70c-162f-11e8-85bf-12bbc86ccf9a.png)

The Angular app works correctly.

If you thing that my Issue has not its place here, please remove it.

Thanks for your help.

**Comment by domaindrivendev** [comment]
I would love to dig in and help you figure this out but unfortunately the cycles just aren’t available. At this point I wouldn’t classify this as a bug report or feature request and would therefore ask that you post to Stackoverflow instead of this issue tracker. Sorry I can’t be of more help

**Comment by ranouf** [comment]
No pb, I understand.

For the next one who will need help about this problem, I created a post on StackOverflow:
https://stackoverflow.com/questions/48889816/iis-rewrite-exclude-folders-and-subfolders-swagger-case
