### ISSUE TITLE
Authorization header missing after updating Swashbuckle.AspNetCore v2.1

### ISSUE THREAD

**Issue by PhilippeCamou** [domaindrivendev/Swashbuckle#1224]
Hi.

I just updated packages of our Net Core 2 WebAPI solution  : Swashbuckle.AspNetCore v2.1 from 1.2.
API Security is based on JWT Bearer token.
Runing solution for validation i get a new UI interface with new good looking style....
BUT now Authorization header is missing in HTTP request even i add the token as before clicking on "Autorize". 
Of course it was working perfectly before in Swashbuckle.AspNetCore V1.2.
Following Documentation i have in Startup.cs :
services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
                c.AddSecurityDefinition("Bearer", new ApiKeyScheme() { In = "header", Description = "Please insert JWT with Bearer into field", Name = "Authorization", Type = "apiKey" });
            });

Nothing have change just update from Gitub with VS2017.
I reverted the changes, backed to previous version of UI V 1.2 and it works perfectly as before.
Then updating to Swashbuckle.AspNetCore v2.1 seems to have issue adding Authorization header in request.
 
Any ideas ? 

Regards

**Comment by domaindrivendev** [comment]
Wrong repo, there’s a separate one for AspNetCore implementation.

Take a look at the issue below. In a nutshell the old UI was adding the header when it shouldn’t be. The new UI fixes this but means you need to add additional metadata

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/603
