### ISSUE TITLE
 this project if support asp.net mvc not webapi

### ISSUE THREAD

**Issue by linyintao2010** [domaindrivendev/Swashbuckle#1226]
dear :
   I am not sure if this project can use for asp.net mvc not webapi.   the project also can  identify Controllers not just apicontrollers。 
        thk

**Comment by domaindrivendev** [comment]
This project only supports WebAPI

**Comment by shuangyuxiaoyi** [comment]
@domaindrivendev Can we edit something for support asp.net mvc?
