### ISSUE TITLE
When is it supported asp.net core 2.1？

### ISSUE THREAD

**Issue by ldg1989** [domaindrivendev/Swashbuckle#1261]
\*\* As per the [contributing guidelines](CONTRIBUTING.md), please restrict the creation of issues to reproducible bug reports and feature requests that align to the project's goals. If you have general questions or feedback around the use of Swashbuckle, PLEASE DON'T CREATE AN ISSUE AND POST TO STACKOVERFLOW INSTEAD.

Also note that Swashbuckle leverages the [swagger-ui project](https://github.com/swagger-api/swagger-ui) but doesn't actually implement any UI code. If you've discovered a UI-specific issue, PLEASE DON'T CREATE AN ISSUE HERE AND POST TO THE SWAGGER-UI REPO INSTEAD \*\*

## VERSION: ##
_Provide the version of Swashbuckle you're using_

## STEPS TO REPRODUCE: ##
_Provide a clear set of steps to reproduce the problem, ideally starting with an empty WebAPI project_

## EXPECTED RESULT: ##
_Provide a description and example of the expected result_

## ACTUAL RESULT: ##
_Provide a description of the actual behavior you're observing_

## ADDITIONAL DETAILS ##
_Provide any additional details here_

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore. It supports ASP.NET Core 1.04 and above
