### ISSUE TITLE
Having issue in Parameter Content-type and Response Object representation

### ISSUE THREAD

**Issue by DrXSsive** [domaindrivendev/Swashbuckle#1270]
Hi Guys,

I just started using Swashbuckle and Swagger to generate Documentation for my Web Api. I am having a problem in the UI. I am using following code to Generate documentation
![code i am using](https://user-images.githubusercontent.com/40558386/45098041-9eca9c80-b13d-11e8-8beb-05e0a0be8030.PNG)
The issue I am facing is with the parameters. Please see the attached Image.
![parameters](https://user-images.githubusercontent.com/40558386/45098077-b144d600-b13d-11e8-8913-0a141111ba2a.png)
and facing issue with the Responses as well.
![response](https://user-images.githubusercontent.com/40558386/45098106-bd309800-b13d-11e8-9a98-c68c00c97276.PNG)
I just wanna know is this a issue or just I am a dumb to figure out the solution> :(

Any help will be appreciated. I am using latest stable version of Swashbuckle which is currently 5.6 and Swagger version 3.0.

Thank you in Advance.

Cheers
DrX

**Comment by lonix1** [comment]
Hey Drx, [the solution](https://stackoverflow.com/questions/55978068/how-do-i-set-parameter-content-type-using-swashbuckle) is

````csharp
[Consumes("application/json")]      // <----
public IActionResult Post() {
//...
}
````
