### ISSUE TITLE
How to customise the name of property?

### ISSUE THREAD

**Issue by petemounce** [domaindrivendev/Swashbuckle#128]
I have a WebApi controller action that takes a `string authToken` parameter, which it reads from the `Auth-Token` header. swagger-ui code-gens this as `authToken` which means requests via swagger-ui don't write the header correctly.

How can I customise the name of this parameter so that swagger-ui does the right thing?

**Comment by domaindrivendev** [comment]
Nice! Glad you got it sorted

**Comment by goldytech** [comment]
I need to see the code `[FromHeader]` attribute . Can you please share it ?

**Comment by DwarfPorter** [comment]
It's very helpful for Swashbuckle version 4, however, in version 5.0.0-rc4 the interface is changed to
` interface IOperationFilter {
void Apply(OpenApiOperation operation, OperationFilterContext context)`; 

and not clearly how to make the parameters
