### ISSUE TITLE
Big blank white bar in header of swagger page

### ISSUE THREAD

**Issue by sonicmouse** [domaindrivendev/Swashbuckle#1280]
upgraded to 4.0.1 and am now seeing a huge white bar at the top:

![image](https://user-images.githubusercontent.com/2473180/48489638-1cb7bd80-e7e9-11e8-9abd-bf76ac722f28.png)

Is this a bug? How do I remove this?

**Comment by sonicmouse** [comment]
So after reading this:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/268

I have to specify schemas.

So, i guess the issue is: If there are none specified, then this bar should be hidden.

The specific code I added to make the bar worthwhile:

```
			app.UseSwagger(c=>
			{
				c.PreSerializeFilters.Add((swagger, httpReq) => swagger.Schemes = new[] { "http", "https" });
			});
```

**Comment by hkosova** [comment]
@sonicmouse The blank white bar [was fixed](https://github.com/swagger-api/swagger-ui/issues/5029) in Swagger UI 3.20.1.

Swashbuckle is bundled with UI 2.2.10, so I guess you use your own copy of Swagger UI. If so, you can just use a newer UI version instead of the `PreSerializeFilters` code.
