### ISSUE TITLE
Swagger UI displayRequestDuration support

### ISSUE THREAD

**Issue by jawn** [domaindrivendev/Swashbuckle#1295]
First posted on [StackOverflow](https://stackoverflow.com/questions/54351293/show-http-request-duration-in-swagger-ui). Reposting here since I get the feeling this is a feature request.

## VERSION: ##
5.6.0

## STEPS TO REPRODUCE: ##

Try to configure the [displayRequestDuration](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) from SwaggerConfig.cs

When set to true, it shows how long a request takes. It's disabled by default.

## EXPECTED RESULT: ##
Can be configured.

## ACTUAL RESULT: ##
Did not find how this can be done.

## ADDITIONAL DETAILS ##
I see this is [possible](https://stackoverflow.com/a/49564414/65545) in the Java version.

**Comment by Brondahl** [comment]
:+1: Just run into this too.

Much more broadly, is it possible to provide direct access to the UI config values.
Obviously the provided configuration handles are much nicer, but if we could have (probably untyped!) access to the underlying config then features like this would come in for free when Swagger add them.

**Comment by jawn** [comment]
@Brondahl : good idea, you may want to create a different issue for direct access to the UI config values.
One of these issues would then solve the current issue.

**Comment by shannalajoie** [comment]
Any updates? Im using the Swashbuckle.Core.5.5.3 package and I dont know where to configure the displayRequestDuration = true

**Comment by nshah31** [comment]
Any Updates ? using version 5.6.0

**Comment by jawn** [comment]
Tested from .NET Core 3.0

In recent versions you can do
```
app.UseSwaggerUi3(
    settings => settings.AdditionalSettings.Add("displayRequestDuration	", true));
)

```

**Comment by Brondahl** [comment]
@jawn I don't understand what's going on here: that `UserSwaggerUi3` method seems to be part of `NSwag` not `Swashbuckle`?

There isn't a `.UseSwaggerUi3` method for me :(
Could you confirm what namespace and dependencies you've imported to get access to that method?

**Comment by jawn** [comment]
> @jawn I don't understand what's going on here: that `UserSwaggerUi3` method seems to be part of `NSwag` not `Swashbuckle`?
> 
> There isn't a `.UseSwaggerUi3` method for me :(
> Could you confirm what namespace and dependencies you've imported to get access to that method?

You are right, it's an NSwag method!

![image](https://user-images.githubusercontent.com/1705112/80120493-65050e80-858b-11ea-96d6-d99d2c26659f.png)

**Comment by Brondahl** [comment]
I think I'm missing something?
Isn't `NSwag` a _different_ Swagger generation library?
That namespace isn't available, when I install the Swashbuckle nuget package?

This doesn't seem like a solution to "please can Swashbuckle support this Swagger feature"?

**Comment by Brondahl** [comment]
Bump?

**Comment by jawn** [comment]
Reopening the issue.

**Comment by Brondahl** [comment]
As per @do-it-ger's PR in an unrelated repo, as of `5.3.3`, at some point this functionality **has** become available in Swashbuckle.

In `Startup.Configure(IApplicationBuilder app, IHostingEnvironment env)`, when you call `app.UseSwaggerUI(Action<SwaggerUIOptions> opts)`...

either 

    opts.DisplayRequestDuration();

or the identical

    opts.ConfigObject.DisplayRequestDuration = true;

will enable RequestDuration in the UI.

Note that it's only available for successful searches.

**Comment by Brondahl** [comment]
>Note that it's only available for successful searches.

Is this under Swashbuckle's control? Or is that part of Swagger itself (which Swashbuckle is merely configuring)?

**Comment by Boz0r** [comment]
I don't understand why this issue is closed. I've run into needing this in a .NET Framework project, and it seems like the issue is closed because it works in another library, even though it's still not working in Swashbuckle.WebApi.

**Comment by Brondahl** [comment]
@Boz0r there was a brief confusion where, you're right, it got closed because it worked in `NSwag`.
But it *also* now works in `Swashbuckle`, as of `5.3.3`.
See my comments 2nd May 2020.

**Comment by Boz0r** [comment]
@Brondahl Sure, but what you're mentioning in that comment is for the AspNetCore repo, and not this one, as far as I can tell.

**Comment by SMayer135** [comment]
I am also missing how to configure this setting in a .net framework project.

**Comment by muratozbayraktar** [comment]
This topic should be opened. I'm looking for this
