### ISSUE TITLE
Define Enum DataType As Int

### ISSUE THREAD

**Issue by technicallyerik** [domaindrivendev/Swashbuckle#131]
Since by default WebAPI returns Enums as Ints when it serializes the result, I feel as though DataTypeRegistry.cs should be modified to reflect that:

```
if (type.IsEnum)
return new DataType { Type = "int", Enum = GetEnumValues(type) };

....

private IList<string> GetEnumValues(Type t)
{
    var result = new List<string>(); 
    var values = Enum.GetValues(t);
    foreach(var value in values)
    {
        result.Add(string.Format("{0}: {1}", (int)value, Enum.GetName(t, value)));
    }
    return result;
}
```

As a workaround (without creating a custom build of Swashbuckle), I have to do this to generate proper documentation:

```
SwaggerSpecConfig.Customize(c =>
{
    var enums = Assembly.GetExecutingAssembly()
        .GetTypes()
        .Where(t => t.IsEnum && t.IsPublic);

    foreach (Type t in enums)
    {
        Type type = t;
        typeof(SwaggerSpecConfig).GetMethod("MapType").MakeGenericMethod(type).Invoke(c, new object[] { (Func<DataType>)(() => new DataType { Type = "int", Enum = GetEnumValues(type) })});
    }
});
```

Thanks,

**Comment by enkafan** [comment]
We've been setting the json converter globally in when configuring the webapi. It'd be slick if the converter could check GlobalConfiguration.Configuration.Formatters.JsonFormatter for the default behavior so we aren't decorating each enum.
