### ISSUE TITLE
DisplayRequestDuration

### ISSUE THREAD

**Issue by shannalajoie** [domaindrivendev/Swashbuckle#1322]
Any updates? Im using the Swashbuckle.Core.5.5.3 package and I dont know where to configure the displayRequestDuration = true 

## VERSION: ##
Swashbuckle.Core.5.5.3

## STEPS TO REPRODUCE: ##
I dont know where to configure the displayRequestDuration = true 

## EXPECTED RESULT: ##
displayRequestDuration is configured to TRUE

Please help.

**Comment by jawn** [comment]
See #1295
