### ISSUE TITLE
Request examples are not generated if serialize as V2.

### ISSUE THREAD

**Issue by tmarkovski** [domaindrivendev/Swashbuckle#1349]
## VERSION: ##
5.0.0-rc4

## STEPS TO REPRODUCE: ##
- Add Examples filter (https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters)
- `app.UseSwagger(c => { c.SerializeAsV2 = true; });`

## EXPECTED RESULT: ##
Examples should show in the swagger doc

## ACTUAL RESULT: ##
Examples don't show.

## ADDITIONAL DETAILS ##
It works fine when not using `SerializeAsV2`

**Comment by wallymathieu** [comment]
Isn't this issue for https://github.com/domaindrivendev/Swashbuckle.AspNetCore ?
