### ISSUE TITLE
Adding a FileOperationFilter with the latest Swashbuckle

### ISSUE THREAD

**Issue by arrkaye** [domaindrivendev/Swashbuckle#1357]
Hi,

We have a FileOperationFilter we were using on 1.2.0 that I'm having trouble upgrading to the latest version of Swashbuckle.

What do I need to change to be compatible?

```
	public class FileOperationFilter : IOperationFilter
	{
		private HashSet<string> _remove = new HashSet<string>(){ "contentType", "contentDisposition", "headers", "length", "name", "fileName" };
		public void Apply(Operation operation, OperationFilterContext context)
		{
			if (context.ApiDescription.ParameterDescriptions.Any(x => x.ModelMetadata.ContainerType == typeof(IFormFile)))
			{
				var temp = new List<IParameter>();
				foreach (var operationParameter in operation.Parameters)
				{
					if (_remove.Contains(operationParameter.Name))
					{
						temp.Add(operationParameter);
					}
				}

				temp.ForEach(t => operation.Parameters.Remove(t));

				operation.Parameters.Add(new NonBodyParameter
				{
					Name = "file", // must match parameter name from controller method
					In = "formData",
					Description = "Upload file.",
					Required = true,
					Type = "file"
				});
				operation.Consumes.Add("application/form-data");
			}
		}
	}
```

**Comment by jinek** [comment]
Just a hint:
```
public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            operation.parameters = new List<Parameter>();
            
            operation.parameters.Add(new Parameter
            {
                name = "uploadedFile",
                @in = "formData",
                description = "Upload File",
                required = true,
                type = "file"
            });
            operation.consumes.Add("multipart/form-data");
        }
```

**Comment by inbarbarkai** [comment]
I have the same issue on 5.0.0-rc5.
@jinek Your solution doesn't apply.

**Comment by arrkaye** [comment]
Thanks @jinek,

I'm trying to build the same thing on 5.0.0-rc5. The code I posted works for the old version. Would appreciate any insight you can offer.

**Comment by jinek** [comment]
What I posted works for me in version 5.6.0.
I'm not sure about version 5.0.0-rc5 (I even don't see it in nuget, only 5.0.0-rc1), but can you show list of your errors? May be you can change uppercase/lowercase, use another type instead of "NonBodyParameter" etc?

**Comment by arrkaye** [comment]
Hi @jinek 

Are we talking about the same library?

I'm using the Swashbuckle.AspNetCore 5.0.0-rc5. In the package I have, the `Operation` class does not exist, and has been superseded by the `OpenApiOperation` class.

https://www.nuget.org/packages/Swashbuckle.AspNetCore

**Comment by arrkaye** [comment]
Ah, I see what I've done. My bad, and apologies. I'll move my issue across to the right repo.

**Comment by arrkaye** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1479
