### ISSUE TITLE
c# 8 nullable reference types support

### ISSUE THREAD

**Issue by ketovdk** [domaindrivendev/Swashbuckle#1362]
Hello.

## VERSION: ##
5.1.0.

## STEPS TO REPRODUCE: ##
Register swagger: 
`			services.AddSwaggerGen(c =>
			{
				c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
			});`
`			app.UseSwagger();
			app.UseSwaggerUI(c =>
			{
				c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
				c.RoutePrefix = "";
			});`
Create DTO:
`	public class WeatherForecast
	{
		public string Description { get; set; } = "Cold";
	}`
Create controller:
`	[ApiController]
	[Route("[controller]")]
	public class WeatherForecastController : ControllerBase
	{
		[HttpGet]
		public WeatherForecast Get()
		{
			return new WeatherForecast();
		}
	}`

## EXPECTED RESULT: ##
Field Description of type WeatherForecast should be not nullable

## ACTUAL RESULT: ##
Field Description of type WeatherForecast is nullable

## ADDITIONAL DETAILS ##
I tried to find anything, about c# 8 NRT support, but i did not. It is vital to know, are they supported or will they be supported (and when).

**Comment by domaindrivendev** [comment]
Wrong repo - please create in the AspNetCore specific repo - Swashbuckle.AspNetCore
