### ISSUE TITLE
Ignore read only/private setter properties for a POST/PATCH 

### ISSUE THREAD

**Issue by freeranger** [domaindrivendev/Swashbuckle#138]
Hi,

I have some models where the setter is private.  For a GET request, these values will be returned to the user, but for a POST or PATCH, they should not be provided by the user at all, so I would like the documentation to reflect this.

Can you provide the ability to ignore these when documenting a POST/PATCH, or extend IModelFilter so that Apply takes an Operation parameter and then I can provide a custom implementation that hides properties as and when required.
This would be more consistent with the IOperationFilter Apply method also.

Thanks

**Comment by daerhiel** [comment]
Just wanted to ask if there're an updates on this since 2014?

**Comment by bugproof** [comment]
That was tricky to solve, but it works.

```csharp
public class ReadOnlySchemaFilter : ISchemaFilter
{
    public void Apply(Schema model, SchemaFilterContext context)
    {
        if (model.Properties == null)
        {
            return;
        }

        foreach (var schemaProperty in model.Properties)
        {
            var property = context.SystemType.GetProperty(schemaProperty.Key, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);

            if (property != null)
            {
                var attr = (ReadOnlyAttribute)property.GetCustomAttributes(typeof(ReadOnlyAttribute), false).SingleOrDefault();
                if (attr != null && attr.IsReadOnly)
                {
                    // https://github.com/swagger-api/swagger-ui/issues/3445#issuecomment-339649576
                    if (schemaProperty.Value.Ref != null)
                    {
                        schemaProperty.Value.AllOf = new List<Schema>()
                        {
                            new Schema()
                            {
                                Ref = schemaProperty.Value.Ref
                            }
                        };
                        schemaProperty.Value.Ref = null;
                    }

                    schemaProperty.Value.ReadOnly = true;
                }
            }
        }
    }
}
```

Usage:

```csharp
public class Order
{
    [ReadOnly(true)]
    public int Id { get; set; }

    [ReadOnly(true)]
    public Product Product { get; set; }
}
```

One disadvantage: Swagger UI will hide it from POST example, but unfortunately will show it in the model tab:

![image](https://user-images.githubusercontent.com/3116731/39274516-7e0bdf68-48e2-11e8-83ad-509576bb6962.png)

**Comment by YoannDiguet** [comment]
Hello,
This does not work if you have a JsonProperty attribute on your property, as the name in the swagger and the real property name are not in sync anymore.
