### ISSUE TITLE
Support Swagger-UI version >= 3.27.0

### ISSUE THREAD

**Issue by BillLudwig** [domaindrivendev/Swashbuckle#1384]
Thanks for all the hard work that goes into this project. I know that support for Swagger-UI 3.26.0 was just recently added but our team is wanting to take advantage of the click-to-copy feature that was added in 3.27.0. 

Thanks again.

## VERSION: ##
5.5.X

**Comment by BillLudwig** [comment]
Sorry, opened this in the wrong place. Closing.

**Comment by ahsteele** [comment]
[Issue 1784 created for Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1784)
