### ISSUE TITLE
using multiple IncludeXmlComments, but solution is considering only last file.

### ISSUE THREAD

**Issue by Maxx1996** [domaindrivendev/Swashbuckle#1387]
Hi,

We are using below specifications:

.Net Framework 4.7.2
Swashbuckle.Core V 5.6.0
All the code has been done with reference to link "https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments" and "https://github.com/domaindrivendev/Swashbuckle/blob/5489aca0d2dd7946f5569341f621f581720d4634/Swashbuckle.Dummy.Core/App_Start/SwaggerConfig.cs#L261".

In our solution we are having multiple projects. There are 2 projects in which controllers are defined and we are showing comments inserted in these projects in swagger. The main project which is the default project is different from these 2 projects.

As per the guidelines we have defined the name in build section and enabled XML Documentation File. We have also added the reference of these xml in bin of main project and set the properties to updated the files every time the solution is built.

To include multiple comments file we are using "c.IncludeXmlComments(filename)" method twice with specific file names.

Issue:
Comments from both of these files are getting included and are visible in swagger, when code is executed on localhost. But when we commit the solution in PR environment only a few of comments appear. On analysis our judgement is in PR environment the comments provided by 2nd file "Api2.xml" is getting included. Its appearing as if the comments which are provided in 1st file (execution of code order) is over written by 2nd file and hence none of the comments of 1st file is appearing.

I will be really grateful if you can help us with the issue. Please let us know in case any other information is required from our end.

Reference Text: 

using System.Web.Http;
using WebActivatorEx;
using CMSApp;
using Swashbuckle.Application;
using System.IO;
using Swashbuckle.Swagger;
using System;

[assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]

namespace CMSApp
{
    public class SwaggerConfig
    {
        public static void Register()
        {
            var thisAssembly = typeof(SwaggerConfig).Assembly;

            GlobalConfiguration.Configuration
                .EnableSwagger(c =>
                {
                    
                    c.SingleApiVersion("v1", "API");

                    
                    // If you annotate Controllers and API Types with
                    // Xml comments (http://msdn.microsoft.com/en-us/library/b2s063f7(v=vs.110).aspx), you can incorporate
                    // those comments into the generated docs and UI. You can enable this by providing the path to one or
                    // more Xml comment files.
                    var filePath = Path.Combine(System.AppContext.BaseDirectory, "bin\\Api1.xml");

                    if (File.Exists(filePath))
                        c.IncludeXmlComments(filePath);

                    var filePathForCustomCode = Path.Combine(System.AppContext.BaseDirectory, "bin\\Api2.xml");

                    if (File.Exists(filePathForCustomCode))
                        c.IncludeXmlComments(filePathForCustomCode);
                    
                    // If you want to post-modify "complex" Schemas once they've been generated, across the board or for a
                    // specific type, you can wire up one or more Schema filters.
                    c.SchemaFilter<MyFilter>();
                    
                    // In accordance with the built in JsonSerializer, Swashbuckle will, by default, describe enums as integers.
                    // You can change the serializer behavior by configuring the StringToEnumConverter globally or for a given
                    // enum type. Swashbuckle will honor this change out-of-the-box. However, if you use a different
                    // approach to serialize enums as strings, you can also force Swashbuckle to describe them as strings.

                    c.DescribeAllEnumsAsStrings();

                })
                .EnableSwaggerUi(c =>
                {
                                            
                });
        }
    }

    public class MyFilter : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
        {
            schema.title = type.Name;
        }
    }
}

Thankyou

**Comment by B3thL1nd3n** [comment]
I found the solution (finally):

                List<string> xmlFiles = Directory.GetFiles(AppContext.BaseDirectory, "*.xml", SearchOption.TopDirectoryOnly).ToList();
                xmlFiles.ForEach(xmlFile => setupAction.IncludeXmlComments(xmlFile));

this takes all xml files in the solution directories bin folders, and add them to SwaggerUI

**Comment by Jordan9232** [comment]
> I found the solution (finally):
> 
> ```
>             List<string> xmlFiles = Directory.GetFiles(AppContext.BaseDirectory, "*.xml", SearchOption.TopDirectoryOnly).ToList();
>             xmlFiles.ForEach(xmlFile => setupAction.IncludeXmlComments(xmlFile));
> ```
> 
> this takes all xml files in the solution directories bin folders, and add them to SwaggerUI

This is what worked for me too. Although I can see this possibly causing undesired results if your project already outputs some other .xml files other than the auto generated ones that you may not want to be included. In my case, I have 3 projects in my solution, only 2 of which I have setup to generate a .xml file. So I did this:

```
var assemblies = AppDomain.CurrentDomain.GetAssemblies()
  .Where(x => x.GetName().Name?.StartsWith("SomeStringAllYourProjectsStartWith") ?? false);

foreach (var assembly in assemblies)
{
  var xml_path = Path.Combine(AppContext.BaseDirectory, $"{assembly.GetName().Name}.xml");
  if (File.Exists(xml_path))
  {
    options.IncludeXmlComments(xml_path);
  }
}
```

**Comment by jaanca** [comment]
Thanks for the solution, i used it in my .Net core 6.0 web api 

```console
builder.Services.AddSwaggerGen(c =>
{
    ....
    ...
    List<string> xmlFiles = Directory.GetFiles(AppContext.BaseDirectory, "*.xml", SearchOption.TopDirectoryOnly).ToList();
    foreach (string fileName in xmlFiles)
    {
        string xmlFilePath = Path.Combine(AppContext.BaseDirectory, fileName);
        if (File.Exists(xmlFilePath))
            c.IncludeXmlComments(xmlFilePath, includeControllerXmlComments: true);
    }
});
```
