### ISSUE TITLE
[Question] How to include api version in swaggerUI route

### ISSUE THREAD

**Issue by macchmie3** [domaindrivendev/Swashbuckle#1390]
## VERSION:  v5.6.0 ## 

I have an API that implements versioning with "api-version" header - no version is specified in URL. This versioning is done with `Microsoft.Web.Http.Versioning` package.

This is my swagger config:

```
config.EnableSwagger("docs/{apiVersion}/swagger", c =>
                    {
                       c.MultipleApiVersions(
                            (apiDescription, version) => apiDescription.GetGroupName() == version,
                            info =>
                            {
                                foreach (var group in apiExplorer.ApiDescriptions)
                                {
                                    var description = $"Build: {typeof(SwaggerConfig).Assembly.GetName().Version}";

                                    if (group.IsDeprecated)
                                    {
                                        description += " This API version has been deprecated.";
                                    }

                                    info.Version(group.Name, $"{group.ApiVersion}")
                                        .Description(description);
                                }
                            });
                    })
                .EnableSwaggerUi(c =>
                    {
                        c.EnableDiscoveryUrlSelector();
                    });
```

With this config the url to swagger is: `https://my.api.com/swagger/ui/index`
And url to an example method is: `https://my.api.com/swagger/ui/index#!/MyController/MyController_MyMethodV2`

Now the problem is as follow:
The swagger UI page allows me to browse through a different versions of the API (since I used `EnableDiscoveryUrlSelector`). Default version that loads up is v1. I can create a link to a method (MyMethodV2) that is only implemented in v2 version of the api, and is only visible in swagger UI when you browse through v2 version of the API.

Unfortunately link `https://my.api.com/swagger/ui/index#!/MyController/MyController_MyMethodV2` will redirect you to methods in 'MyController' in version v1, and the method 'MyMethodV2' will not be visible. I was wondering how to include selected version in the SwaggerUI route, but unfortunately  ` .EnableSwaggerUi("swagger/ui/{apiVersion}/{*assetPath}", c=> ...` does not work?

Any idea how I could create a link to api method that will load up the page with correct version of the API?

**Comment by commonsensesoftware** [comment]
The documents are bucketized by API version. You specify the value of the version in `info.Version`. This is where the value of `{apiVersion}` is coming from for each document. In this version of the UI, you have to choose the JSON document you want and click **Explore**. Using the configuration you've provided, I was able to make it work as expected. If this isn't working, then you'll need to provide some additional context or a repro.

**Comment by macchmie3** [comment]
I can see everything as you explained with **Explore** button. I was wondering if you can create a link to a specific method in specific version - so that when you click the link, the page with proper JSON document already loaded is opened.

**Comment by commonsensesoftware** [comment]
I believe you are asking whether you can create a _deep link_ to an API in a specific version and document. I'm not sure you can, at least, not without some customization. I'm not familiar with that process, but it's technically feasible.
