### ISSUE TITLE
Swagger ui freeze on nested models.

### ISSUE THREAD

**Issue by bugrakosen** [domaindrivendev/Swashbuckle#1398]
My DTOs are very nested. When i try expand post and put endpoints the ui freeze like that;

![freeze](https://user-images.githubusercontent.com/32344242/100648105-87e17780-3351-11eb-8280-e737fdc075dd.PNG)

I've tried multiple solutions like removing nested properties or examples section on model with document and schema filter, installing Swashbuckle.AspNetCore.Newtonsoft package and ignore reference loop handling. Its run normally when i remove the schemas with document filter, but i need schemas in documentation. I've already tried solutions described in anothes issues for this;
```
  c.DefaultModelExpandDepth(1);
  c.DefaultModelsExpandDepth(1);
```

Swashbuckle.AspNetCore version : 5.6.3
Swashbuckle.AspNetCore.Newtonsoft version : 5.6.3
.Net Core version : 3.1
Generated JSON documentation file size : 12.0 MB
I included xml file in documentation. Xml file size : 1.3 MB

Thank you in advance for your help.

**Comment by muhdammar** [comment]
hi do you fix this error

**Comment by bugrakosen** [comment]
Yes, my issue about [FromForm] annotation. If you have IFormFile in your model and you pass parameter with [FromForm] attribute,  swashbuckle generate unnecessary codes in docs.json. 

I've solved this issue with exclude this endpoints in my docs like below;

```
[ApiExplorerSettings(IgnoreApi = true)]
public async Task<IActionResult> AddProductAsync([FromForm] ProductDTO product)
{
      ...
      some code
      ...
}
```

**Or;**

```
[AttributeUsage(AttributeTargets.Property)]
public class SwaggerExcludeAttribute : Attribute
{
}
```

```
public class SwaggerExcludeFilter : ISchemaFilter
{
       public void Apply(OpenApiSchema schema, SchemaFilterContext context)
       {
            if (schema?.Properties == null)
            {
                return;
            }

            var excludedProperties =
                context.Type.GetProperties().Where(
                    t => t.GetCustomAttribute<SwaggerExcludeAttribute>() != null);

            foreach (var excludedProperty in excludedProperties)
            {
                var propertyToRemove =
                    schema.Properties.Keys.SingleOrDefault(
                        x => x.ToLower() == excludedProperty.Name.ToLower());

                if (propertyToRemove != null)
                {
                    schema.Properties.Remove(propertyToRemove);
                }
            }
       }
}
```

```
public class ProductDTO
{
     [SwaggerExclude]
     public IFormFile Image { get; set; }
}
```


In swagger configuration;

```
 services.AddSwaggerGen(options =>
 {
          ...
          options.SchemaFilter<SwaggerExcludeFilter>();
          ...
 });
```
