### ISSUE TITLE
Is there a way to exclude a controller?

### ISSUE THREAD

**Issue by joseph-ortiz** [domaindrivendev/Swashbuckle#140]
Is there a way to exclude an API  controller? I don't want to show this controller because i'm still working on it. 

I've added the obsolete method on each action but I find it it repetitive. Is there a configuration, annotation, or better way to exclude controllers not ready for documentation?

**Comment by mattlpage** [comment]
Is it possible to dynamically change the visibility of controllers within Swashbuckle, based upon a url?

For example
/internal/swagger
might show internal/diagnostic endpoints that a public
/swagger
might not?

Just an idea. Thanks so much for this project!

**Comment by mishrsud** [comment]
@mattlpage probably too late for you but adding here for reference:
The [ApiExplorerSettings] attribute is allowed at Controller as well as Action method level. So effectively, one can exclude a single endpoint/route from a controller

**Comment by 3263927** [comment]
please, make settings to ignore all API but only has [SwaggerInclude] attribute or something

**Comment by fspezi** [comment]
My code has a Base class: this is shown in Swagger documentation.  
So i try to remove it with `[ApiExplorerSettings(IgnoreApi = true)]`, then the Base controller class is hidden.  
But so, all inherited controller classes are hidden.  
Then I add `[ApiExplorerSettings(IgnoreApi = false)]` to any inherited controller classes: now I can see theese controller, but base controller also.

I think there is something wrong... 

PS: this is the Base controller declaration:

```cs
    public abstract class EntityControllerBase<T>: Microsoft.AspNetCore.Mvc.ControllerBase
        where T : Models.Entity.Cfg.Support.EntityBase
    {
```
