### ISSUE TITLE
Custom model binder not working with swagger

### ISSUE THREAD

**Issue by ghost** [domaindrivendev/Swashbuckle#1425]
I have a custom model binder which binds data from route and from body into a single request model

    public async Task BindModelAsync(ModelBindingContext bindingContext)
    {
        if (bindingContext == null) throw new ArgumentNullException(nameof(bindingContext));

        bindingContext.HttpContext.Request.EnableBuffering();

        Stream body = bindingContext.HttpContext.Request.Body;

        body.Position = 0;

        string stringAsJson = await new System.IO.StreamReader(body).ReadToEndAsync();

        object modelInstance = JsonConvert.DeserializeObject(stringAsJson, bindingContext.ModelType);

        foreach (PropertyInfo propertyInfo in modelInstance.GetType()
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(propertyInfo => propertyInfo.GetCustomAttributes(typeof(FromRouteAttribute), false).Length > 0))
        {
            string routeFragmentValue = (string)bindingContext.ActionContext.RouteData.Values[propertyInfo.GetCustomAttribute<FromRouteAttribute>().Name];

            _typeConverter[propertyInfo.PropertyType].Invoke(propertyInfo, modelInstance, routeFragmentValue);
        }

        bindingContext.Result = ModelBindingResult.Success(modelInstance);
    }

which works just fine from postman, programatic api call, browser clients. 

However it does not work when using the swagger UI, to be more precise it fails at this line

    string stringAsJson = await new System.IO.StreamReader(body).ReadToEndAsync();

which returns an empty string, thus the modelInstance is null, which resutls in a null object access.

This is how the action looks 

        [HttpPut("{id}")]
        [MapToApiVersion("1")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public Task Update([ModelBinder(BinderType = typeof(CustomModelBinder))] EditSiteRequestrequest) => CommandAsync(Mapper.Map<EditSiteCommand>(request));

and this is the request object

    public class EditSiteRequest
    {
        [JsonIgnore]
        [FromRoute(Name = "id")]
        [NotDefault]
        public Guid Id { get; set; }

        [FromBody]
        public string Name { get; set; }
        [FromBody]
        public string Description { get; set; }
    }

What exactly do I have to do in order to make swagger work ?

**Comment by vardhan03** [comment]
Hello @remus-corneliu, I have the same structure for one of the endpoints. I am developing a web API using .NET 6.
With the custom model binder in the GET request, my swagger UI is not loading, can you please let me know if there is any way to resolve the issue?
