### ISSUE TITLE
Problem using namespaces to version Web APIs

### ISSUE THREAD

**Issue by TheGiggler** [domaindrivendev/Swashbuckle#143]
I initially appended this question to https://github.com/domaindrivendev/Swashbuckle/issues/51, but it may actually be a different issue.

I, too, have implemented the solution found at http://blogs.msdn.com/b/webdev/archive/2013/03/08/using-namespaces-to-version-web-apis.aspx for versioning my Web API.

For documentation, I've used your solution posted in Issue #51 and I am able to get the dropdown for multiple versions, and the documentation is rendered accordingly depending on which I select, which is great!

However, the urls for the API operations are in the form /api/{namespace}/v1.Controller/{id}, where "v1" should be in the place of "{namespace}".

Further, "namespace" is listed as a required parameter.

I'm guessing I'm missing some further configuration? 

Thanks!

**Comment by domaindrivendev** [comment]
Closing this one and referring back to the original #51 as it's all related to the same problem - namely the effect that replacing the DefaultHttpControllerSelector has on ApiExplorer and by extension, Swashbuckle.

Working on a more detailed response ...
