### ISSUE TITLE
Same controller in different version namespaces not seen

### ISSUE THREAD

**Issue by verronep** [domaindrivendev/Swashbuckle#144]
In my project, I have controllers versioned by namespaces.  For example, my folder structure looks like the following:

Controllers
- v1
--UsersController (namespace: Project.Controllers.v1.UsersController)
--TagsController (namespace: Project.Controllers.v1.TagsController)
--CategoriesController (namespace: Project.Controllers.v1.CategoriesController)

-v2
-- UsersController (namespace: Project.Controllers.v2.UsersController)
-- CategoriesController (namespace: Project.Controllers.v2.CategoriesController)

When I access swagger-ui, I only see TagsController in the list - not the UsersController or CategoriesController.  If I delete UsersController from one of the folders (doesn't matter which folder) then I see UsersController.

When I step through the following code, only controllers that are in one of the folders (not both) are in the array.

```csharp
c.SupportMultipleApiVersions(
                GetVersionsList(),
                (apiDesc, version) =>
                {
                    var controllerNamespace = apiDesc.ActionDescriptor.ControllerDescriptor.ControllerType.FullName;
                    if (CultureInfo.InvariantCulture.CompareInfo.IndexOf(controllerNamespace, string.Format(".{0}.", version), CompareOptions.IgnoreCase) >= 0)
                    {
                        return true;
                    }

                    return false;
                });
```

Any idea what I'm doing wrong?

(I'm using API versioning via accept-header, but I don't think that matters here - even when I revert to the standard Controller Selector with no versioning and comment out SupportMultipleApiVersions, the same behavior occurs).

Will also add that I'm using the latest release version (4.1)

**Comment by domaindrivendev** [comment]
Independent of Swashbuckle, have you verified that your versioned routes are working correctly. For example, are you able to hit the specific versions of each controller through something like "Postman"?

The default controller selector does NOT support name-spaced controllers - in fact if it completely removes the mappings when it encounters two controllers with the same name. This would result in the exact behavior you're seeing above - i.e. Tags is the only controller without a duplicate in another namespace. 

You mentioned a custom implementation for the controller selector. I would hazard a guess that it does not handle the duplicate controller issue correctly either. Can you pass on the code, in particular the implementation for __GetControllerMapping__? This method is used by WebApi's built-in metadata layer - ApiExplorer which itself is subsequently used by Swashbuckle.

The WebApi team advise against customizing the controller for this reason because, among other issues,  it breaks the descriptions generated by ApiExplorer. See the following for more info:

http://blogs.msdn.com/b/webdev/archive/2014/08/22/customizing-web-api-controller-selector.aspx

**Comment by Rohit9968** [comment]
I have two versions of  controllers with names say ABCV1Controller and ABCV2Controller, the version information come from the accept header and I have separate implementation to resolve the version information coming from the accept header which works fine in browser tools like RestClient. I want to know how to pass an accept header information and any other custom header information when using the swashbuckle tool. Kindly help.

**Comment by Chris-Upshop** [comment]
> Independent of Swashbuckle, have you verified that your versioned routes are working correctly. For example, are you able to hit the specific versions of each controller through something like "Postman"?
> 
> The default controller selector does NOT support name-spaced controllers - in fact if it completely removes the mappings when it encounters two controllers with the same name. This would result in the exact behavior you're seeing above - i.e. Tags is the only controller without a duplicate in another namespace.
> 
> You mentioned a custom implementation for the controller selector. I would hazard a guess that it does not handle the duplicate controller issue correctly either. Can you pass on the code, in particular the implementation for **GetControllerMapping**? This method is used by WebApi's built-in metadata layer - ApiExplorer which itself is subsequently used by Swashbuckle.
> 
> It's worth noting that the WebApi team advise against customizing the controller selector for this reason because, among other issues, it breaks the descriptions generated by ApiExplorer. See the following for more info:
> 
> http://blogs.msdn.com/b/webdev/archive/2014/08/22/customizing-web-api-controller-selector.aspx
> 
> I'm happy to offer my advice but am going to close this issue because I don't think it's an error with Swashbuckle. Swashbuckle merely maps ApiExplorer to a Swagger format. If you've extended WebApi in such a way that breaks ApiExplorer - then Swashbuckle cannot be responsible.

I'm looking for a way to make this work.  I do have my own HttpControllerSelector derived from DefaultHttpControllerSelector.  Code I found online (https://forums.asp.net/t/2124595.aspx?Managing+API+MVC+Controllers+with+the+same+Name).  What I'm trying to do is have Controllers with the same name but different namespace and routes.

/api/MyController/MyMethod
vs
/apitest/MyController/MyMethod

One is the real API the apitest is for testing purposes.  The code I found for the HttpControllerSelector does seem to do what I want but like others have found it breaks Swagger by not showing controllers at all that are duplicate.  Would love to find a solution for this if anyone can help.   My project is a C# WebAPI using the latest version of .NET (not using MVC or Core right now)
