### ISSUE TITLE
[Swashbuckle 4.0] Can't get description for a property inherits from parent class.

### ISSUE THREAD

**Issue by PeterZong** [domaindrivendev/Swashbuckle#150]
Hi,

I have a method:
public User GetUser([FromUri] GetUserRequest getUserRequest)

GetUserRequest inherits from GetRequest. The definition of the GetUserRequest and GetRequest:
    public class GetUserRequest : GetRequest
    {
        /// <summary>
        /// User id
        /// </summary>
        [Required]
        public int UserId { get; set; }
        /// <summary>
        /// User name
        /// </summary>
        [Required]
        public string UserName { get; set; }
        /// <summary>
        /// User status
        /// </summary>
        [Required]
        public UserStatus Status { get; set; }
        /// <summary>
        /// User address
        /// </summary>
        public Address Address { get; set; }
    }

    public class GetRequest
    {
        /// <summary>
        /// Other information
        /// </summary>
        public string Other { get; set; }
    }

I use operationFilter to convert the complex parameter to be several query parameters. I need to get model.Property.Value.Description for the every properties of GetUserRequest including Other property. But I can't get the description for the Other property which inherits from GetRequest class.

What should I do for this?

Thanks,
Peter

**Comment by domaindrivendev** [comment]
Fixed in the swagger_2.0 branch - hoping to release within a week or so

**Comment by domaindrivendev** [comment]
Swashbuckle 5.0.0 released! This issue should now be resolved. Please try it out when you get a chance.
