### ISSUE TITLE
ResponseMessage object does not allow specification of schema

### ISSUE THREAD

**Issue by shtusha** [domaindrivendev/Swashbuckle#155]
I have a common error model that is returned in case of http response codes >= 400.

swagger spec and swagger ui define a way to specify that schema...
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responses-definitions-object-

ResponseMessage class only has properties for code and message not for schema.

When adding standard response codes in my operationfilters I would like to specify a schema as well.

any plans on supporting that?

**Comment by domaindrivendev** [comment]
Which version of Swashbuckle are you using? The specification you've referenced above is for Swagger 2.0 and the current (stable) version of Swashbuckle only supports Swagger 1.2 which doesn't allow for Schema descriptions in the ResponseMessage

However, there is an alpha version of Swashbuckle which fully supports the 2.0 specification. If you're willing to make the upgrade, you will be able to add Schema's to your response messages

Read more here ... https://github.com/domaindrivendev/Swashbuckle/tree/swagger_2.0
