### ISSUE TITLE
SwaggerConfig should allow customized way of handling definitions / schema with the same name

### ISSUE THREAD

**Issue by ljhljh235** [domaindrivendev/Swashbuckle#157]
In some Web APIs there are response / request classes with the same names, while under different namespaces. SwaggerConfig should allow adding customized ways of handling them, similar to what we have today for resolving conflicting methods. Being allowed to something like
```csharp
c.ResolveConflictingDefinitions(defs => {
    return defs.ForEach(/* some work */);
});
```
would be very helpful.

**Comment by domaindrivendev** [comment]
I recently added the UseFullTypeNameInSchemaIds setting to the swagger_2.0 branch. This provides a workaround for API's that contain multiple classes with the same name.

**Comment by ljhljh235** [comment]
Thanks for adding that :)
