### ISSUE TITLE
MVC6 / ASP.NET 5 (previously known as vNext) support in Alpha 5?

### ISSUE THREAD

**Issue by Ciantic** [domaindrivendev/Swashbuckle#161]
I just installed Visual Studio 2015. I'm wondering does the Swashbuckle Alpha 5 support MVC6 aka ASP.NET 5?

Edit: More info about vNext at http://www.asp.net/vnext it appears to be in beta: https://github.com/aspnet/home

**Comment by domaindrivendev** [comment]
Not yet but it's next up in the pipeline!

**Comment by colemickens** [comment]
Any update on this? A branch where we can watch progress or try stuff out for vnext?

**Comment by domaindrivendev** [comment]
Hey there

I've just kicked off this work and will get something available to view (either as a branch or separate repo)  very shortly. Hang tight ...

**Comment by troyschneringer** [comment]
any word on this?

**Comment by domaindrivendev** [comment]
Working on a local "spike" branch at the moment but still a ways off something that could be tested out.

Rest assured, it's top priority at the moment and is getting all the free time I can spare :). Will update the ticket as soon as I have something to share.

**Comment by SiqiLu** [comment]
Could you share the branch online? This is really wanted.

**Comment by domaindrivendev** [comment]
See working repo here - https://github.com/domaindrivendev/Ahoy
