### ISSUE TITLE
XML doc comments do not render proper HTML

### ISSUE THREAD

**Issue by tillig** [domaindrivendev/Swashbuckle#166]
XML doc comments [can sometimes include additional tags](https://msdn.microsoft.com/en-us/library/5ast78ax.aspx) that need to be translated into HTML markup. For example, this...

```csharp
/// <remarks>
/// <para>
/// There's a little <c>inline code</c> here.
/// </para>
/// <para>
/// This is a list of information.
/// </para>
/// <list type="bullet">
/// <item>
/// <term>First Item</term>
/// </item>
/// <item>
/// <term>Second Item</term>
/// </item>
/// </list>
/// </remarks>
```

...should be translated into this:

```html
<p>
There's a little <code>inline code</code> here.
</p>
<p>
This is a list of information.
</p>
<ul>
<li>First Item</li>
<li>Second Item</li>
</ul>
```

This sort of thing becomes problematic when including XML API documentation directly into the Swagger docs - it renders all wrong, sometimes hiding information (because the browser doesn't know, say, what a `<c>c tag</c>` is) and that isn't so great.

The XML API doc inclusion should support rough HTML translation with at least [the standard set of C# doc elements](https://msdn.microsoft.com/en-us/library/5ast78ax.aspx).

**Comment by tillig** [comment]
**Let me know if this is something interesting to include in the project.** I already have [a reasonable body of code](https://code.google.com/p/cr-documentor/) that does this sort of conversion that I could adapt for this purpose and submit a pull request. The [NuDoc package might also help here](http://www.nuget.org/packages/NuDoc/) since it already allows reading the XML doc files into an in-memory structure.

But I won't go to the effort if it's not interesting to include.

**Comment by pareshnawale** [comment]
Hi Travis,
Could you please share your solution? In my case only <summary> tag is showing up in Swagger UI.
I tried <response> as mentioned in document but no luck.

Thanks
Paresh

**Comment by tillig** [comment]
I don't actually _have it done_ but when I do end up getting it done, I can submit a PR if it has a chance of being accepted. I won't trouble folks if it's not interesting.

**Comment by stevegreatrex** [comment]
I definitely think this would be useful - so much so that I wrote a partial solution myself.  You can see it at #189

**Comment by domaindrivendev** [comment]
Closing as there's more detail in a duplicate - #258. Please refer to that ticket for further updates on this issue
