### ISSUE TITLE
Nullable primitives on a model

### ISSUE THREAD

**Issue by enkafan** [domaindrivendev/Swashbuckle#172]
This is more related to an issue with the Swagger spec itself (https://github.com/swagger-api/swagger-spec/issues/229) but I thought it would be important to track here too. Right now there's no difference between a required field and a nullable field. Let's say I have a model that looks like this

```csharp
class Product
{
    [Required]
    public int ProductId {get;set;}

    [Required]
    public string ProductName {get;set;}

    public string Description {get;set;}

    [Required]
    public int? SomeSuperValidReasonThisFieldShouldBeNullableAndRequiredBesidesBadDesignThatImMarriedTo {get;set;}
}
````

The best way to do this would be have the nullable field be `"type" : ["number","null"]`but alas swagger doesn't support that. 

Right now I'm adding in custom mapping in the swaggerconfig for each of the main nullables and praying no one else does anything weird in the project to require other value types to be exposed as a nullable and putting a vendor extension of "x-nullable"

**Comment by withinboredom** [comment]
Also misses it on parameters. For example:

``` csharp
[Route("{secretName:alpha}/{version:int?}")]
[HttpGet]
public Secret GetSecret([FromUri] string secretName, [FromUri] int? version = null)
```

Shows version as required even though it has a default set and its set as optional in the route.

**Comment by domaindrivendev** [comment]
I'm going to close this as it's a Swagger limitation. It's worth noting that in a separate thread I'm proposing the introduction of a separate package that extends Swashbuckle with vendor extensions that are required for client generators such as AutoRest - #776
