### ISSUE TITLE
[ResponseType(typeof(IEnumerable<int>))] not showing up correctly in Swagger UI

### ISSUE THREAD

**Issue by DavidDeSloovere** [domaindrivendev/Swashbuckle#173]
I've used the ResponseType attribute successfully for lists of complex types.
But for an array/list of integers the Swagger UI doesn't show the correct response.

![image](https://cloud.githubusercontent.com/assets/352626/5939573/3464fb10-a705-11e4-855e-fd5fc81c6c04.png)

5.0.0-alpha

**Comment by domaindrivendev** [comment]
Hey there

This is a bug with swagger-ui. I've already submitted the issue and am tracking daily so that I can get a fix in to Swashbuckle asap.

https://github.com/swagger-api/swagger-ui/issues/857

Richie

**Comment by DavidDeSloovere** [comment]
If only I had thought of looking in the swagger ui repo. 
Thanks for this.
