### ISSUE TITLE
Add support for X-Forwarded-Proto that checks http/https

### ISSUE THREAD

**Issue by DavidDeSloovere** [domaindrivendev/Swashbuckle#174]
After a few hours of coding, testing, building, deploying I have come to the conclusion that SSL offloading and DefaultRootUrlResolver are a bad combination. 
This isn't a bug in Swashbuckle, or even the .NET framework for that matter. 

The loadbalancer forwards an https request to the webserver as http, so the root url (or more precisely the schema) is also returned as http by Swashbuckle. However the original request was over https.

It can easily be fix by checking the headers. I would like to contribute this code to Swashbuckle so other people won't have to go through the same frustration as I did. 
Can I send a PR and if so in the swagger_2.0 branch?

I'm talking about this method:
https://github.com/domaindrivendev/Swashbuckle/blob/swagger_2.0/Swashbuckle.Core/Application/SwaggerDocsConfig.cs#L220

**Comment by domaindrivendev** [comment]
Yep - load balanced/proxy environments is exactly the reason why the RootUrl can be configured with a custom lambda that takes a HttpRequestMessage.

But if your happy that the "X" headers are standard enough to incorporate into the default resolver, then it would be nice to solve this out-of-the-box for other people. I guess technically it should account for all the forwarded headers?

X-Forwarded-Proto
X-Forwarded-Host
X-Forwarded-Port

Thanks for your input on this - a PR would be awesome.

**Comment by DavidDeSloovere** [comment]
PR has been created: https://github.com/domaindrivendev/Swashbuckle/pull/176
