### ISSUE TITLE
Generation of doc from xml comments does not work when the type of an argument is a nested class

### ISSUE THREAD

**Issue by mbettex** [domaindrivendev/Swashbuckle#177]
When generating the doc of an endpoint from xml comments of the method, if the type of an argument of the method is a nested class, the documentation is not properly generated. Here is an example:

```C#
using System.Web.Http;

namespace Doc.Controllers
{
    public class DemoController : ApiController
    {
        /// <summary>
        /// My demo endpoint that does not work :-(
        /// </summary>
        public string Get(InternalClass argument)
        {
            return "hello";
        }

        public class InternalClass
        {
            public string Value { get; set; }
        }
    }
}
```

The problem is in ApplyActionXmlComments.TypeNameFor(...) method. When the type is a nested type, the type name returned does not match what is in the xml documentation. Because of that, the filter does not find the node in the xml documentation and the filter is skipped.

**Comment by domaindrivendev** [comment]
Swashbuckle 5.0.0 released! This issue should now be resolved. Please try it out when you get a chance.

**Comment by mbettex** [comment]
I tried it and it works fine.

Thanks a lot for the super quick fix :-)
