### ISSUE TITLE
How to specify no return type when using IHttpActionResult

### ISSUE THREAD

**Issue by skrusty** [domaindrivendev/Swashbuckle#179]
Hi,

Is it possible to make the swagger definition return no return type when using IHttpActionResult to control responses from an ApiController?

Currently, you can use [ResponseType()] attribute to force a specific return type (and not show IHttpActionResult) but you can't make it show no return type (that I can see). Any suggestions?

e.g. 
```c#
public IHttpActionResult SomeMethod(string someParam)
{
    return Ok();
}
```

**Comment by domaindrivendev** [comment]
I'm wondering if the use of IHttpActionResult is really necessary here. If you just make the action return void, then WebApi will respond with a 204 - No Content which seems appropriate in this case ... or am I missing something.

**Comment by skrusty** [comment]
I think you're right, I was trying to use one pattern fits all, and I really should have just been using void and then (for example)
```c#
throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));
```
For passing back http responses.

using void worked just fine, thanks for you quick response
