### ISSUE TITLE
ActionName Attribute to override Nickname

### ISSUE THREAD

**Issue by skrusty** [domaindrivendev/Swashbuckle#181]
Is it possible to override the default nickname in the swagger spec? I tried using the ActionName attribute, but that has no effect.

I see that the nickname is populated from ApiDescription.ActionDescriptor.ActionName. Any pointers on how this can be set in code?

Thanks

**Comment by stevegreatrex** [comment]
+1

**Comment by domaindrivendev** [comment]
You can create a custom "Operation Filter" (see readme) and in it set the nickname on each Operation according to your own custom strategy.
