### ISSUE TITLE
Support for "containers of containers"

### ISSUE THREAD

**Issue by stevegreatrex** [domaindrivendev/Swashbuckle#182]
If I'm reading the [swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#items-object-) correctly, 2.0 includes support for containers of containers or nested arrays.

I can't find any examples of how such a scenario should appear in the swagger definition.  There's nothing in the pet store examples (see https://github.com/swagger-api/swagger-spec/issues/273) but if someone can provide some guidance then I'm happy to implement the change

**Comment by domaindrivendev** [comment]
The complete 2.0 specification and therefore nested containers will be supported in the next major version of SB (currently in alpha and available as a Nuget pre-release package)
