### ISSUE TITLE
5.0 {{basePath}} not set

### ISSUE THREAD

**Issue by kspearrin** [domaindrivendev/Swashbuckle#191]
Using the new v5 release. I notice that the `{{basePath}}` property is not set in the main.handlebars template.

Screenshots:
http://puu.sh/g0Sy4/419c5a00b2.png
http://puu.sh/g0SAQ/627d1cb86a.png

**Comment by domaindrivendev** [comment]
What value are you expecting to be there? "basePath" will only have a value if your API is hosted under a virtual directory.
