### ISSUE TITLE
5.0 Request Model Types Not Correct

### ISSUE THREAD

**Issue by kspearrin** [domaindrivendev/Swashbuckle#192]
Since moving to v5, my request model types are not correct. Every property shows as a string type.

Example

    public class RequestModel
    {
        [Required]
        public int? CategoryId { get; set; }

        [Required]
        public decimal? UnitPrice { get; set; }

        [Required]
        public bool? IsFavorite { get; set; }

        public string Description { get; set; }

        public IEnumerable<int> ModifierIds { get; set; }
    }

Generates as:

    {
      "CategoryId": "string",
      "UnitPrice": "string",
      "IsFavorite": "string",
      "Description": "string",
      "ModifierIds": [
        0
      ]
    }

Interesting that the `IEnumerable<int>` did generate correctly though.

**Comment by kspearrin** [comment]
Any idea what's going on here? I am unable to upgrade to 5.0 because of this.

**Comment by domaindrivendev** [comment]
Thanks for this. I can confirm it's a bug - it seems nullable types are not handled correctly.

I'll be getting a fix out for this ASAP ... stay tuned!

**Comment by domaindrivendev** [comment]
Should be fixed in latest release (5.0.1)
