### ISSUE TITLE
5.0: how to add XML comments for OData endpoints

### ISSUE THREAD

**Issue by codesoul** [domaindrivendev/Swashbuckle#195]
Hi,

I have been trying to produce a Swagger JSON file from an OData enabled Web API project (using ASP.NET MVC 5, Web API 2.2, OData4 and Swashbuckle V5).

It seems there are very few resources on the web about the topic - this blog post shows that it IS possible to provide support for it: http://catchsoftware.com/blogs/2013/08/get-your-swagger-on/

I also found an OData.org sample swagger json file, which is located here:
https://github.com/OData/ODataSamples/tree/master/swagger
And with 1317 lines of json, I figured that it wasn't handwritten...

It seems that the required XML Comments are not extracted at build time by the WebApi ApiExplorer for OData endpoints according to this SO answer: http://stackoverflow.com/a/23097825 

The last section in the md help file seems to indicate that the magic tricks will be described soon:
https://github.com/domaindrivendev/Swashbuckle#how-to-configure-oauth2-support

Can anybody share how to do it?
Any help, hints or links would be much appreciated.

Best regards,
Morten

**Comment by domaindrivendev** [comment]
Unfortunately, this is a Swagger constraint and not an issue with SB. These "conflicting operations" cannot be described individually in a Swagger 2.0 document. If you don't want to change your application code, you can merge the resulting Operation descriptions, i.e. for the purposes of documentation only, as described in the readme ...

https://github.com/domaindrivendev/Swashbuckle#working-around-swagger-20-constraints

Here's another discussion on the subject ...

https://github.com/domaindrivendev/Swashbuckle/issues/142

**Comment by rbeauchamp** [comment]
@codesoul Try [Swashbuckle.OData](https://github.com/rbeauchamp/Swashbuckle.OData). It now supports XML comments on ODataControllers.
