### ISSUE TITLE
No API description with MVC 5

### ISSUE THREAD

**Issue by Iloshka** [domaindrivendev/Swashbuckle#197]
I got 2 controllers with routing attributes

    [Route("api/v1/countries")]
    public class CountriesV1Controller : ApiController
    {
        // GET api/v1/countries
        public string Get()
        {
            return "Response from CountriesV1";
        }
    }

    [Route("api/v2/countries")]
    public class CountriesV2Controller : ApiController
    {
        // GET api/v2/countries
        public string Get()
        {
            return "Response from CountriesV2";
        }
    }

If i choose MultipleApiVersions, it doesnt allow show any methods
                        c.MultipleApiVersions(
                            (apiDesc, targetApiVersion) => ResolveVersionSupportByRouteConstraint(apiDesc, targetApiVersion),
                            (vc) =>
                            {
                                vc.Version("v2", "Swashbuckle Dummy API V2");
                                vc.Version("v1", "TestAPI");
                            });
![image](https://cloud.githubusercontent.com/assets/8014244/6277609/dc026a92-b844-11e4-9235-32ac6995cff9.png)

If I select SingleApiVersion, i see 2 different versions, with API version v1
![image](https://cloud.githubusercontent.com/assets/8014244/6277646/2ee916fc-b845-11e4-83c9-7ef2a62f6542.png)

Is Swashbuckle 5.0 support routing attributes? If so, what im doing wrong?

**Comment by domaindrivendev** [comment]
Can I see your impl of ResolveVersionSupportByRouteConstraint? Have you confirmed it works for the  versioned route pattern your using above?

**Comment by Iloshka** [comment]
Here is implementation
        public static bool ResolveVersionSupportByRouteConstraint(ApiDescription apiDesc, string targetApiVersion)
        {
            var versionConstraint = (apiDesc.Route.Constraints.ContainsKey("apiVersion"))
                ? apiDesc.Route.Constraints["apiVersion"] as RegexRouteConstraint
                : null;

            return (versionConstraint == null)
                ? false
                : versionConstraint.Pattern.Split('|').ToList().Contains(targetApiVersion);
        }

I am able to hit API directly, using routes.

**Comment by domaindrivendev** [comment]
So that impl is not going to work. It is expecting a reg ex constraint in your Routes which you are not using. It's up to the consuming application to tell SB how to determine which API's belong to which versions - it cannot know this. The code above is just copied from the SB Dummy app which implements versioning via regex Route constraints.

You need to tweak it for your implementation ...
