### ISSUE TITLE
Schemalogic does not take a type's namespace into account

### ISSUE THREAD

**Issue by joerisneyders** [domaindrivendev/Swashbuckle#199]
Hi,

We recently started using the Swashbuckle and noticed that for several operations on our controllers the documentation was not correct.  After digging into to code I noticed that the namespace of a type is not taken into account when building the schema definitions.

To illustrate this behaviour, I created the following example:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Http;

namespace eXimius.Api.Services.Namespace1
{
    public class TestRequest
    {
        public string TestPropertyForNamespace1 { get; set; }
    }
}

namespace eXimius.Api.Services.Namespace2
{
    public class TestRequest
    {
        public string TestPropertyForNamespace2 { get; set; }
    }
}

namespace eXimius.Api.Services
{
    [System.Web.Http.RoutePrefix("api/test")]
    public class TestController : System.Web.Http.ApiController
    {
        [System.Web.Http.Route("method1")]
        public IHttpActionResult Method1(eXimius.Api.Services.Namespace1.TestRequest request)
        {
            return this.Ok();
        }

        [System.Web.Http.Route("method2")]
        public IHttpActionResult Method2(eXimius.Api.Services.Namespace2.TestRequest request)
        {
            return this.Ok();
        }
    }
}

Swagger UI  is showing the following:

![capture](https://cloud.githubusercontent.com/assets/6309519/6283728/8212c55a-b8e8-11e4-9fac-f582da48c00f.JPG)

When looking at the swashbuckle code I noticed that the method to create a friendlyId only looks at the name of a type and ignores the namespace.

public static string FriendlyId(this Type type)
{
	if (type.IsGenericType)
	{
		string[] array = (
			from t in type.GetGenericArguments()
			select t.FriendlyId()).ToArray<string>();
		return new StringBuilder(type.Name).Replace(string.Format("`{0}", array.Count<string>()), string.Empty).Append(string.Format("[{0}]", string.Join(",", array).TrimEnd(new char[]
		{
			','
		}))).ToString();
	}
	return type.Name;
}

Will this scenario be supported in the future?

**Comment by domaindrivendev** [comment]
Swagger describes a HTTP/REST API and not C# classes. So, IMO, it should not leak implementation details like full C# type names. This is the rationale behind my decision to omit namespaces in Schema identifiers by default.

With that said, if you upgrade to Swashbuckle 5.0 (may have breaking changes) you can opt-in to the behavior you're looking for ...

https://github.com/domaindrivendev/Swashbuckle#usefulltypenamesinschemaids
