### ISSUE TITLE
Shashbuckle 5.0 support for Swagger 1.x

### ISSUE THREAD

**Issue by Iloshka** [domaindrivendev/Swashbuckle#201]
After i finished my project using Shashbuckle 5.0, i was told that our Service Portal doesnt support Swagger 2.0. I tried to downgrade to 4.2, but then i loose routing attribute. How hard is to add an option to select Swagger version?

**Comment by domaindrivendev** [comment]
Sorry ... I'm not going to support the (vastly different) 1.2 spec in the latest version. The code is so different it would amount to maintaining two libraries.

Not sure what you mean by "route attribute"? Attribute routing is fully supported in 4.x. If there is a feature you want in 4.x, fork off the 4.2 tag and submit a PR. I'd be happy to release a hot fix for 4.x
