### ISSUE TITLE
index.html 404 (Not Found)

### ISSUE THREAD

**Issue by seesharper** [domaindrivendev/Swashbuckle#203]
This is a self hosted Web Api and I have followed the installation procedure as described in the docs.

When I try to navigate to http://localhost:8080/swagger/ui/index.html it returns with the following message:

{"Message":"An error has occurred.","ExceptionMessage":"Mapping not found - index.html","ExceptionType":"Swashbuckle.SwaggerUi.AssetNotFound","StackTrace":"   at Swashbuckle.SwaggerUi.EmbeddedAssetProvider.GetAsset(String rootUrl, String path)\r\n   at Swashbuckle.Application.SwaggerUiHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)"}

My startup is like this.

    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var config = new HttpConfiguration();
            
            ConfigureHttpRoutes(config);
            config.MapHttpAttributeRoutes();
            config.Formatters.Clear();
            config.Formatters.Add(new JsonMediaTypeFormatter());
            config.EnableSwagger(c => c.SingleApiVersion("v1", "TEST")).EnableSwaggerUi();            
            app.UseWebApi(config);

        }

        private static void ConfigureHttpRoutes(HttpConfiguration config)
        {
            config.Routes.MapHttpRoute(
                name: "API Default",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
    }

My packages config 

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebApi.OwinSelfHost" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.Owin" version="2.0.2" targetFramework="net451" />
  <package id="Microsoft.Owin.Host.HttpListener" version="2.0.2" targetFramework="net451" />
  <package id="Microsoft.Owin.Hosting" version="2.0.2" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net451" />
  <package id="Owin" version="1.0" targetFramework="net451" />
  <package id="Swashbuckle.Core" version="5.0.1" targetFramework="net451" />
</packages>
```

Navigating to http://localhost:8080/swagger/docs/v1 returns the raw json as expected
```json
{"swagger":"2.0","info":{"version":"v1","title":"TEST"},"host":"localhost:8080","schemes":["http"],"paths":{"/api/Values":{"get":{"tags":["Values"],"operationId":"Values_Get","consumes":[],"produces":["application/json","text/json"],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Object"}}},"deprecated":false}}},"definitions":{"Object":{"type":"object","properties":{}}}}
```

This is where it breaks

        public Asset GetAsset(string rootUrl, string path)
        {
            if (!_pathToAssetMap.ContainsKey(path))
                throw new AssetNotFound(String.Format("Mapping not found - {0}", path));

the path is "index.html", but the key in pathToAssetMap is "index"

If I change the path from "index.html" to "index" in the debugger and continue, the ui loads as expected. 

Any idea what I'm doing wrong here?

**Comment by domaindrivendev** [comment]
As of v 5.0, SB serves up the swagger-ui via extension-less URL's. This removes the need to have runAllManagedModuledForAllRequests set in your web.config which was causing perf. concerns for many people.

So, you've really answered this yourself ... just navigate to swagger/ui/index to view the UI. If you already have your docs published at index.html and don't want to break live links, you should just add a permanent redirect to your web server

**Comment by seesharper** [comment]
That makes perfect sense. Thanks a lot for your help

**Comment by jon-peel** [comment]
I get a 404 when I look at "swagger/ui/index", but "swagger/docs/v1" shows JSON.

Any idea of what I might be able to look at?
