### ISSUE TITLE
IEnumerable<primitive> is not working

### ISSUE THREAD

**Issue by christopheblin** [domaindrivendev/Swashbuckle#211]
Let's say you have the following [ResponseType(typeof(UserEntry))]

UserEntry is the following :
```c#
public class UserEntry
	{
                public IEnumerable<string> Tokens { get; set; }
                public IEnumerable<Application> Apps { get; set; }
	}
```

Then in swagger-ui, for the model I have
```javascript
"tokens": [
    "string"
  ],
"apps": [
    {
      "id": "string",
      "name": "string",
      "url": "string"
    }
  ]
```

So far so good (it seems all good i nthe json model too) but now when I click on the Model, I have 
```
tokens(string, optional)  //here is problematic
apps(Array[Application], optional) //here is ok
```
whereas I should have
```
tokens(Array[string], optional)  
apps(Array[Application], optional)
```

This is with swashbucle 5.0.0 (5.0.1 seems to reproduce the problem too).

Is this only a problem from swagger-ui or also from swashbuckle, I can not say...

**Comment by domaindrivendev** [comment]
Hi there

Thanks for the update - it's a straightforward and repro and looks to me like a bug in the swagger-ui. Would you mind creating an issue there and referencing this one?

At it's core SB is a Swagger generator. It just comes bundled with infrastructure to serve an up-to-date version of swagger-ui through your WebApi. With this in mind, it's a pretty good rule of thumb to say if the raw Swagger doc looks correct but the ui is behaving incorrectly, then it's likely a bug in the swagger-ui. Not definitely, but likely :)

Cheers

**Comment by christopheblin** [comment]
BTW, in the latest version of swagger-ui you packaged in swashbuckle5.0.1, there is a more critical bug because when you click on model there is nothing displayed at all...

So you will have 2 reasons to upgrade to a newer version of swagger-ui :)

**Comment by domaindrivendev** [comment]
Appears to fixed with the latest swagger-ui which I've bundled into a SB pre-release (5.1.0-rc1). Can you please check it out and make sure everything works as expected ...

    Update-Package Swashbuckle -Pre
