### ISSUE TITLE
send string as form data when sending files does not add string to payload

### ISSUE THREAD

**Issue by giladwe** [domaindrivendev/Swashbuckle#212]
i tried using [fromBody], and got a binding error .

then i tried adding a param in  IOperationFilter like this, but the parameter was not sent:
operation.parameters.Add(new Parameter { name = "key", @in = "body", required = false, type = "string"});

**Comment by kobynet** [comment]
We are facing the same issue. any help?

**Comment by giladwe** [comment]
this is the way i try to add file and string in the form data.
it can send only files, or only strings. not both.

public class AddFileUploadParams : IOperationFilter
	{
		public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
		{
			if (operation.operationId == "id")
			{
				operation.consumes.Add("application/form-data");
				operation.parameters.Add(new Parameter { name = "File", @in = "formData", required = false, type = "file" });
				operation.parameters.Add(new Parameter { name = "File2", @in = "formData", required = false, type = "file" });
				operation.parameters.Add(new Parameter { name = "Key", @in = "formData", required = false, type = "string" });
			}
		}
	}

**Comment by giladwe** [comment]
maybe related to this issue
https://groups.google.com/forum/#!topic/swagger-swaggersocket/V9CcJyHdDv0

**Comment by domaindrivendev** [comment]
This is fixed in the latest version
