### ISSUE TITLE
XML comment - Response codes

### ISSUE THREAD

**Issue by babinecm** [domaindrivendev/Swashbuckle#216]
Hello,
when I comment my API method with xml comment like this

`<response code="401">Unauthorized</response>`

then I don't see model schema in Swagger UI, see following image:

![snap_2015 03 09_12h17m42s_001](https://cloud.githubusercontent.com/assets/11158216/6554020/2df0bc8a-c657-11e4-852c-678b8690806a.png)

When I remove response xml comment, model schema is shown:

![snap_2015 03 09_12h18m33s_002](https://cloud.githubusercontent.com/assets/11158216/6554073/b07997b2-c657-11e4-9334-4599aaee4299.png)

What's the problem?

**Comment by domaindrivendev** [comment]
I guess you can consider SB as having two modes when it comes to response codes ... "implicit" and "explicit". In the former case it will use WebApi default behavior (200/204) for success and provide the model from response type automatically.

If you want to be explicit (as in your case) then it expects you to specify "all" response codes not just the error cases. If you add a 2xx code in your Xml comments you should get the model

**Comment by babinecm** [comment]
Problem solved. Thank you very much.
