### ISSUE TITLE
Xml Documentation: Add support for specifying a return type

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle#221]
All of our api methods return `IHttpActionResult` as a result our documentation is very limited. I'd like to be able to specify a return type like

```xml
/// <returns><see cref="PersistentEvent"/></returns>
```

It would be also nice to specify if return header values (as we also return a link to the next and previous document).

**Comment by pareshnawale** [comment]
You can use ResponseType attribute to specify return type
```
[ResponseType(typeof(ModelNameHere)]
```

**Comment by niemyjski** [comment]
Thanks!
