### ISSUE TITLE
Change default api_key query string parameter to access_token

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle#222]
Is there any way to change the default access key query string that is appended from api_key to access_token.

I tried adding this to my custom.js file

```js
ApiKeyButton.prototype.applyApiKey = function () {
    var elem;
    window.authorizations.add('access_token', new ApiKeyAuthorization('access_token', $("#input_apiKey_entry").val(), this.model["in"]));
    window.swaggerUi.load();
    return elem = $('#apikey_container').show();
};
```

**Comment by domaindrivendev** [comment]
Hi there

Admittedly, there is a general lack of support for this in both SB and to a lesser extent the swagger-ui.

However, SB does provide a simple mechanism to inject custom JavaScripts into the UI which you can use to workaround this issue with relative ease. You should have a quick read over the section in the readme entitled "Injecting Custom Content". Then, tweak and inject the following script:

    $(function () {
        $('#input_apiKey').off();
        $('#input_apiKey').on('change', function () {
            value = this.value;
            if (value && value.trim() != '')
                window.authorizations.add('myKey', new ApiKeyAuthorization("mykey", value, "header"));
        });
    });

**Comment by niemyjski** [comment]
Thanks, I'll try it out in the morning :)

**Comment by niemyjski** [comment]
I wasn't able to get this to work with that code. I was able to get it to work if it was appended to the header with the following code:

```javascript
$(function () {
    $('#input_apiKey').off();
    $('#input_apiKey').on('change', function () {
        var key = this.value;
        if (key && key.trim() !== '') {
            key = 'Bearer ' + key;
            window.authorizations.add('key', new ApiKeyAuthorization('Authorization', key, 'header'));
        }
    });
})();
```

**Comment by replaysMike** [comment]
Thanks guys, this resolved it for me as well.

**Comment by RobvanGeloven** [comment]
@niemyjski 
With your solution I get  "Uncaught TypeError: value.apply is not a function".

Anyone got an idea what that's about?

**Comment by niemyjski** [comment]
@RobvanGeloven Are you sure you are seeing an issue with my code? I'm not calling apply() anywhere.

**Comment by RobvanGeloven** [comment]
My apolagies: I see that there's an updated script on the wiki:

// add a new SwaggerClient.ApiKeyAuthorization when the api-key changes in the ui.
$('#input_apiKey').change(function() {
  var key = $('#input_apiKey')[0].value;
  if(key && key.trim() != "") {
    swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("api_key", key, "header"));
  }
})

That one works like charm :)

**Comment by johnnyqian** [comment]
Thank you guys, you save me a night.
