### ISSUE TITLE
Using the apiKey security scheme in header not working

### ISSUE THREAD

**Issue by replaysMike** [domaindrivendev/Swashbuckle#224]
Hi guys,

I'm currently using the following security setting for the api-key:

c.ApiKey("apiKey")
   .Description("API Key Authentication")
   .Name("apikey")
   .In("header");

It seems to however always be sent via query string, instead of a header. Is there a mistake in the default template?

Thanks!

**Comment by domaindrivendev** [comment]
Merging with #222 as the subtext for both issues is just a general lack of support for api keys authorization. See that issue for a fairly simple workaround.
