### ISSUE TITLE
How to displaying Multiselect in Swagger UI? 

### ISSUE THREAD

**Issue by spyksoftware** [domaindrivendev/Swashbuckle#225]
Hi there,

I notice in the public Petstore swagger example, "Find Pet by Status", you can provide a multiselect list of strings.  http://petstore.swagger.io/#!/pet/findPetsByStatus

How do we do that with Swashbuckle? 

I've tried each of an array of enums, List of enums, IEnumerable of  enums, and enabled " c.DescribeAllEnumsAsStrings();" in Swashbuckle Config.

Thanks, and thanks for a brilliant tool!

Tim

**Comment by valentinedwv** [comment]
I used attributes, and fixed values, see: SwaggerEnumValue in

https://github.com/valentinedwv/CuahsiWOFSwagger/blob/master/Wb/Wb/SwaggerDefaultValues.cs
