### ISSUE TITLE
Documentation is skipped on array types

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle#227]
I have a few of the following methods defined as follows

```csharp
        [Route("{ids:objectids}")]
        public override Task<IHttpActionResult> Delete([CommaDelimitedArray]string[] ids) {
            return base.Delete(ids);
        }
```

I found that if the type is an array then the documentation isn't picked up. @domaindrivendev Do you have a workaround for this issue?

**Comment by niemyjski** [comment]
Do I need to do something like this: https://github.com/domaindrivendev/Swashbuckle/issues/128 ?

**Comment by niemyjski** [comment]
I tried that and it didn't work ideas?

**Comment by niemyjski** [comment]
@domaindrivendev I've updated this issue as I found the root behavior that is causing this.

**Comment by domaindrivendev** [comment]
There are known issues around arrays with the swagger-ui currently being worked. See #200 and #211. Is this a different issue to these?

**Comment by niemyjski** [comment]
This seems to be a completely different issue. It's not even contained in the schema or listed in the ui (I searched for my comment of remove and it wasn't even in the list).

**Comment by domaindrivendev** [comment]
Hi there

I'm unable to repro this issue. Can you try with the latest version?

**Comment by niemyjski** [comment]
We are using the latest stable version
