### ISSUE TITLE
SwaggerConfig won't compile

### ISSUE THREAD

**Issue by onkami** [domaindrivendev/Swashbuckle#232]
Hello, regarding Swashbuclke 5:

in freshly installed SwaggerConfig.cs I un-commented lines 

                        c.IncludeXmlComments(GetXmlCommentsPath());

                        c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());

and got messages:

Error	1	Cannot convert lambda expression to type 'string' because it is not a delegate type	C:\SVN\samplemgmt\src\Core\SamWise.Core.WebApi\App_Start\SwaggerConfig.cs	17	32	SamWise.Core.WebApi
Error	2	The name 'GetXmlCommentsPath' does not exist in the current context	C:\SVN\samplemgmt\src\Core\SamWise.Core.WebApi\App_Start\SwaggerConfig.cs	136	46	SamWise.Core.WebApi
Error	3	'System.Collections.Generic.IEnumerable<System.Web.Http.Description.ApiDescription>' does not contain a definition for 'First' and no extension method 'First' accepting a first argument of type 'System.Collections.Generic.IEnumerable<System.Web.Http.Description.ApiDescription>' could be found (are you missing a using directive or an assembly reference?)	C:\SVN\samplemgmt\src\Core\SamWise.Core.WebApi\App_Start\SwaggerConfig.cs	143	88	SamWise.Core.WebApi

What would be the way to fix this?

**Comment by domaindrivendev** [comment]
The commented sections are just samples. You need to provide the path for  you're Xml comment files

**Comment by domaindrivendev** [comment]
Same goes for the conflicting actions lambda
