### ISSUE TITLE
No responce types

### ISSUE THREAD

**Issue by Cromathaar** [domaindrivendev/Swashbuckle#233]
Hi.
I installed Swashbuckle 5.0.4 to my project which runs Web API 2.2 and targets .NET Framework  4.5.1. In works but not entirely. In particular there are no response types. At all. Even if I do a really simple thing like

        [HttpPost]
        [Route("signin")]
        public String SignIn()
        {
            return "gererated access token";
        }

UI doesn't show String as a response type (I tried a custom type as well, still no luck). Descriptions are there, Response Messages are there, even input parameters are there, but no Response Types. Tried 

        [ResponseType(typeof(String))]

attribute as well, doesn't really make any difference. Am I doing this wrong or is it a bug or is it maybe something else?

**Comment by Cromathaar** [comment]
Figured out that it actually works if no <response> tags are used in XML descriptions. However the question now is why those tags break the stuff.

**Comment by domaindrivendev** [comment]
SB offers two approaches for specifying response types - "implicit" and "explicit". The former includes a 200 (or 204 for void) and creates the response schema according to your declared response type.

The custom "response" tags can be used if you need to be explicitly list many responses. But, being "explicit", it does expect a tag for all response codes not just the errors.

In summary, if you're using the response tags, you also need to specify the 2xx response

**Comment by Cromathaar** [comment]
Got it, now it works. Thank you a lot!
