### ISSUE TITLE
Add custom non-controller operation

### ISSUE THREAD

**Issue by kelostrada** [domaindrivendev/Swashbuckle#234]
I would like to add a custom operation which isn't a part of any controller. For example I use owin token authorization and I would like to include the `/token` action into Swagger to be able to test just the login action. Is it possible?

**Comment by domaindrivendev** [comment]
Yep - you can create an IDocumentFilter (see readme) that modifies the SwaggerDocument after it's generated. Just have your implementation add the description for the token operation.

NOTE: Here you're essentially authoring your own Swagger description and so should have a reasonable understanding of the 2.0 spec. I don't know the exact semantics of the operation above so you'll need to tweak accordingly but here's and example to get you started ...

    public class AddAdditionalOperations : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
        {
            swaggerDoc.paths.Add("/token", new PathItem
                {
                    post = new Operation
                    {
                        operationId = "CreateToken",
                        parameters = new[] {
                            new Parameter
                            {
                                name = "createTokenBody",
                                @in = "body",
                                schema = schemaRegistry.GetOrRegister(typeof(CreateTokenBody))
                            }
                        },
                        responses = new Dictionary<string, Response>()
                        {
                            { "200", new Response{ schema = schemaRegistry.GetOrRegister(typeof(string)) } }
                        }
                    }
                });
        }
    }  

As shown above, you can optionally use the schemaRegistry to generate schemas from system types and, if applicable, register them with the global "Definitions" in the Swagger doc.

**Comment by kelostrada** [comment]
Thanks for the tip! Unfortunately as far as I know OWIN's `/token` doesn't allow JSON models as a POST body. My token request is as follows at the moment:

```
POST /token HTTP/1.1
Host: localhost:1552
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=test&password=test&client_id=ngApp
```

How can I change the schema to be of type `x-www-form-urlencoded`?

**Comment by kelostrada** [comment]
I've created something like this, but it doesn't send `x-www-form-urlencoded`

```c-sharp
public class AddAdditionalOperations : IDocumentFilter
        {
            public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
            {
                swaggerDoc.paths.Add("/token", new PathItem
                {
                    post = new Operation
                    {
                        operationId = "CreateToken",
                        parameters = new[]
                        {
                            new Parameter
                            {
                                name = "grant_type",
                                schema = schemaRegistry.GetOrRegister(typeof (string)),
                                @default = "password",
                                type = "query"
                            },
                            new Parameter
                            {
                                name = "username",
                                schema = schemaRegistry.GetOrRegister(typeof (string)),
                                @default = "test",
                                type = "query"
                            },
                            new Parameter
                            {
                                name = "password",
                                schema = schemaRegistry.GetOrRegister(typeof (string)),
                                @default = "123qwe",
                                type = "query"
                            },
                            new Parameter
                            {
                                name = "client_id",
                                schema = schemaRegistry.GetOrRegister(typeof (string)),
                                @default = "ngSimpleFxApp",
                                type = "query"
                            },
                        },
                        responses = new Dictionary<string, Response>()
                        {
                            {"200", new Response {schema = schemaRegistry.GetOrRegister(typeof (string))}}
                        }
                    }
                });
            }
        }
```

**Comment by kelostrada** [comment]
Okay, I've managed to accomplish it by following Swagger spec :) Leaving it here for future reference. One more question though, how can I change the name of the group? It's `default` at the moment, and usually it is a name of controller. Can I change it and/or move it to the top of page?

```csharp
public class AddAdditionalOperations : IDocumentFilter
        {
            public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
            {
                swaggerDoc.paths.Add("/token", new PathItem
                {
                    post = new Operation
                    {
                        operationId = "CreateToken",
                        consumes = new List<string>
                        {
                            "application/x-www-form-urlencoded"
                        },
                        parameters = new[]
                        {
                            new Parameter
                            {
                                name = "grant_type",
                                @in = "formData",
                                schema = schemaRegistry.GetOrRegister(typeof (string)),
                                @default = "password",
                                type = "query"
                            },
                            new Parameter
                            {
                                name = "username",
                                @in = "formData",
                                schema = schemaRegistry.GetOrRegister(typeof (string)),
                                @default = "test",
                                type = "query"
                            },
                            new Parameter
                            {
                                name = "password",
                                @in = "formData",
                                schema = schemaRegistry.GetOrRegister(typeof (string)),
                                @default = "test",
                                type = "query"
                            },
                            new Parameter
                            {
                                name = "client_id",
                                @in = "formData",
                                schema = schemaRegistry.GetOrRegister(typeof (string)),
                                @default = "ngApp",
                                type = "query"
                            },
                        },
                        responses = new Dictionary<string, Response>()
                        {
                            {"200", new Response {schema = schemaRegistry.GetOrRegister(typeof (string))}}
                        }
                    }
                });
            }
        }
```

**Comment by domaindrivendev** [comment]
Nice job!. Swagger-ui uses operation.tags to identify operation groups. It's an array of strings and the first in the array is used as the group name. So, the following should do the trick ...

    operationId = "CreateToken",
    tags = new[] { "Tokens" }
    ...

**Comment by langdonx** [comment]
@kelostrada Thanks for sharing!  I was creating a Controller with fake types... this is miles better.

**Comment by rawdenhoff** [comment]
> Yep - you can create an IDocumentFilter (see readme) that modifies the SwaggerDocument after it's generated. Just have your implementation add the description for the token operation.
> 
> NOTE: Here you're essentially authoring your own Swagger description and so should have a reasonable understanding of the 2.0 spec. I don't know the exact semantics of the operation above so you'll need to tweak accordingly but here's an example to get you started ...
> 
> ```
> public class AddAdditionalOperations : IDocumentFilter
> {
>     public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
>     {
>         swaggerDoc.paths.Add("/token", new PathItem
>             {
>                 post = new Operation
>                 {
>                     operationId = "CreateToken",
>                     parameters = new[] {
>                         new Parameter
>                         {
>                             name = "createTokenBody",
>                             @in = "body",
>                             schema = schemaRegistry.GetOrRegister(typeof(CreateTokenBody))
>                         }
>                     },
>                     responses = new Dictionary<string, Response>()
>                     {
>                         { "200", new Response{ schema = schemaRegistry.GetOrRegister(typeof(string)) } }
>                     }
>                 }
>             });
>     }
> }  
> ```
> As shown above, you can optionally use the schemaRegistry to generate schemas from system types and, if applicable, register them with the global "Definitions" in the Swagger doc.

This helped me, thank you. I had to decorate the .issued and .expires properties in the CreateTokenBody class with Newtonsoft.Json.JsonProperty(PropertyName etc though as you can't have properties in c# that start with a period.
