### ISSUE TITLE
Order of properties in the Json document

### ISSUE THREAD

**Issue by Bicolt** [domaindrivendev/Swashbuckle#237]
I need to do a "diff" between different swagger.json files, generated with Swashbuckle for different versions of my API. But this gives me some "false positive" results because of the random order of the properties in complex objects.
For example: 
![image](https://cloud.githubusercontent.com/assets/3645205/6683699/b169ba34-cc89-11e4-8dfb-594aa442413c.png)

I suppose that the Json.NET framework is responsible for exploring the properties of an object, and this may be an intended behavior, but I wanted to raise the question.

For the moment I'm using a simple SchemaFilter to do the sorting, but I would like to know if there is a better solution.

**Comment by domaindrivendev** [comment]
For an accurate API description at the HTTP layer, Swashbuckle takes serialization/deserialization behavior into account when describing types. So, if you specify the order in which properties should be serialized (via Json.Net annotations), then Swashbuckle will preserve this ordering in it's type description. For example, you could achieve explicit ordering for serialization, and therefore swagger, as follows: 

    [JsonProperty(Order = 1)]
    public string Name { get; set; }

    [JsonProperty(Order = 2)]
    public string Description { get; set; }
