### ISSUE TITLE
How can I add custom headers or Api Key

### ISSUE THREAD

**Issue by doneal1992** [domaindrivendev/Swashbuckle#246]
How do I add an Api Key or Request Header, so that in the SwaggerUI i get the correct response. Right now I cant send a request to my api because I am missing the header necessary to gain me access to the api of my site. How would I go about correcting this?

**Comment by domaindrivendev** [comment]
If you want to submit an ApiKey with every request based on the api_key input field in the swagger-ui, then take a look at the #222

If you have parameters to certain operations that are provided via Http Header, then you can create an IOperationFilter that add a Parameter (with in = "header") to the relevant Operation descriptions. See the readme for details on wiring up an IOperationFilter

**Comment by doneal1992** [comment]
so the @in is where I would actually place the header I want to send with the Http Request right? Im pretty new to this so I just want to make sure I understand it correctly.
