### ISSUE TITLE
Responses schema model is object when using operation filter 

### ISSUE THREAD

**Issue by alxwest** [domaindrivendev/Swashbuckle#247]
Hi

I have this IOperationFilter:
```c#
 public class AddDefaultResponse : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            var errorSchema = schemaRegistry.GetOrRegister(typeof(HttpError));

            operation.responses.Add("400", new Response
            {
                description = "Bad request",
                schema = errorSchema,
                examples = new HttpError("Bad request")
            });
            operation.responses.Add("401", new Response
            {
                description = "Unauthorized",
                schema = errorSchema
            });
        }
    }
```
Which gives me this JSON:
```javascript
   responses:{  
      200:{  
         description:"OK",
         schema:{  
            $ref:"#/definitions/Contact"
         }
      },
      400:{  
         description:"Bad request",
         schema:{  
            type:"object",
            additionalProperties:{  
               $ref:"#/definitions/Object"
            }
         },
         examples:{  
            Message:"Bad request"
         }
      },
      401:{  
         description:"Unauthorized",
         schema:{  
            type:"object",
            additionalProperties:{  
               $ref:"#/definitions/Object"
            }
         }
      }...
```
I was expecting it to give me a HttpError object for 400 and 401 and create that HttpError in the definitions . Have I configured something wrong or misunderstood something?
 Below is what I was expecting:
```javascript
   responses:{  
      200:{  
         description:"OK",
         schema:{  
            $ref:"#/definitions/Contact"
         }
      },
      400:{  
         description:"Bad request",
         schema:{  
            $ref:"#/definitions/HttpError"
         },
         examples:{  
            Message:"Bad request"
         }
      },
      401:{  
         description:"Unauthorized",
           schema:{  
            $ref:"#/definitions/HttpError"         
         }
      }...

```

**Comment by domaindrivendev** [comment]
If you look closer at HttpError, you'll see that it's actually just a Dictionary of objects...

    public sealed class HttpError : Dictionary<string, Object>

The schema description you're seeing is actually the correct description for a dictionary of objects according to Swagger 2.0 and Json Schema. It makes perfect sense if you think about it - there's really not much else it can tell you about the object because all it's keys and values will be dynamically populated at runtime and could contain anything (hence the use of additionalProperties).

Unfortunately though, the swagger-ui doesn't currently have much support for describing these types (aka Maps). However I believe it may be added soon.

**Comment by alxwest** [comment]
That's true but I wanted the additional properties of Exception, Message and ModelState defined in Swagger. I've created a work around by defining my own HttpError class in a different namespace.

**Comment by dicksonl** [comment]
Hi, I was in a similar situation a few days ago. if you haven't solved the problem yet you might want to try this instead:


public class AddDefaultResponse : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescriptionapiDescription)
        {
            schemaRegistry.GetOrRegister(typeof(HttpError));

            operation.responses.Add("400", new Response
            {
                description = "Bad request",
                schema = new schema { @ref =  "#/definitions/HttpError"},
                examples = new HttpError("Bad request")
            });
            operation.responses.Add("401", new Response
            {
                description = "Unauthorized",
               schema = new schema { @ref =  "#/definitions/HttpError"},
            });
        }
    }
