### ISSUE TITLE
Swashbuckle 5.0 not showing response class definition

### ISSUE THREAD

**Issue by BaneSays** [domaindrivendev/Swashbuckle#248]
After updating the NuGet pkg of Swashbuckle to 5.0, I noticed that none of the Response Class models were getting rendered in the Documentation. In the previous versions of Swashbuckle I would see this under "Implementation Notes" 

![image](https://cloud.githubusercontent.com/assets/6628456/6812804/6e942190-d22e-11e4-9047-45a35fabb633.png)

This is no longer the case, which leaves clients with no details to run by. My controllers have been decorated with [ResponseType(typeof (MyObject))] attributes and I am importing XML comments as I always have with the previous versions of the pkg.

Please advise.

I originally posed this question to Stackoverflow and you can view my original question here: http://bit.ly/1bqZbKI 

EDIT:
I have now noticed that I can get the Response Class to show if I remove all descriptive XML comments from the controller method.

![capture](https://cloud.githubusercontent.com/assets/6628456/6813084/06d49a56-d230-11e4-9a99-a86f7ff44d57.PNG)

**Comment by domaindrivendev** [comment]
If you're explicitly stating individual response codes with the "response" tag, then you also need to include one for the 2xx response. 

Take a look at #233 - I think it may solve your problem.
