### ISSUE TITLE
Response code 201 not showing in documentation

### ISSUE THREAD

**Issue by OnamChilwan** [domaindrivendev/Swashbuckle#249]
Hello all, I was wondering how would I show a 201 Created response? I have a method which does the following:

The problem is when I access the documentation via url/swagger it doesn't show 201 as a possible response? I imagine it is related to the return type being a HttpResponseMessage?

        /// <summary>
        /// Initialises something
        /// </summary>
        /// <remarks>
        /// Some remarks.
        /// </remarks>
        /// <param name="request">Request to initiate.</param>
        /// <response code="201">Account created</response>
        /// <response code="202">Lovely.</response>
        /// <response code="301">Jubbly.</response>
        /// <response code="400">Invalid request.</response>
        /// <returns></returns>
        [Route("helloworld")]
        public HttpResponseMessage Post(RequestV1 request)
        {
            return this.Request.CreateResponse(HttpStatusCode.Created, new RequestV1());
        }

**Comment by domaindrivendev** [comment]
Hmmm - this maybe an issue with the swagger-ui as opposed to SB. Can you navigate directly to the raw  swagger (e.g. yourapi.com/swagger/docs/v1) and ensure the responses are ate least present in the Swagger description. If so, then SB is doing it's job correctly but the swagger-ui doesn't seem to support multiple 2xx codes on the same operation and you should probably create an issue in that repo

**Comment by davetransom** [comment]
Just a note: It seems swagger-ui will take the first 2xx response code and use that as the *sample response*. It'll also omit this from the additional response codes that are displayed afterwards.

**Comment by domaindrivendev** [comment]
Closing this issue as the Swagger JSON, generated by Swashbuckle, includes the additional responses but the swagger-ui chooses not to show multiple 2XX responses.

I took a quick look in the swagger-ui repo (https://github.com/swagger-api/swagger-ui) and couldn't find any related issues. If this is still a problem for you, I would recommend submitting one there.

Thanks
