### ISSUE TITLE
OAuth2 scopes broken

### ISSUE THREAD

**Issue by svrooij** [domaindrivendev/Swashbuckle#251]
The embedded Swagger-UI version has a bug when requesting multiple scopes on the token endpoint. They seem to have fixed it, but you're using an older version. Is there some way to fix this?

This describes the issue on the Swagger-UI repo (https://github.com/swagger-api/swagger-ui/issues/1031)

**Comment by domaindrivendev** [comment]
Should be fixed in the latest pre-release version

    Update-Package Swashbuckle -Pre

**Comment by domaindrivendev** [comment]
Oauth 2 flow works well when I try locally.

Can you provide more details - JS console errors etc.
