### ISSUE TITLE
Decimal could be added as a format. The sequel of the issue #253

### ISSUE THREAD

**Issue by alexkostyanikov** [domaindrivendev/Swashbuckle#255]
Hi once again
I have discussed about the issue #253 with swagger-spec guys. Could you have a look?
https://github.com/swagger-api/swagger-spec/issues/316

The main point is
"The spec does allow you to use whichever format you want, so if you want to call it float128bit or decimal, you can. It doesn't mean the tools will be able to parse it automatically though. As for the type, it's definitely number in this case."

It is described in https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types, third paragraph.

Could you do this?

**Comment by domaindrivendev** [comment]
Thanks for digging deeper and getting this additional info from the Swagger folks. I'm on the fence about adding an unknown format, particularly if there's a chance it could degrade any existing tools out there just to satisfy one specific client generator for .Net. I would need to think about it a bit more.

In the meantime, it's worth noting you can override the mapping for System.Decimal very easily on the server-side with the following config setting (see readme for more info)

    config.MapType<decimal>(() => new Schema { type="number", format="decimal" });

On the client-side, this may not help much, but you could use double by default and provide a howto on getting decimal support into a WebApi. In fact, server-side changes will be required to even make the WebApi JSON serializer handle doubles differently to decimals in the first place.

**Comment by alexkostyanikov** [comment]
oh. it is very useful advise.
thanx

Another point that i had regards to nullable values. Is it the same solution? we can override mapping for this? 
config.MapType<int?>(() => new Schema { type="number", format="int?" });

or there is another cause that you don't support them?

**Comment by domaindrivendev** [comment]
"decimal", "int?" etc. are all formats which would be quite specific to the .NET stack. Swagger isn't about describing a .NET API - it's about describing a REST/HTTP-based API independent of the platform that the service happens to be hosted on.

At this level of abstraction a nullable type would be represented as a "non-required", "primitive" JSON schema.

**Comment by fingers10** [comment]
With latest version, you need to map as follows,

`config.MapType<decimal>(() => new OpenApiSchema { Type="number", Format="decimal" });`
