### ISSUE TITLE
Exclude controllers from docs

### ISSUE THREAD

**Issue by thomasddn** [domaindrivendev/Swashbuckle#261]
Hi,

How can I exclude controllers from the generated doc? The controllers I'd like to exclude are added by the CMS platform I'm using, so I'm not able to modify them. 

I've tried misusing the ResolveConflictingActions method, but it doesn't like a null as return value.

In issue #90 (which is slightly different because they have access to the other controllers), it has been announced that it would be possible in the upcoming major release. Any progress on that or am I missing something?

As an alternative, dictating the controllers to include is fine too.

Kind regards,
Thomas

**Comment by domaindrivendev** [comment]
You have a couple of options ...

Take a look at #153 and #228

**Comment by domaindrivendev** [comment]
Just saw your additional constraint of not having access to the controllers - so #228 is the way to go

**Comment by thomasddn** [comment]
Thanks, didn't know you could establish that with a DocumentFilter. Thanks for pointing out! And sorry I didn't found this issue myself, my search term was controller, not route. :)
