### ISSUE TITLE
500 : undefined http://localhost:80/........../swagger/docs/v1

### ISSUE THREAD

**Issue by michaelstephensonuk** [domaindrivendev/Swashbuckle#263]
Hi
I had a page with SB working perfectly and then at somepoint I have changed something and it now does not display.

I get the below test displayed on the swagger ui

500 : undefined http://localhost:80/............/swagger/docs/v1

I have tried this code snipped in a controller and it seems to pull the description ok
var content = GlobalConfiguration.Configuration.Services.GetApiExplorer().ApiDescriptions;

My controllers are all working fine too

Ive tried a few different things and nothing is working. 

Are there any options around turning on some logging or diagnostics so i try and get more info on the problem?

Cheers
Mike

**Comment by cbird** [comment]
I had the same issue last week. My problem was in a custom OperationFilter I had which added a bunch of default headers. If you have any OperationFilters, try turning them off one-by-one to find the culprit.

Unfortunately I don't know of any debug option, but perhaps this helps.

**Comment by domaindrivendev** [comment]
Navigate directly to the errant url ( e.g. /swagger/docs/v1). This should return the raw swagger json for the UI to consume but is clearly failing to do so. If you navigate there directly you should get a more detailed error message

**Comment by michaelstephensonuk** [comment]
thanks that sorted it for me.  When I navigated to /swagger/docs/v1 it gave me an error that there was an invalid path when importing my xml comments file.  Once i fixed that it started working fine

Cheers
Mike

**Comment by Kum4r4n** [comment]
@michaelstephensonuk How you solve it can  you tell me the solution
