### ISSUE TITLE
Swagger/Swashbuckle OAuth2 Authorizations not set

### ISSUE THREAD

**Issue by danutzplusplus** [domaindrivendev/Swashbuckle#267]
I've found an issue and I'm not sure where it stems from. The point where it fails in inside a Swagger js library (swagger-ui-js), but it might either because of a misconfiguration in Swashbuckle, or an actual bug in Swagger (version: v2.1.0-M2).

The issue I found was after upgrading Swashbuckle from 4.x to 5 (in 4.x it worked without a hitch), and it manifests in the following way:
I've a couple of WebAPI services exposed using Swashbuckle, and I've configured them (just the same as I've configured 4.x) to use a local OAuth2 token issuer. I hit the [On/Off] button on a particular service, and start the OAuth2 requests, finalizing with the access_token stored locally in swagger (the [On/Off] button is [On], meaning authentication succeeded). 

When I attempt to perform the actual call to the WebAPI service, it breaks locally in the javascript code, in swagger-ui-js, at line nr 900, at the point where it tries to call apply(obj, authorizations) on the reference retrieved from this.authz["oauth2"]

result = value.apply(obj, authorizations); // it breaks here because value is an empty js object, and apply is undefined

I've uploaded a screenshot of the firefox debugger: http://oi61.tinypic.com/2q1wk6e.jpg

I've traced where this.authz[key] is set, and its in the 
SwaggerAuthorizations.prototype.add = function (name, auth) {
  this.authz[name] = auth;

  return auth;
};

I've then traced it, at least I hope I traced it correctly, to:
window.swaggerUi.api.clientAuthorizations.add.apply(window.swaggerUi.api.clientAuthorizations, arguments);
and I noticed arguments is an array, and the "oauth2" key has an empty js object, but I've not been able to find out where that arguments object is populated from.

Anyone else had this issue? Could this be just because of a misconfiguration server-side on my part? I would imagine if this was the case, the OAuth2 flow would break a lot sooner than when trying to perform the actual request with the received bearer token.

Thanks, and I hope someone is able to shed some light on this, and I'm stumped.

**Comment by omniscient** [comment]
You are further than I am. I don't even know what you mean by On/Off button. Even the sample (Dummy.Core/Dummy.WebHost) in latest code that is supposed to be configured for OAuth2 doesn't seem to do anything in terms of requesting a token, passing it down to controllers.The controllers themselves in the sample do not validate any security. I am at lost as well.

**Comment by danutzplusplus** [comment]
I've only had issues after upgrading from 4.x to 5. It worked fine before.

**Comment by domaindrivendev** [comment]
@danutzplusplus - thanks for pointing this out, I'm also able to repro. This seems to have been introduced by the swagger-ui upgrade to v2.1.0-M2 and so I believe that's where the issue lies but I'll need to investigate further. Stay tuned ...

**Comment by danutzplusplus** [comment]
It's good to hear it's not just me then. I also started an issue on swagger github for this.
https://github.com/swagger-api/swagger-ui/issues/1134

**Comment by domaindrivendev** [comment]
Great - the Swagger guys are awesome so lets keep an eye on that thread and assist in any way we can

**Comment by danutzplusplus** [comment]
@domaindrivendev The guys at Swagger said if we could re-test the applied fix. I was using Swagger through Swashbuckle  so I'm not sure how easy it is for me to test it. Could you please re-test it to see if it's fixed?

https://github.com/swagger-api/swagger-ui/issues/1134#issuecomment-92439065

**Comment by niemyjski** [comment]
I got this error after upgrading from 5.0 to 5.1. It appears that initOAuth(opts) is giving me the following error:

0: "missing appName"
1: "missing client id"
2: "missing realm"
length: 3

```javascript
Uncaught ReferenceError: log is not definedswagger-oauth-js:190 
initOAuthindex:67 
window.swaggerUi.SwaggerUi.onCompleteindex.js:24 
window.SwaggerUi.Backbone.Router.extend.renderindex.js:24 
options.successspec-converter.js:123 
SwaggerClient.buildFromSpecmodel.js:144 
Resolver.resolveresolver.js:208 
obj.on.responsespec-converter.js:515 
(anonymous function)index.js:24 
Request.callbackindex.js:24 
(anonymous function)index.js:24 
Emitter.emitindex.js:24 
xhr.onreadystatechange
```

The only custom javascript I have is: https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Content/docs.js to change the auth schemes.

**Comment by niemyjski** [comment]
I went back to 5.0.4 and I get this in the console but everything works:

XHR finished loading: GET "http://localhost:50000/schema/v2".
swagger-ui-js:75 auth unable initialize oauth: missing appName,missing client id,missing realm

**Comment by domaindrivendev** [comment]
@danutzplusplus - when I wire up the develop_2.0 branch, the on/off buttons for oauth don't show up anymore. Just a no-show - no console errors.

However, if I apply the one-line fix from the PR on it's own the whole flow works end-to-end. So, the fix looks good (although it should also be added to dist/lib/swagger-oauth.js) but it seems something else in the develop_2.0 branch is preventing oauth from being enabled.

**Comment by danutzplusplus** [comment]
An update from webron: https://github.com/swagger-api/swagger-ui/issues/1134#issuecomment-92482900 (it's getting silly with me pasting references from one issue to the other :D)

**Comment by danutzplusplus** [comment]
@domaindrivendev I guess Swagger the fix hasn't been deployed on version 5.1.1 of Swashbuckle, on nuget yet? I updated to that version and it still behaves the same. Thanks

**Comment by domaindrivendev** [comment]
I need to wait for a stable release of swagger-ui (with the fix) before I can embed it into SB. I don't believe this is available yet

**Comment by domaindrivendev** [comment]
In the meantime, I've just monkey patched the version of swagger-ui that comes with SB.

Check the latest release - 5.1.2, should be fixed.

**Comment by danutzplusplus** [comment]
@domaindrivendev Thanks for the fix. It worked. Have a good one. :)
