### ISSUE TITLE
Licensing of Json.NET Schema

### ISSUE THREAD

**Issue by tjrobinson** [domaindrivendev/Swashbuckle#268]
At the moment Swashbuckle has a dependency on Json.NET 4.5 and uses the JSON Schema functionality from it.

In the latest versions of Json.NET the JSON Schema parts have been marked as [Obsolete] because "JSON Schema validation has been moved to its own package. See http://www.newtonsoft.com/jsonschema for more details."

The new Json.NET Schema package is AGPL 3.0 licensed.

Will you be using/writing an alternative to the Json.NET schema code to get round this complication?

**Comment by domaindrivendev** [comment]
Actually, SB doesn't use the Json.NET Schema functionality at all. I looked at it originally but it fell well short of what's needed to be Swagger compliant and so I ended up rolling my own - https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Swagger/SchemaRegistry.cs

It does depend on the IContractResolver but this is part of the core serialization functionality that's also used by WebApi. So, the dependency on WebApi and indirectly Json.NET should be safe for now :)
