### ISSUE TITLE
HowTo Change Base url of swagger?

### ISSUE THREAD

**Issue by Gentlehag** [domaindrivendev/Swashbuckle#271]
I'd like to have the help page generated blow

/help/ not /swagger/

how can i set this?

**Comment by domaindrivendev** [comment]
See the readme section on Custom Routes ...

https://github.com/domaindrivendev/Swashbuckle#custom-routes

**Comment by mburumaxwell** [comment]
hey,
I tried this but the UI doesn not show at /sandbox/ui/index it returns an expection
"Mapping not found - ui/index"
The /docs/v1 works fine and returns json text.
I am running version 5.2.1

**Comment by raaga123** [comment]
I'm having the same problem, up to and including "Mapping not found - ui/index". Has a solution been found for this?

**Comment by adegroff** [comment]
I have also noticed, if you use a custom route, the default route mapping is no longer used (eg. ../swagger routes to ../swagger/ui/index).  In order to do this with your custom mapping, you must manually put an additional route mapping into your route configuration:
```c# 
config.Routes.MapHttpRoute(
		name: "help_ui_shortcut",
		routeTemplate: "help",
		defaults: null,
		constraints: null,
		handler: new RedirectHandler(SwaggerDocsConfig.DefaultRootUrlResolver, "help/ui/index"));
```
