### ISSUE TITLE
Issue setting authorization scheme when updating to the latest version.

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle#273]
I got this error after upgrading from 5.0 to 5.1. It appears that initOAuth(opts) is giving me the following error:

0: "missing appName"
1: "missing client id"
2: "missing realm"
length: 3

```javascript
Uncaught ReferenceError: log is not definedswagger-oauth-js:190 
initOAuthindex:67 
window.swaggerUi.SwaggerUi.onCompleteindex.js:24 
window.SwaggerUi.Backbone.Router.extend.renderindex.js:24 
options.successspec-converter.js:123 
SwaggerClient.buildFromSpecmodel.js:144 
Resolver.resolveresolver.js:208 
obj.on.responsespec-converter.js:515 
(anonymous function)index.js:24 
Request.callbackindex.js:24 
(anonymous function)index.js:24 
Emitter.emitindex.js:24 
xhr.onreadystatechange
```

The only custom javascript I have is: https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Content/docs.js to change the auth schemes.

I went back to 5.0.4 and I get this warning/log in the console but everything works:

XHR finished loading: GET "http://localhost:50000/schema/v2".
swagger-ui-js:75 auth unable initialize oauth: missing appName,missing client id,missing realm

**Comment by domaindrivendev** [comment]
Do you have the following line in your SwaggerConfig.cs ...

    .EnableSwaggerUi(c =>
        {
            c.EnableOAuth2Support("test-client-id", "test-realm", "Swagger UI");
        });

**Comment by niemyjski** [comment]
Nope, we are not using oauth2:

https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/AppBuilder.cs#L148-L158

We just have simple bearer auth.

**Comment by domaindrivendev** [comment]
Ahh I see ... with that config, it shouldn't even be calling the initOAuth function.

Could you "view source" on the swagger-ui page and check the assignments to window.swashbuckleConfig? The oauth entry should look like this ...

    oAuth2Enabled: Boolean('False')

This is then used further down in the JavaScript to optionally enable OAuth2 ...

    if (typeof initOAuth == "function" && swashbuckleConfig.oAuth2Enabled) {
        initOAuth({
            clientId: swashbuckleConfig.oAuth2ClientId,
            realm: swashbuckleConfig.oAuth2Realm,
            ppName: swashbuckleConfig.oAuth2AppName
        });
    }

I don't have access to my .Net environment at the moment, is there any chance you could throw some console.log statements in to see why it's getting inside the above conditional?

**Comment by niemyjski** [comment]
I'm currently reverted to the previous version and working on a different project for the rest of the week. I can check this out next week / first chance I get. Should I be setting an oauth2disabled in swashbuckle (csharp)? It seems like it should be disabled by default unless I buy into it..

**Comment by domaindrivendev** [comment]
Yep this should be disabled by default - so there's a bug of some sort there

**Comment by niemyjski** [comment]
Thanks for the heads up, the code I linked you to is the exact project I work on hehe and we are not enabling oauth.

**Comment by domaindrivendev** [comment]
This was indeed a regression bug introduced with the SB config code. Just released a new patch version with the fix

**Comment by niemyjski** [comment]
Awesome! Thank you
