### ISSUE TITLE
Generic Types not getting resolved correctly for XML Comments

### ISSUE THREAD

**Issue by jasonlind0** [domaindrivendev/Swashbuckle#274]
I have the following class:

    /// <summary>
    /// Holder class for query results
    /// </summary>
    /// <typeparam name="TResult">Type of result</typeparam>
    public sealed class QueryResults<TResult>
    {
        public QueryResults() { }
        /// <summary>
        /// The total results returning in the query (ignoring paging)
        /// </summary>
        public long TotalResultsCount { get; set; }
        /// <summary>
        /// The results for the current page
        /// </summary>
        public IEnumerable<TResult> Results { get; set; }
        /// <summary>
        /// Available properties from the query
        /// </summary>
        public IEnumerable<string> AvailableProperties { get; set; }
    }
Which produces the following XML:
    <member name="T:HallData.Repository.QueryResults`1">
            <summary>
            Holder class for query results
            </summary>
            <typeparam name="TResult">Type of result</typeparam>
        </member>
        <member name="P:HallData.Repository.QueryResults`1.TotalResultsCount">
            <summary>
            The total results returning in the query (ignoring paging)
            </summary>
        </member>
        <member name="P:HallData.Repository.QueryResults`1.Results">
            <summary>
            The results for the current page
            </summary>
        </member>
        <member name="P:HallData.Repository.QueryResults`1.AvailableProperties">
            <summary>
            Available properties from the query
            </summary>
        </member>
        <member name="T:HallData.Repository.QueryResult`1">
            <summary>
            Holder class for a query result
            </summary>
            <typeparam name="TResult">Type of result</typeparam>
        </member>
        <member name="P:HallData.Repository.QueryResult`1.Result">
            <summary>
            The result
            </summary>
        </member>
        <member name="P:HallData.Repository.QueryResult`1.AvailableProperties">
            <summary>
            Available properties from the query
            </summary>
        </member>
Your current logic attempts to resolve this path by filling in the type to comment path which I believe is incorrect, I commented out the offending logic and it now produces the correct descriptions for the model type:
 public static string XmlCommentsQualifier(this Type type)
        {
            var builder = new StringBuilder(type.FullNameSansTypeParameters());
            builder.Replace("+", ".");

            //if (type.IsGenericType)
            //{
            //    var typeParameterQualifiers = type.GetGenericArguments()
            //        .Select(t => t.XmlCommentsQualifier())
            //        .ToArray();

            //    builder
            //        .Replace(String.Format("`{0}", typeParameterQualifiers.Count()), String.Empty)
            //        .Append(String.Format("{{{0}}}", String.Join(",", typeParameterQualifiers).TrimEnd(',')))
            //        .ToString();
            //}

            return builder.ToString();
        }

**Comment by domaindrivendev** [comment]
Good catch!

It's not quite as simple as just uncommenting the above code because that logic is required when constructing the lookup name for methods. In this case, the full type name is required including generic parameters. For example ...

    <member name="M:Swashbuckle.Dummy.Controllers.XmlAnnotatedController.Search(System.Collections.Generic.IEnumerable{System.String})">

It just requires a little refactor - I'll get to it later this evening

Thanks for letting me know

**Comment by domaindrivendev** [comment]
Just pushed a release candidate with the fix ...

http://www.nuget.org/packages/Swashbuckle/5.1.4-rc1

Can you try it out and ensure all your comments are being pulled into the swagger doc as expected? Let me know as soon as you get a chance?

Thanks

**Comment by jasonlind0** [comment]
Can u push out core?

Sent from my Windows Phone
________________________________

**Comment by domaindrivendev** [comment]
Both should be out there?

**Comment by domaindrivendev** [comment]
Sorry ... what I mean is I pushed them both together so both should be available for download

**Comment by jasonlind0** [comment]
Yes that appears to work.

Thanks,

Jason Lind
EVP / Chief Software Architect
Lind Innovation
jason@lind-i.com<mailto:jason@lind-i.com>
414.788.2820

**Comment by domaindrivendev** [comment]
Fix released and available in v5.1.1
