### ISSUE TITLE
JSON Encoded URL Query Parameters not populating correctly

### ISSUE THREAD

**Issue by jasonlind0** [domaindrivendev/Swashbuckle#277]
I have complex objects as query strings and have written a model binder to bind them to url encoded json. However swashbuckle reads them wrong.

An example method is:

    Task<QueryResults<TModel>> GetMany([Description("Filter for the view results, must be url encoded JSON")][JsonEncode]FilterContext<TView> filter = null,
            [Description("Sort for the view results, must be url encoded JSON")][JsonEncode]SortContext<TView> sort = null,
            [Description("Page for the view results, must be url encoded JSON")][JsonEncode]PageDescriptor page = null, CancellationToken token = default(CancellationToken));

Where FilterContext:
     
    [JsonObject]
    public class FilterContext : IEnumerable<FilterDescriptor>
    {
        public FilterContext()
        {
            Filters = new List<FilterDescriptor>();
        }
        /// <summary>
        /// The filters in the context
        /// </summary>
        [JsonProperty]
        public List<FilterDescriptor> Filters { get; set; }
        /// <summary>
        /// A raw search string to filter against
        /// </summary>
        [JsonProperty]
        public string SearchCriteria { get; set; }
    }
    [JsonObject]
    public sealed class FilterDescriptor
    {
        public FilterDescriptor() { }
        public FilterDescriptor(string property, object compareValue, FilterOperation operation = FilterOperation.Like)
        {
            this.Property = property;
            this.CompareValue = compareValue;
            this.Operation = operation;
        }
        [JsonProperty]
        public string Property { get; set; }
        [JsonProperty]
        public object CompareValue { get; set; }
        [JsonProperty]
        public FilterOperation Operation { get; set; }
    }
    public enum FilterOperation
    {
        Equals,
        Like
    }

It populates optional, searchCritera : string and filters Array[] as query parameters. I  wrote the following operation filter to handle this:

    public class DescriptionAttributeOperationFilter : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            ServiceMethodHttpActionDescriptor actionDescriptor = apiDescription.ActionDescriptor as ServiceMethodHttpActionDescriptor;
            if(actionDescriptor != null)
            {
                var operationDescription = actionDescriptor.BusinessyMethod.GetCustomAttribute<DescriptionAttribute>(true) ?? actionDescriptor.InterfaceMethod.GetCustomAttribute<DescriptionAttribute>(true);
                if (operationDescription != null)
                    operation.description = operationDescription.Description;
                foreach(var parameter in actionDescriptor.GetParameters().Select(p => p).Cast<ServiceMethodParameterDescriptor>())
                {
                    var parmDescription = parameter.Parameter.GetCustomAttribute<DescriptionAttribute>(true) ?? parameter.InterfaceParameter.GetCustomAttribute<DescriptionAttribute>(true);
                    var jsonEncoded = parameter.Parameter.GetCustomAttribute<JsonEncode>(true) ?? parameter.InterfaceParameter.GetCustomAttribute<JsonEncode>(true);
                    if(jsonEncoded != null)
                    {
                        var schema = schemaRegistry.GetOrRegister(parameter.ParameterType);
                        if (parameter.ParameterType == typeof(FilterContext) || parameter.ParameterType.IsSubclassOf(typeof(FilterContext)))
                        {
                            operation.parameters.Remove(operation.parameters.SingleOrDefault(p => p.name == "filters"));
                            operation.parameters.Remove(operation.parameters.SingleOrDefault(p => p.name == "searchcriteria"));

                        }
                        else if (parameter.ParameterType == typeof(SortContext) || parameter.ParameterType.IsSubclassOf(typeof(SortContext)))
                            operation.parameters.Remove(operation.parameters.SingleOrDefault(p => p.name == "sorts"));
                        else if(parameter.ParameterType == typeof(PageDescriptor))
                        {
                            operation.parameters.Remove(operation.parameters.SingleOrDefault(p => p.name == "pagesize"));
                            operation.parameters.Remove(operation.parameters.SingleOrDefault(p => p.name == "currentpage"));
                        }
                        operation.parameters.Remove(operation.parameters.SingleOrDefault(p => p.name == parameter.ParameterName));
                        operation.parameters.Add(new Parameter()
                        {
                            name = parameter.ParameterName,
                            @in = "query",
                            schema = schema,
                            required = false
                        });
                    }

                    var parm = operation.parameters.SingleOrDefault(p => p.name == parameter.ParameterName);
                    if(parmDescription != null && parm != null)
                        parm.description = parmDescription.Description;
                }
            }
        }
    }

Is this a bug in swashbuckle or is my action parameter not being described correctly?

**Comment by domaindrivendev** [comment]
I'm not sure I understand what the question is.

If it's a custom model binder, SB can't possibly know how to describe it and so an operation filter is necessary.

Can you elaborate what you would expect SB to do in this case

**Comment by jasonlind0** [comment]
I'd like it to put the json type as a query parameter.

Sent from my Windows Phone
________________________________

**Comment by domaindrivendev** [comment]
Looking at the swagger spec. (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameter-object), this doesn't appear to be supported.

For query parameters, you are limited to the following types - "string", "number", "integer", "boolean", "array" or "file".

So in your case, the best you can do is describe it as a string and then provide some additional comments in the description to describe the structure of the string. For this, I would use the following operation filter:

    public class HandleJsonEncodeParams : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            foreach (var param in apiDescription.ParameterDescriptions)
            {
                if (param.ParameterDescriptor == null) continue;

                if (param.ParameterDescriptor.GetCustomAttributes<JsonEncodeAttribute>().Any())
                {
                    var swaggerParam = operation.parameters.SingleOrDefault(p => p.name == param.Name);
                    if (swaggerParam == null) continue;

                    swaggerParam.@in = "query";
                    swaggerParam.schema = null; // no schema for query params - see swagger spec for more info
                    swaggerParam.type = "string";
                    swaggerParam.description = "A JSON-encoded object ..."
                }
            }
        }
    }

**Comment by jasonlind0** [comment]
If i set the schema to a strong type it shows up in the ui correctly.

Sent from my Windows Phone
________________________________
