### ISSUE TITLE
How to  test POST method to post a file ASP.NET Web Api 2

### ISSUE THREAD

**Issue by Divyesh-CitiusTech** [domaindrivendev/Swashbuckle#280]
How to  test POST method to post a file ASP.NET Web Api 2?
I tried out but without success. Does the POST support uploading files?

**Comment by domaindrivendev** [comment]
I have an example of this in the dummy app ... at least as far as describing the operation correctly and allowing the swagger-ui to post a file upload. Take a look at the following ...

1. An unimplemented file upload controller
https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Dummy.Core/Controllers/FileUploadController.cs

2. A corresponding IOperationFilter to amend the corresponding operation description with a "file" parameter
https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Dummy.Core/SwaggerExtensions/AddFileUploadParams.cs

3. Config. to inject the operation filter
https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Dummy.Core/App_Start/SwaggerConfig.cs (see line 156)
