### ISSUE TITLE
RootUrl not working

### ISSUE THREAD

**Issue by buybackoff** [domaindrivendev/Swashbuckle#281]
I set up my WebAPI under a separate map:
```
app.Map("/api", appApi => {
                var config = new HttpConfiguration();
                config.EnableSwagger(c => {
                    //c.RootUrl((req) => "/api/"); // doesn't work now
                    c.IncludeXmlComments(GetXmlCommentsPath());
                    c.SingleApiVersion("v1", "WebHost API");
                }).EnableSwaggerUi();

                config.DependencyResolver = new AutofacWebApiDependencyResolver(container);
                WebApiConfig.Register(config);
                appApi.UseAutofacMiddleware(container);
                appApi.UseAutofacWebApi(config);
                appApi.UseCors(CorsOptions.AllowAll);
                app.UseStageMarker(PipelineStage.MapHandler);
                appApi.UseWebApi(config);
            });
```

It shows empty API list:
![image](https://cloud.githubusercontent.com/assets/489852/7215691/12e519ae-e5ec-11e4-89ae-e84453d24ecb.png)

If I edit the address, then my API shows up:
![image](https://cloud.githubusercontent.com/assets/489852/7215702/52f16c82-e5ec-11e4-98dd-554704fc27f7.png)

But, the link to try out my API is broken:
![image](https://cloud.githubusercontent.com/assets/489852/7215714/a812e31c-e5ec-11e4-891c-cac1fef838dc.png)

I tried to use the setting `c.RootUrl((req) => "/api/");` with and without `/` on both ends, but I get Internal Server Error (500) with a cryptic message "invalid url...". And there is additional `/` in the address if I uncomment the RootUrl setting:
![image](https://cloud.githubusercontent.com/assets/489852/7215730/1ea152de-e5ed-11e4-8679-3c23884049f7.png)

I remember a similar issue since v4, but then haven't been using Swashbuckle for a long time. If this not a bug, could you please help me with correct settings?

**Comment by dennisdoomen** [comment]
I've observed the same problem with the latest build. It really looks like a bug.

**Comment by domaindrivendev** [comment]
RootUrl expects a lambda that returns an absolute URL. The following should work ...

    c.RootUrl(req => SwaggerDocsConfig.DefaultRootUrlResolver(req) + "/api");

**Comment by sgwatgit** [comment]
Thanks for this!

I am running a very similar setup where I have my web api OWIN app running under a different map than the rest of my app and have been struggling with the configuration for several hours. I finally got everything working except for swagger.

I got rid of the `SwaggerConfig.cs` file and moved all configuration to my Web Api app startup configuration

```
public void Configure(IAppBuilder appBuilder)
{
    appBuilder.Map("/api", app =>
    {
		HttpConfiguration config = new HttpConfiguration();
		NinjectWebCommon.ConfigureNinject(app, config);
		config.EnableSwagger(c => ConfigureSwagger(c))
                    .EnableSwaggerUi();
                ...
    }
}
```
And my ConfigureSwagger function is defined below my Configure function as
```
private static void ConfigureSwagger(SwaggerDocsConfig config)
{
	config.RootUrl(req => SwaggerDocsConfig.DefaultRootUrlResolver(req) + "/api");
	config.SingleApiVersion("v1", "My Api");
}
```

That RootUrl call, with that specific configuration, fixed everything (I hope).

**Comment by dlukyanov** [comment]
why the rootpath relative to host not supported in Swashbuckle? it works well in swaggerui itself.
this could really help when publishing apis behind reverse proxy that has different transport, host, port...
