### ISSUE TITLE
Double Values Don't Exist In ModelSchema

### ISSUE THREAD

**Issue by melihmucuk** [domaindrivendev/Swashbuckle#282]
Double values don't exist in model schema. weight and height are double values they exist in model but don't exist in model schema. I'm using swashbuckle v5.1.4 and here is my swashbuckle config:

<pre><code>config.EnableSwagger(c =>
            {
                c.SingleApiVersion("v1", "MyApp");
                c.DescribeAllEnumsAsStrings();
            }).EnableSwaggerUi();
</code></pre>

![swashbuckle_model](https://cloud.githubusercontent.com/assets/3147488/7227178/61002702-e757-11e4-847b-2d2f3a321bfd.PNG)
![swashbuckle_modelschema](https://cloud.githubusercontent.com/assets/3147488/7227179/6101fca8-e757-11e4-91a0-672eecc1f7f2.PNG)

**Comment by domaindrivendev** [comment]
Should be fixed in the latest version (5.1.5)
