### ISSUE TITLE
Remove media='screen' for custom CSS

### ISSUE THREAD

**Issue by yesenin** [domaindrivendev/Swashbuckle#286]
For now, it's impossible to customize CSS for media='print'.
If "media='screen'" for ext/ is removed from SwaggerUiConfig it will be possible to use "@media print" in custom CSS.

**Comment by domaindrivendev** [comment]
Will address this in the next release, probably adding an optional "media" param to InjectStyleSheet.

For now though, you'll have to override the entire index.html (see https://github.com/domaindrivendev/Swashbuckle#provide-your-own-index-file)

**Comment by yesenin** [comment]
@domaindrivendev , yes, default value for the attribute and opportunity to change it would be also great. Thank you.

**Comment by domaindrivendev** [comment]
Should be resolved in latest release - 5.2.0
