### ISSUE TITLE
Swashbuckle UI doesn't with custom reason phrase

### ISSUE THREAD

**Issue by jonmiller1** [domaindrivendev/Swashbuckle#287]
I'm trying to send back custom reason phrase of messages with a 404 status code.   When I do this the test swashbuckle UI doesn't display an error.  It just keeps spinning like it is waiting for a response.  Any ideas on this would be appreciated.

**Comment by domaindrivendev** [comment]
Can you provide some code examples? I need a little more information to fully understand what you're trying to do

**Comment by domaindrivendev** [comment]
Closing due to lack of additional information
