### ISSUE TITLE
Value cannot be null exception

### ISSUE THREAD

**Issue by shotai** [domaindrivendev/Swashbuckle#288]
Hi, I have an issue with the c.IncludeXmlComments()

I am using my own comments, however, the swachbuckle throw out the exception in below function.

 private static void ApplyParamComments(Operation operation, XPathNavigator methodNode)
        {
            var paramNodes = methodNode.Select(ParameterExpression);
            while (paramNodes.MoveNext())
            {
		            var paramNode = paramNodes.Current;
		            var parameter =
			            operation.parameters.SingleOrDefault(param => param.name == paramNode.GetAttribute("name", ""));
		            if (parameter != null)
			            parameter.description = paramNode.Value.Trim();
            }
      }

Exception message is:

Value cannot be null. Parameter name: source

The XML of the paramNodes which throws the exception is like below:
&lt;member name="getData"&gt;
      &lt;summary&gt;
           get resource data
            &lt;/summary&gt;
      &lt;param name="id"&gt;id&lt;/param&gt;
      &lt;returns&gt;&lt;/returns&gt;
   &lt;/member&gt;

Could some one help with this problem?

Thanks!

**Comment by shotai** [comment]
I see the issue seems caused by operation.parameters. If this one is null, then the error will throw out. however, I have no idea why this one could be null.

**Comment by domaindrivendev** [comment]
Does the id parameter actually exist on the corresponding method signature?

The swagger spec does not allow an empty parameters collection - if there are no parameters, then the parameters property should be omitted altogether. So, if an action accepts no parameters, then operation.parameters will be null.

This could be causing your issue and if so you can resolve by simply removing the param node from your XML comments (which makes sense if the param doesn't actually exist).

With all that said, SB should handle this a bit more gracefully - so I'll keep the issue open so I remember to address it when I get the chance.

Richie

**Comment by shotai** [comment]
Thanks, Richie. You're right. The parameter didn't exist on the corresponding method signature. After removing it, SB works fine now. Great thanks!

**Comment by MerickOWA** [comment]
I also discovered this bug.  https://github.com/domaindrivendev/Swashbuckle/pull/293 is a pull request to fix it.

**Comment by domaindrivendev** [comment]
Should be resolved in latest release - 5.2.0
