### ISSUE TITLE
add mediaType parameter to InjectStylesheet()

### ISSUE THREAD

**Issue by calvin998** [domaindrivendev/Swashbuckle#289]
I need to override some css class just for print. But InjectStylesheet() seems only inject media='screen'. Can this method takes a (optional) mediaType paramter? 

Or is there any way I can inject individual css to the index.html (without replacing the entire index.html)?

**Comment by domaindrivendev** [comment]
Going to close and refer to #286 as they both refer to the same underlying problem.
