### ISSUE TITLE
Show Authorization Header in UI

### ISSUE THREAD

**Issue by tiwari-abhishek** [domaindrivendev/Swashbuckle#290]
I have protected all my APIs with oAuth and need to be able to pass Access Token to the API through Authorization header in the try out UI. How can I do that? as of now I just have the Controller methods showing up which wont actually work without the header being passed.

Any help appreciated.

**Comment by billzhuang** [comment]
i also want to know how to implement this issue, i did not use OAuth, i just need pass a customized key in header, currently my workround is run below method in console 
```swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("x-accesskey", "eeee", "header"));```

but is there any trick i can let me input header in swagger UI

**Comment by adamfisher** [comment]
I also need this. https://github.com/swagger-api/swagger-ui#header-parameters shows how to add it in swagger but I'm not seeing a way to do it from the config in Swashbuckle.

**Comment by jskrepnek** [comment]
Use an operation filter.

```c#
public class AddAuthorizationHeaderParameter: IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            var scopes = apiDescription.ActionDescriptor.GetFilterPipeline()
                                       .Select(filterInfo => filterInfo.Instance)
                                       .OfType<AuthorizeAttribute>()
                                       .SelectMany(attr => attr.Roles.Split(','))
                                       .Distinct();

            if (scopes.Any())
            {
                operation.parameters.Add(new Parameter {
                    name = "Authorization",
                    @in = "header",
                    description = "access token",
                    required = true,
                    type = "string"                    
                });
            }
        }
    }
```

**Comment by MarwaAhmed** [comment]
I want to add the: "AddAuthorizationHeaderParameterOperationFilter" to specific service methods.
for ex: api/students  ---> uses the that certain header key-value.

and i want to add the basic authentication in a certain service method;
for ex: api/authenticate --> this uses basic http authentication.

any suggestions? thanks in advance.

**Comment by MarwaAhmed** [comment]
okay, i've figured it out. I'm just writing the solution in case if anyone faced it.

In the class "AddAuthorizationHeaderParameterOperationFilter", "Apply" method i did:

var myTokenAttribute = apiDescription.GetControllerAndActionAttributes<MyToken>().Any();
//note: i wrote the attribute above a controller and sometimes above an actionmethod.
Then:
 if (myTokenAttribute)
 {           
     if (operation.parameters == null)
     {
          operation.parameters = new List<Parameter>();
      }            
      operation.parameters.Add(new Parameter()
      {
           name = "Authorization Token",
           @in = "header",
            description = "my token description",
            required = true,
            type = "string"
        });
   }

**Comment by domaindrivendev** [comment]
Nice - this is similar to what I would have recommended.

I'm not familiar with your implementation of MyToken, but I'm guessing it's just a "marker" attribute that has no effect on the actual implementation.

Although it's not always possible, I try to implement operation filters that are bound to actual implementation so you get "living" documentation. For example, I use the WebApi "Authorize" attribute to enforce authorization and then have an operation filter that includes the relevant header parameter if operation's are decorated with that attribute. This way, the documentation always reflects the actual behavior.

**Comment by MarwaAhmed** [comment]
@domaindrivendev: Yes, MyToken is an attribute which checks if the api's user is logged in & has a sessionId. Waiting for your documentation example; this is going to be very helpful. Would you please includeo http basic authentication with an actual example as well? Thank you.

![image](https://cloud.githubusercontent.com/assets/6348433/7586420/0dbeb29a-f8ad-11e4-94c9-3ef8ba1f4d90.png)

**Comment by adamfisher** [comment]
Wow thank you but I am still having an issue with it returning any data once I add the filter.

I'm waiting on issue #329 to be resolved so I can debug with Fiddler. How does it layout the header exactly? I am expecting it to output this:

	Authorization: Bearer sdjfniwebwdfmsdkf.sdfnuwehefunwienfwef.wefuweiufwenfwenf

I am integrating with the JwtForWebApi library and I would like the Authentication token field to appear any time I decorate [Authorize] on a controller or action method. This is what I have so far.

	public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
	{
		var filterPipeline = apiDescription.ActionDescriptor.GetFilterPipeline();
		var isAuthorized = filterPipeline.Select(filterInfo => filterInfo.Instance).Any(filter => filter is IAuthorizationFilter);
		var authorizationRequired = apiDescription.GetControllerAndActionAttributes<AuthorizeAttribute>().Any();

		if (isAuthorized && authorizationRequired)
		{
			operation.parameters.Add(new Parameter
			{
				name = "Authorization Token",
				@in = "header",
				description = "JWT security token obtained from the service method Login.",
				required = true,
				type = "string"
			});
		}
	}

**Comment by jskrepnek** [comment]
@adamfisher 

Did you register the filter?, like so

httpConfig
.EnableSwagger("docs/{apiVersion}", config => {
config.SingleApiVersion("v1", "api");
config.OperationFilter<AddAuthorizationHeaderParameterOperationFilter>();
})
```

If you did, when you step through the Apply method, are you seeing expected values for isAuthorized and authorizationRequired?  You're determining this differently compared to the solution I shared above.

Also, the 'name' of the parameter should be just 'Authorization' rather than 'Authorization Token'.

**Comment by MarwaAhmed** [comment]
Yes, correction: 'Authorization Basic' and 'Authorization: Basic' are not valid HTTP header fields names. 
This work out if:
```javascript
 name = "Authorization"
```
but in the swagger UI, the api's user could pass: basic or whatever the used token name.
here's mine:

![image](https://cloud.githubusercontent.com/assets/6348433/7637614/8658d834-fa6f-11e4-8667-1b865a645d9f.png)

**Comment by adamfisher** [comment]
That worked for me. Thanks guys!

**Comment by deepakvij** [comment]
Great post. Saved me a lot of time, thanks!!

**Comment by johnkors** [comment]
@domaindrivendev  How's this going to work when we're using owin middleware to define _how_ authorization works for our APIs? The [Authorize] attribute only says that it's in need of auth, not how it's done.

**Comment by Sandiejat** [comment]
@johnkors - Did you figure out a way to do that?
When I try the above solutions authorizationRequired is null in 
var authorizationRequired = apiDescription.ActionDescriptor.GetCustomAttributes<AuthorizationFilterAttribute>().Any();

**Comment by MrOnyancha** [comment]
I have failed to add the operation filter. any guidance please...

**Comment by hsfoggia** [comment]
In Vb.NET

Public Class AddAuthTokenHeaderParameter
    Implements IOperationFilter

    Public Sub Apply(operation As Operation, schemaRegistry As SchemaRegistry, apiDescription As ApiDescription) Implements IOperationFilter.Apply

        Dim filterPipeline = apiDescription.ActionDescriptor.GetFilterPipeline()
        Dim isAuthorized = filterPipeline.Select(Function(s) s.Instance).Any(Function(sc) sc.GetType().Equals(GetType(UnisyncAuthorizeAttribute)))

        Dim allowAnonymous = apiDescription.ActionDescriptor.GetCustomAttributes(Of AllowAnonymousAttribute)().Any()

        If isAuthorized And (Not allowAnonymous) Then
            If operation.parameters Is Nothing Then
                operation.parameters = New List(Of Parameter)
            End If
            operation.parameters.Add(New Parameter With {
                    .name = "Authorization",
                    .in = "header",
                    .description = "access token",
                    .required = True,
                    .type = "string"
                })
        End If

    End Sub
End Class
