### ISSUE TITLE
Multiple ResponseCode with classes

### ISSUE THREAD

**Issue by Gentlehag** [domaindrivendev/Swashbuckle#292]
One Api has Two possible outcomes (OK or ACCEPTED) for each i have a diffrent response model.

How can i tell swashbuckle how they are related to which status code?

**Comment by MerickOWA** [comment]
You can use the [SwaggerResponse] attribute.  For example.

		[SwaggerResponse(HttpStatusCode.OK, Type = typeof(OKResponse))]
		[SwaggerResponse(HttpStatusCode.Accepted, Type = typeof(AcceptedResponse))]
		public HttpResponseMessage Get()
		{
		}
