### ISSUE TITLE
Redirection to root application path only works in IIS Express but fails on IIS

### ISSUE THREAD

**Issue by tiwari-abhishek** [domaindrivendev/Swashbuckle#294]
I am running swashbuckle and Owin-Katana based web api. The redirection from URL
http://localhost:<port>/swagger to http://localhost:<port>/swagger/ui/index
happens correctly when using IIS Express.

however when deploying to IIS, this redirects to 
http://localhost/swagger/ui/index (which is the Default Web Site on local machine). It should redirect to 
http://localhost/MyApp/swagger/ui/index

I can directly access the http://localhost/MyApp/swagger/ui/index page on IIS though. Can this be fixed?

More Updates:
1. I have removed the [assembly: PostApplicationStartMethod(typeof(SwaggerConfig), "Register")] from the SwaggerConfig
2. Exposed a public static HttpConfiguration property
3. I am calling SwaggerConfig.Register from Owin Startup configuration.

**Comment by alexgurman** [comment]
Same problem

**Comment by domaindrivendev** [comment]
Closing this one and referring to as subsequent duplicate where I've already provided some detail - #305

**Comment by csrowell** [comment]
@Adriien-M's [(comment)](https://github.com/domaindrivendev/Swashbuckle/issues/42#issuecomment-67848109) on issue #42 worked in my case when VirtualPathRoot wasn't: 

`c.RootUrl(req => req.RequestUri.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/").TrimEnd('/'));`
