### ISSUE TITLE
Swagge UI in OWIN host as console application

### ISSUE THREAD

**Issue by swaggerquery** [domaindrivendev/Swashbuckle#295]
I am trying to integrate the swashbuckle.core in my owin host which is hosted in console application.
Based on the steps provided in https://github.com/domaindrivendev/Swashbuckle the page not displayed anything.

I have added the following source in my owinhost startup.class

 config
    .EnableSwagger( c => 
                {
                   c.SingleApiVersion("v1", "A title for your API");
                    c.IncludeXmlComments(GetXmlCommentsPath());
                }
            )
    .EnableSwaggerUi(); 

But it does not display anything when am trying with my host url 
http://localhost:port/swagger/ui/index
![swashbuckle](https://cloud.githubusercontent.com/assets/12095489/7314200/a419d71a-ea7f-11e4-85cd-58ce91df7fda.png)

**Comment by domaindrivendev** [comment]
The description endpoint (.../swagger/docs/v1) is returning an error. Navigate to it directly and you'll get more info about the error

**Comment by domaindrivendev** [comment]
Is this resolved?

**Comment by swaggerquery** [comment]
when i hosted the application in http, it is working perfectly. I would like to host the OWIN in https.
But it is enable the swaggerui for https. Even I have provided the code as follows,

 config
                    .EnableSwagger(c =>
                    {
                        c.SingleApiVersion("v1", "Test API");
                        c.Schemes(new[] { "http", "https" });
                        c.ResolveConflictingActions(apiDescriptions => apiDescriptions.FirstOrDefault());
                        c.IncludeXmlComments(XmlCommentsPath());
                    }
                    )
                    .EnableSwaggerUi();

**Comment by domaindrivendev** [comment]
Think #296 is a duplicate. Closing this one as there's already more information in that ticket
