### ISSUE TITLE
HAL Accept Header

### ISSUE THREAD

**Issue by six5hunter** [domaindrivendev/Swashbuckle#297]
Possible to add custom accept types to ui without having to resort to swagger core?

**Comment by domaindrivendev** [comment]
Can you please elaborate a little more with some examples if possible?

**Comment by six5hunter** [comment]
Sure. 

We use application/hal+json and custom formats IE application/vnd.github[.version].param[+json]

I want to get that injected into the ui response content type  dropdown (Accept headers)

So the dropdown will display

application/json
application/hal+json
application/xml
application/hal+xml
application/vnd.ourcompany.v1.item

**Comment by domaindrivendev** [comment]
Technically, this should just work if you're adding additional MediaTypeFormatters to handle the HAL media types. wiring example, if you were using the following library to implement HAL, you will automatically see the corresponding media types listed in the swagger-ui option.

https://github.com/JakeGinnivan/WebApi.Hal

If you're implementing HAL without the use of custom formatters, then you'll have to wire-up a custom  IOperationFilter (see readme) that automatically adds the additional consumes/produces entries to each Operation description.

**Comment by vtortola** [comment]
I am doing exactly this and I don't see `application/hal+json` being added to the dropdown.

I have my own `MediaTypeFormatter` for HAL that in the constructor adds the media type doing `SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/hal+json"));`, but nothing shows up in the drop down. It works, just that it is not respecting the `Accept` HTTP header and I need to fix that.

Do I have to do anything else to make sure the HAL media type appears in the drop down?

**Comment by RehanSaeed** [comment]
This needs to be reopened. The following code adds support in MVC for custom media types to the existing `JsonInputFormatter`.  You would expect this to show up in Swagger but it doesn't, you only see `application/json`.

```
services.AddMvc(
    options    
        .InputFormatters
        .OfType<JsonInputFormatter>()
        .First()
        .SupportedMediaTypes
        .Add("application/vnd.restful+json"));
```
