### ISSUE TITLE
Simplify EnableSwaggerUi template and redirect hander configuration

### ISSUE THREAD

**Issue by Rast1234** [domaindrivendev/Swashbuckle#299]
For now, if i want to have custom UI route, i have to do this:

			var uiRouteTemplate = string.Format("{0}/{{*assetPath}}", uiPrefix);  // i have to append {{*assetPath}} by hand
			swaggerEnabledConfig.EnableSwaggerUi(uiRouteTemplate);

			var redirectTo = string.Format("{0}/index", uiPrefix);  // and if i'd like to have a shortcut to "uiPrefix/index", i have to open Swashbuckle sources and copypaste this:
			config.Routes.MapHttpRoute("custom_swagger_ui_shortcut", uiPrefix, null, null, new RedirectHandler(SwaggerDocsConfig.DefaultRootUrlResolver, redirectTo));

Why not do something like this?

			swaggerEnabledConfig.EnableSwaggerUi(uiPrefix);  // <-- will automatically append {{*assetPath}} in this method and register redirect route to "uiPrefix/index"

If you are interested, i can make it and do a pull request.

**Comment by domaindrivendev** [comment]
This does make sense ... the only reason I didn't do it originally was for backwards compatibility.

The existing redirect is from "/swagger" and not "/swagger/ui". With the changed you've suggested, "/swagger" would no longer redirect and I would consider this to be a breaking change.

My thinking at the time was to just leave redirecting (if desired) up to the main app (it's not exactly a difficult thing to do) while continuing support of the existing redirect for anyone who's using the out-of-the-box route template.

The above does simplify things though, so maybe worth putting into the next major version
