### ISSUE TITLE
Parameter binding to object generating unwanted docs..

### ISSUE THREAD

**Issue by mattwoberts** [domaindrivendev/Swashbuckle#302]
Firstly, this tool is proving to be an awesome asset for my API building, thanks :)

I've got a List method that allows a lot of fitler options, that will all be passed in the request querystring (`?startdate=X&enddate=Y&userId=Z...`). 

In my Web API Controller, I define a POCO to bind all these values to a nice class that I can then use. But the generated swagger docs just describe the input to my method as a JSON object, which I can understand why it would do this.

Is there a config option somewhere that I missed that will allow me to describe the input values as though they were a bunch of primitive values passed to the List? The POCO class that I use is really an implementation detail that I don't want to expose...

Cheers.

**Comment by domaindrivendev** [comment]
Are you decorating your POCO parameter with the FromUri attribute? In WebApi, this would be the typical way to bind query parameters to properties in a POCO. If you do it this way, Swashbuckle will automatically break the parameter down into multiple query parameters in the operation description.

If this isn't working, I imagine you're using some other approach to bind query params to a POCO. Can you let me know how you're doing this?

Thanks

**Comment by mattwoberts** [comment]
Aha - I didn't have a FromUri attribute on the class, so that's where I was going wrong, thanks!

I've sorted that now, and I see that the parameters are broken down now. I just need to see if I can get the descriptions from the class properties to be taken into the schema too...

Thanks

Matt
