### ISSUE TITLE
Empty API documentation using {version} in HttpRoute

### ISSUE THREAD

**Issue by aviadavi** [domaindrivendev/Swashbuckle#303]
Hi,

My WebAPI.Config file looks like that :

```c#
    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "v{version}/{controller}/{id}/{controller2}/{id2}",
```

when I build my application, and going to /swagger  the list of controllers are empty.

when I remove the "v{version}/" at the routeTemplate, i can see all controllers and API documentation is generated

Any idea how to work with "{version} ?

**Comment by domaindrivendev** [comment]
Have a read through #51 and #144 as I believe you're likely experiencing the same issue.

If you don't want to read though them all - here's the summary ...

I'm assuming you've created your own version of IHttpControllerSelector to support controller selection based on the "version" route parameter? Depending on the implementation, this is most likely breaking WebApi's built-in metadata layer - "ApiExplorer" and subsequently Swashbuckle.

This is one of the reasons why the WebApi team recommend using attribute routing over a custom IHttpControllerSelector to implement versioning:

http://blogs.msdn.com/b/webdev/archive/2014/08/22/customizing-web-api-controller-selector.aspx
