### ISSUE TITLE
SwaggerUI customization

### ISSUE THREAD

**Issue by mkhezrian** [domaindrivendev/Swashbuckle#307]
I wanted to hide "Try it out!" button and remove some of Response Content Type"  combo-box values.
Is it possible to do that with Swashbuckle?

Is  "Resource Owner Password Credentials" grant type supported in UI?

Any help appropriated.

**Comment by domaindrivendev** [comment]
There's a whole section in the readme on "Customizing the swagger-ui"  (https://github.com/domaindrivendev/Swashbuckle#customizing-the-swagger-ui). Have you take a look at that?

You'll have to get creative for your particular goal, but I would suggest looking at the "InjectJavaScript" option - you could manipulate the DOM accordingly after the UI initially loads.

Another option would be to use your own version of index.html (also described in the docs) and try setting supportedSubmitMethods = [] (empty array). I think this will remove the "Try it out" button.

The described "Content-Types" are driven from the swagger.json API description that comes down from the server. It will create values according to the formatters that are configured in your WebApi.

However, if you like, you can override this by creating a custom IOperationFilter (also described in the docs) that updates the "produces" and "consumes" properties on each Operation description.

**Comment by mkhezrian** [comment]
Thanks for your detailed response. Do you have any idea about my last question, UI support for OAUTH "Resource owner password credential" ?

**Comment by zh-wowtv** [comment]
But I got 404 for all lib/xxxxxx.js.
