### ISSUE TITLE
Swashbuckle.Dummy.Webhost not working

### ISSUE THREAD

**Issue by erikbra** [domaindrivendev/Swashbuckle#308]
I am trying to unserstand more about how Swashbuckle should best be used, and forked Swashbuckle. However, when i clone and try to run the standard web examples, lots of javascript resources from /lib are missing. Am I supposed to fetch jquery, swaggerui, etc, from somewhere else? If so, where do I put them to make stuff work? 

I start the Swashbuckle.Dummy.WebHost project at http://localhost:3429/swagger/, but get 404 errors on the following:

Navigated to http://localhost:3429/swagger/ui/index
index:8 GET http://localhost:3429/swagger/ui/css/reset-css 
index:13 GET http://localhost:3429/swagger/ui/lib/jquery-1-8-0-min-js 
index:11 GET http://localhost:3429/swagger/ui/css/print-css 
index:14 GET http://localhost:3429/swagger/ui/lib/jquery-slideto-min-js 
index:15 GET http://localhost:3429/swagger/ui/lib/jquery-wiggle-min-js 
index:17 GET http://localhost:3429/swagger/ui/lib/handlebars-2-0-0-js 
index:19 GET http://localhost:3429/swagger/ui/lib/backbone-min-js 
index:18 GET http://localhost:3429/swagger/ui/lib/underscore-min-js 
index:16 GET http://localhost:3429/swagger/ui/lib/jquery-ba-bbq-min-js 
index:20 GET http://localhost:3429/swagger/ui/swagger-ui-js 
index:21 GET http://localhost:3429/swagger/ui/lib/highlight-7-3-pack-js 
index:22 GET http://localhost:3429/swagger/ui/lib/marked-js 404 (Not Found)
index:27 Uncaught ReferenceError: $ is not defined(anonymous function) @ index:27
index:1 GET http://localhost:3429/swagger/ui/images/logo_small-png 404 (Not Found)
index:1 GET http://localhost:3429/swagger/ui/fonts/droid-sans-v6-latin-700-woff2 
index:1 GET http://localhost:3429/swagger/ui/fonts/droid-sans-v6-latin-regular-woff2 
index:1 GET http://localhost:3429/swagger/ui/fonts/droid-sans-v6-latin-700-woff 
index:1 GET http://localhost:3429/swagger/ui/fonts/droid-sans-v6-latin-regular-woff 
index:1 GET http://localhost:3429/swagger/ui/fonts/droid-sans-v6-latin-700-ttf 
index:1 GET http://localhost:3429/swagger/ui/fonts/droid-sans-v6-latin-regular-ttf

**Comment by erikbra** [comment]
After a lot of searching and reading source code, I found the following in Swashbuckle.Core.csproj, and that explains a lot:

    
      <ItemGroup>
        <EmbeddedResource Include="..\swagger-ui\dist\**\*.*">
          <LogicalName>%(RecursiveDir)%(FileName)%(Extension)</LogicalName>
          <InProject>false</InProject>
        </EmbeddedResource>
      </ItemGroup>

So, solution was to copy swagger-ui's "dist" folder into the "swagger-ui" folder of swashbuckle, and everything worked fine!!! Cased closed. Some hours of my life I'll never get back...

**Comment by domaindrivendev** [comment]
Hey man - sorry about that. I really need to add a quick note to the readme.

Actually, the swagger-ui is embedded into the solution as a git submodule tied to a specific version (2.1.1-M1). To pull down the correct bits, you just need to execute the following from the solution root

    git submodule update

Thanks

**Comment by erikbra** [comment]
No sweat. But a note would be good. So, there is such a thing as git submodules? Nice to know... Learning more about git every day :) I'll remove the manually downloaded bits and exchange with the submodule. Thanks for the clarification.

**Comment by zuosc** [comment]
你这个坑挖的真好！！！！！！

简直干的漂亮！！！！！！！！
~！！！！！！！！！！！！！
！！！！！！！！

**Comment by willapp** [comment]
It would be really great if the docs could be updated to mention the manual copying of the dist folder. I had exactly the same issue - downloaded the ZIP of this repo (company policy prevents cloning from here) and I couldn't get it working due to the 404 on all .js files.

Got it fixed by also downloading the ZIP of the main swagger-ui repo and copying the dist folder over as suggested by @erikbra.
