### ISSUE TITLE
Ability to set operation id with xml comment

### ISSUE THREAD

**Issue by dmyers** [domaindrivendev/Swashbuckle#310]
Azure API management uses the operationID as the display name field and would be nice to be able to set it in Swagger when importing to there.

**Comment by dcinzona** [comment]
+1

**Comment by domaindrivendev** [comment]
This will be supported in the next release via the SwashbuckleOperation annotation

    [SwashbuckleOperation("GetProductsByCategory")]
    public IEnumerable<Product> Get(string category)
    {
        ...
    }

**Comment by dmyers** [comment]
Thanks! :+1:

**Comment by domaindrivendev** [comment]
Should be resolved in latest release - 5.2.0

**Comment by dmyers** [comment]
Thank you @domaindrivendev! I appreciate your work on this project! :+1:

**Comment by cmshawns** [comment]
Just grabbed the 5.2 release. Thank you for this :+1:
