### ISSUE TITLE
swashbuckle with swagger ui@ webapi

### ISSUE THREAD

**Issue by MarwaAhmed** [domaindrivendev/Swashbuckle#311]
Kindly, if you would help me how could i view the swagger UI.

my project tools:
- asp.net webapi doesn't have owin
what i did:
- using nuget console: install-package shwashbuckle 
- edit swaggerconfig.cs: uncomment the line code:   c.IncludeXmlComments(GetXmlCommentsPath());
wrote the function's body: 
      private static string GetXmlCommentsPath()
        {
            return string.Format(@"{0}\bin\SwaggerWebApi.XML", System.AppDomain.CurrentDomain.BaseDirectory);
        }
- builld the webapi project -> i got my default page
- when i browse: to point http://localhost:15073/swagger.index.html
i got that the resource didn't exist?
what shall i do in order to see the swagger's UI?
thanks in advance,
Marwa

**Comment by domaindrivendev** [comment]
Not sure if it's a typo but the URL above is wrong (where did you get it from?). Try one of the following instead ...

http://localhost:15073/swagger
http://localhost:15073/swagger/ui/index.html

**Comment by MarwaAhmed** [comment]
@domaindrivendev :+1: Thank you. it works! http://localhost:15073/swagger
