### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by michaeldotknox** [domaindrivendev/Swashbuckle#314]
Have you considered adding logging into Swashbuckle?  It's really an excellent package and is becoming the go-to method of providing documentation for our internal apis, but troubleshooting any problems can be cumbersome.  @damainh has an excellent library called LibLog at https://github.com/damianh/LibLog that would probably be ideal.

**Comment by domaindrivendev** [comment]
Can you give an example of an issue you've been troubleshooting where logging would have helped as opposed to say improved exception messages?

I'm loathe to scatter logging concerns (hard dependency or not) throughout the code base. If anything, I would introduce a simple pub/sub mechanism and have the code raise "domain events" that an application can subscribe to for logging, analytics or whatever it sees fit.

But, given the nature of Swashbuckle, there would have to be a strong case to introduce this additional complexity as opposed to just improving the information bubbled up through exceptions

**Comment by michaeldotknox** [comment]
I had an issue similar to this one: https://github.com/domaindrivendev/Swashbuckle/issues/295

Unfortunately, I had to rollback the changes that introduced Swashbuckle for unrelated reasons, but I've also been working with a project that uses LibLog and I've learned to appreciate the ease with which it allows logging that is not coupled to a specific logging framework.

If I get a chance to add Swashbuckle back into the project I'll see if I can get you some more information on the problem.  You can certainly do the same thing with additional information coming from exceptions and that would likely help troubleshooting a great deal.  The thing that I like about logging is that you can easily see the error messages that occur and where they occur without seeing the message on the screen yourself.

**Comment by domaindrivendev** [comment]
If you can provide me with more details, in particular where richer exception messages would help we can re-open. In the meantime, I've no plans to build logging into the framework.

Thanks
