### ISSUE TITLE
Ability to show class XML description  in UI for response and parameter model

### ISSUE THREAD

**Issue by mkhezrian** [domaindrivendev/Swashbuckle#315]

**Comment by domaindrivendev** [comment]
Need more information .. examples ...

**Comment by mkhezrian** [comment]
Currently, by calling IncludeXmlComments, in case of model  classes, all XML comments of public properties are displayed, but the model class description(class <summary>)is not displayed. No need to say that displaying XML description for controller classes doesn't make scene, but for model classes that can be informative in term of documentation.

I implemented ISchemaFilter and debugged the case and realized all XML comments are loaded as well as class description, but only class descriptions, are not injected into the swagger UI. 

I would be happy if I could contribute to implement this feature if it's not supported now.

**Comment by domaindrivendev** [comment]
If I understand correctly, you want to take the Schema "description" property, which is being correctly pulled from Xml comments, and render it somewhere in the UI.

If this is the case, then really the change needs to happen in the swagger-ui project - https://github.com/swagger-api/swagger-ui.

First and foremost, SB is a Swagger generator. For convenience, it does provide an embedded version of swagger-ui but other than that isn't overly concerned with how the swagger-ui is implemented.
