### ISSUE TITLE
No Documentation for modeltype ModelStateDictionary created

### ISSUE THREAD

**Issue by Gentlehag** [domaindrivendev/Swashbuckle#318]
In a api i return the WebApi ModelStateDictionary if validation errors occur.
The Method is annotated like this:

[SwaggerResponse(400, Type = typeof(ModelStateDictionary)

Now I can see taht 400 is generated as response but no model oder modelschema is shown  for this case in the documentation.

What am I doing wrong?

**Comment by Gentlehag** [comment]
Any help?

**Comment by domaindrivendev** [comment]
Being a dictionary, that specific type is described in the outputted swagger json as follows:

    schema: {
        type: "object",
        additionalProperties: {
            $ref: "#/definitions/System.Web.Http.ModelBinding.ModelState"
        }
    }

While this is the correct way to describe dictionary / map types in Swagger, the swagger-ui does not appear to support documentation of schema's that use "additionalProperties". It has been reported through the following issue but you may want to add a +1 to give things a little push.

https://github.com/swagger-api/swagger-ui/pull/990

It's worth noting that you can wire up your own custom description for that type as follows but I'm not sure that really helps

    c.MapType<ModelStateDictionary>(() => Schema { ... });
