### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by dmyers** [domaindrivendev/Swashbuckle#329]
Is it possible for this package that creates the routes for the swagger JSON to set the CORS headers automatically? I'm unsure how to set them manually.

https://github.com/swagger-api/swagger-ui#testing-cors-support

**Comment by adamfisher** [comment]
I need this is as well so I can debug from Fiddler.

**Comment by domaindrivendev** [comment]
Just read the following blog on CORS in WebApi and was easily able to enable it for the swagger JSON endpoints using a custom policy provider ...

https://msdn.microsoft.com/en-us/magazine/dn532203.aspx

    Install-Package Microsoft.AspNet.WebApi.Cors

    // WebApiConfig.cs
    config.EnableCors(new CustomCorsPolicyProvider());

    // CustomCorsPolicyProvider.cs
    public class CustomCorsPolicyProvider : ICorsPolicyProvider
    {
        public Task<CorsPolicy> GetCorsPolicyAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var corsPolicy = new CorsPolicy();

            if (request.RequestUri.PathAndQuery.StartsWith("/swagger/docs"))
            {
                corsPolicy.AllowAnyHeader = true;
                corsPolicy.AllowAnyMethod = true;
                corsPolicy.AllowAnyOrigin = true;
            }

            var tsc = new TaskCompletionSource<CorsPolicy>(); 
            tsc.SetResult(corsPolicy);
            return tsc.Task;
        }
    }

**Comment by dmyers** [comment]
Thanks! I ended up finding a way to add CORS to the web api I was in globally and that is a good solution as well.

**Comment by mishrsud** [comment]
Hi @dmyers, could you elaborate on what you mean by "the web api I was in globally"?

**Comment by mishrsud** [comment]
@domaindrivendev I ran into this issue in an IIS hosted Katana application, followed your suggestion to add the custom CORS policy provider but I don't see the Access-Control-Allow-Origin header coming back (inspected in Fiddler). I even tried adding the header through web.config as suggested [here](https://github.com/domaindrivendev/Swashbuckle/issues/354) - the CORS header now comes back in response but swagger UI still doesn't render.
In Chrome, in the Network profiling tab, I can see that the call from swagger-ui-min JS is blocked with a status "blocked:mixedcontent" - what am I doing wrong?

**Comment by mishrsud** [comment]
@domaindrivendev I figured it out! the issue wasn't CORS but the fact that in Swagger UI, the URL in the text box defaulted to http whereas we were accessing an otherwise secure https URL. Changing this line in SwaggerConfig:

`c.RootUrl(req => ...);`

to append HTTP or HTTPS based on configuration fixed the issue!

**Comment by aj11** [comment]
Can you provide example using c.rooturl(), how to make swagger working for https urls, if i call https url, it internally calls http url and throws origin exception...

**Comment by srinivasteella** [comment]
aj11, I had the same issue. Resolved it by adding below configuration.

public static void Register()
        {
            var thisAssembly = typeof(SwaggerConfig).Assembly;

            string ResolveBasePath(HttpRequestMessage message)
            {
                var virtualPathRoot = message.GetRequestContext().VirtualPathRoot;

                var schemeAndHost = (message.RequestUri.Host.Equals("localhost", StringComparison.InvariantCultureIgnoreCase) ?
                                        "http://" : "https://") + message.RequestUri.Authority;
                return new Uri(new Uri(schemeAndHost, UriKind.Absolute), virtualPathRoot).AbsoluteUri.TrimEnd('/');
            }

            GlobalConfiguration.Configuration
                      .EnableSwagger(c =>
                      {
                          c.RootUrl(ResolveBasePath);
                          c.SingleApiVersion("v1", "API Name");
                          c.ResolveConflictingActions(apiDescriptions => apiDescriptions.FirstOrDefault());
                          c.IncludeXmlComments(string.Format(@"{0}\bin\SwaggerDemoApi.XML",
                                               System.AppDomain.CurrentDomain.BaseDirectory));
                          c.DescribeAllEnumsAsStrings();
                          c.OperationFilter<AddAuthorizationHeaderParameterOperationFilter>();
                      })
                      .EnableSwaggerUi(a => { a.DocExpansion(DocExpansion.List);
                          a.DisableValidator();
                      });
            
                      
        }
