### ISSUE TITLE
Improve Enum Descriptions

### ISSUE THREAD

**Issue by technicallyerik** [domaindrivendev/Swashbuckle#330]
Wanted to get your thoughts on this before sending a PR.

What if the enum description returned both the integer and string value, regardless of if the enum is used as an integer or a string.  Sometimes I want end-users to conceptually understand what the integer enum values mean.

This would change `CreatePrimitiveSchema` in `SchemaRegistry.cs` to something like this:

```
if (type.IsEnum)
{
    var converter = primitiveContract.Converter;
    var describeAsString = _describeAllEnumsAsStrings 
        || (converter != null && converter.GetType() == typeof(StringEnumConverter));

    return describeAsString
        ? new Schema { type = "string", @enum = GetEnumValues(type).Cast<object>.ToArray() }
        : new Schema { type = "integer", format = "int32", @enum = GetEnumValues(type).Cast<object>.ToArray() };
}
```

With the addition of this method:

```
private static IList<string> GetEnumValues(Type t)
{
    var result = new List<string>(); 
    var values = Enum.GetValues(t);
    foreach(var value in values)
    {
        result.Add(string.Format("{0}: {1}", (int)value, Enum.GetName(t, value)));
    }
    return result;
}
```

Right now my workaround without forking is this:

```
public class ApplyDocumentVendorExtensions : IDocumentFilter
{
    public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
    {
        foreach (var schemaDictionaryItem in swaggerDoc.definitions)
        {
            var schema = schemaDictionaryItem.Value;
            foreach (var propertyDictionaryItem in schema.properties)
            {
                var property = propertyDictionaryItem.Value;
                var propertyEnums = property.@enum;
                if (propertyEnums != null && propertyEnums.Count > 0)
                {
                    var enumDescriptions = new List<string>();
                    for (int i = 0; i < propertyEnums.Count; i++)
                    {
                        var enumOption = propertyEnums[i];
                        enumDescriptions.Add(string.Format("{0} = {1} ", (int)enumOption, Enum.GetName(enumOption.GetType(), enumOption)));
                    }
                    property.description += string.Format(" ({0})", string.Join(", ", enumDescriptions.ToArray()));
                }
            }
        }
    }
}
```

**Comment by domaindrivendev** [comment]
Unless I'm missing something, your proposed changes appear a little different to those applied by your document filter. The former changes the enum values to invalid values which would not actually be correctly de-serialized by WebApi. I assume, this is a typo and your intention is to provide the value/name format as a description on any properties which are enum types.

Thanks for the suggestion but, I'm not overly keen on providing this out-of-the-box. XML comments are the standard way to provide a description for properties, enum or otherwise. Furthermore, if I'm serializing enums as strings, then the integer value could well be an implementation detail that service providers don't want to expose to the outside world - and vice versa.

Thanks for the suggestion and support.

**Comment by CarlosSardo** [comment]
@technicallyerik how did you exactly integrate this ApplyDocumentVendorExtensions in your SwaggerConfig.cs?

Thanks!

**Comment by Teilmann** [comment]
I have succesfully implemented your VendorExtension, but the outcome looks a bit weird to me.

Category (integer): (0 = WATCHPOST , 1 = ARTICLE , 2 = DISCUSSION , 3 = QUESTION , 4 = REVIEW , 5 = VIDEO , 6 = COLLECTION , 7 = QUIZ ) **= ['0', '1', '2', '3', '4', '5', '6', '7']**

Is it possible to exclude the text highlighted in bold? (i highlighted the text, it's actually not highlighted in swagger)

**Comment by resquej** [comment]
Hi,
It happens the same for me. Any solution to clear the list in bold?
