### ISSUE TITLE
F# Discriminated Unions support

### ISSUE THREAD

**Issue by nibras85** [domaindrivendev/Swashbuckle#331]
I'm modelling my API resources using F#. I noticed that F# Discriminated Unions aren't handled properly by Swashbuckle 

Example: 
My GET endpoint is:

        [Route("{id}"), HttpGet]
        [ResponseType(typeof(Status))]
        public IHttpActionResult GetStatus(Guid id)
        {
           //example
            return Ok(Status.InProcess);
        }

and the Status F# DU looks like: 

     type Status = 
        | InProcess
        | Approved of Details
        | Deleted
    and Details = 
      { ApprovedBy               : int
        ApprovalDateTime     : DateTime }

This is what I get:

![image](https://cloud.githubusercontent.com/assets/11825028/7632128/f136fcc4-fa17-11e4-87a7-a8b98d1d83c9.png)

Swashbuckle properly handles F# Records (https://msdn.microsoft.com/en-us/library/dd233184.aspx). The only exception here is Discriminated Unions (https://msdn.microsoft.com/en-us/library/dd233226.aspx).

**Comment by et1975** [comment]
I'm using F# as well, but I'm kinda surprised you'd expose DU as a boundary DTO type. I'd think type hierarchies in general are not a good fit for DTOs.

**Comment by nibras85** [comment]
I'm basically trying to keep the API type as close as possible to the domain type. I'm using DUs in the domain type.  What do you suggest?

**Comment by et1975** [comment]
Unless you use XML your type hierarchy is not consumable "as is". In order for something like JS to handle what the API returns you need to flatten/restructure the hierarchy into some kinda of DTO/view model - maybe a discriminator attribute and a structure for every DU case.
Personally, I'm looking at [lenses](https://github.com/xyncro/aether) to convert to and from public DTOs.
Once you have any kind of transformation going, as a bonus you get to setup a pipeline that can handle Option<> and return something like (HttpStatusCode.OK, result) | (HttpStatusCode.NotFound).

**Comment by domaindrivendev** [comment]
Sounds like there's a deeper, non SB, issue here? Although it's on my todo list at some stage, I'm not overly familiar with F#. Feel free to re-open if you feel it's a true SB issue.
