### ISSUE TITLE
How can I restrict access to documentation URLs

### ISSUE THREAD

**Issue by streamstr** [domaindrivendev/Swashbuckle#334]
Hello everyone. I'm testing Swashbuckle on our WebApi project, all works great. But i want to implement behaviour when documentation and swagger ui are available only to users, who has token. Some info about current authorization logic in service: Each controller is marked with attributre [Authorize]. So to access any action Authorization header with token is required. Anyone, who wants to access API calls specific method (ex. api/v1/account/token) and supplies username and password in request. Server responds with token. Client uses this token to access each service method.

I cant find any info on how to restrict access to swagger documentation. Can anyone help?
Thanks.
Serg

**Comment by domaindrivendev** [comment]
Off the top of my head I would say a DelegatingHandler is what you need here.

It can be configured to execute earlier in the pipeline than the Swagger handlers. First it can check if the request is for a swagger resource. If so, it should return a 403 forbidden response unless the required token is available. For all other cases just delegate to the next handler in the chain
