### ISSUE TITLE
No swagger output when running WebAPI self-hosted server as a Windows service

### ISSUE THREAD

**Issue by gwalschl** [domaindrivendev/Swashbuckle#335]
I have successfully used Swashbuckle with my C#/.NET/WebAPI based REST server running in a console window.  The output looks great and is just what I expected to see.  I see a title line and all my controllers, can expand them, try out calls, etc.  All works great.  

However, using the exact same code running as a service (via ServiceBase.Run() in .NET), when I request the swagger UI output, I get the title to appear at the top of my swagger UI just as always, but now there's absolutely no content below that title.  Again, running as a console it works great.  

While running as a Windows service, I can access any of my REST services successfully as well.  So there's no difference in addressing and server is responsive to normal REST operations, I just don't get any content in my swagger UI page.  

Additionally, I have ensured that I run the service using the same user account as well.  I'm a bit stumped.  Any help greatly appreciated.

**Comment by Schandlich** [comment]
Are there any javascript errors on the page? Can you hit the generated json doc?

**Comment by gwalschl** [comment]
Schandlich, thanks for the response.  I just realized earlier this morning that I made a dumb mistake and didn't have the resources (CSS, etc.) accessible when deployed as a service.  I'll have to close this issue on my sillyness.  Thanks!

**Comment by leonfibal** [comment]
What do you mean saying "didn't have the resources (CSS, etc.) accessible"? I have a similar problem

**Comment by NahumLitvin** [comment]
can you please explain how you solved this issue?

**Comment by nishantdave** [comment]
Having the same issue, anybody found a resolution here? please help!
