### ISSUE TITLE
What is swagger doc generated by Swashbuckle?

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#337]
I am learning Swagger and part of it I found Swashbuckle for my web api project.

I was reading documentation at link https://github.com/domaindrivendev/Swashbuckle and found one point under "Swashbuckle Core Features:"

==> "Extensibility hooks for customizing the generated Swagger doc"

What is swagger doc ? Where do I see generated swagger doc?

**Comment by domaindrivendev** [comment]
Swagger is a service description language for HTTP/REST API's. You can read more about it here - http://swagger.io. A "Swagger Document" is a JSON document that describes your API according to the Swagger 2.0 specification - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md.

First and foremost, Swashbuckle is Swagger generator. That is, it auto-generates the JSON to describe your service. Once installed, you can access the raw JSON document here:

\<your-root-url\>/swagger/docs/v1

The swagger-ui on the other hand, is just one of many awesome tools that consume this document to provide tooling around your service.
