### ISSUE TITLE
Doubt about Swagger 2.0 document

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#338]
I was going through documents about Swashbuckle and got doubt in the below mentioned paragraph.

---------------------------------------------------
Schemes:
If schemes are not explicitly provided in a Swagger 2.0 document, then the scheme used to access the docs is taken as the default. If your API supports multiple schemes and you want to be explicit about them, you can use the Schemes option.
---------------------------------------------------

As per the paragraph, where is Swagger 2.0 located and how do I do modifications?

**Comment by domaindrivendev** [comment]
See #337
