### ISSUE TITLE
how do I handle windows authentication using Swashbuckle?

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#340]
how do I handle windows authentication using Swashbuckle for my asp.net web api?

**Comment by domaindrivendev** [comment]
You should read up on the API security schemes supported in the swagger spec - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-definitions-object

Swashbuckle is a Swagger 2.0 generator that comes bundled with a corresponding swagger-ui that consumes the generated Swagger to document your API.

If you've figured out a way to do what you're trying to do with the Swagger spec and swagger-ui (independent of Swashbuckle) then I can help you get things wired up. But until then you'll have to do some deeper digging into "Swagger" itself.
