### ISSUE TITLE
About Api_Key in Swagger UI

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#341]
I have installed Swashbuckle on my web api project and hit URL - http://localhost:port/swagger/ui/index. It opened Swagger UI having 2 textboxes at top of page.

1st text box has URL - http://localhost:port/swagger/docs/v1 and 2nd text box has place holder "api_key". What is significance of this text box and button Explore adjacent to it.

**Comment by domaindrivendev** [comment]
Swashbuckle is built on top of "Swagger". I think you should read up more on "Swagger" itself  (http://swagger.io/) as most of your issues are broader Swagger questions.
