### ISSUE TITLE
How to send Authorization header with a request in Swagger UI ?

### ISSUE THREAD

**Issue by martadoberschuetz** [domaindrivendev/Swashbuckle#342]
I have a ASP.NET Web Api 2 application and added Swashbuckle to it. It displays my endpoints no problem, but in order to send a request I need to attach an Authorization header to that request. If I understand correctly in order to do that I need to modify the index.html file (https://github.com/swagger-api/swagger-ui#how-to-use-it) so I git cloned Swashbuckle project in order to modify index.html and add some headers.

Is that the only way to send Authorization header with the request in Swashbuckle?

**Comment by domaindrivendev** [comment]
You don't need to fork the repo. Swashbuckle provides a simple way to inject your own version of "index.html". See the readme for details.

Another option would be to add a corresponding "header" parameter to all applicable operations so it would just get rendered as another input with each operation. You would use an IOperationFilter (again see readme) for this.

Of course you'd probably want a convenient login widget on the page to auto populate these so you'd need to customize "index.html" anyway. But this approach makes the actual service description a bit more accurate

**Comment by martadoberschuetz** [comment]
Assuming that the index.html is located at D:\ is this the correct way to load my custom index.html: ?

     using System.Web.Http;
     using WebActivatorEx;
     using Name.Of.The.Project;
     using Swashbuckle.Application;

     [assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]

     namespace Name.Of.The.Project
     {
	     public class SwaggerConfig
         {
		     public static void Register()
		     {
			var thisAssembly = typeof(SwaggerConfig).Assembly;

			GlobalConfiguration.Configuration
				.EnableSwagger(c =>
				{
					c.SingleApiVersion("v1", "Name.Of.The.Project");
					c.OperationFilter<AddHeaders>();
				})
				.EnableSwaggerUi(c =>
				{
					c.CustomAsset(@"D:\index.html", thisAssembly, "Name.Of.The.Project.index.html");
				});
		}
	}

**Comment by martadoberschuetz** [comment]
Ok, so this is the correct way to load the file:

       c.CustomAsset("index", thisAssembly, "Name.Of.The.Project.index.html");

I thought that the first argument of CustomAsset is "path" - I thought it was the path to where the custom index.html was located...
Now I have a different problem, the application can't find any of the javascript or css files...
