### ISSUE TITLE
Void with ResponseType attribute

### ISSUE THREAD

**Issue by henkosch** [domaindrivendev/Swashbuckle#344]
Take a look at the following snippet:
```
public class ValuesController : ApiController
{
    public void Put()
    {
    }

    [ResponseType(typeof(void))]
    public IHttpActionResult Post()
    {
        return StatusCode(HttpStatusCode.NoContent);
    }
}
```

I expect the two operation to have the same result in the responses field. 

Both should have: 
```
"responses":{"204":{"description":"No Content"}}
```

But instead the Post operation gets the following:
```
"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Void"}}}
```

This generates the following on swagger-ui:
![screenshot 2015-05-21 00 50 56](https://cloud.githubusercontent.com/assets/908091/7738357/a1b01f78-ff53-11e4-89b1-adbfdee497f1.png)

Which is clearly wrong. I need the Post operation to have IHttpActionResult, so I can return with BadRequest() or Unauthorized() etc. That is why I used the ResponseType attribute to specify when it succeeds it should return 204 No content, without a schema reference.

How can I remove these strange "schema":{"$ref":"#/definitions/Void"} references from my operations?

**Comment by domaindrivendev** [comment]
This is a SB bug - just isnt handled because I never thought of the case where you would use ResponseType instead of void on the action signature. Simple fix ... will go out with next release

**Comment by domaindrivendev** [comment]
In the meantime, you could do the following as a workaround ...

    [SwaggerResponseRemoveDefaults]
    [SwaggerResponse(204, "No Content")]
    public IHttpActionResult Post()
    {
        ...
    }

**Comment by domaindrivendev** [comment]
Should be resolved in latest release - 5.2.0

**Comment by dmyers** [comment]
Thanks I needed this too! Great release! :+1:

**Comment by mc0re** [comment]
What about .NET Core version? It has no `SwaggerResponseRemoveDefaults` attribute, and `[ProducesResponseType(StatusCodes.Status204NoContent, Type = typeof(void))]` does not seem to work.
