### ISSUE TITLE
How document custom Types

### ISSUE THREAD

**Issue by Gentlehag** [domaindrivendev/Swashbuckle#347]
Hi

I've a webapi method like this

     public void Post([MyFormatter] IBaseType argument)

Now i can pass different types implementing IBaseType. I'd like to create documentation for all known possibilities (i got a static typeList of them). Is there a way to get them into the swashbuckle documentation ? If the they were generally documentated i could manully insert the link to the types in the comment.

**Comment by Gentlehag** [comment]
Any hints?

**Comment by domaindrivendev** [comment]
Just to clarify ... do you mean that, for the above operation, you want to document all possible types that can be passed to the operation?

If so, then this is a duplicate of the #313. Can you confirm that I've understood your question correctly?

Cheers

**Comment by Gentlehag** [comment]
yeah it is . thx for the hint
