### ISSUE TITLE
OAuth2 and Azure Active Directory - invalid_resource

### ISSUE THREAD

**Issue by ChrisHimsworth** [domaindrivendev/Swashbuckle#348]
I am trying to use Swashbuckle/Swagger with OAuth2 using Azure Active Directory as the identity provider.
I am managing to authorise my application, but the issue comes when Swagger requests a token from Azure Active Directory, I get the response:
"error":"invalid_resource","error_description":"AADSTS50001: Resource identifier is not provided.

Looking at MSDN docs: https://msdn.microsoft.com/en-us/library/azure/dn645542.aspx, under the heading "Use the Authorization Code to Request an Access Token", there is an optional field called resource, but it seems that in this scenario Microsoft requires this field.

Is there a way in which Swashbuckle and Swagger can be changed to pass this in?

**Comment by Snelbinder** [comment]
Swagger currently only supports the implicit OAuth2 flow, you are trying to use the authorization code grant flow.

https://github.com/swagger-api/swagger-ui/issues/807
