### ISSUE TITLE
Is there any way I can use Swashbuckle to generate Swagger UI/Doc for already deployed app?

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#349]
We have a already deployed web api application. Is there any way we can use Swashbuckle to generate Swagger UI/Doc for already deployed app. Consider we do not have option to again build thoes application.

**Comment by domaindrivendev** [comment]
It's not really an intended use-case and so you would have to jump through a lot of hoops to get it working. Generating the corresponding docs in a separate process - so, long as you have access to the DLL's, it's essentially not very different from what the SB tests do - https://github.com/domaindrivendev/Swashbuckle/tree/master/Swashbuckle.Tests.

Have you considered not using SB and manually creating a static swagger.json file for your API. You could then host this, along with the swagger-ui (https://github.com/swagger-api/swagger-ui) in a separate static website.

**Comment by ravi032** [comment]
I am new to SB and swagger. So, kindly suggest ho do I do it i.e. generate swagger.json without SB from my API?
