### ISSUE TITLE
Remarks from action being placed on controller header in UI

### ISSUE THREAD

**Issue by jslaybaugh** [domaindrivendev/Swashbuckle#351]
I've spent the last couple days playing around with Swashbuckle and the config options and I think I got everything the way I wanted it, and then as I was commenting my new methods, I noticed something strange. I added a `<remarks></remarks>` to my first **action** and it added that as a description after a colon to the heading for the **controller** in the UI (see screenshots below).

![screen shot 2015-05-21 at 11 33 37 am](https://cloud.githubusercontent.com/assets/306883/7753857/b87842da-ffad-11e4-9335-814182387454.png)
![screen shot 2015-05-21 at 11 33 55 am](https://cloud.githubusercontent.com/assets/306883/7753859/ba699df0-ffad-11e4-98b6-4b4c94e6afa6.png)

Notice how the content provided in the `<remarks></remarks>` is appearing in the Implementation Notes like it is supposed to, but for some reason, it is also appearing in the controller header.

I had already followed your suggestion from https://github.com/domaindrivendev/Swashbuckle/issues/217 to make my own customization. I'd LOVE if I could use the `<remarks></remarks>` **on the controller** to do this instead, but having it pull from the action, really messes me up.

Is this a bug or something I've done wrong?

**Comment by domaindrivendev** [comment]
Which version of Swashbuckle are you using? I think this is actually a dup of #190 and should be resolved as of 5.01

**Comment by jslaybaugh** [comment]
Ugh, you're right. I was shuffling a bunch of stuff around in projects and forgot that this one came with the Azure API app template in VS, so it wasn't the latest -- it was 5.0.0.

I've updated and it seems fine now. Sorry for the false alarm.
