### ISSUE TITLE
Request URL is Different from URL in Browser

### ISSUE THREAD

**Issue by adamfisher** [domaindrivendev/Swashbuckle#352]
While testing out Swagger on our server, I navigate to **https://mydomain.com/swagger** (without a port number) but when I try a request, I get back "no content" in the response body. I noticed the request URL is including a port number as shown below.

![capture](https://cloud.githubusercontent.com/assets/1834711/7758597/c7efbf06-ffd8-11e4-818c-37519d43e3fa.PNG)

The server sits behind Microsoft TMG and is load balanced so I think Swagger is detecting the internal port and not setting the request URL based on what is actually navigated to in the browser. Is there a way to configure Swashbuckle to use the client side URL in the browser vs. creating it on the server side?

**Comment by cguedes** [comment]
Same problem here with a site hosted in AppHarbor.

The issue is in this line: https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Application/SwaggerDocsConfig.cs#L248

@domaindrivendev you should read those values from the request header `host`.

**Comment by cguedes** [comment]
@adamfisher In the meanwhile you can use the RootUrl setting: https://github.com/domaindrivendev/Swashbuckle#rooturl

**Comment by domaindrivendev** [comment]
@cguedes - I don't believe that line is the issue. The host header is being used (via RequestUri.Host). It's only when the X-Forwarded- headers are present, that these are used instead. This is an attempt to handle proxy setups where the original Host is not preserved.

This is likely what's happening ... my guess is that the request from the load balancer to your API contains a Host header with the internal host / port combination but doesn't include any of the X-Forwarded headers. I would imagine it's providing it in some other header and so you would have to provide your own implementation via the _RootUrl_ setting. 

@adamfisher - I think you're correct in saying that this would be better handled on the client side. This is something I'm looking into for the next major release (targeted to AspNet vNext) but will likely punt on for the 5.2.0 release. So, the RootUrl workaround is the way to go for now

**Comment by adamfisher** [comment]
I tried ```c.RootUrl(req => "https://mydomain.com");``` but the port number still shows up in the request URL in the Swagger docs. No matter what variation I tried with the request URL object it also didn't load successfully. For now I am probably going to just live with it because it only occurs in our higher environments protected by TMG with load balancing.

**Comment by martincostello** [comment]
Same problem here. Despite using ```c.RootUrl()``` to return the host name which I had configured in the ```Web.config``` file, the default protocol (i.e. 443 for HTTPS) is contained in the URL. Swashbuckle should not be inserting ports into the host downstream of what is configured by the user on startup.

Have resorted to working around it by adding a custom ```IDocumentFilter``` implementation.

**Comment by martincostello** [comment]
For reference, the implementation of the ```IDocumentFilter``` is below:

```
using System;
using System.Web.Http.Description;
using Swashbuckle.Swagger;

/// <summary>
/// A class representing a document filter to work around <c>https://github.com/domaindrivendev/Swashbuckle/issues/352</c>.
/// </summary>
internal sealed class RemoveDefaultPortFromHostFilter : IDocumentFilter
{
    private const string HttpsPortSuffix = ":443";

    /// <inheritdoc />
    public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
    {
        if (swaggerDoc != null && swaggerDoc.host != null)
        {
            if (swaggerDoc.host.EndsWith(HttpsPortSuffix, StringComparison.Ordinal))
            {
                swaggerDoc.host = swaggerDoc.host.Substring(0, swaggerDoc.host.Length - HttpsPortSuffix.Length);
            }
        }
    }
}
```

**Comment by martincostello** [comment]
Looks like PR #470 will resolve this.

**Comment by adamfisher** [comment]
It's not fixed in 5.2.2 which is the latest but I don't see where that commit is tied to a nuget release?

**Comment by JessieGit** [comment]
Is this problem got resolved?

**Comment by domaindrivendev** [comment]
@adamfisher, @JessieGit - is this still an issue for you with the latest version (5.6)? Because it's been a while and I think this should be resolved, I'm going to close for now. But please reopen if you're still having issues
