### ISSUE TITLE
xml error in frontend

### ISSUE THREAD

**Issue by mrtristan** [domaindrivendev/Swashbuckle#353]
So I just updated my Swashbuckle implementation from one that I got fully functional a couple months ago and submitting a json request is all fine, but when i change the request type to text/xml it never returns.

If i don't use swagger and actually hit it with that request type, it all plays nice.

I looked in my chrome console and i'm seeing the following:

https://www.dropbox.com/s/mwnlbchfyuimru8/swagger.png?dl=0

any thoughts? thanks!

**Comment by Snelbinder** [comment]
Can confirm this issue, I've also been experiencing this.

**Comment by domaindrivendev** [comment]
Which version of SB are you using? I've tried it out with the latest (5.1.5) and am unable to repro

**Comment by Snelbinder** [comment]
I'm using version 5.1.5 as well, it occurs for any simple route. Using request content type "application/xml" and "application/json" work perfectly. "text/xml" and "text/json" show the loader but never returns.

**Comment by domaindrivendev** [comment]
This was a swagger-ui issue. Looks like its fixed as of the v.5.2.1 release of Swashbuckle
