### ISSUE TITLE
Path parameter is marked as not required if it has a default value in the method signature

### ISSUE THREAD

**Issue by RPrimrose** [domaindrivendev/Swashbuckle#355]
I came across some code that's resulting in Swashbuckle producing invalid output. Specifically, it's marking a path parameter as not required, which then fails when you try to validate it.

The problem is with a method in a controller that looks like
```
[HttpGet, Route("{version:int}/Variables")]
public IHttpActionResult GetTemplateVariables(Guid templateId, int version = 0)
```
The resulting entry in the generated JSON looks like
```
"/api/Templates/{templateId}/Versions/{version}/Variables": {
	"get": {
		"tags": [
			"Template Versions"
		],
		"summary": "Get the variables for a template",
		"operationId": "TemplateVersion_GetTemplateVariables",
		"consumes": [],
		"produces": [
			"application/json",
			"text/json",
			"application/xml",
			"text/xml"
		],
		"parameters": [
			{
				"name": "templateId",
				"in": "path",
				"description": "",
				"required": true,
				"type": "string"
			},
			{
				"name": "version",
				"in": "path",
				"description": "",
				"required": false,
				"type": "integer",
				"format": "int32"
			}
		],
		"responses": {
			"200": {
				"description": "OK",
				"schema": {
					"$ref": "#/definitions/DiscoveryTemplate"
				}
			}
		},
		"deprecated": false
	}
},
``` 

Obviously it doesn't make sense to have a default value for the version variable and once I removed that the generated JSON was then fine, but given the initial code compiles and works fine ideally Swashbuckle should generate valid/correct JSON from it.

**Comment by domaindrivendev** [comment]
ApiExplorer (the WebApi meta-data component which SB is built on top of) describes the parameter as being optional. Given that it makes no sense to bind an optional method parameter to a required route parameter, I'm happy to let this one go rather than introduce the extra code into SB.
