### ISSUE TITLE
Exception when running self host in Mono

### ISSUE THREAD

**Issue by cprieto** [domaindrivendev/Swashbuckle#357]
I am having a weird exception thrown when running in Mono, I have tried to debug but I have no luck to find that mysterious type not found...

Details with the exception (including a simple example to reproduce) are here https://gist.github.com/cprieto/d70db69ecf4fcf9aaf50

Thanks a lot for your help

Running in Mono 4.0.1
Tested in MacOSX, FreeBSD and Ubuntu Linux, not luck at all :(

**Comment by slogen** [comment]
+1 Exact same issue here

**Comment by rjvdboon** [comment]
If Swashbuckle.Core would be compiled for .net 4.5 I think it would work.
The current reference to System.Net.Http is to the NuGet package (assembly version 2.0.0.0), but with .net 4.5 it would reference the framework assembly includes in .net 4.5 (assembly version 4.0.0.0).

Apparently mono resolves the assemblies different from ms.net.

**Comment by johanhelsing** [comment]
Same issue here with the `mono` docker image and the `microsoft/aspnet` image.

**Comment by deluvas** [comment]
@rjvdboon +1

```
Mono: Failed to load assembly Swashbuckle.Core[0x10f7b10]
Mono: Could not load file or assembly 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

**Comment by jpdillingham** [comment]
In Mono versions prior to the latest at the time of this post (5.2.0 SR4, 5.2.0.224) the assembly redirect was not working for whatever reason.  Updating Mono to the latest fixed the problem for me, and the assembly redirect is no longer necessary.

I also noted that targeting .NET Framework 4.5 will automatically update Swashbuckle.Core's internal reference to System.Net.Http to 4.x which would also likely resolve the issue on older versions of Mono.

I would recommend closing this issue.

**Comment by deluvas** [comment]
Can confirm the above.
