### ISSUE TITLE
Is there any way I can use Swashbuckle to generate Swagger Doc for already deployed app?

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#358]
We have a already deployed web api application. Is there any way we can use Swashbuckle to generate Swagger JSON Document for already deployed web api application. 

We are in situation that we deployed vary large application and could not get option to build full app and again deploy. 

Kindly suggest a way do integrate SB in deployed app?

**Comment by domaindrivendev** [comment]
Closing as this is not a supported use-case. With that said however, you can look at #356, where I've described some brief steps to host Swashbuckle in a separate app to the actual API. In this case, you need the actual API's DLL's to be present in the bin folder of the docs application.
