### ISSUE TITLE
Inherited operations does not include XML comments

### ISSUE THREAD

**Issue by monobjorn** [domaindrivendev/Swashbuckle#359]
In my project I have a BaseController class which inherits from ApiController.  
In my BaseController I have a "Get" method which I have written XML comments for.  
None of the controllers inheriting from BaseController get any comments in Swagger-UI (or in the generated Swagger-JSON).  
Is this a bug or is that the expected behavior?

**Comment by domaindrivendev** [comment]
This is the expected behavior - inherited documentation is not supported

**Comment by dandesybsb** [comment]
Is there a workaround for these base class methods to show up on the UI?
We implemented "ping" functionality at the base controller level, and would like to see it exposed for all services.

**Comment by mgerega-accruent** [comment]
@dandesybsb have you found a solution for this? We have a similar issue, with functions (and documentation) at the base level, and the documentation is not brought forward to the extending classes.

**Comment by patrickjrs** [comment]
We had the same issue and since it was expected behavior we ended up creating a custom OperationFilter that recursively checks for base class documentation. Basically just modeled it after https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Swagger/XmlComments/ApplyXmlActionComments.cs

Here's the code that gets the operation node:

'''csharp
private XPathNavigator GetOperationNode(XPathNavigator navigator, HttpActionDescriptor actionDescriptor, string optionalControllerName = null)
        {
            var controllerName = optionalControllerName ?? actionDescriptor.ControllerDescriptor.ControllerType.XmlLookupName();
            var operationNode = navigator.SelectSingleNode(XPathFor(actionDescriptor, controllerName));
            if (operationNode == null)
            {
                // If no operation node found using given controller name and action descriptor, let's check the base class to see if we can find it there 
                var controllerType = Type.GetType(controllerName);
                if (controllerType != null && controllerType.BaseType != null)
                {
                    controllerName = controllerType.BaseType.FullName;
                    var controllerNameSegments = controllerName.Split('.');
                    if (controllerNameSegments.Contains("ApiController"))
                    {
                        // We've reached the base class of all controllers without an operation node, nothing more to see here.
                        return null;
                    }

                    operationNode = GetOperationNode(navigator, actionDescriptor, controllerName);
                }
            }

            return operationNode;
        }
'''

**Comment by WarrenFerrell** [comment]
@patrickjrs any chance you could post your full workaround? Have a use case but not the time to implement it myself.

**Comment by ckarcz** [comment]
@domaindrivendev I think this library should handle the inherited documentation, which is the *actual* expected result; as all .net IDEs work this way as well and it's just more natural. It seems it's not difficult to resolve the base type docs using @patrickjrs 's method. It just would need to be done for all operations and types.

**Comment by thrixton** [comment]
A long time later but if you apply the  ///<inheritdoc/> tag to the class then the base class comments show up.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc

e.g.
```csharp
public class BaseClass
{
  /// <summary>
  /// The fu prop
  /// </summary>
  public int Fu { get; set; }
}

/// <summary>
/// A child class
/// </summary>
///<inheritdoc/>
public class ChildClass{}
