### ISSUE TITLE
Swashbuckle 4.1 - Authorizations not appearing in SwaggerApi

### ISSUE THREAD

**Issue by chrischapman-peon** [domaindrivendev/Swashbuckle#360]
Hi,

In our SwaggerConfig, we have set Basic Authorization using.
c.Authorization("basic", new Authorization { Type = "basicAuth", PassAs = "header" });

When I set a break-point and look at the swaggerApi object passed into the onComplete function for SwaggerUI, I see that authSchemes, authorizationScheme and authorizations are null or undefined.

... works as expected for 5.0, with authSchemes being populated.

**Comment by chrischapman-peon** [comment]
More information ... appears to only be affecting services with multiple APIs. If I have a services with only a single API then the objects are being populated correctly.

**Comment by chrischapman-peon** [comment]
Confirming in the morning if it also happens with later versions of Swashbuckle

**Comment by domaindrivendev** [comment]
Did you get to the bottom of this?

**Comment by domaindrivendev** [comment]
Closing for now due to inactivity, please re-open if you're still experiencing this issue
