### ISSUE TITLE
Allow collapse / hiding  of response models and move below the request

### ISSUE THREAD

**Issue by Hilleque** [domaindrivendev/Swashbuckle#362]
Usability Request.

In the swagger UI for a controller, each operation contains 3 sub-headers; Implementation Details, Response Class, Parameters. I think the logical order is to show the response after parameters (and the Try It button). Also, response schemas can get quite long, which makes for a lot of scrolling. Can the display of models and model schema be collapsed or hidden by default?

**Comment by monobjorn** [comment]
I think this issue belongs in the Swagger UI repo: https://github.com/swagger-api/swagger-ui  
(Swashbuckle creates the Swagger definition that is used by Swagger UI. It does not alter the looks of the UI.)

**Comment by domaindrivendev** [comment]
Agreed - this issue belongs in the swagger-ui repo.
