### ISSUE TITLE
How to document parameter type "form" ?

### ISSUE THREAD

**Issue by christopheblin** [domaindrivendev/Swashbuckle#367]
Similar to #120, but for Swagger 2.0 and Swashbuckle 5

At the moment, I have the following which is not bad but incomplete 
  I do not manage to tell swashbuckle that I can repeat this parameter for a multi form upload
  I do not manage to have the Parameter Type and Data Type filled in swagger-ui

    public class AddFileParamTypes : IOperationFilter
    {
        private readonly string operationNickname;

        public AddFileParamTypes(string operationNickname)
        {
            this.operationNickname = operationNickname;
        }

        public void Apply(Operation operation, SchemaRegistry dataTypeRegistry, ApiDescription apiDescription)
        {
            if (operation.operationId == operationNickname)
            {
                operation.consumes.Add("multipart/form-data");
                if (operation.parameters == null)
                {
                    operation.parameters = new List<Parameter>();
                }
                operation.parameters.Add(new Parameter
                {
                    name = "file",
                    required = true,
                    type = "file"
                }
                );
            }
        }
    }

**Comment by Snelbinder** [comment]
Use the following:
```
new Parameter
{
    name = "file",
    required = true,
    @in = "formData",
    type = "file",
}
```
This worked for me.

**Comment by domaindrivendev** [comment]
@Snelbinder's solution should work

**Comment by christopheblin** [comment]
Sorry, this does not work to repeat this parameter for a multi form upload.

I.E I am able to upload only one file, and I would like to upload 2 files (my controller checks that 2 files are present)

Is that possible ?
