### ISSUE TITLE
Replace swagger-ui with completely custom verzion

### ISSUE THREAD

**Issue by brazilianldsjaguar** [domaindrivendev/Swashbuckle#373]
Not sure how the inner-workings are adaptable here, but is there a way to inject or otherwise replace the **entire implementation of swagger-ui**?

The only reason I ask, is I'd like to take advantage of some modifications done on other swagger-ui forks, such as https://github.com/jensoleg/swagger-ui for making swagger-ui responsive w/ twitter bootstrap.

This might already be possible with a combination of style injection, script injection, and index.html injection, and if so I'm open to enlightenment.

**Comment by domaindrivendev** [comment]
I would recommend disabling the embedded swagger-ui in Swashbuckle by removing the following call:

    config.EnableSwaggerUi();

Once this is done, SB will just provide an endpoint for accessing the Swagger JSON document.

Then you can just pull down the latest swagger-ui assets (via bower or directly from repo) and just serve them from your website as static assets. In the index.html, just update the discoveryUrl to be that  provided by Swashbuckle

**Comment by brazilianldsjaguar** [comment]
Okay, I knew I could omit the `config.EnableSwaggerUi();` function call, but I didn't quite understand that, having done that, how any other swagger would reference the Swagger schema that Swashbuckle created.

What I've come to understand is, it's created that document accessible via a URL, not a physical file somewhere on the web server (e.g. I was browsing file explorer looking for some type of *.json file). Having figured out that I can reach the Swagger schema by using this url:

    http://localhost:61344/swagger/docs/v1

I understand now how I can "de-couple" the Swashbuckle-swagger-ui and a static-swagger-ui.

Thanks for the clarification!
