### ISSUE TITLE
Route shortcut also for custom route template

### ISSUE THREAD

**Issue by hbbq** [domaindrivendev/Swashbuckle#374]
In Swashbuckle.Core/Application/HttpConfigurationExtensions.cs the method EnableSwaggerUi registers a redirect for route "swagger" to "swagger/ui/index".
This redirect is not created when using a custom value for routeTemplate,

It would be nice if this shortcut was also created for custom routeTemplate; so if I have "documentation/ui/(*assetPath)" a shortcut is created for "documentation" that redirects to "documentation/ui/index"

**Comment by domaindrivendev** [comment]
Closing as this is a dup of #299
