### ISSUE TITLE
Primitive response type not rendered correctly

### ISSUE THREAD

**Issue by rehoutm** [domaindrivendev/Swashbuckle#379]
With following action method markup:

        /// <summary>
        /// Creates new queue with given name
        /// </summary>
        /// <param name="queueName"></param>
        /// <returns>Created queue id</returns>
        [HttpPost]
        [ResponseType(typeof(int))]
        public IHttpActionResult Post(string queueName)
        {
            throw new NotImplementedException();
        }

The rendered response is "Response Class (Status 200)" which is wrong. Using version 5.2.1

**Comment by rehoutm** [comment]
Generated schema is:

            "responses":{
               "200":{
                  "description":"OK",
                  "schema":{
                     "format":"int32",
                     "type":"integer"
                  }
               }
            },

**Comment by domaindrivendev** [comment]
Why is this wrong, what are you expecting?

**Comment by rehoutm** [comment]
I expected it to show the int32 return type, which it does not. This behaviour is intended?

**Comment by domaindrivendev** [comment]
type = integer, format = int32

Still don't understand your issue. Please provide an example of what you think the swagger Json should loll like?

**Comment by rehoutm** [comment]
The swagger json is just okay, but the displayed value is not. :(

As you can see here - http://ctrlv.cz/mA5A it shows model as class, that is empty, without description or type...

**Comment by domaindrivendev** [comment]
OK - that clarifies things a little bit ...

The issue you're seeing appears to be a bug in the swagger-ui:
https://github.com/swagger-api/swagger-ui/issues/1186

As soon as a fix is released, I'll update the version of swagger-ui that comes bundled with SB.

It's worth noting that the core logic behind Swashbuckle is primarily concerned with auto-generating Swagger JSON. It does come bundled with an embedded version of swagger-ui that consumes the generated Swagger but, of itself, doesn't really include any UI related code.

As a rule of thumb (and I should really make this more clear in the docs) - if the generated Swagger looks correct, then it's more than likely an issue in the swagger-ui as opposed to SB.

**Comment by ben3005** [comment]
bump as the original swagger-ui issue has now been closed

**Comment by domaindrivendev** [comment]
I believe this is resolved in v5.4.0
