### ISSUE TITLE
Question: How to support multiple endpoints

### ISSUE THREAD

**Issue by mbukosky** [domaindrivendev/Swashbuckle#381]
Hi,

I was wondering if Swashbuckle supported pulling in multiple endpoints together into a single page. I can't seem to find any solid examples or documentation from searching the tubes. 

Ideally, I will love to have a single index page that groups by the individual endpoints. Here is an example api I [found](http://swagger.eyefi.com).

![capture](https://cloud.githubusercontent.com/assets/6832123/8067452/d1df3afe-0ebb-11e5-9f7c-c5a3f6f8506f.PNG)

How would you go about having multiple VS solutions with their own APIs joined together into a single API? From reading over the Swagger-UI [forms](https://github.com/swagger-api/swagger-ui/issues/1060), it seems that it can handle multiple SwaggerUi objects but I am not sure how to use that with Swashbuckle.

Any ideas or suggestions?

Thanks for all the help

**Comment by dcolliervb23** [comment]
+1

**Comment by tynor88** [comment]
This was supported in swagger-spec 1.2, but unfortunately it does not work with swagger-spec 2.0. One of the maintainers of swagger-spec said it would be supported in a "different way". I hope to see this feature soon as well. See this issue for a reference https://github.com/swagger-api/swagger-spec/issues/275

For now we fixed this, by merging the swagger docs from different API's, to a single spec manually with some javascript.

**Comment by mbukosky** [comment]
Thanks for the feedback. That is what I was expecting. I was able to hack together a solution by throwing the swagger-ui into an angular SPA. I use ui-routing to swap in and out the state for each API. Nothing too hard, but it would be nice if it was built in.

**Comment by domaindrivendev** [comment]
The core responsibility of SB is to enable a self-descriptive API, building on top of the Swagger ecosystem.

Rather than self-description, you're asking for something that orchestrates the descriptions of multiple, separately deployed services. I don't

**Comment by domaindrivendev** [comment]
Continued ... I don't think SB is the place for this.

For such a scenario, I would recommend hosting the swagger-ui separately and then customizing it to combine the Swagger JSON docs emitted (via SB) from each of the separately deployed services
