### ISSUE TITLE
IEnumerable in query parameter is not working

### ISSUE THREAD

**Issue by christopheblin** [domaindrivendev/Swashbuckle#386]
If you have the following model
    
    public class MyCriteria {
        public List<String> Tags {get;set}
    }

Then the following Controller

    public List<Pet> FindPets([FromUri] MyCriteria c) {
        ...
    }

Then the generated swagger spec seems to be missing something since that is what I see in sawagger-ui :

![image](https://cloud.githubusercontent.com/assets/11044877/8077985/78fcf49a-0f5a-11e5-9645-9bdc9d26ac1a.png)

Whereas you can see this is working on swagger-ui demo (http://petstore.swagger.io/#!/pet/findPetsByTags)

![image](https://cloud.githubusercontent.com/assets/11044877/8077996/946b461e-0f5a-11e5-91b7-2a9f378837a9.png)

Also note that if I have a List of MyEnumType, it should generate a swagger spec that can render (http://petstore.swagger.io/#!/pet/findPetsByStatus)

![image](https://cloud.githubusercontent.com/assets/11044877/8078008/b72289ec-0f5a-11e5-80bb-70c0ff661f80.png)

I think this is a bug in how swashbuckle use the multiple parameter of swagger spec, but I am no specialist ...

Thanks for your help

**Comment by domaindrivendev** [comment]
You might just need to upgrade. There was an issue around this in a previous version of the swagger-ui but it was fixed and integrated back into SB. Just verified, both cases above work as expected in the latest version of SB - 5.2.1

**Comment by christopheblin** [comment]
i'll check that tomorrow but i think we've upgraded to SB 5.2.1 last week...

**Comment by christopheblin** [comment]
We have upgraded to 5.1.5 so I close this issue and I'll get back to you if the bug persist when we have  a chance to upgrade to 5.2.1
