### ISSUE TITLE
passing a nonce with the oauth2 request

### ISSUE THREAD

**Issue by RobRolls** [domaindrivendev/Swashbuckle#390]
Hi,

I need to pass a nonce with the oauth2 authenticate request when using the implicit flow.  Any thoughts on the best way to accomplish this?

**Comment by RobRolls** [comment]
For instance.  If the current request to authorize looks like this

`GET http://MySite/identity/connect/authorize?response_type=token&redirect_uri=http%3A%2F%2Flocalhost%3A7000%2Fswagger%2Fui%2Fo2c-html&realm=test-realm&client_id=MyClient&scope=read%20write%20profile%20openid&state=0.7868448935914785`

I need it to look like this

`GET http://MySite/identity/connect/authorize?response_type=token&redirect_uri=http%3A%2F%2Flocalhost%3A7000%2Fswagger%2Fui%2Fo2c-html&realm=test-realm&client_id=MyClient&scope=read%20write%20profile%20openid&state=0.7868448935914785&nonce=0.575656767832955`

**Comment by snothub** [comment]
Will this be handled any time soon? It would help a lot.

**Comment by domaindrivendev** [comment]
Going forward, I'm going to avoid further customization to the swagger-ui components that are bundled with Swashbuckle. The Swagger generation in itself is already a significant scope for this project.

This is really a feature request for the swagger/swagger-ui folks and should be posted with that repo and specifically against the 2.x version - https://github.com/swagger-api/swagger-ui/tree/2.x.

Two additional things worth noting ...
1. You might be able to workaround this issue today by injecting your custom version of swagger-oath.js via the __CustomAsset__ functionality provided with SB (see readme)
2. At some point in the future, I'd like to update this repo to support the new major versions of the Swagger spec and swagger-ui. But, this is likely some ways off.
