### ISSUE TITLE
Swashbuckle 4.0 how to filter out generating swagger spec for action methods with paths with a certain pattern

### ISSUE THREAD

**Issue by decoder318** [domaindrivendev/Swashbuckle#392]
Hi @domaindrivendev,

What do you suggest is the right way to filter out swagger-spec generation for certain action methods which have path in a particular pattern (like "~/internal/~")?

What I did for that is that in the injected javascript (onComplete.js), I look for those dom elements and remove them from dom.

It is slow and kind of takes about a minute to load entirely.. (also the injected script in onComplete.js gets executed atleast thrice for some reason)

Also, how can I configure swagger path to something different from "mysite/api/swagger "? 
like eg:- "mysite/api/apidoc"

Thanks,
VRPS.

**Comment by domaindrivendev** [comment]
For this, you should create a custom IDocumentFilter and wire it up as described in the readme.

The implementation can replace the "paths" property on the SwaggerDocument with a version that is filtered according to your requirements. Here's an example:

    public class FilterPathItems : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
        {
            swaggerDoc.paths = swaggerDoc.paths
                .Where(entry => entry.Key.StartsWith("/Products"))
                .ToDictionary(entry => entry.Key, entry => entry.Value);
        }
    }

Regarding a custom path for your swagger documentation, this is also explained in the readme - https://github.com/domaindrivendev/Swashbuckle/#custom-routes
