### ISSUE TITLE
Not clear if swashbuckle supports namespace versioning

### ISSUE THREAD

**Issue by joehoppe** [domaindrivendev/Swashbuckle#393]
My routes are defined as per [MSDN blogs' namespace routing]:(http://blogs.msdn.com/b/webdev/archive/2013/03/08/using-namespaces-to-version-web-apis.aspx):

    config.Routes.MapHttpRoute("DefaultApi", "api/{namespace}/{controller}/{id}", new { id = RouteParameter.Optional } );

When I go to /swagger/ui/index, I can see my endpoints, but they are not separated by version. And if I go to use the test form, namespace is a parameter. The parameter doesn't work... When I try it, it sends a request to /api/v1/v1.Test2, which obviously results in a 404.

When I enable API versioning, which is what I really want to do, Swagger UI no longer shows my endpoints. Instead, I only see a version at the top of the page.

    .EnableSwagger(c => c.MultipleApiVersions(
        ResolveVersionSupportByRouteConstraint,
        vc =>
        {
            vc.Version("v1", "v1 - Initial Release");
            vc.Version("v2", "v2 - Future release");
        }))

How do I get it to work with custom routes?

This is what I see in the browser: 
![temp](https://cloud.githubusercontent.com/assets/4017029/8114027/d3af120c-103f-11e5-9d08-b057271779e0.png)

There's a [stackoverflow question](http://stackoverflow.com/questions/26387353/using-swagger-with-a-namespaced-versionned-webapi) in which multiple people are interested.

I see a class AppendVersionToBasePath in the repository and a unit test It_handles_additional_route_parameters, but it's still not clear.

**Comment by domaindrivendev** [comment]
This is a dup of #317 and #303. You should read through both of them.

In summary, there is a flaw in the above implementation of "namespace routing" as it breaks the WebApi metadata layer - ApiExplorer and hence Swashbuckle
