### ISSUE TITLE
Default Values in a Body Parameter

### ISSUE THREAD

**Issue by allenpsuner** [domaindrivendev/Swashbuckle#397]
I have a request that takes a JSON body as a parameter. When I start up the service and pull up the UI, and look at the request, I notice that in the body some default values are imposed on the fields in the JSON body:

![screen shot 2015-06-15 at 12 23 24 pm](https://cloud.githubusercontent.com/assets/10819359/8168820/819a0670-135a-11e5-996a-a7435dc0cdb5.png)

I want to take advantage of being able to click that UI element and auto-populating the "payload" text field, but those default parameters make me wary of exposing this feature to the users. Is there a way to set those default values for the fields in the JSON payload? Or maybe could I pass in an instance of that class to an attribute of the controller, something like:

```
[SwaggerDefaultValue(payload, new ExamplePayload)]
public IHttpActionResult ExampleAction(string id, ExamplePayload payload)
{
...
}
```

Where I set the default value of the parameter by it's name with a value I pass in? I apologize if this issue has been raised already before, but I didn't see anything like it already.

**Comment by domaindrivendev** [comment]
Checkout #283 - it details a solution to this problem via per-schema filters. In summary, you would create a schema filter specific to the type in question, which assigns the "default" property accordingly, and then wire it up as follows:

    [SwaggerSchemaFilter(typeof(CustomerPayloadExamples))]
    public class CustomerPayload
    {
    ....

**Comment by domaindrivendev** [comment]
The thread in that issue is pretty long - start reading from here onwards: https://github.com/domaindrivendev/Swashbuckle/issues/283#issuecomment-101174333

**Comment by allenpsuner** [comment]
Thanks @domaindrivendev, you're prompt responses are always appreciated.
