### ISSUE TITLE
Inherited properties not included in ModelSpec

### ISSUE THREAD

**Issue by jtol84** [domaindrivendev/Swashbuckle#40]
A few months back, a change was made so that only declared properties are included in the ModelSpec.  Now several of my classes that inherit from a base class no longer show all their properties in the swagger description.
The change was in this commit: https://github.com/domaindrivendev/Swashbuckle/commit/a8e84cc9af7199c6a4deb77994fe87841d4a51b7

**Comment by gzinger** [comment]
I do see properties of the base class in Swashbuckle version 4.1, but XML comments for base properties are still missing. Could you tell us how to show those XML comments?

Thanks.

**Comment by Kestrel12** [comment]
I submitted a pull request #151 that fixes that, but it hasn't been merged in yet.

**Comment by gzinger** [comment]
That's great news! @Kestrel12, @domaindrivendev when do you think you could integrate this fix into a release?

Thanks.

**Comment by domaindrivendev** [comment]
Hey all - sorry about the delay in getting to this. I'm just in the process of merging into the swagger_2.0 branch (aka Swashbuckle 5.0).

swagger-ui is just about to release it's first stable version with Swagger 2.0 support. This means I can go ahead and release a stable version of Swashbuckle 5.0 (including the fix for this issue) shortly. I'm going to tentatively say give me a week, assuming the "bill paying" job doesn't get in the way to much :)

**Comment by domaindrivendev** [comment]
Swashbuckle 5.0.0 released! This issue should now be resolved. Please try it out when you get a chance.

**Comment by gzinger** [comment]
Yes, I confirm that it is showing up with the new version of SB

**Comment by mcianc** [comment]
still now availale?

**Comment by monobjorn** [comment]
@mcianc Inherited properties (including their XML comments) shows up for me in 5.1.5.  

XML comments for inherited operations does not seem to work. I'm opening a new issue for that (#359).

**Comment by dragonfly91** [comment]
Hi, 

The inherited properties from the base class are showing up for me. However, is it possible to retain the class hierarchy as it is? Can the base class be kept intact and the derived class inherit from the base using an allOf tag?

**Comment by lisamariet** [comment]
Is it possibel to view inheritance in the GUI of Swagger?
I have a parent class that has multiple childs that extend the parent. Then in the surronding model I used the Parent class. Like the [swagger specification examle](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#527-model-object). 

Then when asking for a Zoo with a list of animals.. the Zoo Model would be:

´´´c#
public class Zoo
{
    string Name;
    List<Animal> Animals;
}
´´´

And also the same when creating a New Zoo it could also pass in a list of all animals. Being either Cat, Dog or whatever. All derived from Animal.
