### ISSUE TITLE
Hiding Properties?

### ISSUE THREAD

**Issue by phillip-haydon** [domaindrivendev/Swashbuckle#402]
Is the only way to hide a property from Swagger to use the Obsolete attribute? 

If this is the case then a new attribute needs to be added to hide properties, marking properties as obsolete in order to hide them is massively retarded IMO. You're marking it as something its not for an entirely different intention.

**Comment by domaindrivendev** [comment]
Firstly, I think your choice of words above is offensive and suggest that you show a little more tact when posting to public forums.

Secondly, omitting obsolete actions/properties in an API from documentation, to discourage future use while still maintaining compatibility during a transition, is a common practice for API providers. This is why Swashbuckle provides the option to hide actions or properties marked with the Obsolete attribute. This is the only use-case for which this feature is intended.

In fact, I can't really think of any other good reason to expose a property in your API but still hide it in your documentation. Perhaps you could elaborate on your specific case a little more?

**Comment by phillip-haydon** [comment]
Because of the way webapi works its not easy to intercept a model and modify it while hiding it from the consumer. 


Using an explicit interface doesn't help because swagger includes it regardless. Obsolete marks it as deprecated when it's not. You can ignore a route but not a property. Which is against what you just said. Why would you hide a route if its not used. 


I stand by my statement that the use of obsolete is stupid. It's abuse of an attribute. If a property is to be marked as obsolete with a message, but not meant to be hidden from the api. It breaks the intent of the attribute. 


Don't get me wrong. The project is awesome and been a huge help. But I'm reading the docs for two trivial things. Hiding routes and properties. And both IMO are done wrong. 




Sent by Outlook for Android





On Sun, Jun 21, 2015 at 10:17 PM -0700, "domaindrivendev" <notifications@github.com> wrote:












Firstly, I think your choice of words above is offensive and suggest that you show a little more tact when posting to public forums.



Secondly, omitting obsolete actions/properties in an API from documentation, to discourage future use while still maintaining compatibility during a transition, is a common practice for API providers. This is why Swashbuckle provides the option to hide actions or properties marked with the Obsolete attribute. This is the only use-case for which this feature is intended.



In fact, I can't really think of any other good reason to expose a property in your API but still hide it in your documentation. Perhaps you could elaborate on your specific case a little more?

**Comment by domaindrivendev** [comment]
Just to clarify, Swashbuckle IS NOT saying:

"Use the Obsolete attribute when you wish to hide a property"

What it's saying is:

"If you have an obsolete property, you MAY choose to hide it from your docs by applying the IgnoreObsoleteProperties setting"

Do you see the difference?

Also, just be be clear on the intent of the Obsolete attribute in C# ...

https://msdn.microsoft.com/en-us/library/22kk2b44(v=vs.90).aspx)
"The Obsolete attribute marks a program entity as one that is no longer recommended for use"

That is, it can still be consumed but is no longer recommended for use. Don't you think it stands to reason that an API provider may want to completely omit such a property from the docs???

Finally, leaving the "Obsolete" discussion aside, I'd really like to understand what you're actually trying to do and why you have a property on your contract model that you don't want to document. A code sample might help ...

**Comment by phillip-haydon** [comment]
One example is, given a request for say, a list of accounts a user has access to:

```
public class AccountsController : ...
{
    ...

    [HttpGet, Route("accounts")
    public GetAccountsResult List(GetAccountsRequest request)
    {
        return queryHandler.Handle<GetAccountsRequest, GetAccountsResult>(request);
    }
}
```

We intercept the request object and bind the user data to it so the next layer has all the information:

```
public class GetAccountsRequest : IRequireUserContext
{
    public IUserContext UserContext {get;set;}
}
```

This data is not supplied by the client, its supplied by either the tokens or the cookies depending on the method of authentication. 

This is omitted from the SDK by having a different model. But Swashbuckle picks it up.

I tried making the class usage explicit:

`IUserContext IRequireUserContext.UserContext {get;set;}`

As well as making it internal. But it's still picked up. However, in both cases it's easily missed to not explicitly implement or make internal. 

Ideally we would want to mark it on the interface as `[SwashIgnore]` and it wouldn't get picked up. 

Hope that makes sense. We have other features we wish were in Swash/Swagger but I don't think they fit and are rather complicated for a single use case.

**Comment by domaindrivendev** [comment]
Just use accurate C# semantics in your code as follows ...

    public class GetAccountsRequest : IRequireUserContext
    {
        internal IUserContext UserContext {get;set;}
    }

I just tested this locally and confirmed that the property is ignored from the resulting Swagger. I don't want to introduce an additional attribute for an intent (internal setting as you described) that can already be expressed by a C# keyword

**Comment by phillip-haydon** [comment]
Hmmmm I tried the internal last week but it was still appearing. 

I'll try internal again and if it does indeed ignore it I'll close this. 

Thanks.

**Comment by phillip-haydon** [comment]
Ok @domaindrivendev, I re-tested the internal, not sure what I was doing wrong because it was coming through and then it just stopped. It must have not been updating the assembly so I guess it picked up the one before it was set to internal.

Sorry for the hassle. I still find it a little inconvenient because its something that now needs to be policed. 

Now to figure out how to strip off inherited types from showing when we do:

`public class GetAccountsRequest : SomeBaseRequest, IRequireUserContext`

Causes Swagger to display both request objects.

**Comment by domaindrivendev** [comment]
Just make the interface internal too - that way it won't be possible for anyone to expose it as a "public" property

**Comment by phillip-haydon** [comment]
It's a little bit more complicated than that.

I have a .NET SDK. This SDK use a request object like:

```
public class AccountsRequest
{
   public int Subsidary {get;set;}
}
```

In WebAPI we inherit this class to add additional stuff to it:

```
public class GetAccountsRequest : AccountsRequest, IRequireUserContext, IQueryRequest
{
   ....
}
```

This is so the SDK just gets a clean POCO and nothing more but the API has the stuff it needs, and we don't have to maintain to POCOs that are identical.

Making the AccountsRequest internal would prevent the SDK from being consumed. It can't be made abstract because its instantiated, but it causes an API endpoint in swagger to have 2 models. 

For now we have hidden all models from swagger so it only shows a single JSON representation, making the property internal so its not shown.

(complicated somewhat hacky stuff :cry: )

**Comment by kudoz83** [comment]
I recoginze this is long closed - not sure on the protocol for commenting in this case but came across this in google looking to solve an issuse...

public StatusCodes? StatusCode { get; internal set; }

The intention is that the status code be serialized and returned when people are performing GET operations... but not be included in the documentation as a property to submit for PUT and POST operations.   I'd prefer not to create an entirely new model for the PUT and POST operations just to suppress this property from the docs.  Might be a use case where Obsolete is not preferable but internal doesn't seem to behave as desired.

**Comment by g2petter** [comment]
@josh-sachs I came across this thread with this exact question, I.E. hiding the ID on POST but not on GET. Did you ever find a solution to it?

**Comment by heldersepu** [comment]
@g2petter 
See Issue #1098 you can hide whatever you want using a DocumentFilter

**Comment by josh-sachs** [comment]
@g2petter we tagged stuff obsolete with a comment that it wasn't really obsolete.   I haven't revisited this in some time to explore what better solutions may exist.  Sorry I can't be more help.

**Comment by Looooooka** [comment]
Sure we can hack up an attribute and remove properties at runtime by looping through that "superb"  event handler but let's be honest. It would be nice if this option was finally added.
Why would I need it you ask?
Because we have some properties that are not for everyone to use. They are used when the user is validated but we would like to hide them from the documentation so other people (literally 99% of our users) aren't bothered with them, ask about them or even go adding them to their client implementations. 
ApiExplorerSettings on properties would solve all this without this ridiculous discussion on how something should be coded, despite having no background to why things are the way they are.
Hell last time I checked people were paid to code and just expecting them to rewrite someone's entire project so that some properties aren't visible is to say the least...unrealistic.

**Comment by heldersepu** [comment]
@Looooooka What is your proposed solution?

You don't wanna code an attribute that removes stuff at run-time using a DocumentFilter...
Do you mind showing some sample  code on what you mean by:
> ApiExplorerSettings on properties would solve all this

**Comment by Looooooka** [comment]
On the core version it seems to be a class usage only property?

**Comment by heldersepu** [comment]
You are wrong @Looooooka 
> last time I checked people were paid to code 

Check again, most open source project don't have financial backing
