### ISSUE TITLE
OAuth2 Authorization Header not added to requests with form data parameters

### ISSUE THREAD

**Issue by nastassiar** [domaindrivendev/Swashbuckle#403]
Hi, 
I am using Swashbuckle.Core 5.2.1 and I am having issues with OAuth2 authentication with requests that have form data parameters. 

The only thing different about the requests that don't work is is they have form-data. They are API calls for uploading images, but I don't see why how this would cause them to lose their authorization headers. 

I am using an IOperationFilter to add the form-data parameters
It seems that adding the parameter is what is causing the issue:

                    operation.parameters.Add(new Parameter
                    {
                        name = "file",
                        required = true,
                        type = "file",
                        @in = "formData"
                    }
                    );

When I don't apply the filter the authorization header is sent, but obviously then there is no form-data.

Anyone else had a similar problem? Or am I adding the form-data parameter incorrectly?

**Comment by nastassiar** [comment]
Oh sorry this may be a duplicate of https://github.com/swagger-api/swagger-ui/issues/1249 has this been merged into Swashbuckle.Core yet?

**Comment by psibernetic** [comment]
Is this still pending a release?

**Comment by domaindrivendev** [comment]
See 5.3.1
