### ISSUE TITLE
Wrong generated controller name

### ISSUE THREAD

**Issue by mad93** [domaindrivendev/Swashbuckle#404]
I've a collection of controllers that doesn't have a direct inheritance of ApiController. It's like:

    public abstract class BaseController : ApiController
    public abstract class FirstController : BaseController
    public abstract class SecondController : BaseController

The controllers inherit from FirstController and SecondController and swashbuckle generates the urls like (in case of login):
`api/v1/loginControllerFist`
or
`api/v1/loginControllerSecond`
and should be
`api/v1/login`

If I directly inherit from ApiController this error doesn't happen. It's a bug or I'm doing something wrong. How I can solve this?

**Comment by domaindrivendev** [comment]
There has to be something else at play here - I can't see how the inheritance hierarchy can affect the path for the controller. Just tried it out locally with an empty project and controller structure you described and confirmed it works as expected.

I see you have a version in your path ... are you by chance using a custom HttpControllerSelector for this? There is a known issue with that approach to WebApi versioning because it breaks WebApi's metadata layer (ApiExplorer) and hence Swashbuckle

**Comment by domaindrivendev** [comment]
Can provide more details if this is the case

**Comment by mad93** [comment]
Yes, It's the case you expose. I created a custom HttpControllerSelector, and the names and urls displayed match the ones generated on the ControllerSelector.

I add the module name to each controller because each module can have controllers with the same name and then the ControllerSelector crashes complaining about repeated keys if not added the module name to the generated controller list.

I don't know if this can be solved with my current implementation.

**Comment by domaindrivendev** [comment]
Technically, I think you could work around this by creating an IDocumentFilter (sea readme) that modifies the SwaggerDocument (post initial generation) and converts the invalid paths:

    swaggerDoc.paths = swaggerDoc.paths.ToDictionary(
        entry => ConvertToCorrectPath(entry.Key),
        entry => entry.Value
    );

From what you've described, converting the invalid path to the correct "versioned" path should be a straight forward transformation.

Let me know how it goes

The alternative is to just use Attribute routing as it makes path-based versioning trivial and doesn't break Swashbuckle :)

**Comment by mad93** [comment]
IDocumentFilter worked perfectly, Thank you!
