### ISSUE TITLE
Question: Accepting OAuth "Authorization" header as "AuthToken" header

### ISSUE THREAD

**Issue by IAnonymousDev** [domaindrivendev/Swashbuckle#405]
I am using OAuth implicit flow and successfully accepting authorization bearer token on the server side. However, the library I am using  to authenticate the user expects auth header by the name of "AuthToken" instead of "Authorization". Is there a way for me to define that anywhere? Just a note that I am using Swashbuckle ver 5.2.1 and my application is not using OWIN middleware.

Thanks,

**Comment by domaindrivendev** [comment]
This is really a question for the folks who build swagger-ui (https://github.com/swagger-api/swagger-ui). As far as I know, it's not supported through configuration.

However, If you're happy to do a little monkey patching, you could get it working fairly quickly. You just need to inject you're own version of the swagger-oauth JavaScript, with the following line modified ...

https://github.com/domaindrivendev/Swashbuckle/blob/v5.2.1/Swashbuckle.Core/SwaggerUi/CustomAssets/swagger-oauth.js#L280

SB provides a config option to inject custom content - https://github.com/domaindrivendev/Swashbuckle#injecting-custom-content. Follow the instructions and you'll be able to apply this technique for your custom oauth solution:
