### ISSUE TITLE
If there is an ampersand sign in xml type comment (summary) the whole comment is not shown is swagger ui.

### ISSUE THREAD

**Issue by AndrewSav** [domaindrivendev/Swashbuckle#410]
Create an action that returns an object.
Put an xml comment with the summary tag on a property of the class if that object
Include the ampersand sign into the comment
Go to swagger ui and look at the documentation for the property
The comment won't be displayed

**Comment by davetransom** [comment]
I've used ampersands before with no issues.

Are you encoding the ampersand as `&amp;` so it makes valid xml?

**Comment by AndrewSav** [comment]
Oh right. Shows how often I use xml comments.
