### ISSUE TITLE
how to change host value

### ISSUE THREAD

**Issue by lakeba** [domaindrivendev/Swashbuckle#411]
the json doc return host: "mydomain:80", how can I have only "mydomain"?

**Comment by AndrewSav** [comment]
Does this help? https://github.com/domaindrivendev/Swashbuckle/issues/387

**Comment by lakeba** [comment]
no help

**Comment by domaindrivendev** [comment]
You can wire-up a simple IDocumentFilter (see readme) to modify the "host" property in the generated SwaggerDocument prior to serialization.
