### ISSUE TITLE
Replacing index.html with custom one

### ISSUE THREAD

**Issue by mad93** [domaindrivendev/Swashbuckle#413]
I've replaced index.html with a custom one, right now is just a copy of Swashbuckle index.html, with the configuration setting:

`c.CustomAsset("index", typeof(SwaggerConfig).Assembly, "Namespace.Classes.index.html");`

If I do so css, javascripts, etc are no longer reachable. It's the expected behaviour? I mean I must include all the assets myself with CustomAsset?

**Comment by domaindrivendev** [comment]
This isn't the expected behavior - you should only have to replace the one file. Can you provide any more details around the failed requests (you shoul be able to see these in your browser dev console). Are they returning 404, what is the response etc?

**Comment by mad93** [comment]
All the assets are returning an error 404.
![Console log](http://postimg.org/image/gyo1g5wo9/full/)

**Comment by mad93** [comment]
Forget it, my mistake. I just noticed that in the files all dots are replaced by "-". Changing this all worked as expected.

Thank you.
