### ISSUE TITLE
operationsSorter ?

### ISSUE THREAD

**Issue by lucasmaj** [domaindrivendev/Swashbuckle#416]
I would like to be able to change sort of actions within action groups. Right now actions are sorted by alpha which results in all verbs get/put/post/delete mixed up. I would like to be able to control that so that maybe gets are first then posts, puts, deletes. Doesn't swagger-ui already support it via operationsSorter? If so how do I get to this setting?

**Comment by domaindrivendev** [comment]
For the next major release of Swashbuckle (6.0.0 targeting AspNet 6), I'm going to remove the C# interface for customizing swagger-ui settings. Instead, the recommended approach for customizing the UI will be to provide your own version of index.html. There, you can customize the UI as described in the swagger-ui documentation - https://github.com/swagger-api/swagger-ui#swaggerui
.
So, with this being the approach going forward, I'm not going to add any additional settings to the current version. To resolve your issue right now, you can inject your own version of index.html as described here - https://github.com/domaindrivendev/Swashbuckle#provide-your-own-index-file.
