### ISSUE TITLE
How to make my own version of ObsoleteAttribute?

### ISSUE THREAD

**Issue by jslaybaugh** [domaindrivendev/Swashbuckle#419]
I've been customizing quite a bit of my swagger output using the flexibility that Swashbuckle offers, but for this one thing, I'm at a loss.  My API takes a header where you specify a version. That version is in the format of a date (yyyy-mm-dd). I've got Swashbuckle configured to output routes based upon an attribute I have where I can set an "before" and/or "after" date that that route is supported. That way, when exploring the API via swagger, it only returns methods that match the date provided in that header.

So, with all that said, I want to do something similar with an attribute on the properties in my classes. For instance, if I decide to add a new property and make an old property obsolete on 2015-09-01, I'd like to decorate the old property with something like `[ObsoleteAfter("2015-09-01")]` and decorate the new property with something like `[ObsoleteBefore("2015-09-01")]`. That way if you are passing in a version like 2015-05-20, you'll see the old property but won't see the new property. And the opposite would be true for those consuming the API after 2015-09-01.

The problem is that ObsoleteAttribute is a sealed class, so I can't just subclass it and add my own functionality that way.

And within Swashbuckle, I assume this would be done with a DocumentFilter, but I can't find any similar examples with a DocumentFilter, and I'm unable to determine how to properly use the properties on `IDocumentFilter.Apply(swaggerDoc, schemaRegistry, apiExplorer)` to do what I want to do. 

I also tracked down the code where you utilize `.IgnoreObsoleteProperties()` and it looks like you're basically just telling JSON.net to not serialize anything marked with `[Obsolete]`. So, alternatively, If I could hook in there somehow and just prevent the output like you're doing, that would be cool too.

Can you point me in the right direction or tell me if this is even going to be possible?

**Comment by domaindrivendev** [comment]
Ideally this could be done via a Schema filter. However, version information is not currently available to Operation or Schema filters. This will be added in the next major release - although that's targeted to AspNet 6 so that might be a little too much upgrading to take on just to get this working.

In the meantime, you can accomplish this with a combination of a Schema filter and a Document filter (which does have knowledge of the current API version). The Schema filter will inspect properties and add a Swagger "vendor extension" to capture the value from the ObsoleteAfter attribute, if applicable. Then, the Document filter can iterate all Schema properties and filter them by comparing the document version and the above vendor extension. Here's some sample code to get you started ...

The Schema filter:

    public class ApplySchemaVendorExtensions : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
        {
            foreach (var schemaProperty in schema.properties)
            {
                var typeProperty = type.GetProperty(schemaProperty.Key);
                if (typeProperty == null) continue;

                var customAttributes = typeProperty.GetCustomAttributes(false);

                AddObsoleteAfterMetadata(schemaProperty.Value, customAttributes);
            }
        }

        private void AddObsoleteAfterMetadata(Schema schemaProperty, object[] customAttributes)
        {
            var obsoleteAfter = customAttributes.OfType<ObsoleteAfterAttribute>().FirstOrDefault();
            if (obsoleteAfter == null) return;

            schemaProperty.vendorExtensions.Add("x-obsolete-after", obsoleteAfter.Date);
        }
    } 

The Document filter

    public class FilterPropertiesByObsoleteAfter : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
        {
            foreach (var schema in swaggerDoc.definitions.Values)
            {
                schema.properties = FilterByVersion(schema.properties, swaggerDoc.info.version);
            }
        }

        private IDictionary<string, Schema> FilterByVersion(IDictionary<string, Schema> properties, string version)
        {
            return properties
                .Where(entry =>
                    !entry.Value.vendorExtensions.ContainsKey("x-obsolete-after") ||
                    version.CompareTo(entry.Value.vendorExtensions["x-obsolete-after"]) < 1   
                )
                .ToDictionary(entry => entry.Key, entry => entry.Value);
        }
    }

**Comment by jslaybaugh** [comment]
Sorry, been tied up with other things, but thanks!! I tried it and it works! That's pure magic!

**Comment by jslaybaugh** [comment]
Is there any way to do this with query string parameters on GETs? Something like `Get(string bar, string foo, [ObsoleteAfter("2015-01-01")]bool old = true)`

I tried that but it doesn't seem to be anywhere in the schema...
