### ISSUE TITLE
More control over whether a parameter is marked as required

### ISSUE THREAD

**Issue by Beagle97** [domaindrivendev/Swashbuckle#421]
First off, thanks for a great project. Love Swashbuckle.

We decided for our api, to treat bad or missing query parameters as http 400, bad request. We want to say that we found the resource, it's just some of your parameters are wrong or missing and we cannot service it. We want to handle this in our api to make the error response as user friendly as we can.

To allow the routing to find our method, we are experimenting with giving the required parameters a default value of null. Otherwise we are finding that the response is inconsistent. Sometimes the framework returns a 404 because it cannot matchup parameters from the request to the action signature.

However this has the consequence of creating swagger docs with optional parameters when they are in fact required.

To address this we added a hook to Swashbuckle to add the flexibility of allowing the ApplyXmlActionComments class to call out to a parameter filter for further processing. So we can have an xml comment in our controller such as this.

/// <param name="fromLastModifiedDate" required="true">The earliest date a patient was modified</param>

Is this something that would be of interest to add to the Swashbuckle project?

It adds an interface similar to IOperationFilter. 

    public interface IParameterFilter
    {
        void Apply(XPathNavigator xmlNode, Parameter parameter, Operation operation, DataTypeRegistry dataTypeRegistry, ApiDescription apiDescription);
    }

It changes SwaggerSpecConfig to take an optional parameter filter

    public SwaggerSpecConfig IncludeXmlComments(string xmlCommentsPath, IParameterFilter parameterFilter = null)

ApplyXmlActionComments in Swashbuckle would optionally call out while it is processing xml params.

    if (_parameterFilter != null)
    {
        _parameterFilter.Apply(parameterNode, parameter, operation, dataTypeRegistry, apiDescription);
    }

Then in our api, we can simply add code for further control on how the parameters are handled. We could add anything to the xml comment for the param as an attribute in our controller, and affect the Swashbuckle.Swagger.Parameter accordingly.

    private const string RequiredExpression = "required";
    private const string TrueExpression = "true";
    public void Apply(XPathNavigator xmlNode, Parameter parameter, Operation operation, DataTypeRegistry dataTypeRegistry, ApiDescription apiDescription)
    {
        var requiredValue = xmlNode.GetAttribute(RequiredExpression, string.Empty);

        if (!string.IsNullOrEmpty(requiredValue))
        {
            parameter.Required = requiredValue.Equals(TrueExpression, StringComparison.OrdinalIgnoreCase);
        }
    }

Sorry for what seems to me a long post. It is my first attempt at finding out whether a contribution is wanted to an open source project.

Thanks.

**Comment by domaindrivendev** [comment]
Thanks for your comments and support, I'm glad you're finding Swashbuckle useful.

For the next major release of SB, I'm actually moving away from the use of Xml comments for anything other than "textual" metadata (e.g. summary, description etc.). For the more functional descriptors (e.g. response codes etc.), I'm introducing annotations (some of which are already available) that you can decorate your classes with to customize the generated Swagger.

For the problem you've described above, my recommendation would be a custom OperationFilter which detects the presence of some custom attribute on the action (or parameter) and updates the corresponding parameter descriptions accordingly. You could take a look at a similar approach I've used to support response codes via annotations:

https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Swagger/Annotations/ApplySwaggerResponseAttributes.cs

Cheers
