### ISSUE TITLE
Document Authorize Attribute

### ISSUE THREAD

**Issue by mbeckenbach** [domaindrivendev/Swashbuckle#422]
It would be great if the Authorize or AllowAnonymous attributes would be documented in a similar way as obsolete. (Use case: Auditing)

**Comment by domaindrivendev** [comment]
Swashbuckle is an implementation of the Swagger service description but does not actually define it. The specification (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) does support metadata for some standard security schemes (basic, api-key and oauth).

If you want to auto-populate this information into the Swagger that Swashbuckle generates based on the use of attributes like Authorize and AllowAnonymous, you will have to customize Swashbuckle. See here for more details - https://github.com/domaindrivendev/Swashbuckle#describing-securityauthorization-schemes

You can also see a sample of this in the dummy app ...

https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Dummy.Core/App_Start/SwaggerConfig.cs#L78

https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Dummy.Core/SwaggerExtensions/AssignOAuth2SecurityRequirements.cs
