### ISSUE TITLE
Grouping of resources based on namespace

### ISSUE THREAD

**Issue by nibras85** [domaindrivendev/Swashbuckle#424]
This is more of a question than an issue. 

I use attribute routing to separate my API resources into namespaces. 

ex: 
    /namespace1/resource
    /namespace2/resource

My controllers live in the same folder structure as above. 

When viewing this through the Swagger UI, what's the easiest way to have a top level grouping of resources based on these namespaces and then under each one, a list of all resources (controllers) underneath it?

**Comment by domaindrivendev** [comment]
Take a look at the __GroupActionsBy__ config option (see readme). It accepts a lambda where you can inspect the ApiDescription and obtain the controller namespace

**Comment by nibras85** [comment]
Thanks. But wouldn't that provide 1 level of grouping? I was thinking something like this:

> namespace1
>> resource1
>>> endpoint
>>> endpoint


> namespace2
>> resource1
>>> endpoint
>>> endpoint


Basically, you have namespaces at the top and under each one, their resources(controllers), and under each resource, their endpoints with verbs.

**Comment by domaindrivendev** [comment]
Nested grouping isn't possible with the current swagger-spec/swagger-ui. Swashbuckle say to-generates a Swagger-based description and then integrate

**Comment by domaindrivendev** [comment]
Sorry ... meant to say that SB is built on top of Swagger and if Swagger doesn't support it then SB can't either.

Your best bet would be to ask the question at the swagge-you repo
