### ISSUE TITLE
Add Business Rules

### ISSUE THREAD

**Issue by kuttiram** [domaindrivendev/Swashbuckle#428]
swashbuckle documentation very help to how all the information but here I want to show some business rules. can you please help how can able to show business rules. business rules like paragraph or link file.

If there is any option available kindly guide me to develop it

**Comment by MerickOWA** [comment]
Look at IOperationFilter and IDocumentFilter, IOperationFilter, and ISchemaFilter.  You should be able to customize the documentation to add anything you need.

**Comment by kuttiram** [comment]
Thank you for you valuable feedback. I now this technique will be available in swashbuckle. but I want to know how to implement this can you pls guide me regarding that.

I was developed web api in dot net so I want to implement in dot net application can pls guide me
