### ISSUE TITLE
No documentation for methods with custom http verbs

### ISSUE THREAD

**Issue by UserName312** [domaindrivendev/Swashbuckle#429]
Hello,

thank you very much for this great package. Unfortunately, I have the following little problem: Some of my methods use custom HTTP verbs instead of the standard ones, for example:

    [Route("api/mymethod")]
    [AcceptVerbs("MYVERB")]
    public string MyMethod()
    {
      return "Hello";
    }

In the generated swagger.json, the corresponding path appears, but no further information:

    {
    ...
    "paths": {
        "/api/mymethod": { }
        }
    }

Accordingly, the method also does not appear in the Swagger.UI, cannot be interactively explored etc.
Is there any workaround to adding methods like this?
Thank you very much in advance for any help!

**Comment by domaindrivendev** [comment]
I think this issue would be better addressed in the swagger-specific repos:

https://github.com/swagger-api/swagger-spec
https://github.com/swagger-api/swagger-ui

First and foremost, SB is a Swagger generator. That is, it generates a Swagger document, complying with the spec referenced above, by inspecting your API implementation. It also bundles in the swagger-ui tool, which renders a UI driven off the Swagger document.

While the spec doesn't mention custom verbs, it does allow for vendor-specific extensions ("x-" prefixed properties) on the PathItem object and so SB could describe custom verbs as follows:

    {
        ...
        "paths": {
            "/api/mymethod": {
                "x-MYVERB": {
                }
            }
        }
    }

However, vendor extensions are only useful to consumers who understand them, out of the box , the swagger-ui will not.

So, I think you're use-case is pushing the limits on Swagger and it's associated tool-chain. If you really wanted to pursue this further, you could potentially introduce a DocumentFilter (see readme) which enhances the generated document by adding the above extension for relevant operations. Then, you could customize the UI (see readme) to honor this extension. This is all theoretical and I'm sure it wouldn't be trivial but I think it would be possible if you're willing to invest the time.
