### ISSUE TITLE
Swagger not showing all routes

### ISSUE THREAD

**Issue by johanhaest** [domaindrivendev/Swashbuckle#431]
Hi,

We're using swashbuckle to generate our API and it's awesome!
The only problem we're facing is that not every controller shows in the API. For example we see subscriptions, but we don't see the cvsWithSubscription and the educations controller.

Here is a sample from our config:

    config.Routes.MapHttpRoute(
        name: "subscriptions",
        routeTemplate: "sollicitation/subscriptions/{personId}",
        defaults: new { controller = "subscriptions", personId = RouteParameter.Optional }
    );

    config.Routes.MapHttpRoute(
        name: "cvsWithSubscription",
        routeTemplate: "sollicitation/subscriptions/{personId}/cvs/{cvId}",
        defaults: new { controller = "cvsWithSubscription", cvId = RouteParameter.Optional }
    );

    config.Routes.MapHttpRoute(
        name: "educations",
        routeTemplate: "sollicitation/subscriptions/{personId}/educations",
        defaults: new { controller = "educations" }
    );

I tried looking but haven't found any solutions yet so I thought i'd post here.

**Comment by MerickOWA** [comment]
Do all your methods in your CvsWithSubscriptionsController take a personId & cvId parameter?

Do all your methods in EducationsController take a personId parameter?

One bug I've run into is that ApiExplorer won't return/expose a method if it can't match all the route parameters.

**Comment by johanhaest** [comment]
Not as method parameters

        [HttpPost]
        public HttpResponseMessage Add([FromBody] LanguageSkills languages)
        {
            try
            {
                var personId = Convert.ToDecimal(Request.GetRouteData().Values["personId"]);

And when I changed it to be 

       [HttpPost]
       public HttpResponseMessage Add(decimal personId, [FromBody] LanguageSkills languages)

It showed up! Thanks a lot!
