### ISSUE TITLE
Routle parameter

### ISSUE THREAD

**Issue by diegodfsd** [domaindrivendev/Swashbuckle#434]
Hi,

I'm using Swashbuckle successfully in my APIs, but in the cases where I need define a route like this below
```
[Route("{state:regex(actives|inactives|all)=all}")]
```
Swashbuckle tries send the parameter in the querystring and not like a part of the route.

This is how it sends:
http://localhost/api/groups/{State}?state=all

But the correct is:
http://localhost/api/groups/all

Someone knows how to fix it?

**Comment by diegodfsd** [comment]
I solve my problem using an OperationFilter, but the real problem is that the Swashbuckle can't understands when some parts of route are properties of a complex object I need use an operation filter to change the param in. I think that Swashbuckle could do this for us.

**Comment by domaindrivendev** [comment]
Hi there

I'm unable to repro this issue. I created the following controller ...

    [RoutePrefix("api/groups")]
    public class GroupsController : ApiController
    {
        [Route("{state:regex(actives|inactives|all)=all}")] 
        public IHttpActionResult GetGroups(string state)
        {
            throw new NotImplementedException();
        }
    }

I'm seeing "state" listed as a path parameter and when I try out the operation, it correctly adds it to the path:

http://localhost/api/groups/all

**Comment by diegodfsd** [comment]
The main difference between your code and my code it's that I'm using a complex object as a parameter in my action as I described in my last comment.

```
[Route("{state:regex(all|open|closed)=all}")]
[ResponseType(typeof(ResourceSet<GroupResource>))]
public IHttpActionResult Get([FromUri] QueryGroup course)
{
        // do something
}
```

**Comment by domaindrivendev** [comment]
Actually, the route binding you've setup above is ambiguous, even to WebApi

Swashbuckle aside, the following 3 path's will all be routed to your action method and with course.State = "closed". So, WebApi doesn't quite know what route you're trying to create and hence neither does Swashbuckle.

/api/groups?state=closed
/api/groups/all/?state=closed
/api/groups/closed

So, you can document your API one way but the truth is ... with the above implementation it WILL accept "state" as a path OR query parameter and furthermore, the query param value will win

**Comment by diegodfsd** [comment]
@domaindrivendev I'm sorry, but you may be wrong about Web API, because Route attribute require that route parts specified in route template are in url as a path parameter and not as a querystring parameter, but the Swashbuckle when we use a complex object as parameter in our action it treat the route parameter like querystring and when it tries to call the uri my api don't know how to respond for this request.

Here we have an example to confirm what I said above.

```
[RoutePrefix("api/values")]
    public class ValuesController : ApiController
    {
        // GET api/values
        [Route("{state:regex(all|open|closed)}")]
        public IEnumerable<string> Get([FromUri] Query query)
        {
            return new string[] { "value1", "value2" };
        }
    }

    public class Query
    {
        public string State { get; set; }
    }
```

**Comment by domaindrivendev** [comment]
Actually, that's not my point at all. It's your use of FromUri that's introducing the ambiguity not the Route attribute. I'll try break it down to make it a little clearer ...

The following line tells WebApi that there is a "state" param that MUST come from the path - agreed!

    [Route("{state:regex(all|open|closed)}")]

However, the use of FromUri tells WebApi that properties of Query MAY come from path OR query-string parameters

    [FromUri] Query query

Hence, the following two paths are valid to invoke your action.

api/values/all
api/values/open?state=closed

Furthermore, if the second variation is used, the query-string value will overwrite the path value. Please .. put a breakpoint in your controller and inspect the values in your Query object for each case.

**Comment by diegodfsd** [comment]
@domaindrivendev Well, I need use a complex object instead of specify each parameter and how I need use a complex object for avoid an complex action definition I need use too [FromUri] attribute besides I'm use regex on route attribute because I think this is the best and fast way to restrict the users to use a invalid route parameter.

Do you yet think that this is not a problem in Swashbuckle? As I said before, I solved the problem removing the duplicated parameters and changing the "in" property to "path" when it should be "path" but it is "query".

**Comment by domaindrivendev** [comment]
I'm afraid I don't see this as a SB issue. Swashbuckle provides "living" documentation for your WebApi. That is, the descriptions it provides are bound to the "actual" behavior. As I've demonstrated with the examples above, the "actual" behavior you will observe from your code is two possible parameters of the same name, one in the path and the other in the query-string, with the query value taking precedence if both are provided.

If SB were to only document the path option then it's not doing its duty, working off an assumption rather than actual behavior.

If you don't see this point then let's agree to disagree. In any case, it sounds like you can achieve what you're trying to do with a simple op filter.

**Comment by diegodfsd** [comment]
Well, then wait for others issues to confirm if this is a SB problem.
