### ISSUE TITLE
Swashbuckle not working with WCF

### ISSUE THREAD

**Issue by cpp-made-easy** [domaindrivendev/Swashbuckle#437]
Do you have plans to integrate Swashbuckle with WCF?
Where and how would I start, if I wanted to contribute?

**Comment by domaindrivendev** [comment]
Hey there. Thanks for the interest but I have no plans to support WCF. SB is intrinsically coupled to WebApi and its abstractions. I would see little potential for code reuse in a WCF stack and so would suggest a completely separate project if this is something you're looking to build.

Thanks
