### ISSUE TITLE
Dictionary<Key, Value> in model schema

### ISSUE THREAD

**Issue by semone** [domaindrivendev/Swashbuckle#438]
I have some problems with my schemas. I have noticed that my dictionaries not are rendered as I would expect them to, or matybe they are and I just need an explanation on why! 
This is what i get in my swagger.json: 
```json
"Recipients": {
  "type": "object",
  "additionalProperties": {
      "type": "string"
}
```
And this is what it becomes in swagger UI
![swagger2 0uipng](https://cloud.githubusercontent.com/assets/2510433/8821433/e646331c-305d-11e5-9a93-f7e9e227934f.png)

How do I know which type the key and value should be?  

From my model: 
public Dictionary < string, string >  Recipients { get; set; }

**Comment by MerickOWA** [comment]
From the swagger specification
http://swagger.io/specification/

>**Model with Map/Dictionary Properties**
>
>For a simple string to string mapping:
```
{
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}
```

**Comment by semone** [comment]
@MerickOWA Thank you for pointing me in the right direction! 
I think you are correct it is a swagger ui/swagger js issue, additionalProperties seams to not be supported. 

I found this issue https://github.com/swagger-api/swagger-ui/issues/558
