### ISSUE TITLE
c# boolean parameter with [FromBody] attribute prevents ui from rendering

### ISSUE THREAD

**Issue by AndyGJ** [domaindrivendev/Swashbuckle#440]
I have an issue with a webapi project using Swashbuckle.Core 5.2.1  installed via nuget, A method with the signature (int idRequest, [FromBody]bool authorisation) causes the docs generation to fail. A part of the usual docs page is visible, but the message "Finished Loading Resource Information. Rendering Swagger UI..." continues to be displayed.

If the method signature is switched to an integer (or any other primitive type) the docs page loads fine. If [FromBody] is removed, the page also generates fine. The JSON generated for this method is as follows:

```json
    "\/api\/MyDetails\/PendingRequests\/{idRequest}": {
      "post": {
        "tags": [
          "Member"
        ],
        "operationId": "Member_ApproveRequest",
        "consumes": [
          "application\/json",
          "text\/json",
          "application\/xml",
          "text\/xml",
          "application\/x-www-form-urlencoded"
        ],
        "produces": [
          "application\/json",
          "text\/json",
          "application\/xml",
          "text\/xml"
        ],
        "parameters": [
          {
            "name": "idRequest",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "authorisation",
            "in": "body",
            "required": true,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#\/definitions\/Object"
            }
          }
        },
        "deprecated": false
      }
    },

**Comment by MerickOWA** [comment]
Check your browsers console.  I keep getting an error of "Cannot read property toLowerCase' when i use schema like yours.  I think this is actually a bug in swagger ui, not in Swashbuckler itself.

**Comment by AndyGJ** [comment]
Yup, nailed it, good spot. 

I'll re-raise this on the swagger-ui project page, cheers for the pointer.

**Comment by rbeauchamp-lendingtree** [comment]
Unfortunately this issue is still open in the swagger-ui project: https://github.com/swagger-api/swagger-ui/issues/1502

If anyone is still interested, a work-around is to create a wrapper class, for example:
```
public class AuthorisationWrapper
{
    public bool Authorisation { get; set; } 
}
```
and use the wrapper type in the API method:
```
(int idRequest, [FromBody]AuthorisationWrapper authorisation) 
```

Note that the wrapper does change the PATCH body from a simple `true` to a `{ "authorisation": true }`
