### ISSUE TITLE
Javascript not running from custom index.html

### ISSUE THREAD

**Issue by raaga123** [domaindrivendev/Swashbuckle#443]
Hi -

This is one of those issues that just HAS to be something stupid I'm overlooking....

I've just upgraded to Swashbuckle 5.0. I have been able to customize it to use the substitute .html index file I was using under 4.0, but none of the javascript seems to be running. The new configuration code is:

config.EnableSwagger(c =>
     {
          c.IncludeXmlComments(xmlCommentsPath);
          c.SingleApiVersion("v2", "My Own Special API");
      }).EnableSwaggerUi( c=>
      {
          Assembly exAssemb = Assembly.GetExecutingAssembly();
          c.CustomAsset("index", exAssemb, "MYLOCALPATH.loginTest.html");
          c.CustomAsset("chevrons_clear.png", exAssemb, "MYLOCALPATH.chevrons_clear.png");
           c.InjectStylesheet(exAssemb, "MYLOCALPATH.myStyleSheet.css");
           c.InjectJavaScript(exAssemb, "MYLOCALPATH.setupLogic.js");
      });

Of these, the index file, the image file, and the style sheet are all working, but the javascript doesn't execute. The .html and .js files are unchanged from the versions that were working under Swashbuckle 4.0.

Any idea what I might be missing here?

Thanks,
      Lyn

**Comment by martindavid** [comment]
Have you change the build type of that css and javascript to `embedded_resources`, and what is your index.html looks like? I prefer using `CustomAsset` than Inject to insert custom javascript.

**Comment by MerickOWA** [comment]
So Swashbuckler uses template parameters in the embedded resources to pass these settings along.

For example, the InjectStylesheet function adds to the %(StylesheetIncludes) template parameter a block of html for a link to the embeded stylesheet, which is referenced/used in the default index.html as follows

```html
<head>
  <title>Swagger UI</title>
  ...
  <link href='css/print-css' media='print' rel='stylesheet' type='text/css' />
  %(StylesheetIncludes)
  <script src='lib/jquery-1-8-0-min-js' type='text/javascript'></script>
```

For InjectJavaScript, this just adds adds the embedded resource url to %(CustomScripts) which is pipe separated.

For this to work in your custom index.html, you must have some JavaScript in your custom index.html to parse these URLs and do the appropriate action to load up these scripts.  For example, the default index.html does the following code.  Note, I've omitted many of the other lines of javascript code just to demonstrate how %(CustomScripts) is working.

```javascript
  <script type="text/javascript">
  $(function () {

      // Get Swashbuckle config into JavaScript
      function arrayFrom(configString) {
        return (configString !== "") ? configString.split('|') : [];
      }

      window.swashbuckleConfig = {
        customScripts: arrayFrom('%(CustomScripts)'),
      };

      window.swaggerUi = new SwaggerUi({
        onComplete: function (swaggerApi, swaggerUi) {
          _.each(swashbuckleConfig.customScripts, function (script) {
            $.getScript(script);
          });
        },
  });
  </script>
```

**Comment by raaga123** [comment]
Thanks for all the help! I ended up simply starting from the index file generated by the new version of Swagger, then re-inserting my javascript and other customizations into that. It's working now.

**Comment by MurtuzaTravadi** [comment]
how exactly do you do that customization add java script function
@raaga123
