### ISSUE TITLE
How do I integrate my custom authentication? 

### ISSUE THREAD

**Issue by makerofthings7** [domaindrivendev/Swashbuckle#448]
I'm using custom credentials to authenticate to my existing API.  That means I send an encrypted string from the client to the server in the HTTP header, or as a parameter string.

How should I surface this within swashbuckle? 

Any pointers or tips are appreciated

**Comment by domaindrivendev** [comment]
Take a look at this - http://stevemichelotti.com/customize-authentication-header-in-swaggerui-using-swashbuckle/
