### ISSUE TITLE
Using Xml Comments along with Operation Filters in the correct order

### ISSUE THREAD

**Issue by paul3291** [domaindrivendev/Swashbuckle#450]
I just came across this one today, we are using 'IncludeXmlComments' to pull in details from our code and then updating certain portions dynamically via Operation Filters.

In the sample config that is provided the 'IncludeXmlComments' call is after the add custom Operation Filters sample, which will basically over write any modifications that you may have made via your operation filters if the same info is in the xml comments.

Hope that makes sense. Just thought a change to the default ordering in the sample or a note about usage may be required. Or there may already be something there and I haven't seen it?

**Comment by domaindrivendev** [comment]
See v5.2.2
