### ISSUE TITLE
SwaggerDocument should support ref property on inline parameter definitions

### ISSUE THREAD

**Issue by naveedaz** [domaindrivendev/Swashbuckle#453]
Swashbuckle should be able to support operations with parameters that are just references instead of fully defined objects. 

"paths": {
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/certificates": {
      "get": {
        "tags": [
          "Certificates"
        ],
        "summary": “”,
        "operationId": “”,
        "consumes": [],
        "produces": [ … ],
        "parameters": [
          {
              "$ref": "#/parameters/subscriptionIdParameter"
          }
        ],
        "responses": {… },
        "deprecated": false
      }
    },
 },
"definitions": { … },

**Comment by domaindrivendev** [comment]
Available in v5.2.2
