### ISSUE TITLE
Revisiting #271: "HowTo Change Base url of swagger?"

### ISSUE THREAD

**Issue by raaga123** [domaindrivendev/Swashbuckle#455]
I am trying to follow the instructions in the Swashbuckle document for customizing the URL. The code compiles, but when I run it and try to go to my URL (localhost:9002/MyDocPath) I get the following:

     <Error>
     <Message>An error has occurred.</Message>
     <ExceptionMessage>Mapping not found - ui/index.html</ExceptionMessage>
     <ExceptionType>Swashbuckle.SwaggerUi.AssetNotFound</ExceptionType>
     <StackTrace>
     at Swashbuckle.SwaggerUi.EmbeddedAssetProvider.GetAsset(String rootUrl, String path) in        c:\{my directory}\Swashbuckle\Swashbuckle.Core\SwaggerUi\EmbeddedAssetProvider.cs:line 24 at Swashbuckle.Application.SwaggerUiHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in c:\{my directory} \Swashbuckle\Swashbuckle.Core\Application\SwaggerUiHandler.cs:line 28
     </StackTrace>
     </Error>

It looks like somebody else posted a comment to #271 after it was closed, indicating that he had had the same problem. Is there a step I'm missing?

**Comment by raaga123** [comment]
(I am using Swashbuckle 5.2.1)

**Comment by raaga123** [comment]
For anyone else who encounters this problem: I was able to make it work by changing EnableSwaggerUi("MyDocPath/{*assetPath}") in the Custom Routes instruction to EnableSwaggerUi("MyDocPath/ui/{*assetPath}").

**Comment by raaga123** [comment]
This worked for a little while, then IIS stopped picking up anything at all -- I was getting a blank web page in place of the doc. ???? 

I had to remove the route customization to fix this. Gah.

**Comment by raaga123** [comment]
OK, learned that I needed to explicitly route to "index".

**Comment by JJ-Q** [comment]
Hi raaga123,

Do you have a way to configure Swashbuckle that allow one to emit the 'index' at the very end, if configuring the endpoint as myPath/{*assetPath} ?

Thanks,
JJ

**Comment by raaga123** [comment]
Hi, JJ -

I am not aware of such a way. If there's enough demand, maybe one of the Swashbuckle developers will add this enhancement. If you find out anything more, please post -- the "index" workaround does the job for now, but it would be better not to need it.

Lyn

**Comment by TuckermanRav** [comment]
Hi raaga123,

Were you able to find a resolution allowing you to emit the 'index' at the end of the url?
