### ISSUE TITLE
Caching swagger resulting docs

### ISSUE THREAD

**Issue by tatarincev** [domaindrivendev/Swashbuckle#456]
Hi, very nice solution.
But we have one problem, we cannot find any way to caching resulting swagger docs  used in swagger ui. For our project ui generation takes more that 10 seconds  and not confortable for usage.
Nice solution for me it will be posibility to override **ISwaggerProvider** in configuration step, but currently it no possible, or maybe you have another most better suggestion.
Thanks.

**Comment by domaindrivendev** [comment]
Available in v5.2.2 via "CustomProvider" config option

**Comment by tatarincev** [comment]
Thank you very much!
Finally we can get rid of private Swashbuckle nuget package that contains improvement.

**Comment by patrickjrs** [comment]
Awesome, thank you @domaindrivendev !
