### ISSUE TITLE
Swashbuckle rename Data Type in Model

### ISSUE THREAD

**Issue by weretac0** [domaindrivendev/Swashbuckle#457]
I'm putting together a web API that needs to match an external sources XML format and was looking to rename the Data Type objects in the swagger output.

It's working fine on the members of the class but I was wondering if it was possible to override the class name as well.

Example:

    [DataContract(Name="OVERRIDECLASSNAME")]
    public class TestItem
    {
       [DataMember(Name="OVERRIDETHIS")]
       public string toOverride {get; set;}
    }

In the generated output I end up seeing Model:

    TestItem {
        OVERRIDETHIS (string, optional)
    }
I'd hope to see

    OVERRIDECLASSNAME 
    { 
        OVERRIDETHIS (string, optional) 
    }

Is this possible?

Thanks,

**Comment by domaindrivendev** [comment]
In the next milestone release - 5.2.2, it will be possible to provide a custom strategy for determining Schema Id's for complex Types. With this in place, you'll be easily able to wire up a strategy that inspects Types for the presence of the DataContract attribute.

    c.SchemaId(Func&lt;Type, string&gt; schemaIdStrategy)

**Comment by domaindrivendev** [comment]
See v5.2.2
