### ISSUE TITLE
Customize URL

### ISSUE THREAD

**Issue by RahulRParmar** [domaindrivendev/Swashbuckle#458]
Hi ,

I am trying to customize URL of Swagger using below code

httpConfiguration
    .EnableSwagger("docs/{apiVersion}/swagger", c => c.SingleApiVersion("v1", "A title for your API"))
    .EnableSwaggerUi("sandbox/{*assetPath}");

But it is not working.

I got error like Couldn't found map...

Can you guide us for the same. Actually I want to change URL like "/api/"

**Comment by davetransom** [comment]
You'll probably find that if you go to "http://.../sandbox/index" it displays fine.

The route for swgger-ui doesn't set a default value for `assetPath` - which means you need to specify `index` in the url.

I did the following to use index" as the default.

    config
      // .snip
      .EnableSwaggerUi("sandbox/{*assetPath}");

    config.Routes.First(x => x.RouteTemplate == "sandbox/{*assetPath}").Defaults["assetPath"] = "index";

Then to handle the url without a trailing slash i.e. "http://.../sandbox", added this to the `web.config`

    <system.webServer>
      <rewrite>
        <rules>
          <rule name="sandbox_ensure_trailing_slash">
            <match url="sandbox$" ignoreCase="true" />
            <action url="sandbox/" type="Redirect" appendQueryString="true" />
          </rule>
        </rules>
      </rewrite>
    </system.webServer>

**Comment by RahulRParmar** [comment]
Thanks Dave

**Comment by domaindrivendev** [comment]
Yep, as of now, when you use a custom route template you just get the canonical URL (i.e. including index) and so have to implement the redirect yourself. This will be improved in the next "major" version, targeted to AspNet 6.

There's been a few dup's of this issue, you can refer to the original here - #299

**Comment by RahulRParmar** [comment]
Hi Dave

We have used virtual directory concepts in our application.

Let's say If application path like http;//localhost and then application web-api helper page working fine. But if application URL http://localhost/abc then it creates problem and getting error while fetching API content.

Code ::
var url = "http://" + window.location.host + "docs/v1/CalibanAPI";
 window.swaggerUi = new SwaggerUi({
              url: url,
});

I am using html page for rendering web-api content. Could you please guide to getting the Application URL?

Waiting for your reply.
Thanks

**Comment by raaga123** [comment]
Using the full URL seems to work for me. I tried following Dave's suggestion:

> config.Routes.First(x => x.RouteTemplate == "MyPath/{*assetPath}").Defaults["assetPath"] = "index";

But I get "System.Web.Http.HttpRouteCollection does not contain a definition for 'First' and no extension method 'First' accepting a first argument of type 'System.Web.Http.HttpRouteCollection' could be found (are you missing a using directive or an assembly reference?)

What am I missing?

**Comment by davetransom** [comment]
@raaga123: sounds like you're missing the reference to LINQ. Do you have `using System.Linq;` at the top of your file?

**Comment by davetransom** [comment]
@RahulRParmar: 
Firstly, it looks like your URL is wrong as it'll be missing a trailing slash, at least in the example you've given (could be a typo).

`window.location.host` will just output the host name e.g. "github.com"

So your exmaple should be like this (note the "/docs")

    var url = "http://" + window.location.host + "/docs/v1/CalibanAPI";


I'm not sure if you've changed your route. Your first issue uses "docs/{apiVersion}/swagger" as the swagger route, but the next issue uses "docs/v1/CalibanAPI". This should be "docs/v1/swagger" if you haven't changed the route.
