### ISSUE TITLE
Dictionary<TKey,TValue> as response class property (version 5.2.1)

### ISSUE THREAD

**Issue by aareu** [domaindrivendev/Swashbuckle#459]
**Situation:**
API result class holds a simple generic dictionary property: 
*public Dictionary<string, int> MyDictionary { get; set; }*

Swashbuckle does not seem to be generating meta-json properly for this dictionary; the response's property on Swagger shows up like
**MyDictionary** (object, *optional*)

**Question:**
Is it a bug (from source I saw that only value type is somewhat interpreted by Swashbuckle) or is there a way, so that MyDictionary is defined properly (describing both: key and value types)?

**PS.** Only Dictionary has that kind of problem.

**Comment by domaindrivendev** [comment]
Closing as this is a dup of #318

In summary, SB generates the correct Swagger JSON to describe a Dictionary but the swagger-ui does not support this yet.
