### ISSUE TITLE
swagger-ui.js missing data-sw-translate

### ISSUE THREAD

**Issue by robschne** [domaindrivendev/Swashbuckle#464]
When I look at the file swagger-ui.js in the swagger repo it has the attribute data-sw-translate on the dom elements `<a class=\"snippet-link\" href=\"#\" data-sw-translate>Model Schema</a>` but the output from swashbuckle doesn't `<a class="snippet-link selected" href="#">Model Schema</a>`

i need the data-sw-translate attribute.

**Comment by domaindrivendev** [comment]
Available in v5.2.2
