### ISSUE TITLE
Swashbuckle assets need compression and minification

### ISSUE THREAD

**Issue by centur** [domaindrivendev/Swashbuckle#467]
Javascript and css assets, that are part of SwaggerUI need minification and compression (as in Swashbuckle.Core.5.2.1). 
E.g.

> GET /swagger/ui/swagger-ui-js   - 1.5Mb Unminified uncompressed

Downloading 1.5 Mb of javascript everytime when opening Swagger UI is not the best experience.
Also as it is extension-less asset - it not being cached properly by client browsers.

I tried to add GZip compression using Global filter in webapi pipeline, but seems that Swashbuckle somehow ignores global setup. 
It'd be nice to enable some way to configure filters for /swagger route so we can protect this UI it with basic auth, add compression and modify some behaviour if needed (main idea is to protect UI with auth and add compression to outputs)

**Comment by daward** [comment]
I too have this problem, it makes this version of swashbuckle nearly unusable and should be a pretty minor change to use minified version.

**Comment by centur** [comment]
I wrote a middleware that minifies everything what comes from /swagger url but it needs some extra work to function properly - somehow it messes up with api responses in SwaggerUI

**Comment by domaindrivendev** [comment]
@centur - I was going to suggest a DelegatingHandler (see http://www.asp.net/web-api/overview/advanced/http-message-handlers) for intercepting the swagger request and applying additional customization (authorization, compression etc.). Of course if you're using OWIN, you could achieve the same result with middleware.

@daward - For the next release, I'll update the swagger-ui index.html served up by SB to reference the minified version of swagger-ui.js. In the meantime though, you could achieve the same thing by injecting your own version (copied from https://github.com/domaindrivendev/Swashbuckle/blob/v5.2.1/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html) with the modified reference. See the readme for details - https://github.com/domaindrivendev/Swashbuckle#provide-your-own-index-file.

On a final note, I switched to extension-less URL's to avoid the need for setting runAllManagedModulesForAllRequests and hence the associated perf. concerns. I hadn't anticipated that browsers would not cache assets as a result and that's an unfortunate side effect.

It's worth noting that extensionless URL's will not be used in the next major version, targeting AspNet 6.0.

**Comment by centur** [comment]
Just in case anyone wants it now - here is [the simple gzip middleware](https://gist.github.com/centur/eee30685d2d52a5f2f20) that compresses js and css on the fly (OWIN based)

**Comment by domaindrivendev** [comment]
Using minified swagger-ui in v5.2.2 - now available
