### ISSUE TITLE
[FromUri] GET object with array parameter

### ISSUE THREAD

**Issue by svickers** [domaindrivendev/Swashbuckle#469]
When using an object with an array property with the [FromUri] attribute the swagger docs should specify collectionFormat: "multi".

    public class Search{
        public ICollection<int> id{get;set;}
    }

    public IHttpActionResult Search([FromUri]Search search){ 
    ...
    }

If it is missing, the requested url looks like this:

    ?search.id=1,2,3

But should be:

    ?search.id=1&search.id=2&search.id=3

Happy to submit a pull request with a fix.

**Comment by domaindrivendev** [comment]
Good catch - a PR would be awesome thx
