### ISSUE TITLE
Swagger UI: Change Parameter Input Type from TextBox to DropDownList

### ISSUE THREAD

**Issue by cletisgipson** [domaindrivendev/Swashbuckle#473]
How do we change the parameter input type from a textbox to a predefined list of available options?

**Comment by domaindrivendev** [comment]
Is your parameter defined as a string? It sounds like it could be defined as an enum instead. For example,

    [HttpGet]
    public IEnumerable<Product> GetAllByType(ProductType type)
    {
         ...
    }

    // By default, WebApi serializes enum's as integers. This tells it to use strings instead
    [JsonConverter(typeof(StringEnumConverter))
    public enum ProductType
    {
        Book = 2,
        Album = 4
    }

If you do this, SB will automatically display a drop-down.

**Comment by JobaDiniz** [comment]
I have a `CultureInfo` type parameter in my action, how can I show a dropdown in swagger with the only supported cultures?
