### ISSUE TITLE
How to hide default log in swagger UI

### ISSUE THREAD

**Issue by kuttiram** [domaindrivendev/Swashbuckle#476]
Is there a functional requirement for the header graphic logo and colors to be customized for the Brands or anything else or is swagger branding acceptable?

**Comment by kuttiram** [comment]
Is there any option to change swagger logo and header background color?

**Comment by kylepope** [comment]
Why not just use the InjectSytlesheet method to add your own CSS that can override the defaults? You can do this pretty easily by first configuring via something like the following to inject your own custom CSS (which I think needs to be an embedded resource):
configuration.EnableSwaggerUi( c =>
{
    c.InjectStylesheet( typeof( Startup ).Assembly, "Directory.Path.File.Name.css" );
}

Then, in the CSS, you can do something like the following - this will hide the header entirely:
#header {
    display:none;
}

You also have the option to provide your own HTML but that might be more work than it's worth. I think some documentation is provided in the default docs in this repository.

**Comment by kuttiram** [comment]
Thank you for valuable feedback

**Comment by aloneguid** [comment]
What do you have to do to get "Directory.Path.File.Name.css"? Where do you put it?

**Comment by kylepope** [comment]
It depends on the namespace of your web project and the folder you put the file in. If your project's namespace is "Foo.Bar" and you put "CoolStuff.css" in "~/Areas/Docs/Content/Styles", you would use the following string: "Foo.Bar.Areas.Docs.Content.Styles.CoolStuff.css"

Don't forget to make the "CoolStuff.css" an embedded resource in your web project...

**Comment by jasongraff** [comment]
Put a breakpoint on the line where you call InjectStylesheet(), and calling / watching `GetType().GetTypeInfo().Assembly.GetManifestResourceNames()` should get you the names of currently embedded resources so you can reference the CSS resource properly.

**Comment by nzolotar** [comment]
debugging and watching "typeof(Startup).Assembly.GetManifestResourceNames()" gave me info on path. dont forget to change CSS to embedded resource or it wont work.
