### ISSUE TITLE
Is it possible to hide a variable from getting documented in the Swagger UI?

### ISSUE THREAD

**Issue by LeythG** [domaindrivendev/Swashbuckle#479]
I am using this with ASP.NET web api 2 and I have two objects.  One is a Data transfer object and one is the object itself.  In the controller, the get endpoints return the actual object itself.  The Add/Post endpoint is the only one that receives the Data transfer object.  The data transfer object is almost the same as the main object itself, but it is missing variables that are auto generated on the DB layer.

This all works perfectly and is documented very nicely.  However, when it comes to the update/put endpoint, I need to pass in the main object, but there is one variable in that object that is not updateable.  Logically, I can prevent any updating of this variable.  However, to keep it self explainable to the consumers of the service I would like this variable to not be exposed in the Model Schema for the Put endpoint in swagger.  Is this possible?  

At the moment, the only solution I can think of is creating a Return object that contains the variable so that we can see it, creating a data transfer object that contains the variable so that we can define it in the add, and a 3rd model that contains only the variables that we are allowed to update or that we require for an update (so that we can find the object.)

Thanks ahead

**Comment by MerickOWA** [comment]
So, swagger documentation has a definition of readOnly, and Swashbuckler will expose C# readonly properties/fields as such.

It doesn't appear however that swagger UI makes it very clear that which properties are readOnly.  It appears to be a proposed feature that is being worked on [here](https://github.com/swagger-api/swagger-ui/issues/1248)

Until then, you could always attempt some fancy schema filtering which creates 2 version of a class.  One version would represent which you return in a response and one version you accept in a request, and then customize what properties are exposed in each version based on custom attributes and/or reflection information.

**Comment by domaindrivendev** [comment]
As indicated by @MerickOWA, the correct way to model your situation in C# code is with the use of readonly properties. SB will assign the readOnly flag accordingly in the Swagger JSON. But unfortunately, the swagger-ui does not reflect this flag in the HTML pages. So technically, this is a swagger-ui issue.

Depending on your JS/DOM manipulation skills, you could inject some JavaScript (see the SB readme) that modifies the UI accordingly.

@MerickOWA - thanks so much for your continued support on these issues, it's incredibly helpful and much appreciated.
