### ISSUE TITLE
Properties in path that are on the model schema should be excluded from model schema

### ISSUE THREAD

**Issue by phillip-haydon** [domaindrivendev/Swashbuckle#480]
This is mostly going to affect vNext but this affects me because I've fixed the broken model binding in my Web API project.

![image](https://cloud.githubusercontent.com/assets/895629/9650871/ab814d8e-523b-11e5-9561-5e73472c414a.png)

When request models are composed from the Route / Query String, and Body into a single request object. This results in Swashbuckle displaying duplicate properties.

The actual expectation is: 

![image](https://cloud.githubusercontent.com/assets/895629/9650894/ebac1b96-523b-11e5-911a-52db498ae79b.png)

My temporary work around, since I have an isolated issue and know I'll never have 2 objects on my method signature. Is:

```c#

public class SchemaFixFilter : IDocumentFilter
{
    private static readonly string[] Verbs = {"get", "put", "post", "delete", "partial", "patch"};

    public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
    {
        foreach (var path in swaggerDoc.paths)
        {
            foreach (var verb in Verbs)
            {
                var operation = (Operation) path.Value.GetType().GetField(verb).GetValue(path.Value);

                if (operation.parameters.Any(x => x.@in == "path"))
                {
                    var body = operation.parameters.FirstOrDefault(x => x.@in == "body");

                    if (body != null)
                    {
                        var bodySchema = schemaRegistry.Definitions[body.schema.@ref.Replace("#/definitions/", "")];

                        foreach (var urlPath in operation.parameters.Where(x => x.@in == "path"))
                        {
                            bodySchema.properties.Remove(urlPath.name);
                        }
                    }
                }
            }
        }
    }
}
```

With vNext, MVC will now do model binding across all 3 bits of data instead of just 1.

**Comment by domaindrivendev** [comment]
I have already ported Swashbuckle to vNext and thankfully, the model binding you've described is actually accounted for by WebApi's built-in metadata layer (which SB uses). So this shouldn't be an issue for vNext.

The ported version is currently in the following working repo:

https://github.com/domaindrivendev/Ahoy

It's also available as a beta version on the existing Swashbuckle Nuget feed.

**Comment by phillip-haydon** [comment]
@domaindrivendev so it wont work for Web API 2, just vNext? I can live with that. I've solved the issue for my scenario, but good to know its not an issue in vNext. :heart:
