### ISSUE TITLE
Need support for multiple independent APIs

### ISSUE THREAD

**Issue by cookting** [domaindrivendev/Swashbuckle#483]
I can't find any way to support 2+ different APIs.  Let's say I have one API called PetStore, and another called PhoneBook.  Each has a different version number.  Is this supported?

**Comment by domaindrivendev** [comment]
Can you elaborate on what you mean by "independent" API's - are they two separate WebApi applications?

**Comment by cookting** [comment]
I meant two independently versioned APIs within a single WebApp (originally).

Since I wrote this I learned that I can have multiple WebApps in the same process and call EnableSwagger once per context and it will work OK (which was my solution).

I wish there was some better documentation out there about this though, it wasn't obvious how to handle this.   It would also be useful to be able to handle multiple APIs within one WebApp, but it's not critical.
