### ISSUE TITLE
Inheritance from Dynamic Object breaks schema generation

### ISSUE THREAD

**Issue by ttarney** [domaindrivendev/Swashbuckle#487]
This filter
public class ProvideApiExampleFilter : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaRegistry schemaRegistry, System.Type type)
        {
            // instantiate and get what properties this guy exposes
            bool providesApiDocumentation = typeof (IProvideApiExample).IsAssignableFrom(type);
            if (providesApiDocumentation)
            {
                IProvideApiExample i = (IProvideApiExample) Activator.CreateInstance(type);
                List<ApiDocHelper> apiHelpers = i.ApiHelpers;

                foreach (ApiDocHelper apiHelper in apiHelpers)
                {
                    schema.properties[apiHelper.PropertyName].example = apiHelper.PropertyValue;
                }
            }
        }
    }

will not recognize any type derived from DynamicObject

works fine:
public class Foo : IProvideApiExample
{
}

no longer works
public class Foo : DynamicObject, IProvideApiExample
{
}

Thoughts?

**Comment by freeranger** [comment]
Sounds like it's related to my issue: https://github.com/domaindrivendev/Swashbuckle/issues/412

**Comment by ttarney** [comment]
For now created a class around dynamicobject to get around this

**Comment by domaindrivendev** [comment]
Going to close as the underlying issue is captured in #412
