### ISSUE TITLE
Vendor Extensions causing invalid JSON

### ISSUE THREAD

**Issue by nastassiar** [domaindrivendev/Swashbuckle#488]
I am working off of the master branch of Swashbuckle.Core (latest commit d774c528cc) and I am having issues with the vendor extensions. I didn't do anything with them and I they are causing my JSON to be invalid. 
```
{
  "swagger": "2.0",
  "info": {
    "version": "v2",
    "title": "Test API",
    "vendorExtensions": {}
  },
  "host": "localhost",
  "schemes": [
    "https"
  ],
  "paths": {
   }
}
```
Am I missing a filter? When debugging it looks like VendorExtensionsConverter is never being called even though it is added to the converters. Is this a potential bug or is there something I am missing?

**Comment by domaindrivendev** [comment]
I'm unable to repro this locally. It's definitely strange that the VendorExtensionsConverter isn't being called as it's explicitly wired up here:

https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Application/SwaggerDocsHandler.cs#L52

I wonder if this is something to do with the version of Newtonsoft.Json you're using?

**Comment by nastassiar** [comment]
For the Swagger.Core project I'm using Newtonsoft.Json.4.5.6 for the rest of my projects I'm using 7.0.1 I will try upgrading

**Comment by nastassiar** [comment]
Opps well this is embarrassing turns out my custom Content Negotiator wasn't adding the converter. 

Fixed now!

Thanks for pointing me in the right direction.
