### ISSUE TITLE
Custom ISwaggerProvider configuration option for Swashbuckle 5.x

### ISSUE THREAD

**Issue by patrickjrs** [domaindrivendev/Swashbuckle#489]
This is really not an issue but wanted to check with you if you were planning to release another version of Swashbuckle on Nuget.org that would have the cache configuration option available but not rely on Asp.NET 6? Wasn't sure if you'll be releasing more 5.x Nuget's since you have Swashbuckle 6.0.0 in beta already.
Cheers,
Patrick

**Comment by domaindrivendev** [comment]
Closing as this is a dup of #456.

Short answer is yes, the 5.2.2 (hope to release within the next week) will include the ability to inject a custom provider
