### ISSUE TITLE
SwaggerResponseAttribute and Models' comment

### ISSUE THREAD

**Issue by Florleseige** [domaindrivendev/Swashbuckle#490]
Hello,

First thanks for your work, this is just awesome !

Please consider myself as a beginer to C# .NET, I've tried however I can't get it working.

I have two problems.

My first problem is : in my actual project I have already an attribute for my responses :
`[ResponseForApi(HttpStatusCode.NotFound)]` for example.
I know the Attribute : `[SwaggerResponse(HttpStatusCode.OK)]`, but I need my own attribute.

So, I am trying to create a new Attribute who will use both of them.
To do that, I created a new class : `SwaggerErrorResponsesForApi` inheriting from `SwaggerResponseAttribute`.

My problem is situated in this new attribute. I try to instanciate the 'StatusCode' from my new attribute. But StatusCode is private... Is there a way to instanciate it ?

My second problem is I have models for my responses/parameters. But my models have the XML comments only if the models are in the same file. Is it normal ?

Thank you for your answers.

Florleseige.

**Comment by domaindrivendev** [comment]
For your first problem, I would recommend sticking with your original attribute, and then just wire up a custom IOperationFilter to detect it and update the Operation description accordingly. Here's an example:

    public class ApplyResponseForApiAttributes : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            var attributes = apiDescription.GetControllerAndActionAttributes<ResponseForApiAttribute>()
                .OrderBy(attr => attr.StatusCode);

            foreach (var attr in attributes)
            {
                var statusCode = attr.StatusCode.ToString();
                operation.responses[statusCode] = new Response
                {
                    description = attr.Description ?? InferDescriptionFrom(statusCode);
                };
            }
        }

        private string InferDescriptionFrom(string statusCode)
        {
            HttpStatusCode enumValue;
            if (Enum.TryParse(statusCode, true, out enumValue))
            {
                return enumValue.ToString();
            }
            return null;
        }
    }

For your second problem, you'll have to elaborate a little. You can tell SB about one or more Xml Comment files via the IncludeXmlComments option. Obviously, one of these would have to contain the Xml comments for your models if you want them to be incorporated into the Swagger ouput

**Comment by Florleseige** [comment]
Thanks you !

With your code, I resolved my problem ! 

For the second problem I find an other solution when I organized my code.

Thanks you again.
