### ISSUE TITLE
XML comment of an action is not visible in swagger ui

### ISSUE THREAD

**Issue by bastienJS** [domaindrivendev/Swashbuckle#492]
When I go to /swagger url and open the get action I can see no description of my method?

Thats my xml:
```
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>TGB.API</name>
    </assembly>
    <members>
        <member name="M:TGB.API.Controllers.TestsController.GetTests(System.Int32)">
            <summary>
            this is crap...
            </summary>
            <param name="id"></param>
            <returns>the data...</returns>
        </member>
    </members>
</doc>```

Thats my code:


                        var baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
                        var commentsFileName = Assembly.GetExecutingAssembly().GetName().Name + ".XML";
                        var commentsFile = Path.Combine(baseDirectory, "bin", commentsFileName);

                        c.IncludeXmlComments(commentsFile);

The commentsFile exists in my bin folder and I also checked that during runtime with File.Exists(commentsFile);

What do I wrong?

**Comment by bastienJS** [comment]
I found this bug: https://github.com/domaindrivendev/Swashbuckle/issues/184

I have the same problem using web api 2.2 with autofac and when I do inside my action:

            var descriptions = base.RequestContext.Configuration.Services.GetApiExplorer().ApiDescriptions;

I get this:

![image](https://cloud.githubusercontent.com/assets/5945955/9822882/52073906-58c3-11e5-8581-b2b135a600fb.png)

**Comment by bastienJS** [comment]
When I outcomment this in my SwaggerConfig.cs:

//[assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]

Pass a HttpConfiguration object to the its Register method then it works.

but why?

**Comment by domaindrivendev** [comment]
The console error is unrelated - it's a browser feature for debugging JavaScript by attempting to retrieve a source map file, if the web server supports it. SB does not.

Re your issue, if it's working without the pre-app-start directive then you must be invoking the Register method somewhere else. Where are you doing that? Are you by any chance using OWIN?

**Comment by bastienJS** [comment]
I call the Register method in the meanwhile in my Startup.cs which uses OWIN:

[assembly: OwinStartup(typeof(TGB.API.Startup))]
namespace TGB.API
{
    public partial class Startup
    {
        private readonly string issuer = "http://localhost:55555";

        public void Configuration(IAppBuilder app)
        {
            ConfigureOAuthTokenGeneration(app);
            ConfigureOAuthTokenConsumption(app);
            var config = new HttpConfiguration();
            SwaggerConfig.Register(config);
            WebApiConfig.Register(config);
            WebServicesConfig.Register(config);
            LoggingConfig.Register();
            app.UseCors(CorsOptions.AllowAll);
            app.UseWebApi(config);
            HttpConfiguration = config;
        }
   }
}

SWAGGERCONFIG.CS

//[assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]

namespace TGB.API
{
    public class SwaggerConfig
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="config"></param>
        public static void Register(HttpConfiguration config)
        {
            config.EnableSwagger(c =>
                 {

                     c.SingleApiVersion("v1", "TGB.API");

                     var baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
                     var commentsFileName = Assembly.GetExecutingAssembly().GetName().Name + ".XML";
                     var commentsFile = Path.Combine(baseDirectory, "bin", commentsFileName);

                     c.IncludeXmlComments(commentsFile);
                 })
             .EnableSwaggerUi(c =>
                 {
                     // If your API supports the OAuth2 Implicit flow, and you've described it correctly, according to
                     // the Swagger 2.0 specification, you can enable UI support as shown below.
                     //
                     //c.EnableOAuth2Support("test-client-id", "test-realm", "Swagger UI");
                 });
        }
    }
}

That way it works. Do I anything wrong?

**Comment by domaindrivendev** [comment]
Ok that explains it. You'll see a section in the readme with specific instructions for getting started in an OWIN environment.

It's a little different because the pre-app-start stuff won't work. Looks like you arrived at the correct solution anyway
