### ISSUE TITLE
In IE javascript throws an exception

### ISSUE THREAD

**Issue by fhurta** [domaindrivendev/Swashbuckle#496]
In file **swagger-ui-js:1851**

`if(res.body && Object.keys(res.body).length > 0) {`

_Object.keys: argument is not an Object_

In my case the body is string returned from the action.
It works fine in Chrome and Firefox but not in IE11 and lower (tried as Emulation from IE11).

**Comment by christopheblin** [comment]
I am not the maintainer of the package but I had a similar problem in the past.

When you have an error in the frontend, this is usually an error in swagger-ui itself and not in swashbuckle so you better ask directly on the swagger-ui project.

**Comment by fhurta** [comment]
The swagger-ui is bundled into SwashBuckle - there is a handler serving it from this library. That's why I reported here. But I guess it is added to SwashBuckle as is so you are probably right and the issue should be created in swagger-ui repo. 

However, looking into swagger-ui repository, there's 2.1.3 version, while the version bundled into SwashBuckle is 2.1.1. I can't easily verify the issue still exist in current version now.. I leave it on maintainer to decide closing this issue
