### ISSUE TITLE
Can I ask a question here?

### ISSUE THREAD

**Issue by marcbieling** [domaindrivendev/Swashbuckle#498]
Hi,

I don´t know if this is the right place to ask a question...so feel free to lead me in an other direction.

Do you know if someone enabled swashbuckle on a DotNetNuke-Installation. The last two evenings I was not able to find any information regarding this topic on the web.

Thanks in advance,
Marc

**Comment by SeanKilleen** [comment]
Hi Marc,  

I'm completely new here and not involved with the project, so take my pointing with a grain of salt :smile:

However, I think your best bet in this case might be to post the question on a place like StackOverflow, which has a [tag for Swashbuckle](http://stackoverflow.com/questions/tagged/swashbuckle). It looks as thought several people have been able to get questions answered there.
