### ISSUE TITLE
Inheritance Hierarchy not recognized by Swashbuckle?

### ISSUE THREAD

**Issue by amarwadi** [domaindrivendev/Swashbuckle#50]
Hello,
I have realized that in many cases, we use Inheritance hierarchy for certain items. For e.g. we have a base Field class that has a Title and a Key property. Then we have a TextField which derives from a Field class and adds a Description property. When swagger shows documentation for the TextField, it only shows Description as the property and doesn't recognize the underlying Title or Key as properties.

would you be able to look into this and guide me if I'm doing something incorrectly?

Thank You so much!

**Comment by zhangpeng-kooboo** [comment]
Hi @domaindrivendev ,
Is there any news or alternative solutions we can have it in the latest version?
