### ISSUE TITLE
Reorganizing Configuration Options in SwaggerConfig.cs installed via Nuget package

### ISSUE THREAD

**Issue by patrickjrs** [domaindrivendev/Swashbuckle#500]
Hi,

Just wanted to document this here as I just spent a good deal of time on trying to figure out why my changes applied via custom OperationFilter were getting overwritten. Turns out using the IncludeXmlComments option adds an OperationFilter called ApplyXmlActionComments and a SchemaFilter called ApplyXmlTypeComments. Since the SwaggerConfig.cs file had a bunch of commented out configuration options I naively just uncommented what I needed and replaced with my own filters assuming it would all just work fine. Could be helpful when getting started with Swashbuckle to have the commented out options ordered so that anything custom added would not get overwritten. Or perhaps highlight the filter order in the docs.

**Comment by domaindrivendev** [comment]
See v5.2.2
