### ISSUE TITLE
Customize Obsolete Actions 

### ISSUE THREAD

**Issue by bhupinder7** [domaindrivendev/Swashbuckle#502]
Hi, In my api controller i have specified obsolete attribute on a particular action with a message. And, in the swagger ui it end up showing as Warning:Deprecated ( attached image). Is it possible to change the text color of the warning message from green to red and also show the message which was specified on that action.

 [Obsolete("Please use the another method to register")]

![image](https://cloud.githubusercontent.com/assets/5807414/9935933/82777ef8-5d27-11e5-88bd-cc4fb77a612d.png)

**Comment by bhupinder7** [comment]
Okay, I figured to how to mark the obsoleted action as red. I used custom javascript and manually changed the color to red. Here's the snippet if anybody is looking for it and attached image is the result.

var elms = document.getElementById("element_Content_id").getElementsByTagName("h4");
elms[0].style.color = "Red";
elms[0].style.fontWeight = "bold";

![image](https://cloud.githubusercontent.com/assets/5807414/10028243/466734a6-6139-11e5-8da0-f2804fee11a9.png)

**Comment by bhupinder7** [comment]
However, still not sure about the message that we add along with obsolete param.
[Obsolete("Please use the another method to register")]

**Comment by domaindrivendev** [comment]
The swagger-ui is driven purely off the [Swagger JSON](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) that's generated and served up by Swashbuckle. For example, the warning you see above is rendered if the corresponding Operation description has the "deprecated" flag set. The spec doesn't currently support an associated message for this flag but you could extend it and apply some more JS to display the message from your C# attribute in the UI. I haven't tried this but here's the rough idea:

1) Create an IOperationFilter (see readme) that inspects the ApiDescription for the presence of the Obsolete attribute

    apiDesc.ActionDescriptor.GetCustomAttributes<ObsoleteAttribute>

2) If it exists then add a "vendor extension" property to the corresponding Operation description

    operation. vendorExtensions.Add("x-deprecated-message", attribute.Message)

3) Inject some JavaScript that iterates each operation in the DOM

    $("li.operation").each

4) For each one pull out the id attribute and use it to look up the message from the corresponding description

    window.swaggerApi["Account"].operations["Account_Register"]["x-deprecated-message"]

**Comment by bhupinder7** [comment]
Thanks, it makes sense. I will try that.

**Comment by bhupinder7** [comment]
I tried to do like this but not sure how can i see the message in the DOM.

 public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription) 
        {

            if (operation.deprecated == true) 
            {
                                
                operation.vendorExtensions.Add("x-deprecated-message", "This is  a message");
            }        
        }
