### ISSUE TITLE
Response schema for 200 defaults to "Object"

### ISSUE THREAD

**Issue by raaga123** [domaindrivendev/Swashbuckle#503]
How does Swashbuckle pick up the schema for the response type? I haven't been able to make it show up as anything but "Object{}".

**Comment by domaindrivendev** [comment]
Can you show an example of your action signature?

**Comment by raaga123** [comment]
Here is an example. (There's no particular reason why this version should generate a specific response type as far as I know. I've tried adding various annotations and XML comments to this, but nothing changes. I was wondering what the accepted way to do it is.)

        /// <summary>
        /// Gets the current user.
        /// </summary>
        /// <response code="200">Success</response>
        /// <response code="403">Forbidden (invalid or missing authorization token)</response>
        [HttpGet]
        [Route("current")]
        public HttpResponseMessage GetCurrentUser()

**Comment by raaga123** [comment]
I've checked the JSON output, and I can see that the "schema" element of the 200 response is set to the default of Object. Clearly it needs to contain the correct type instead -- how do I make that happen?

**Comment by raaga123** [comment]
It looks like the ResponseType annotation works, but only for some types. So, for example, the annotation [ResponseType(typeof(ClassA))] works correctly, while the annotation [ResponseType(typeof(ClassB))] defaults to Object. Does it have something to do with where the object definitions are? (Visual Studio is able to see both classes when I have the source file open.)

**Comment by raaga123** [comment]
Never mind -- I just checked over at the swagger-ui site, and it looks as though the bug is there -- swagger-ui doesn't seem to like externally defined objects or primitives.
