### ISSUE TITLE
NullRefException fix in FullNameSansTypeParameters

### ISSUE THREAD

**Issue by replaysMike** [domaindrivendev/Swashbuckle#506]
Hello,

I would recommend adding this to the next patch. When encountering generic type arguments, there is no FullName property, so Name must be used:

    public static string FullNameSansTypeParameters(this Type type)
        {
            var fullName = type.FullName;
            if (string.IsNullOrEmpty(fullName))
                fullName = type.Name;
            var chopIndex = fullName.IndexOf("[[");
            return (chopIndex == -1) ? fullName : fullName.Substring(0, chopIndex);
        }

**Comment by replaysMike** [comment]
ack I'll put this through as a pull request.

**Comment by domaindrivendev** [comment]
Sounds good - if you could add a test too that would be awesome. Thanks!
