### ISSUE TITLE
Modularity: unbundling swagger-ui from swashbuckle 

### ISSUE THREAD

**Issue by younanjo** [domaindrivendev/Swashbuckle#509]
Hi guys,

I've recently proposed the use of swashbuckle to integrate swagger in our webapis for the purpose of exposing an APIs functionality internally to our engineers. for our purposes swagger doesn't make sense in production since the apis are back-end..... being an enterprise environment the amount of APIs are large and I can foresee two major issues:
- Size of assembly is around 2.6MB: Assume hundreds of apis build with swahbuckle integrated suddenly the size of all our apps has increased by 4.5 times. An unreasonable hit. Looking at the swashbuckle.core i suspect the bulk of the size is from swagger-ui being bundled. Would it be possible to unbundle swagger-ui from swashbuckle and instead allow swagger-ui to be added through a separate nuget package.
- Bundled swagger-ui within swashbuckle has each and every api having its own instance of swagger-ui. Any customization made to swagger-ui has no effect to other projects unless one also makes that changes to every single api project increasing the effort and reducing maintainability chances. We are hosting swagger-ui centrally and make customization to allow for devs to try their swagger implementation locally (localhost) so are greatly effected by swashbuckle integrating swagge-ui and would've been significantly better off having the option to pull swagger-ui through a separate nuget package optionally.

Is there anything in pipeline to address the above or is our best chance to simply fork and move ahead? Is a modular approach to swashbuckle discussed at all or is it always going one big assembly? 

PS: I've asked the question in stackoverflow in case this isn't the right place to ask questions:
http://stackoverflow.com/questions/32751161/modularity-unbundling-swagger-ui-from-swashbuckle

**Comment by domaindrivendev** [comment]
Hi there. Thanks for the feedback. Actually this is something I've considered in the past, although this is the first time I've heard the argument around assembly size. You've describe it as "An unreasonable hit" - could you elaborate a little? Just for my own understanding, I'd like to know specifically the operational issues this might cause.

That said, I'm all for modularity and for the vNext port (see https://github.com/domaindrivendev/Ahoy) I've spiked out the separation you're proposing. For the use-case which entails both, also the most common use of Swashbuckle, it was tricky to have the UI automatically use the docs URL configured setup through the non-UI package.

With that said though, I have a few new ideas and with your issue prompting me, I'll take another look at the split out for the next major release (vNext).

**Comment by domaindrivendev** [comment]
This change won't happen until the next major release (targeting AspNet 5)

**Comment by domaindrivendev** [comment]
This modularity is implemented in the ASP.Net Core version of Swashbuckle - https://github.com/domaindrivendev/Swashbuckle.aspnetcore. I won't be implementing it for the WebAPI version and so am going to close this issue.
