### ISSUE TITLE
How can I validate a Swagger Document

### ISSUE THREAD

**Issue by DotNetRockStar** [domaindrivendev/Swashbuckle#510]
I was wondering if there is some utility class that can validate a swagger document?  I have gone through some of the code but have not found anything such as this.

For Example:
```
string mySwaggerText = GetSomeAwesomeSwaggerText();
var swaggerValidator = new SwaggerValidator();
var validationResult = swaggerValidator.Validate(mySwaggerText);
if (!validationResult.IsValid)
{
    // Do stuffz
    foreach (var item in validationResult.Items)
    {
         // Cool.  This shows me what is wrong.
    }
}
```

If not that's cool, but exposing some of these tools that are likely being used internally would be awesome for some things I am working on.

Thanks!

**Comment by dthorpe** [comment]
I saw this mentioned in another response in this forum.  POST your json Swagger doc to this url:

http://online.swagger.io/validator/debug

**Comment by DotNetRockStar** [comment]
Thanks for the response.  I was hoping for a way to do this in code rather than making an http call.  I am in need of doing this programatically for potentially more than 1 document.
