### ISSUE TITLE
How to customize schema based on operation?

### ISSUE THREAD

**Issue by ironsheik** [domaindrivendev/Swashbuckle#511]
I have an object that I would like to hide one of its properties when listing the schema for PUT but display its property when listing the schema for GET. I can see that with SchemaFilters I could hide this property but I can't tell how to determine what the operation is.. a Schema Filter seems all or nothing.

An Operation Filter sounds like it would give me the context of what operation I'm on (GET/PUT/etc) but how can I modify the schema at this point?

Thanks!

**Comment by domaindrivendev** [comment]
This is dup of #479

In summary, you should make the properties read-only. SB will then set the "readOnly" flag in the corresponding property description. However, the swagger-ui doesn't currently reflect this flag in the HTML pages.
