### ISSUE TITLE
Swagger-UI not showing content from Swashbuckle JSON

### ISSUE THREAD

**Issue by dthorpe** [domaindrivendev/Swashbuckle#516]
I have a self-hosted Web API 2.0 app with multiple controller classes scattered across several assemblies. Using Swashbuckle.Core v5.2.1 - Swagger for Web API (.NET 4.5+), Microsoft.Asp.Net Web Api 2.2 OWIN v5.2.3

Swashbuckle generates info for all the methods in all my controllers (/swagger/docs/v1) but swagger-ui only displays one controller's worth of methods in the UI.  The controller methods that do display happen to be the ASP.NET Identity and User Management REST API, if that makes any difference.  No methods from any other controllers in my self-hosted server are shown by swagger-ui even though they are present in the JSON generated by Swashbuckle.

In the Chrome browser inspector window on the swagger-ui page, there is an error "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined" logged in the console.  The source line given is usually index.js:22, but that is mostly useless as it appears to be a top level dispatch function. The call stack isn't much help either.

In poking around with this yesterday, I thought I saw an error in the Chrome console that placed the error location near a statement involving "param.type.toLowerCase()" but I can't be certain because I can't repro it now.  Chrome's JS debugger is thoroughly confused by the swagger-ui code - can't set breakpoints most places, can't watch or inspect expressions in the current frame, and when it will let you set a breakpoint, it jumps to a completely different file. Why is swagger-ui so vexing to the Chrome debugger?

Any ideas as to why swagger-ui isn't showing all the content in the Swashbuckle generated JSON?

Thanks

**Comment by dthorpe** [comment]
p.s. The Swagger-UI behavior (not showing a lot of the API methods found in the JSON) is identical between the built-in swagger-ui and using the swagger-ui online demo : http://petstore.swagger.io/

**Comment by dthorpe** [comment]
By process of elimination (commenting out large swaths of code until swagger-ui worked), I've narrowed the problem down to this method declaration:

````c#
[RoutePrefix("v1/Alerts")]
public class AlertsController : BaseUserApiController
{
    [Route("{id}/IsNew")]
    public async Task<IHttpActionResult> Put(Guid id, [FromBody] Boolean isNew)
    {
        ...
    }
}
````
which produces this JSON (extracted from larger document):

````javascript
"/v1/Alerts/{id}/IsNew":
{
  "put": {
    "tags": [
      "Alerts"
    ],
    "operationId": "Alerts_Put",
    "consumes": [
      "application\/json",
      "text\/json",
      "application\/xml",
      "text\/xml",
      "application\/x-www-form-urlencoded"
    ],
    "produces": [
      "application\/json",
      "text\/json",
      "application\/xml",
      "text\/xml"
    ],
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "type": "string"
      },
      {
        "name": "isNew",
        "in": "body",
        "required": true,
        "schema": {
          "type": "boolean"
        }
      }
    ],
    "responses": {
      "200": {
        "description": "OK",
        "schema": {
          "$ref": "#\/definitions\/Object"
        }
      }
    },
    "deprecated": false
  }
}
````

Given the mercurial error near a statement like "param.type.toLowerCase()", I'm guessing the issue has something to do with the "schema": { "type": "boolean" } in parameter "isNew".

Thoughts?  Workarounds?

**Comment by dthorpe** [comment]
I've worked around this issue by changing the API to use a URL parameter for the boolean value rather than the customary body parameter.

Reading the Swagger 2.0 spec regarding body parameters, the Swashbuckle JSON output appears to be 2.0 compliant.  So is the bad behavior a bug in swagger-ui itself, not handling the 2.0 spec body param correctly?

**Comment by brentonmcs** [comment]
I ran into the same problem. I've created a PR on the UI project to resolve it.

https://github.com/swagger-api/swagger-ui/pull/1668

**Comment by domaindrivendev** [comment]
I've updated the UI to 2.1.4 but am still seeing this issue

**Comment by sonofaforester** [comment]
Hacky work around is to create an operation filter like this. Not sure the output is completely correct, but it renders.

` public class SwaggerOperationFilter:IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            if(operation.parameters != null)
            foreach (var parameter in operation.parameters)
            {
                if (parameter.schema != null && parameter.schema.type == "boolean")
                    parameter.type = "boolean";
            }
        }
    }`

**Comment by sonofaforester** [comment]
Sorry, can't seem to get the code to format nicely....

**Comment by domaindrivendev** [comment]
@dthorpe, @sonofaforester v5.4.0 of SB uses v2.2.0 of the swagger-ui. If you get a chance, would you let me know if you're still seeing this issue in that version?

**Comment by dthorpe** [comment]
Sorry, I can't repro the original issue. 2015 was a lifetime ago.  New job, new project, totally different dev stack.
