### ISSUE TITLE
swagger is (almost) empty after recompile in vs2015

### ISSUE THREAD

**Issue by fhdk** [domaindrivendev/Swashbuckle#517]
Only the headline and api-description - the footer and the validation link is rendered.

I have no clue what so ever.

**Comment by fhdk** [comment]
List of packages in project
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Identity.Core" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Identity.EntityFramework" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Identity.Owin" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Cors" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Security.Cookies" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Security.OAuth" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />
  <package id="Swashbuckle" version="5.2.2" targetFramework="net45" />
  <package id="Swashbuckle.Core" version="5.2.2" targetFramework="net45" />
  <package id="WebActivatorEx" version="2.0.6" targetFramework="net45" />

**Comment by fhdk** [comment]
![swagger-ui](https://cloud.githubusercontent.com/assets/14216035/10215407/840767a6-6821-11e5-847a-6fdef1e07348.PNG)

**Comment by alexjamesbrown** [comment]
This is the same as I get...!

**Comment by fhdk** [comment]
I created a new base project from webapi template in vs2015 with the same base namespace.
Then I added swashbuckle and verified it by compiling and running it.
Added all my classes and controllers through drag'n'drop
Removed unneeded classes - not area/helppage

Surely not optimal but it worked :)
