### ISSUE TITLE
Give a better error message when documentation.xml file is missing from filesystem

### ISSUE THREAD

**Issue by withinboredom** [domaindrivendev/Swashbuckle#523]
Getting a 500 response on the ui page: https://microsoft-apiapp01663f23f55d465ebe70625f9b85ddcc.azurewebsites.net/swagger/ui/index

I'm experimenting with azure api ... it works locally, but it doesn't work there. The api is functioning fine and this is just an issue with swashbuckle.

The detailed error page has this to say about it:
- IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.
- IIS was not able to process configuration for the Web site or application.
- The authenticated user does not have permission to use this DLL.
- The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.

![Detailed Error](http://puu.sh/kyPRZ/b3ac23d83c.png)

I checked the event logs and there's nothing interesting in there. Any hints or tips to get this working in azure?

Running 5.2.2 of swashbuckle

**Comment by withinboredom** [comment]
For anyone who runs into this later on: Check to make sure your documentation xml file exists.

**Comment by domaindrivendev** [comment]
If the file is not present, then Swashbuckle will raise a FileNotFoundException. I believe this to be the appropriate behavior - it's an unexpected exception that your end-user can do absolutely nothing about. Furthermore, for any unexpected exception, I believe it's best practice to reveal little or no information to the end-user and instead have the error logged server-side so it can be handled internally.
