### ISSUE TITLE
Best practice recommendation for private / public functions?

### ISSUE THREAD

**Issue by stevemurch** [domaindrivendev/Swashbuckle#526]
Thanks so much for this library. Just getting a handle on moving an API from MVC5 to WebAPI, and before we do so, I'd like to understand how to generate swagger UI that has optional REST endpoints undocumented.

I see the Obsolete attribute, but that really isn't semantically what we're looking for -- the method(s) are not obsolete, simply not something we want to expose to external clients, but keep for internal use only.  What's the best way to do that?  Is there an attribute at work here to flag it for publication or not?  Thanks!

**Comment by stevemurch** [comment]
Found it -- there's a good example here.

http://stackoverflow.com/questions/29701573/how-to-omit-methods-from-swagger-documentation-on-webapi-using-swashbuckle

Is it recommended to simply set all the fields to null in the IDocumentFilter-derived class? Is that the way to "Apply" the filter to effectively remove it from display? Thanks much.

**Comment by domaindrivendev** [comment]
FYI, because SB is built on top off WebApi's metadata layer - ApiExplorer, it's also possible to do this with an attribute:

    [ApiExplorerSettings(IgnoreApi=true)]
    public Order GetOrder(int id)
