### ISSUE TITLE
Routes with optional parameters are parsed out of the paths

### ISSUE THREAD

**Issue by phillip-haydon** [domaindrivendev/Swashbuckle#529]
Given the following:

`products/{type?}`

This is parsed out as:

`products`

The `type` parameter doesn't appear in the parameter list at all.

**Comment by domaindrivendev** [comment]
In Swagger 2.0, the "path" (i.e. uri without the query string) is used to uniquely identify an operation. Therefore, an optional "path" parameter is not possible as described [here](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameter-object) beside the "required" field.

For this particular case (i.e. a filtered collection resource), you typically see the param expressed in the query string and this would play nicer with Swagger/Swashbuckle. This is probably a little more standard (whatever that means) and does have the advantage of being able to add an operation to retrieve a specific product without introducing a route conflict - e.g. "/products/{id}" 

I'm sure you have your reasons though and may not want to modify your API contract. Unfortunately though, your Swagger description will have to describe it as two separate operations (one with the param and one without). The easiest way to do this with SB is to create separate controller actions then internally they could both delegate to the same private implementation.
