### ISSUE TITLE
Embedding ApiKey as a Bearer Token

### ISSUE THREAD

**Issue by amarwadi** [domaindrivendev/Swashbuckle#53]
Hello,
I understand that Swagger allows you to customize the API Key change event to allow adding the key as a part of the Header instead of the Query string parameter by changing the default code shown here:

$('#input_apiKey').change(function() {
var key = $('#input_apiKey')[0].value;
log("key: " + key);
if(key && key.trim() != "") {
log("added key " + key);
window.authorizations.add("key", new ApiKeyAuthorization("api_key", key, "query"));
}
}) 

I know the solution but I don't know how I can change this using Swashbuckle because the template is embedded. I noticed that you have a way to embed Javascript by creating Embedded resource files.

Can you please explain how we could go about doing this? I literally need to make the following change:

$('#input_apiKey').change(function () {
    var key = $('#input_apiKey')[0].value;
    if (key && key.trim() != "") {
        key = "Bearer " + key;
        window.authorizations.add("key", new ApiKeyAuthorization("Authorization", key, "header"));
    }
})

I would highly appreciate it if you could guide me here.

Thanks in advance for your consideration.

**Comment by urig** [comment]
Blog post explaining how to add "the JS file as an embedded resource and added it to SwaggerUI config": http://stevemichelotti.com/customize-authentication-header-in-swaggerui-using-swashbuckle/
