### ISSUE TITLE
Swagger UI request payload structure is including properties w/o public setters

### ISSUE THREAD

**Issue by engenb** [domaindrivendev/Swashbuckle#530]
Hello,

I've got a class modeling a post body that looks something like this
```
public class CreateGroup
{
  public string ApiKey { get; private set; }
  public string Name { get; set; }  

  public void WithApiKey(string apiKey)
  {
    ApiKey = apiKey;
  }
}
```

The ```ApiKey``` property isn't settable as it's populated via ```WithApiKey``` by the controller after the Authorize token is validated.  The idea being I can just add some request info to the model before routing it to its command handler in my system.  This is a simpler solution than having two separate models for the post body and the routed command.

Design choices aside, the Model Schema rendered in swagger UI for this object includes ApiKey.  Is this expected?  I was expecting it to build the sample model based solely on publicly settable properties.

Of course, this isn't a big deal as the ApiKey provided in the post body json is simply ignored, but it may lead to confusion for those using swagger to test out the API I'm building.  This behavior struck me as a little odd so wanted to start a conversation around it.

Thoughts?  Thanks!

**Comment by domaindrivendev** [comment]
This is really a swagger-ui issue as opposed to Swashbuckle. If you look at the raw Swagger that's being generated you should see the "readOnly" flag set on the ApiKey property description. However, swagger-ui doesn't currently honor this. You can follow the related issue here - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameter-object.

Have you tried making the ApiKey property "internal" - I think that might work for your case?

**Comment by engenb** [comment]
oh great - thanks for taking a look!

I ended up taking a slightly different approach that is easier to work with and doesn't suffer from this issue.
