### ISSUE TITLE
Unexpected End of MIME Multipart Stream - Swashbuckle.Core 5.2.2

### ISSUE THREAD

**Issue by chrischapman-peon** [domaindrivendev/Swashbuckle#531]
We recently upgraded from 5.2.1 to 5.2.2 and now our file upload control has started responding with 
"Unexpected end of MIME multipart stream. MIME multipart message is not complete."

We used the examples found here to build the IOperationFilter file media type for 5.2.1
https://github.com/domaindrivendev/Swashbuckle/issues/280

When we use Swashbuckle 5.2.1 with Swashbuckle.Core 5.2.1 it works fine
When we use Swashbuckle 5.2.2 with Swashbuckle.Core 5.2.1 it works fine
When we use Swashbuckle 5.2.2 with Swashbuckle.Core 5.2.2 we get the errors.

Also experiencing the error with:
* Swashbuckle.Core - (.Net 4.5+)
* Swashbuckle (.Net 4.5).

Any ideas?

**Comment by chrischapman-peon** [comment]
Our OperationFilter was not identical to the sample; we had let off the '@in = "formData"' setting.
Putting that back in has seemed to have fixed the error.

**Comment by centur** [comment]
Same for me. Hat tip for finding `@in="formData"` setting
