### ISSUE TITLE
Vendor Extensions in Operations

### ISSUE THREAD

**Issue by MisterJames** [domaindrivendev/Swashbuckle#533]
All requests to the API I am developing require an HTTP header value to be set as part of the request. As a result, all "try it out" calls fall from the Swagger UI as they do not contain the header.

I have tried adding the header via an `IOperationFilter` as such:

````
public class VendorExtensionFilter : IOperationFilter
{
    public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
    {
        operation.vendorExtensions.Add("x-api-required-header-key", "test-value");
    }
}
````

...but I'm not sure of a couple of things:
 1. Is this the intended use?
 1. Does the Swagger UI support testing with this scenario?
 1. Is there an alternate approach to supplying the header to test invoking the operation?

Thanks for any help/guidance.

**Comment by domaindrivendev** [comment]
If I understand you're requirement correctly, I don't think you need a vendor extension because [Swagger](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) already has properties for describing "header" parameters for an operation:

    public class CustomHeaderFilter : IOperationFilter
    {
            if (operation.parameters == null)
                operation.parameters = new List<Parameter>();

            operation.parameters.Add(new Parameter
                {
                    @in = "header",
                    name = "X-CustomHeader",
                    type = "string",
                    @default = "foobar"
                });
        }
    }
