### ISSUE TITLE
fetching resource list please wait

### ISSUE THREAD

**Issue by nickstanbrough** [domaindrivendev/Swashbuckle#539]
locally the swagger UI is working as expected but when I deploy to our dev web server I get  "Fetching resource list xxxxx please wait." When I hit the url it is waiting on directly, it returns to me all the json I would expect. There are no errors in the browser console. 

Any suggestions are much appreciated!

**Comment by domaindrivendev** [comment]
Are you still seeing this issue - my suggestion would be to do exactly what you've done - hit the json URL directly and then check for browser console errors.

**Comment by nickstanbrough** [comment]
We have resolved the  issue. Thanks for checking.

**Comment by MSAAAAuto** [comment]
I have this problem and i have found why.
After start http://localhost:52536/swagger/ i see just:
"fetching resource list: http://localhost:52536/swagger/v5/swagger.json; Please wait"
It is never done.
The thread of the browser use CPU as much as it can an memory is growing from few MB to more than 4 GB and then it restarts and starts again.
In model is a cycle reference. 
I found that Attribute 

> [JsonIgnore] 

can resolve the problem, bud this is not the best solution.

In MVC I can use this configuration:
`services.AddMvc().AddJsonOptions(setupAction => { setupAction.SerializerSettings.PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.All; });`
https://www.newtonsoft.com/json/help/html/PreserveReferencesHandlingObject.htm

**How can I configure JsonOptions in Swagger?
services.AddSwaggerGen ???**

**Comment by pedroknup** [comment]
> I have this problem and i have found why.
> After start http://localhost:52536/swagger/ i see just:
> "fetching resource list: http://localhost:52536/swagger/v5/swagger.json; Please wait"
> It is never done.
> The thread of the browser use CPU as much as it can an memory is growing from few MB to more than 4 GB and then it restarts and starts again.
> In model is a cycle reference.
> I found that Attribute
> 
> > [JsonIgnore]
> 
> can resolve the problem, bud this is not the best solution.
> 
> In MVC I can use this configuration:
> `services.AddMvc().AddJsonOptions(setupAction => { setupAction.SerializerSettings.PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.All; });`
> https://www.newtonsoft.com/json/help/html/PreserveReferencesHandlingObject.htm
> 
> **How can I configure JsonOptions in Swagger? services.AddSwaggerGen ???**

Great @MSAAAAuto. I hadn't even noticed the memory consumption and CPU usage, it was huge. My problem is this cycle referencing too. I added many [JsonIgnore] attributes and now I can see my Swagger documentation. But this isn't the solution, since I need these attributes that are now being ignored. Do you have figured out how to solve this?
