### ISSUE TITLE
Is it possible to generate web.api code by json or yaml file?

### ISSUE THREAD

**Issue by bagusflyer** [domaindrivendev/Swashbuckle#544]
I know Swashbuckle is possible to generate document from web api code. But I'm wondering if it's possible to do the reverse? I have a json/yaml file generated by Swagger editor and want to generate c# .net code. Is that possible? Thanks.

**Comment by chartek** [comment]
As far as I know, it's not possible to do with Swashbuckle. However, Microsoft has a [tool called AutoRest](https://github.com/Azure/autorest) that can generate C# code (or even Node, Java, or Ruby code) based on a Swagger document.

**Comment by bagusflyer** [comment]
Thanks for your reply. But

> The AutoRest tool generates client libraries for accessing RESTful web services.

I'll do more researches on this topic anyway.

**Comment by domaindrivendev** [comment]
This is something I'm strongly considering for the next version of Swashbuckle. However, it's targeted to AspNet 5 (check out the repo here - https://github.com/domaindrivendev/Ahoy) so won't be available unless you've upgraded your WebApi.

**Comment by maingi4** [comment]
you can do this via swagger-codegen, in the Swagger editor itself, open the menu item to generate server side code and choose ASPNet, its the first option if I remember correctly.

**Comment by domaindrivendev** [comment]
I've come to the conclusion that this is outside the scope of Swashbuckle.
