### ISSUE TITLE
Base Url is not populating in V5.2.2

### ISSUE THREAD

**Issue by Krikroff77** [domaindrivendev/Swashbuckle#550]
My config:

config.EnableSwagger("api-docs/{apiVersion}/swagger", c =>
{
c.RootUrl(req => ApiConfig.GetRootUrl());
c.Schemes(new[] { "http" });
c.BasicAuth("Basic");
c.SingleApiVersion(ApiConfig.GetCurrentVersion(), "Gateway REST API documentation")
.Description("Active documentation of Gateway system API");
c.IncludeXmlComments(ApiConfig.GetXmlCommentsPath());
}).EnableSwaggerUi(
ApiConfig.GetApiDocumentationUrl() + "/{*assetPath}"
);

screenshot:

![swagger_0 0 1](https://cloud.githubusercontent.com/assets/3442829/10897184/4f891788-81bf-11e5-9f9e-4f64f3692955.PNG)

Regards

**Comment by domaindrivendev** [comment]
I cant' repro this.

Perhaps it's a misunderstanding of names. When you set "RootUrl" via the config, you're specifying the absolute URL (including host, port and optionally a virtual directory) to the root of your application. However, the "BASE URL" that's displayed in the UI, is just the path portion of this root url - in other words the virtual directory if any.

So, if you applied the following, you would see "/foobar" displayed as the base url

    c.RootUrl(req => "http://localhost:9000/foobar");
