### ISSUE TITLE
Using Tag Options

### ISSUE THREAD

**Issue by phillsta** [domaindrivendev/Swashbuckle#551]
Hi,

I wanted to confirm if Swashbuckle generates tag options as per the swagger definition for ApiControllers? If so how? I've looked through the SwaggerDocument class and the tag option is there but now returned when the document is generated. 

I would assume it would of worked similar as methods and use the <remarks> comments to populate the descriptions of the tags.

Example: 

tags: [
{
name: "pet", <-- Name of the APIController
description: "Everything about your Pets",  <-- <remarks>
...
}

Second question is there a way to rename an APIController in the swagger output?

**Comment by phillsta** [comment]
I came up with an alternative which works so far. What I've done is extend the ApiDescription Class and set the GroupActionsBy to use the extension function.

```
public class Path : Attribute {
   public string Name { get; set; }
}

public static class ApiDescriptionExtensions  {
        public static string GetPathName(this ApiDescription apiDescription) {
              var groupByName = apiDescription.ActionDescriptor.GetCustomAttributes<Path>().FirstOrDefault() ?? apiDescription.ActionDescriptor.ControllerDescriptor.GetCustomAttributes<Path>().FirstOrDefault();

              return groupByName != null ? groupByName.Name : apiDescription.ActionDescriptor.ControllerDescriptor.ControllerName; 
        } 
}

config.EnableSwagger(c =>
            {
                c.GroupActionsBy(apiDesc => apiDesc.GetPathName());
            });
```

The extension function first checks to see if there is Path Attribute against the controller function if null then checks the controller itself. If both null then falls back to the Controller Name.

**Comment by domaindrivendev** [comment]
Yep - this makes sense. Please re-open if you have any other issue with this.
