### ISSUE TITLE
Nuget package is missing files

### ISSUE THREAD

**Issue by dotdot2** [domaindrivendev/Swashbuckle#552]
I cloned the repo locally and build it. However, the generate nuget for Swashbuckle.Core is only ~100KB as opposed to ~3MB for the published package.

What as I missing?

@domaindrivendev

**Comment by vkulkarni1008** [comment]
Did you got any answer for this

**Comment by domaindrivendev** [comment]
The missing piece is cloning the swagger-ui folder before  (it's a git submodule)

**Comment by dotdot2** [comment]
yeah, figured that out. Thanks for the help. Perhaps the build script can throw an error instead of silently building on.
