### ISSUE TITLE
Where is this Defined GetXmlCommentsPathForControllers

### ISSUE THREAD

**Issue by markalanevans** [domaindrivendev/Swashbuckle#557]
In your docs you specify to use : GetXmlCommentsPathForControllers

But VS can't find it.

**Comment by markalanevans** [comment]
I ended up adding a method to the class:

```C#
private static string GetXmlCommentsPath()
        {
            return string.Format(@"{0}\MyAppXmlDocs.XML",
                System.AppDomain.CurrentDomain.BaseDirectory);
        }
```

Where for my project properties, i specified MyAppXmlDocs.XML and enabled XML output to the bin\   dir

In your docs you mention 2 files, any reason to break them up? Is there a better way to do this?

**Comment by domaindrivendev** [comment]
Sometimes people keep their models in a separate library to the MVC application and so you get separate Xml files. The example in the docs is just illustrating that this use case can be supported, but your way is perfectly fine.
