### ISSUE TITLE
Custom OAuth2 Logout functionality 

### ISSUE THREAD

**Issue by dcolliervb23** [domaindrivendev/Swashbuckle#560]
When turning off OAuth2 for a service, it would be nice to have the option to pass a custom url for logging out, so we could notify the Identity Provider that the user is logging off.

Here is an example of a hack to Swagger that accomplishes what I'm requesting.

```
function handleLogout() {
  for(key in window.authorizations.authz){
    window.authorizations.remove(key)
  }
  for(key in window.swaggerUi.api.clientAuthorizations.authz){
+    window.swaggerUi.api.clientAuthorizations.remove(key)
   }
  window.enabledScopes = null;
  $('.api-ic.ic-on').addClass('ic-off');
  $('.api-ic.ic-on').removeClass('ic-on');

  // set the info box
  $('.api-ic.ic-warning').addClass('ic-error');
  $('.api-ic.ic-warning').removeClass('ic-warning');

  // logout from IdP and remove IdP cookie
  $.ajax({

    url: 'https://mysecuritytokenservice.com/v1/identity/connect/endsession',
    type: 'GET',
    crossDomain: true,
    dataType: 'jsonp'
});

}
```

**Comment by domaindrivendev** [comment]
First and foremost, SB is a Swagger generator.

For the UI and associated OAuth2 support, I'm leveraging the community developed swagger-ui (https://github.com/swagger-api/swagger-ui). So, this enhancement request really belongs there.
