### ISSUE TITLE
Wrong generated model by Swagger

### ISSUE THREAD

**Issue by ngallo** [domaindrivendev/Swashbuckle#561]
My application implements a `Package` class which has an `Id` property of `long` type.

My API returns the Package class and swagger is generating the Model for it.  However it is generating the wrong type for the property `Id`, it is showing that my `Id` is of `integer` type instead of `long` type. 

Issue is not restricted to the generated model, as JSON returned by means of Swagger have wrong value in the property `Id` as well.
Whilst calling the same API via Browser or .NET WebClient it works, so problem looks related to swagger.

![swagger](https://cloud.githubusercontent.com/assets/3101667/11019977/0cc1f1f2-8608-11e5-973b-2a7720b68218.jpg)

**Comment by domaindrivendev** [comment]
Take a look the DataTypes section in under the Swagger specification - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types. You'll see that a "long" (which "is" still an integer, just a 64bit version) is described in the spec as an "integer", with format set to "int64")
