### ISSUE TITLE
Custom request header

### ISSUE THREAD

**Issue by goldytech** [domaindrivendev/Swashbuckle#569]
Hi,
I want to apply custom request header in my generated swagger ui. I had utilized `IOperationFilter`for it
Here is my code of the same `

public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
           
            operation.parameters?.Add(new Parameter
            {
                description = "Every API must have client token in request header ",
                name = "UserToken",
                @in = "header",
                required = true
            });
        }
`

I've also added the required code in Swagger.config file 
` c.OperationFilter<ClientTokenFilter>();`

But with this I'm not getting any UI for api operations.
Can anyone guide where I'm going wrong ?

Thanks

**Comment by domaindrivendev** [comment]
The client-side JavaScript is blowing up because your filter is causing an invalid Swagger document to be returned from the server. When describing parameters, "type" is a required field. Try the following:

    operation.parameters?.Add(new Parameter
    {
        description = "Every API must have client token in request header ",
        name = "UserToken",
        @in = "header",
        type = "string",
        required = true
    });
