### ISSUE TITLE
Api key header seems to be ignored

### ISSUE THREAD

**Issue by jochenvanwylick** [domaindrivendev/Swashbuckle#571]
I've configured swagger as follows:

```
c.ApiKey("apiKey")
    .Description("API Key Authentication")
    .Name("apiKey")
    .In("x-ht-apikey");
```

However - this does not seem to influence the requests being sent from the swagger UI - even after setting the Api Key at the top field. I was expecting to see a `x-ht-apikey` in the HTTP headers for the request.

Did I misunderstand how this functionality works or might this be a bug in Swagger as suggested [here] ( http://stackoverflow.com/questions/16899515/how-to-get-swagger-to-send-api-key-as-a-http-instead-of-in-the-url )?

**Comment by jochenvanwylick** [comment]
Seems to have been reported before - and PR is already there. Feel free to close this issue.

**Comment by domaindrivendev** [comment]
There's two issues here. Firstly, you're using it a little incorrectly - in your case, it should look as follows:

    c.ApiKey("apiKey")
        .Description("API Key Authentication")
        .Name("x-ht-apikey")
        .In("header");

Secondly, this only affects the Swagger JSON document that's generated to describe your service. However, the swagger-ui (https://github.com/swagger-api/swagger-ui), which is a consumer of that JSON, doesn't currently provide automatic support for "apiKey" schemes in the service description.   

So, to get this working, you'll need to provide you're own version of the swagger-ui's index.html (as described here - https://github.com/domaindrivendev/Swashbuckle#provide-your-own-index-file) and configure your API key with the following JavaScript snippet:

      function addApiKeyAuthorization(){
        var key = encodeURIComponent($('#input_apiKey')[0].value);
        if(key && key.trim() != "") {
            var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("ApiKey", key, "header");
            window.swaggerUi.api.clientAuthorizations.add("ApiKey", apiKeyAuth);
            log("added key " + key);
        }
      }

      $('#input_apiKey').change(addApiKeyAuthorization);

I've just confirmed that this works locally.

Hopefully, the swagger-ui will be updated soon to support this being driven 100% by the Swagger description ...
