### ISSUE TITLE
weird issue occuring after deployment to pother environment

### ISSUE THREAD

**Issue by VisualBean** [domaindrivendev/Swashbuckle#574]
I have the following Route
<code> 
    .EnableSwaggerUi("documentation/{*assetPath}", c =>
</code>
Which works perfectly on my machine, no problems at all.

But when I deploy to our test environment - I get the following message
>500 : { "Message": "An error has occurred." } /api/swagger/docs/v1

The deployment is to `default web site/api`

Any help as to why this happens?
</code>
Which works perfectly on my machine, no problems at all.

But when I deploy to our test environment - I get the following message
<code> 500 : { "Message": "An error has occurred." } /api/swagger/docs/v1 </code>

The deployment is to <code>default web site/api </code>

Any help as to why this happens?

**Comment by monish001** [comment]
Same error for me as well when I deployed the API project to server. Locally it works perfect.
On the server, I checked that XmlComments.xml file is not getting generated in my case. I am still looking for the actual cause.

**Comment by domaindrivendev** [comment]
I can't really help here without additional information. Can you provide the full stack trace for the exception?

**Comment by VisualBean** [comment]
There is no exception. The header is just not added when pressing "try it out"  so the api returns a 401 on all responses. Checked fiddler and other inspectors. 






On Tue, Jan 26, 2016 at 9:35 AM -0800, "domaindrivendev" <notifications@github.com> wrote:












I can't really help here without additional information. Can you provide the full stack trace for the exception?

**Comment by VisualBean** [comment]
It was my fault all along, I had not named my security scheme uniformly..

**Comment by ivanslater** [comment]
Hi... I have the same problem.

What did you mean by "It was my fault all along, I had not named my security scheme uniformly.."  ? @VisualBean  ?
