### ISSUE TITLE
Bug with adding OAuth2 Security Definition

### ISSUE THREAD

**Issue by DotNetRockStar** [domaindrivendev/Swashbuckle#580]
I am using a tool that will not let my API through because it is saying my Swagger 2.0 JSON is incorrect that is generated from Swashbuckle.  After looking into it I now know why but I am unable to figure out how to fix this issue.

Here is the spec for Security Definitions: http://swagger.io/specification/#securitySchemeObject

In this spec you will see that fields "name" and "in" are REQUIRED fields, not optional.  The problem is that I cannot seem to set these fields using Swashbuckle.  Here is the code I am using to create the oAuth2 security definition:

```
c.OAuth2("dapiOAuth2")
 .AuthorizationUrl("https://login.roguecommerce.com/Login")
  .Description("OAuth2 security protocol used by this API.")
  .Flow("application")
  .Scopes(d =>
  {
    d.Add("RegisteredUser", "Assigned to users of an application if they are registered.");
    d.Add("Admin", "Assigned to the users of an application if they are an administrator. This role can only be granted by an existing administrator");
    d.Add("SuperAdmin", "Assigned to the users of an application with the highest permission. This role can only be granted by an existing super administrator.");
})
  .TokenUrl("https://api.roguecommerce.com/oAuth2/token");
```

There does not seem to be anywhere to specify "in" and "name" fields for this and it is producing invalid swagger JSON.
How can I fix this?  Is it a bug or am I just not seeing where to add it?

Here is the JSON it is producing
```
 "securityDefinitions":{  
      "dapiOAuth2":{  
         "type":"oauth2",
         "description":"OAuth2 security protocol used by this API.",
         "flow":"application",
         "authorizationUrl":"https://login.roguecommerce.com/Login",
         "tokenUrl":"https://api.roguecommerce.com/oAuth2/token",
         "scopes":{  
            "RegisteredUser":"Assigned to users of an application if they are registered.",
            "Admin":"Assigned to the users of an application if they are an administrator. This role can only be granted by an existing administrator",
            "SuperAdmin":"Assigned to the users of an application with the highest permission. This role can only be granted by an existing super administrator."
         }
      }
```

I have also noticed, since adding oAuth2 security definition, that the swagger ui now says "Invalid" at the bottom.  When I click it I get the following:
```
[{"level":"error","domain":"validation","keyword":"oneOf","message":"instance failed to match exactly one schema (matched 0 out of 6)","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/securityDefinitions/additionalProperties"},"instance":{"pointer":"/securityDefinitions/dapiOAuth2"}}]
```

Thanks!

**Comment by domaindrivendev** [comment]
I could be wrong, but I don't believe the lack of "name" and "in" is invalid Swagger. It's my understanding that they're only applicable to "apikey" schemes, hence why the builder doesn't allow you to specify them. In fact, if you look at the oath2 sample at the same link you provided, you'll see those fields are not provided.

So, it must be something else that's causing the issue. I'm not at my dev environment right now but will try check out your config later

**Comment by DotNetRockStar** [comment]
Ah.  You are right.  I totally spaced on the "Validity" column there.  Cool man, thanks for the response.  I'll close this one up.
