### ISSUE TITLE
error opening ui 

### ISSUE THREAD

**Issue by lucamorelli** [domaindrivendev/Swashbuckle#581]
Hi, I just added the rc1 version to an aurelia app, configured startup  and tried to open the ui and I see this

![untitled](https://cloud.githubusercontent.com/assets/127777/11681349/af057196-9e5e-11e5-91a9-debb3ed84ce7.png)

I suppose that the error is:
An unhandled exception occurred while processing the request.</h1>
 <div class="titleerror">NotSupportedException: Unbounded HTTP verbs for path &#x27;api/Attivita/GetLatest/{last}&#x27;. Are you missing an HttpMethodAttribute?</div

but this is the declaration of the action inside the controller

        [Route("[action]/{last:int}")]
        [HttpGet("{last}")]
        public IEnumerable<UltimaAttivitaVm> GetLatest(int last)
        {

am I missing something?

**Comment by nickverschueren** [comment]
Hi, I had the same issue. In our code this was because we had a RouteAttribute both on the controller class and on each action. The issue was solved by putting the full route on each action and removing the attribute from the class.
The RouteAttribute is now also used to replace the RoutePrefixAttribute from MVC5, but this usage does not seem to be supported by Ahoy right now.

**Comment by domaindrivendev** [comment]
@lucamorelli - what is the exact URI that you want expose the GetLatest action with? The combined use of RouteAttribute and HttpGetAttribute seems a little odd to me. If my understanding of those attributes is correct, they're creating two different paths to the same action.

The former creates the "/GetLatest/{last}" and the latter "{last}". Furthermore, a verb constraint is only applied in the second case meaning that the first can actually be invoked via ANY of the HTTP verbs. So, you're example above actually exposes the following routes to that one action:

GET http://<baseURI>/GetLatest/{last}
POST http://<baseURI>/GetLatest/{last}
PUT http://<baseURI>/GetLatest/{last}
DELETE http://<baseURI>/GetLatest/{last}
GET http://<baseURI>/{last}

If you try any one of these through curl or postman, you'll be able to call the action. I'm not sure if this is the desired result but it's this ambiguity that Swashbuckle/Swagger is complaining about - it requires a single canonical URI template per operation.

Again, I'm not sure what you're intention is but if you just want to expose a GET to "GetLatest/{last}", then you could simply do the following:

    [HttpGet("[action]/{last}")]
    public IEnumerable<UltimaAttivitaVm> GetLatest(int last)
    {
        ...
    }

**Comment by Abrissirba** [comment]
I had the same issue but in my case it was because I accidentally had two HttpGet attributes on the same controller

**Comment by tinhtooaung** [comment]
I am having the same issue. Remove route attribute from controller solve the problem. but test project seems to have Route Attribute on the controller.

**Comment by domaindrivendev** [comment]
I'm still not convinced this is a Swashbuckle issue. Will close for now but feel free to re-open if you have an argument to the contrary

**Comment by kudoz83** [comment]
Came across this thread today while googling the same issue.  I think if anything the error message isn't specific enough.  I realized that my issue was I had public methods in my controller that had no verb assigned...  This happened as a result of my code pattern where all of my controllers inherit from a custom, intermediate base controller with some helper functions attached.   I resolved the issue by making all of those methods protected instead of public.

**Comment by freshdev1** [comment]
So I had the same problem today and the resolution was simple... I had the following two GET attributes on the Controller Action:
```
[HttpGet]
[HttpGet("id/{id?}")]
```
While the first one is understandable to WebApi. It is not understandable to Swagger for some reason. I fixed the issue after changing it to this:
```
[HttpGet("")]
[HttpGet("id/{id?}")]
```

Hope this helps someone.

**Comment by salimdeveloper** [comment]
I had the same problem , and one of my Method in the controller did not had any Http Attributes in it.

**Comment by aaronralls** [comment]
Be sure to check the controller and base class for any public methods.

I had a public method in my base class that I had to change to protected.

**Comment by pintojc** [comment]
If using DI on the controller constructor (e.g. .net core + DBContext) - will still have an issue - constructor doesn't have an HTTP Attribute.  Anyone else try this or notice this, and have a workaround?

**Comment by aaronralls** [comment]
I have not had an issue with DI and I'm using .Net Core.

**Comment by bsell93** [comment]
Is it possible to have the controller-level route and tell swagger to simply ignore any methods that don't have the HTTP attribute?

**Comment by bsell93** [comment]
Just figured out how to do this... By setting DocInclusionPredicate in my setup I was able to ignore methods that don't have a specified HttpMethod.

The source code that helped me come to this conclusion: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs#L84

My fix:
```
services.AddSwaggerGen(c =>
{
    c.DocInclusionPredicate((docName, apiDesc) =>
    {
        if (apiDesc.HttpMethod == null) return false;
            return true;
    });
});
```

Also important to note that I am using dotnet core sdk: 1.0.0-rc4-004771, swagger aspnetcore v1.

**Comment by aaronralls** [comment]
@bsell93 Did you do that because you had some public methods in your controllers?

**Comment by bsell93** [comment]
@aaronralls yeah.. Basically. I was inheriting from a BaseController that had public methods.

**Comment by aaronralls** [comment]
@bsell93 Do you control that base class? If so those should probably be Protected vs. Public.

**Comment by bsell93** [comment]
@aaronralls I do. That would make sense except then I wasn't able to properly test my base class.

**Comment by prasanna32** [comment]
@bsell93 's solution to add DocInclusionPredicate worked for me. Thank you.
