### ISSUE TITLE
No embedded resources in Swashbuckle.Core

### ISSUE THREAD

**Issue by hlubovac** [domaindrivendev/Swashbuckle#582]
I couldn't figure out some of the runtime internals, so I decided to plug-in this library into my project and step-through.

I downloaded 5.2.2 source code as a zip file. In isolation, it compiles. Its Tests > WebHosts site manifests the same problem as described below.

The /swagger/ui/index webpage loads with just the green header and empty url/key textboxes. The browser reports only these files downloaded:
index
typography-css
swagger-oauth-js	
screen-css

All of these are reported as not-found:
reset-css
jquery-1-8-0-min-js
jquery-slideto-min-js
jquery-wiggle-min-js	
jquery-ba-bbq-min-js	
handlebars-2-0-0-js
underscore-min-js
backbone-min-js
swagger-ui-min-js
highlight-7-3-pack-js	
marked-js
print-css
logo_small-png
droid-sans-v6-latin-700-woff2
droid-sans-v6-latin-regular-woff2
droid-sans-v6-latin-regular-woff
droid-sans-v6-latin-700-woff	
droid-sans-v6-latin-700-ttf
droid-sans-v6-latin-regular-ttf

/Application/SwaggerUi/CustomAssets folder contains only 5 files (other than 4 that successfully download, also "discoveryUrlSelector.js"). No other files anywhere in the project/solution.

What could be the problem?

Thanks.

**Comment by hlubovac** [comment]
The fact that the project might be missing either some files or setup instructions still stands. I came back to say that I found a work-around that serves my particular goal, and that I'm no longer in big need of finding a solution for the above.

Namely, I downloaded the "dist" of the swagger-ui, and now I use that to point to my API, which is now [temporarily] referencing Swashbuckle.Core project. So, now I'm able to step-through the Core, with the goal of trying to figure out which data exactly to feed it with (and via which object), so that I get it to spit out swagger-json in the way that I expect it to be.

Thanks for the beautiful code!

**Comment by benlaan** [comment]
I have discovered the same issue. This has occurred when I use the clone repository only. works fine with the nuget package

**Comment by robhoffmann32** [comment]
I have the same problem. Where do you find the "dist"?

**Comment by benlaan** [comment]
@robhoffmann32 you need to do a recursive get with git. It will pull down swagger

**Comment by hlubovac** [comment]
"dist" is a folder name of https://github.com/swagger-api/swagger-ui
