### ISSUE TITLE
License Type

### ISSUE THREAD

**Issue by goldytech** [domaindrivendev/Swashbuckle#583]
Which type of license does this project has ? I couldn't find any specific type of license in the repo

**Comment by rbeauchamp-lendingtree** [comment]
See https://github.com/domaindrivendev/Swashbuckle/blob/master/LICENSE

**Comment by domaindrivendev** [comment]
Note ... I just updated to GPL V3

**Comment by bradygaster** [comment]
@domaindrivendev can we discuss this soon?

**Comment by bhameyie** [comment]
#229 states that the license is BSD and so does the nuget package's license information. Is that incorrect?
