### ISSUE TITLE
Owin.EnableSwaggerUi("sandbox/{*assetPath}"... fails to route

### ISSUE THREAD

**Issue by JohnGalt1717** [domaindrivendev/Swashbuckle#585]
If I leave it without a custom path, it works fine. However as soon as I put in a custom path it fails per above.

I have it like this:

}).EnableSwaggerUi("sandbox/{*assetPath}", c =>
            {
<config here>
            });

But no dice. What am I doing wrong?

**Comment by domaindrivendev** [comment]
There's been a few dup's around this - #458, #299, so I'm going to close this one.

In a nutshell ... when you customize the routes, you need to browse to the canonical URL route for the swagger-ui, including "index/html". So, in your case you have to navigate to the following URL to see the swagger-ui:

/sandbox/index.html
