### ISSUE TITLE
TextArea for formData

### ISSUE THREAD

**Issue by kongres** [domaindrivendev/Swashbuckle#587]
I want to have textarea for one of my parameters which accept JSON model.
Please note I use multipart/form-data for my request.
My definition is 
```csharp
            operation.parameters.Add(new Parameter
            {
                name = "file",
                required = true,
                type = "file",
                @in = "formData",
                description = "File with following formats: pdf, png, jpg, bmp."
            });

            operation.parameters.Add(new Parameter
            {
                name = "data",
                required = false,
                @in = "formData",
                type = "object",
                schema = new Schema() { @ref = "#/definitions/SomeModel", type = "object"},
                description = "Desciption",
                
            });
```

And what I have on UI:
![image](https://cloud.githubusercontent.com/assets/7360716/11947973/310bbb4e-a87f-11e5-940e-b244bec44fac.png)

I want to show textarea for 'data' parameter instead of input. I've tried a lot of different ways but unsuccessfuly. Is it possible? How?

**Comment by g2petter** [comment]
I might be coming at this from a wrong angle, but it seems to me like the fix suggested by @HarelM doesn't work. By adding the one parameter as body when you still have one or more other parameters as formData is against the spec, ref. this discussion: https://github.com/swagger-api/swagger-editor/issues/889

>Since form parameters are sent in the payload, they cannot be declared together with a body parameter for the same operation.

So I guess @kongres' question remains: how can you have a formData parameter use a textarea that behaves like a body textarea?

**Comment by justinhorner** [comment]
Very old, but just in case anyone else stumbles across this problem, I used [Javascript injection](https://github.com/domaindrivendev/Swashbuckle.WebApi?tab=readme-ov-file#injecting-custom-content) to 'fix' this.  

```javascript

// get the input element by name (or another unique attribute)
let _input = $('input[name="uniqueName"]');

var $txtArea = $('<textarea />');
// set/re-set desired attributes
$txtArea.attr('class', _input.attr('class'));
$txtArea.attr('name',  _input.attr('name'));
$txtArea.attr('placeholder',  _input.attr('placeholder'));
$txtArea.attr('id',  _input.attr('id'));
$txtArea.val(_input.value);

// replace
_input.replaceWith($txtArea);
```
