### ISSUE TITLE
Bug: Xml comments not picked up when using an array in the list of params in the controller

### ISSUE THREAD

**Issue by tynor88** [domaindrivendev/Swashbuckle#588]
When having an attribute in the param list in the controller 

```csharp
[BindUnknownParams] KeyValuePair<string, string>[] metadata = null
```
Like this:
```csharp
        /// <summary>
        /// Gets a list of data by it's metadata key/value pairs
        /// </summary>
        /// <param name="timeZone">The timezone for which the requested data will be returned in (default:UTC)</param>
        /// <param name="metadata">Metadata key-value pairs to search for in the format: key=value</param>
        /// <returns>A list of datasets</returns>
        [Route("Test")]
        public async Task<IHttpActionResult> Test(ETimeZone timeZone = ETimeZone.UTC, [BindUnknownParams] KeyValuePair<string, string>[] metadata = null)
        {
            return Ok();
        }
```

Swashbuckle does not pickup the Xml document (Summary, Remarks etc.)

![image](https://cloud.githubusercontent.com/assets/2877439/11957377/bc3337fa-a8c1-11e5-97cf-8aa7315865ae.png)

The description/summary properties in the Operation object are null aswell, when creating an OperationFilter:

![image](https://cloud.githubusercontent.com/assets/2877439/11957428/13c7d408-a8c2-11e5-874b-1b78fc7a4fe9.png)

If the attribute is not there, the xml comments are picked up with no problems. Any idea how to fix this?

**Comment by tynor88** [comment]
Might be related to https://github.com/domaindrivendev/Swashbuckle/issues/227 but the issue has been closed.

@niemyjski did you find a work-around?

**Comment by tynor88** [comment]
Changing it to IEnumerable instead of an array fixes the problem, so it's not the attribute, but the array causing the issue like in #227.

This works:
```csharp
[BindUnknownParams] IEnumerable<KeyValuePair<string, string>> metadata = null
```

**Comment by domaindrivendev** [comment]
See 5.3.1
