### ISSUE TITLE
Multiple controllers with the same route

### ISSUE THREAD

**Issue by MikeAndrewsZengenti** [domaindrivendev/Swashbuckle#591]
I've got multiple controllers but they use the same Route.

For example:

TestController uses route "api/test"

HealthCheckController uses "api/test/healthcheck"

However Swagger displays them as "Test" and "HealthCheck" despite the routes being the same. I was wondering if there is a way to filter them so that they can be displayed under the same "Test" name.

I tried testing with GroupActionsBy, but couldn't seem to figure out a way to get it to display as described above.

Regards,

Mike

**Comment by domaindrivendev** [comment]
c.GroupActionsBy(apiDesc => apiDesc.RelativePath.Split('/', '?').First());
