### ISSUE TITLE
Is PATCH supported by Swashbuckle?

### ISSUE THREAD

**Issue by realrover** [domaindrivendev/Swashbuckle#595]
Hi there,
I tried to use PATCH with Swashbuckle and noticed that generated Curl code contains wrong Content-Type field in the header:
curl -X PATCH --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"Operations\": [
    {
      \"value\": \"UPDATED COMMENTS\",
      \"path\": \"/comments\",
      \"op\": \"replace\",
    }
  ]
}" "http://170.28.8.137/accounts/X23456" 

Shouldn't be "Content-Type: application/json-patch" instead of "Content-Type: application/json"?
Thanks.

**Comment by domaindrivendev** [comment]
The "json-patch" media type is a specific JSON format for applying changes to a resource as an array of patch operations. It should be used in combination with the PATCH verb but the use of PATCH on it's own does NOT imply that media-type.

If your operation supports this format, then you need to add it to WebApi as a "custom media formatter" - http://www.asp.net/web-api/overview/formats-and-model-binding/media-formatters

If you do this correctly, then Swashbuckle and hence Swagger will describe the operation with the correct media type.
