### ISSUE TITLE
XML Comments in 6.0.0-rc1-final

### ISSUE THREAD

**Issue by mbeckenbach** [domaindrivendev/Swashbuckle#597]
Hi, 

is it possible to get xml comments working in 6.0.0-rc1-final with asp.net 5?

I've found this blog post:
http://damienbod.com/2015/12/13/asp-net-5-mvc-6-api-documentation-using-swagger/

But it does not really work for me.

thx

**Comment by damienbod** [comment]
Hi

What's not working?

Greetings Damien

**Comment by damienbod** [comment]
See the comment from @domaindrivendev for another example:

https://github.com/domaindrivendev/Ahoy/issues/46

Greetings Damien

**Comment by mbeckenbach** [comment]
Hi Damien, 

thanks for your fast reply. Not working means, that i simply did not see any comments in swagger ui.

I found out why now. The reason was, that even if i set produce outputs on build and trigger a manual build, the file is only beeing read if i completely restart the application. 

Any idea how to get docs into the ui without "produce outputs on build"? Because the current behavior breaks the great edit and refresh behavior of asp.net 5.

Greetings Max

**Comment by domaindrivendev** [comment]
This feature is not currently supported. Please feel free to investigate though and I'd be happy to accept a PR if you can figure it out.
