### ISSUE TITLE
Swashbuckle to base project

### ISSUE THREAD

**Issue by manishagupta81** [domaindrivendev/Swashbuckle#604]
Does it need to be added to every individual project, or can we add to the base project?

**Comment by domaindrivendev** [comment]
Can you please elaborate - I've no idea what your asking here

**Comment by manishagupta81** [comment]
I want to have SwaggerConfig.cs file only at base project like Common Project where i have other common stuff eg: logger , dependency etc.
I don't want every developer to implement swagger for their API in the solution. I want swagger to be at the common project

**Comment by manishagupta81** [comment]
I tried this in the commin project and it works fine. Only problem is it always displays one header (in my case .v1.Http.RAC) for all documents. Looks the like the first site being loaded
  .EnableSwagger(c =>
                {
         
                    c.SingleApiVersion("v1", ".v1.Http.Employee");
                    //  c.SingleApiVersion("v1", ".v1.Http.Account");
                    c.SingleApiVersion("v1", ".v1.Http.CRM");
                    c.SingleApiVersion("v1", ".v1.Http.BSP");
                    c.SingleApiVersion("v1", ".v1.Http.AOR");
                    c.SingleApiVersion("v1", ".v1.Http.RAC");

**Comment by manishagupta81** [comment]
I tested . I can have swaggerconfig.cs at one common project and it works for all Apis, But how can I find the right URL to display as the header in swagger UI. because right now since there is one SwaggerConfig.cs, I had to generalize the name 

   //  c.SingleApiVersion("v1", ".v1.Http.X");
                    //    c.SingleApiVersion("v1", ".v1.Http.A");
                    //    c.SingleApiVersion("v1", "v1.Http.B");
                     //   c.SingleApiVersion("v1", ".v1.Http.C");
                     //   c.SingleApiVersion("v1", ".v1.Http.D");
                       c.SingleApiVersion("v1", "Swagger Documents");

**Comment by manishagupta81** [comment]
![image](https://cloud.githubusercontent.com/assets/16672662/12337490/5bf26b30-bad8-11e5-8e86-e4e02c3b24cf.png)

**Comment by domaindrivendev** [comment]
I'm closing this issue because it's really up to you to figure out how/where Swashbuckle fits into your stack of dependencies.
