### ISSUE TITLE
Using an embedded resource XML file for the XML Comments

### ISSUE THREAD

**Issue by ghost** [domaindrivendev/Swashbuckle#607]
Hello, we're attempting to use Swashbuckle with our API but don't want to expose the XML file Visual Studio generates, and store it as an embedded resource in the project instead. Looking at the code, it seems like there's no way to pass the Logical Name of the file into c.IncludeXmlComments, as the XPathDocument being created in ApplyXmlActionComments and ApplyXmlTypeComments is simply handed a string and assumes a file path.

Is there any way to work around this so we can use the information in that generated XML file?

**Comment by heldersepu** [comment]
You should be able to do that with the latest version... 
there is an overload to the IncludeXmlComments that takes an XPathDocument parameter

**Comment by heldersepu** [comment]
Here is a link to my test:
https://github.com/heldersepu/SwashbuckleTest/commit/bc77540bb82c895d902ed5f3351b7b483d245dae
There I'm reading the XML from the embedded XML file

**Comment by domaindrivendev** [comment]
Closing as per @heldersepu's comment. IncludeXmlComments can now accept a Func for creating the XPathDocument. So, you could easily provide a Func implementation that retrieves your document from an assemblies embedded resources.
