### ISSUE TITLE
Namespaced versioning API uses incorrect URL in Swagger UI

### ISSUE THREAD

**Issue by jamesmundy** [domaindrivendev/Swashbuckle#611]
I have an API which is versioned using namespaces, like so:

```
namespace Project.Controllers.V1
{
  public class LocationController : BaseController
  {
    [HttpsRequired, HttpGet]
    public async Task<ApiResponse> Process(string sessionToken, string id)
````

This method is therefore available at *api/v1/Location/Process*

Swagger is setup to deal with multiple versions like so:

```
c.MultipleApiVersions(
                    (apiDesc, version) =>
                    {
                      var path = apiDesc.RelativePath.Split('/');
                      var pathVersion = path[1];

                      return CultureInfo.InvariantCulture.CompareInfo.IndexOf(pathVersion, version, CompareOptions.IgnoreCase) >= 0;
                    },
                    vc =>
                    {
                      vc.Version("v1", "Foundbite Client API V1");
                    });
```

Which displays all the methods under the correct version number.

However when the Swagger UI is generated the methods have the full namespace and controller name in the url: *api/V1.Location/Process*

Is there any easy way I can edit the method urls to replace the "." with a "/"?

I posted [this question to SO](http://stackoverflow.com/questions/34861229/using-swagger-swashbuckle-with-a-namespace-versioned-asp-net-webapi) but this seems to be where I should have placed my question.

**Comment by domaindrivendev** [comment]
Have a read through #51 and #144 as I believe you're likely experiencing the same issue.

If you don't want to read though them all - here's the summary ...

I'm assuming you've created your own version of IHttpControllerSelector to support controller selection based on the "version" route parameter? Depending on the implementation, this is most likely breaking WebApi's built-in metadata layer - "ApiExplorer" and subsequently Swashbuckle.

This is one of the reasons why the WebApi team recommend using attribute routing over a custom IHttpControllerSelector to implement versioning:

http://blogs.msdn.com/b/webdev/archive/2014/08/22/customizing-web-api-controller-selector.aspx
