### ISSUE TITLE
Controller not displayed whith namespaced versioning API

### ISSUE THREAD

**Issue by alfhv** [domaindrivendev/Swashbuckle#613]
Hello,
I have aa API using versioning on namespace like:

Controllers\
---v1\
-----ContactsController
-----ProductsController
---v2\
-----ProductsController

namespaces are named as:
MyApi.Controllers.v1 and MyApi.Controllers.v2

I'm enabling versioning as:

    config.Services.Replace(typeof(IHttpControllerSelector), new VersionedApiControllerSelector(config));
    config.Services.Replace(typeof(IApiExplorer), new VersionedApiExplorer(config));
    config.DependencyResolver = new DependencyResolver(rootContainer);
    ApiVersioning.Configure(config).ConfigureRequestVersionDetector<DefaultRouteKeyVersionDetector>();

versions are also registered on

    public void Configuration(IAppBuilder app)
    (...)
    config.EnableSwagger(c =>
    {
        (...)
        vc =>
        {
            vc.Version("v2", "Swashbuckle Dummy API V2");
            vc.Version("v1", "Swashbuckle Dummy API V1");
        });
    }
    (...)
    }

Everything works almost ok, but I have an issue on swagger UI, the problem is that Products controller is not available for version v1, only on v2. If I rename it to something else then I have it displayed on swagger UI

I was looking at source code on 
    namespace SDammann.WebApi.Versioning
    public class VersionedApiControllerSelector : IHttpControllerSelector {
    public IDictionary<string, HttpControllerDescriptor> GetControllerMapping() {}

This method is creating a dictionary with a MultiVersionHttpControllerDescriptor, on this dictionary, if 2 controllers have the same name, then we will have only one entry, one key related to all version of controllers, and the latest version is on top of list, and is this latest version the only one available on swagger UI.
could be this the reason why only one of them is displayed on UI ?

thanks

**Comment by domaindrivendev** [comment]
Have a read through #51 and #144 as I believe you're likely experiencing the same issue.

If you don't want to read though them all - here's the summary ...

I'm assuming you've created your own version of IHttpControllerSelector to support controller selection based on the "version" route parameter? Depending on the implementation, this is most likely breaking WebApi's built-in metadata layer - "ApiExplorer" and subsequently Swashbuckle.

This is one of the reasons why the WebApi team recommend using attribute routing over a custom IHttpControllerSelector to implement versioning:

http://blogs.msdn.com/b/webdev/archive/2014/08/22/customizing-web-api-controller-selector.aspx
