### ISSUE TITLE
I can't see anything in swagger/ui/index

### ISSUE THREAD

**Issue by EasonWen** [domaindrivendev/Swashbuckle#615]
I have two project like this -> 

![1453362522651](https://cloud.githubusercontent.com/assets/10205829/12474537/e60e5526-c056-11e5-8166-8c4e79119c87.jpg)

LunchKingSite.Web is main web site , and I inistall Swashbuckle in my LunchKingSite.WebAPI .
now I open the page like this ->
![1453362698049](https://cloud.githubusercontent.com/assets/10205829/12474524/d2c1bbfc-c056-11e5-8754-b7e66952d5a9.jpg)
Any idea ?

**Comment by billpratt** [comment]
Can you share the contents of your SwaggerConfig.cs? I wrote a few blog posts about setting up Swashbuckle. Feel free to take a look and see if that helps: http://wmpratt.com/swagger-and-asp-net-web-api-part-1/

**Comment by plkumar** [comment]
+1 same here...

I didn't change anything on the default SwaggerConfig.cs versions as shown below.

  <package id="Swashbuckle" version="5.2.2" targetFramework="net452" />
  <package id="Swashbuckle.Core" version="5.2.2" targetFramework="net452" />

**Comment by domaindrivendev** [comment]
Take a look at your JS console - I'm guess the UI JavaScript is blowing up for some reason. Post yoru findings and we'll see if we can take it from there.

**Comment by EasonWen** [comment]
Thanks guys.. @domaindrivendev  you are right! when I dowload **Swashbuckle** from https://github.com/domaindrivendev/Swashbuckle (not use nuget) , and swagger-ui floder was **empty**,
so I got it form https://github.com/swagger-api/swagger-ui , and rebuild it  finally counlt work :)

**Comment by jon-peel** [comment]
Hi @billpratt 
I have followed your blog (it was actually the first result I had when I searched how to set this up initially).
Unfortunately, it doesn't work 😞
![image](https://user-images.githubusercontent.com/14907576/139533134-3e7eccc6-efbc-4637-b725-aa99290cc29b.png)
