### ISSUE TITLE
Child Collections of ODataController in Swagger UI

### ISSUE THREAD

**Issue by nealeduncan** [domaindrivendev/Swashbuckle#616]
Child collections are not shown for ODataControllers.  

In the example here: http://swashbuckleodata.azurewebsites.net/swagger/ui/index

The Customers ODataController resource does not show that in the GET, that Orders is available.  It only shows primitive types (string, int etc).  

The ApiController resource shows child resources (in the example Projects is a child collection of Client GET ApiController).

Can child collections be added to ODataControllers please?

**Comment by domaindrivendev** [comment]
Looks like this is specific to the Swashbuckle.OData extension. You should post this issue there instead - https://github.com/rbeauchamp/Swashbuckle.OData
