### ISSUE TITLE
Support for polymorphics types

### ISSUE THREAD

**Issue by oyegorov** [domaindrivendev/Swashbuckle#617]
Swashbuckle (I'm using version 5.2.1) doesn't seem to support polymorphic return types.
(e.g. controller operation:  *DeviceBase[] GetDevices()*, where *DeviceBase* has a number of child classes)

In this case, the generated Swagger document only contains *DeviceBase* definition.
I looked at the source code and there doesn't seem to be any logic to include the children (although Swagger specification supports polymorphic types through the use of *allOf* attribute).

Any advice?

**Comment by domaindrivendev** [comment]
Closing as this is a dup of #534. In summary, what you're looking for is the "oneOf" construct as opposed to the "allOf". The former is NOT supported by the Swagger specification.
