### ISSUE TITLE
'console' is undefined in swagger/ui/index with IE10

### ISSUE THREAD

**Issue by xlpan** [domaindrivendev/Swashbuckle#619]
I am open the page of Swagger UI with IE10, the broswer popup a error "'console' is undefined", if I press F12 to open the developers tool and refresh the page, it is normal. 
![consoleerror](https://cloud.githubusercontent.com/assets/16876006/12546395/7cbf5ca6-c384-11e5-8fea-60b79cbeb85c.jpg)

**Comment by jreames9** [comment]
I've run into this as well. I'll bet it is related to your IE running in compatibility mode, i.e. really old mode so new functions will not work correctly. Check your compatibility view settings and try unchecking the display intranet sites in compatibility view and use Microsoft compatibility lists. Also make sure your domain isn't in there. 

I also add a meta tag into html pages to force IE to run in Edge mode so it doesn't try to run the page using the out dated engines,

<meta http-equiv="X-UA-Compatible" content="IE=edge">

**Comment by domaindrivendev** [comment]
I'm going to close this as it's really an issue for swagger-ui rather than SB. In fact, looks like it's already being tracked and is going to be fixed:

https://github.com/swagger-api/swagger-ui/issues/1355
