### ISSUE TITLE
Swashbuckle and comments in DLL

### ISSUE THREAD

**Issue by mike2859** [domaindrivendev/Swashbuckle#624]
Hello everyone,

I wonder if it is possible to have the comments of the classes found in the DLL in Swashbuckle.

For example: I have a class entity in another project that is guided and which is referenced in the project (DLL), when I go to http://url/swagger I have no comments found in this class.

Thanking you in advance for your help

Mickaël

**Comment by billpratt** [comment]
Assuming you enabled the generation of XML documentation for your DLL, when you build your web app the XML file for that DLL should be in the bin directory. You'll have to include that XML file in SwaggerConfig.cs

For example, if your DLL is named Foo.dll, you should see Foo.xml in the web app's bin directory. Tell Swashbuckle to include this by adding the line

c.IncludeXmlComments($@"{System.AppDomain.CurrentDomain.BaseDirectory}\bin\Foo.xml");

**Comment by mike2859** [comment]
Great It's working.

Thank you very much
