### ISSUE TITLE
Url http://localhost:4822/swagger/docs/v1 is case sensitive but it should not be

### ISSUE THREAD

**Issue by tomekjanicki** [domaindrivendev/Swashbuckle#625]
when I define 
config.SingleApiVersion("V1", "Api");
I got response with url http://localhost:4822/swagger/docs/V1, but there is error for http://localhost:4822/swagger/docs/v1

**Comment by darrelmiller** [comment]
Technically, as per [RFC 7230](http://tools.ietf.org/html/rfc7230#section-2.7.3), for http URLs the path is case sensitive.  Historically the Microsoft stack has ignored this and made paths case-insensitive so the current behaviour although technically correct is violating the principle of least surprise!

**Comment by domaindrivendev** [comment]
I'm happy with the "technically correct" solution. I like being a good citizen of the web :)
