### ISSUE TITLE
Nullable int is not optional in controller

### ISSUE THREAD

**Issue by cpouwels** [domaindrivendev/Swashbuckle#628]
When mapping the following route i'd expect that nullable int id parameters in controllers are optional but for some reason they are not. WebApi does accept this as optional and the token if added through a attribute (removing it doesn't help)

config.MapHttpAttributeRoutes();
config.Routes.MapHttpRoute(
	"DefaultApi",
	"api/{controller}/{id}",
	new {
		id = RouteParameter.Optional
	});

Controllers

public UsersResource GetUsers(int? id = null)

leads to 

![id optional](https://cloud.githubusercontent.com/assets/4035316/12813135/61ac8466-cb36-11e5-9204-8300427e2ceb.png)

 If anyone can help that would be great.

**Comment by domaindrivendev** [comment]
The swagger-spec doesn't support optional "path" parameters -http://swagger.io/specification/#parameterIn. If you want to support the following routes ...

/products
/products/{id}

then swagger (rightly IMO) thinks of them as two separate operations as opposed to an overloaded operation with "optional" id parameter.

**Comment by domaindrivendev** [comment]
Any reason why you can't separate into two separate action methods - seems like that would be cleaner anyway
