### ISSUE TITLE
contextpath/hostname missing from url

### ISSUE THREAD

**Issue by yaneyba** [domaindrivendev/Swashbuckle#630]
Hello,
I created a basic OWIN ASP.NET Web API2, installed SwashBuckle via Nuget, then configured the SwaggerConfig.vb file as follow:

***********************************************
Public Module SwaggerConfig
    Public Sub Register()
        Swashbuckle.Bootstrapper.Init(GlobalConfiguration.Configuration)
        SwaggerSpecConfig.Customize(Sub(c)
                                        c.IncludeXmlComments(GetXmlCommentsPath())
                                    End Sub)
    End Sub
 
    Private Function GetXmlCommentsPath() As String
        Return String.Format("{0}bin\AuthServerApi.xml",  System.AppDomain.CurrentDomain.BaseDirectory)
    End Function

End Module
***********************************************

When I hit the "Try it out!" button - On the Remote Server - to test the API, here's what I get:

http://mydevwebserver/myapi/swagger/api-docs
http://localhost:50648/swagger/api-docs

On IIS Express (Debug Mode) - works as expected
Request URL:
http://localhost:50648/api/audiences
Response Code: 200

On IIS (Release Mode) - NOT WORKING - "myapi" is missing from the URL
Request URL:
http://mydevwebserver:80/api/audiences
Response Code: 404

Thanks for your insight.

Nae

**Comment by domaindrivendev** [comment]
Closing as I believe this to be a dup of #305. Take a look and let me know if it helps
