### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by krk** [domaindrivendev/Swashbuckle#632]
JavaScript error makes UI unusable.

Produced JSON documentation contains "null" everywhere.

Head of "/swagger/docs/v1":

```
{
	"swagger" : "2.0",
	"info" : {
		"version" : "v1",
		"title" : "XXX API",
		"description" : null,
		"termsOfService" : null,
		"contact" : null,
		"license" : null,
		"vendorExtensions" : {}

	},
	"host" : "localhost:49000",
	"basePath" : null,
	"schemes" : ["http"],
	"consumes" : null,
	"produces" : null,
	"paths" : {
```

**Comment by space-alien** [comment]
Same problem here.

A workaround is to set the [NullValueHandling](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_NullValueHandling.htm) to Ignore in the JSON SerializerSettings.

However, this will obviously alter your APIs as well - any null properties will now be omitted from returned JSON.

```
public static class WebApiConfig
{
    public static void Register(HttpConfiguration config)
    {
        var jsonFormatter = config.Formatters.JsonFormatter;

        // Swagger UI is unfortunately choking without this
        jsonFormatter.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
    }
}
```

**Comment by space-alien** [comment]
Hmm, better take a look at #219. For me, this (and other issues) are caused by using a custom IContentNegotiator.

**Comment by domaindrivendev** [comment]
@krk - did you take a look at #219. Sounds like it could be the same issue. Let me know so I can close this one

**Comment by krk** [comment]
This is the same issue, thanks.
