### ISSUE TITLE
Missing F# option support for Uri parameter parsing

### ISSUE THREAD

**Issue by kbilsted** [domaindrivendev/Swashbuckle#633]
In F#

given a complex object for uri parsing

```
   [<CLIMutable>]
    type myparam =
        {
            i : Nullable<int>;
            j : int option;
            k : int;
        }
```

and a get'er

```
        [<HttpGet>]
        [<Route("/foo")>]
        member this.GetAll([<FromUri>] p:myparam) : IHttpActionResult =
```

I only see the parameters `i` and `k`

![image](https://cloud.githubusercontent.com/assets/1616338/12881538/d747d7fe-ce4a-11e5-8706-6c19a95b8210.png)

**Comment by domaindrivendev** [comment]
Unfortunately, I'm not very familiar with F# and given the other priorities for this project, it's unlikely to be something I'll get to anytime soon. However, please feel free to investigate yourself and submit a PR if you discover a suitable fix
