### ISSUE TITLE
Need a consistent strategy for finding XML comments

### ISSUE THREAD

**Issue by taschmidt** [domaindrivendev/Swashbuckle#634]
I have an app that uses Core CLR.  I took and modified some sample code which does the following:

>             var docPath = $"{_appEnv.ApplicationBasePath}\\..\\artifacts\\bin\\{_appEnv.ApplicationName}\\{_appEnv.Configuration}\\" +
                $"{_appEnv.RuntimeFramework.Identifier}{_appEnv.RuntimeFramework.Version.ToString().Replace(".", string.Empty)}\\{_appEnv.ApplicationName}.xml";
            docPath = Path.GetFullPath(docPath);

That works fine when I'm running in my dev environment.  But I'm running inside a docker container and once I do a `dnu publish` the paths are way down under approot/packages/... somewhere.  I really need a consistent way to reference XML comment paths.

**Comment by simonmurdock** [comment]
Isn't this an issue for your `GetXmlComments()` method and not Swashbuckle? Can't you write yours to look in the correct places for each environment?

**Comment by domaindrivendev** [comment]
Apologies for the cross-repo confusion - this will get cleared up soon. I think this is a 6.0 (AspNet Core) question and so you'll find the issues for that over at my Ahoy repo. Looks like a dup of the following - https://github.com/domaindrivendev/Ahoy/issues/67
