### ISSUE TITLE
How to specify the text for "info_description markdown" div

### ISSUE THREAD

**Issue by simonmurdock** [domaindrivendev/Swashbuckle#636]
This is the div below the main title on the page? I have not had much success finding an answer via google. I have edited it here manually in Chrome dev tools to illustrate the text I would like to populate exactly.

<img width="441" alt="screen shot 2016-02-09 at 00 20 09" src="https://cloud.githubusercontent.com/assets/5403478/12903860/ea49a684-cec2-11e5-832e-13584f154263.png">

This project is fantastic by the way!

**Comment by domaindrivendev** [comment]
In your SwaggerConfig.cs, apply the following:

    c.SingleApiVersion("v1", "My Super Duper API")
        .Description("Here is the text you would like to populate");
