### ISSUE TITLE
Generating bogus .json that crashes Swashbuckle.ui and validators

### ISSUE THREAD

**Issue by JohnGalt1717** [domaindrivendev/Swashbuckle#639]
With or without xml definitions the following generated json from swashbuckle:

http://qaapi.cadlearning.com/swagger/docs/v1

Crashes the entire browser. It also crashes:  http://bigstickcarpet.com/swagger-parser/www/index.html

Other online parsers/editors say that it has reached the maximum stack length.

Eventually it will display but it takes > 30 minutes and in the mean time it's litterally hanging the browser completely and the computer itself (a 6 core machine!) is getting hung too.

**Comment by VisualBean** [comment]
Please see this http://stackoverflow.com/q/35605427/1841212

**Comment by simonmurdock** [comment]
I've had the same issue with a controller which returned a serialised windows workflow object.

Luckily that particular API is not for public consumption in our app

**Comment by domaindrivendev** [comment]
Going to close this as it appears to be a dup of #486.
