### ISSUE TITLE
Uncaught SyntaxError: Unexpected token %

### ISSUE THREAD

**Issue by Dzoge** [domaindrivendev/Swashbuckle#642]
Hello,

I have installed the latest version of swashbucke into my WebAPI ASP.NET project.
When launching the ui in browser (Chrome), I get a Javascript error saying:
`"Uncaught SyntaxError: Unexpected token %"`

This happens on the following line:
`oAuth2AdditionalQueryStringParams: JSON.parse('%(oAuth2AdditionalQueryStringParams)')`
of the following url:
`swagger/ui/index`

I can't get any way around it. Any help would be much appreciated.

**Comment by jreames9** [comment]
I ran into the same issue, I think it is related to the changes for 
#522 
If I added a call to EnableOAuth2Support in my SwaggerConfig it sets the parameter and I no longer get the error.

**Comment by Dzoge** [comment]
@jreames9 Thank you, it helped.

**Comment by domaindrivendev** [comment]
See 5.3.1
