### ISSUE TITLE
Filepath to long when building swashbuckle.swagger-ui

### ISSUE THREAD

**Issue by VisualBean** [domaindrivendev/Swashbuckle#648]
Node_module nesting is causing me not being able to build the project using build.bat

ASPNETCOMPILER : error ASPRUNTIME: The specified path, file name, or both are too long. The fully qualified file name m
ust be less than 260 characters, and the directory name must be less than 248 characters. 

What do I do to build my forked project?

**Comment by simonmurdock** [comment]
I thought the newer NPM builds prevented this nesting?

**Comment by VisualBean** [comment]
Fixed it by marking node_modules as hidden
