### ISSUE TITLE
v5.3.1 contains an incompatible API change

### ISSUE THREAD

**Issue by rbeauchamp-lendingtree** [domaindrivendev/Swashbuckle#650]
Hi @domaindrivendev, in v5.3.1 you released an incompatible change to the [API of Swashbuckle.Core](https://github.com/domaindrivendev/Swashbuckle/compare/v5.2.2...v5.3.0#diff-0c05e36dbde6f748e7472a1b27b8c5c9L43) and [broke Swashbuckle.OData](https://github.com/rbeauchamp/Swashbuckle.OData/issues/68) because it is using SchemaRegistry's constructor. Would you mind either reverting to the previous parameter order (preferred) or incrementing the major version if this change is necessary?

**Comment by rbeauchamp** [comment]
Thanks @domaindrivendev! Would you mind publishing a new NuGet package?

**Comment by rbeauchamp** [comment]
Thanks!
