### ISSUE TITLE
Ability to remove existing filters

### ISSUE THREAD

**Issue by dariusdamalakas** [domaindrivendev/Swashbuckle#651]
Hi,

The default [ApplyXmlActionComments](https://github.com/domaindrivendev/Swashbuckle/blob/cafa59f8fd885ac75540abe6780d2e6183c2d5b0/Swashbuckle.Core/Swagger/XmlComments/ApplyXmlActionComments.cs#L68) filter is clearing out any existing responses. That means that any [200 or 204 auto-generated responses](https://github.com/domaindrivendev/Swashbuckle/blob/922b1a42d59442a4ce3749dc24f2cefd92c9f3b8/Swashbuckle.Core/Swagger/SwaggerGenerator.cs#L140) by swashbuckle will be removed. In some cases this is fine, but we would like to change the ability to change this behaviour. 

We can do this by creating our own filter, the only problem is that we can not remove the existing filter.  It would be good if filter collections would exposed, or options to remove them added.

P.s. the code for generating 200 and 204 responses could be one of the default a filters too.

**Comment by domaindrivendev** [comment]
I don't think this feature is necessary. Filters need to be explicitly added by application filters so if you don't want to use one, just don't enable it.

In the case of XML comments, a call to `IncludeXmlComments` will enable the `ApplyXmlActionComments` and `ApplyXmlTypeComments` filters. If you remove this call, neither will be enabled. If you want to enable one and not the other just drop down to the generic `SchemaFilter` or `OperationFilter` methods:

```csharp
c.OperationFilter(() => new Swashbuckle.Swagger.XmlComments.ApplyXmlActionComments(filePath));
```
It's also worth noting that the future version for ASP.NET Core [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) provides a little more flexibility around listing and documenting responses.
