### ISSUE TITLE
Hovering over a property within the UI displays all available tooltips of the type

### ISSUE THREAD

**Issue by timmkrause** [domaindrivendev/Swashbuckle#656]
After updating Swashbuckle.Core from 5.2.2 to 5.3.1 we get the following behavior.

![swagger-5 3 1](https://cloud.githubusercontent.com/assets/2163179/13081313/b1937cf6-d4cc-11e5-9b9f-6e5ba333cf95.png)

The good thing: This is a known and already fixed issue in swagger-ui (https://github.com/swagger-api/swagger-ui/issues/1836).
The bad thing: The fix was merged 10 days after the last release.

**Comment by DerAlbertCom** [comment]
can confirm that.

**Comment by domaindrivendev** [comment]
Looks like it's resolved in swagger-ui but not yet available as a standard release. For SB, I'm inclined to treat it as a known issue as opposed to rolling back the embedded swagger-ui version. Then, as soon as the next swagger-ui is released I'll pull it in.

**Comment by LaserBears** [comment]
As a workaround in the meantime you could inject the following JavaScript into the UI, which rearranges the DOM elements into their proper order:

    $(".model-signature span.propWrap > div:first-child").each(function () {
        var $propWrapDiv = $(this);
        var $propWrapSpan = $propWrapDiv.parent();

        // Reverse the nesting of <span class="propWrap"><div> to be <div><span class="propWrap">
        // and move any other content that was in the <span class="propWrap"> after the <div>.
        $propWrapSpan.contents().insertAfter($propWrapSpan);
        $propWrapDiv.contents().appendTo($propWrapSpan);
        $propWrapSpan.appendTo($propWrapDiv);
    });

**Comment by domaindrivendev** [comment]
I believe this is resolved with v5.4.0 of SB
