### ISSUE TITLE
MVC Site with Api Area

### ISSUE THREAD

**Issue by indxlogic** [domaindrivendev/Swashbuckle#657]
I have a small site that uses areas to separate the MVC Controllers from the WebApi Controllers.  Installing the base swashbuckler package shows an empty set of controllers.  How do I get swashbuckle to look in the area containing the ApiControllers?
![projectsetup](https://cloud.githubusercontent.com/assets/17317599/13147176/d2173ba0-d61d-11e5-959e-e4573f2b4ba9.png)

**Comment by domaindrivendev** [comment]
If memory serves, WebApi doesn't support Areas. Are you using traditional routing or attribute routing for your WebApi controllers? If it's the latter can you share your routes setup?

**Comment by indxlogic** [comment]
I used the following article to modify the routing.

http://blogs.infosupport.com/asp-net-mvc-4-rc-getting-webapi-and-areas-to-play-nicely/

**Comment by domaindrivendev** [comment]
There's known issues with WebAPI's ApiExplorer (heavily used by Swashbuckle) and the use of custom HttpController selectors. Check out the following issues for more info - #303, #611, #613
