### ISSUE TITLE
A way to separate the UI into header, css, javascript, body

### ISSUE THREAD

**Issue by ignatandrei** [domaindrivendev/Swashbuckle#658]
I need for Swashbuckle to have the same layout as ASP.NET MVC layout file.
Could you think for a way to separate the UI into header, css, javascript, body ?
It will be helpful for https://github.com/ignatandrei/Swashbuckle.MVC  
Thank you

**Comment by domaindrivendev** [comment]
Can't you just serve up your own index.html as an MVC vie?

**Comment by domaindrivendev** [comment]
That is, create an MVC route at "/swagger/index", a controller action and a view that is your own version of index.html. So long as u include the same assets and the JS to init SwaggerUi it should be fairly simple - unless I'm missing something?

**Comment by ignatandrei** [comment]
I do not want every time you come with  new asserts( js, css, and so on) to modify a component (https://github.com/ignatandrei/Swashbuckle.MVC )
So , if I could have this separation , I could include in my project ( that, practically, tries to replicate the layout of the site AND including Swashbuckle)

**Comment by domaindrivendev** [comment]
This seems like an overly complex requirement to bake into Swashbuckle. Bare in mind that SB is first and foremost a Swagger JSON generator. It leverages [swagger-ui](https://github.com/swagger-api/swagger-ui) and embeds it to provide an awesome UI experience. There's some plumbing to package this up nicely but other than that I'm happy to rely on the Swagger guys for UI.
