### ISSUE TITLE
Not able to change the requestUrl

### ISSUE THREAD

**Issue by AshrinNida** [domaindrivendev/Swashbuckle#661]
Hi,
I am new to swagger and am facing similar problem.
Am using swashbuckle 5.2.2
NugetPackage : Swashbuckle - Swagger for WebApi 5.2.2
The requested URL is always pointing to local host rather than pointing at hosted server.
([refer image](https://cloud.githubusercontent.com/assets/5681794/11031118/3d9c63b6-86f8-11e5-8fe4-01e12f277939.png) )
Is it should be configurable ?
Can you please help me with the same.

**Comment by domaindrivendev** [comment]
Is your API hosted behind a proxy server? If so your issue is a dup of #352
