### ISSUE TITLE
Swashbuckle 6.0.0-rc1-final not generating swagger.json file? 

### ISSUE THREAD

**Issue by chrohrbach** [domaindrivendev/Swashbuckle#663]
Hi i just integrated Swashbuckle 6.0.0-rc1-final in my ASP.NET Core 1.0 project, it look likes that that no swagger.json is generated, therefore no documentation at the swagger/ui/index.html URL ? Any idea ?
Thank you

**Comment by replaysMike** [comment]
I just upgraded as well from 5.2.2 and nothing is working.

**Comment by FL4X** [comment]
I face the same issue. 
I cannot install "Swashbuckle 5.3.2" as my project uses "EntityFramework 7" so the only option for me is to use the latest version of swashbuckle which does not work((

**Comment by frozenskys** [comment]
I had this problem, and it was related to the way I was specifying the routes in ASP.NET Core - check the error in the VS output pane, do you see the following error? 

`System.NotSupportedException: Unbounded HTTP verbs for path 'x'. Are you missing an HttpMethodAttribute? `

I fixed this by adding `[HttpGet]` to the method declaration.

**Comment by aaronralls** [comment]
Be sure to check the controller and base class for any public methods.

I had a public method in my base class that I had to change to protected.

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore for the Core-specific version of Swashbuckle
