### ISSUE TITLE
Swashbuckle Does Not Include Trailing Slash

### ISSUE THREAD

**Issue by ragnarok111** [domaindrivendev/Swashbuckle#664]
I created a web API with a username in the URL template. Anytime the username has a "." in it, Swashbuckle generate a URL that fails because there is no trailing slash.

/api/users/john.smith
instead of
/api/users/john.smith/

I have tried adding the trailing slash to the route definition but Swashbuckle still creates the Swagger definition without it.

**Comment by domaindrivendev** [comment]
Ideally, adding the trailing slash to the route definition would work but it seems that [ApiExplorer](https://msdn.microsoft.com/en-us/library/system.web.http.description.apiexplorer(v=vs.118).aspx), WebApi's metadata layer that SB depends on, just omits it when describing the various routes.

However, you can workaround this with relative ease using a simple DocumentFilter:

    // SwaggerConfig.cs
    c.DocumentFilter<TrailingSlashDocumentFilter>();

    // TrailingSlashDocumentFilter
    public class TrailingSlashDocumentFilter : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
        {
            swaggerDoc.paths = swaggerDoc.paths.ToDictionary(
                kvp => kvp.Key + "/",
                kvp => kvp.Value
            );
        }
    }

See the readme for a brief description of Document Filters: https://github.com/domaindrivendev/Swashbuckle#documentfilter
