### ISSUE TITLE
Using with MVC 6?

### ISSUE THREAD

**Issue by ko-vasilev** [domaindrivendev/Swashbuckle#665]
Hey, just wanted to know if it is possible to use swashbuckle with MVC 6? It does not use IAppBuilder/HttpConfiguration in Startup anymore.

**Comment by thabart** [comment]
To install SWAGGER on ASP.NET 5, the nuget packages "Swashbuckle.SwaggerGen" & "Swashbuckle.SwaggerUi" need to be installed on your project. The new github project url is : https://github.com/domaindrivendev/Ahoy. 
Swagger has been implemented on my personnal ASP.NET 5 project, the code source can be fetched from this url : https://github.com/thabart/SimpleIdentityServer/tree/master/SimpleIdentityServer/src/SimpleIdentityServer.Manager.Host

**Comment by ko-vasilev** [comment]
Thank you!
