### ISSUE TITLE
Release Swashbuckle under a standard licence

### ISSUE THREAD

**Issue by cbundy** [domaindrivendev/Swashbuckle#666]
Swashbuckle does not appear to be released under a standard licence agreement (e.g. MIT/Apache).

This can restrict an organisation's ability to use it as they are limited to standard licence agreements that have been pre-approved or vetted.

Would it be possible to release Swashbuckle under either MIT or Apache licence?

Thanks

**Comment by matthewkimber** [comment]
It is released under a standard license. The license that is being used is the ["Revised BSD License"](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29).
