### ISSUE TITLE
SchemaFilter NuGet Version?

### ISSUE THREAD

**Issue by senj** [domaindrivendev/Swashbuckle#674]
Which Version of swashbuckle supports SchemaFilter?
I don't find it in mine. (v6.0.0-rc1-final for swaggerGen and swaggerUI)

**Comment by domaindrivendev** [comment]
So, the version you're using is next-gen (targeting ASP.Net "Core") and is not reflected in the current readme. I'm working hard to close out critical issues with the 5.x line before re-shifting my focus back to 6.x (including providing some docs for that version).

In the meantime, I can tell you that SchemaFilter's are called ModelFilter's in the next-gen version. Hopefully this helps.
