### ISSUE TITLE
Return model for IDictionary with a Enum as key

### ISSUE THREAD

**Issue by alefranz** [domaindrivendev/Swashbuckle#676]
It would be nice to nice to have the model definition for a property defined as:
`public IDictionary<MyEnum, MyClass> Values { get; set; }`

Right now the property type is just defined as **object**
It would be nice to have the type defined like this (if using _StringEnumConverter_):
```
MyEnumDictionary {
  myEnumValue1: MyClass,
  myEnumValue2: MyClass
}
```

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Swashbuckle/commit/f5f3a187e1648e818778eddbdb4e1b6e35b6d83d

Will be available when 5.4.0 get's released
