### ISSUE TITLE
Mixed JSON arrays

### ISSUE THREAD

**Issue by bragma** [domaindrivendev/Swashbuckle#682]
Hi,
how can I use swashbuckle to document an API returning an array of mixed arrays? In particular, specify the types and meaning of the inner array values.

[
	[ 10, 0.5, "Red" ],
	[ 15, 0.2, "Green"]
	[ 1, 0.4, "Yellow"]
]

Thanks!

**Comment by domaindrivendev** [comment]
As far as I'm aware, [OpenAPI](http://swagger.io/specification/) (formerly known as Swagger), the API description language that Swashbuckle is built around, does not support mixed arrays. You may want to search the following repo for rationale or to find out if it's likely to be supported in the future:

https://github.com/OAI/OpenAPI-Specification

**Comment by bragma** [comment]
@domaindrivendev  Thanks for the answer!

**Comment by Davilink** [comment]
https://swagger.io/docs/specification/data-models/data-types/#mixed-array

Do mixed array are supported ?
