### ISSUE TITLE
Error with ErrorCode 999

### ISSUE THREAD

**Issue by rakran** [domaindrivendev/Swashbuckle#683]
Hi,

I am new to swashbuckle and when I am trying to access swagger help I am getting following error:
500 : {"ErrorMessage":"One or more errors occurred. Error code 999, An unexpected error occurred. Check the service log for details. ","ErrorCodes":["999"],"CorrelationId":"4ac9f8fd-de81-454f-a286-c00fdd5a61f4"} https://localhost:44306/swagger/docs/v1

I am not sure how to debug this and from where this CorrelationId is coming.

Regards,
Rakesh

**Comment by domaindrivendev** [comment]
The exception above is not directly thrown by Swashbuckle. It's possible that SB is throwing an error but something else in your stack is swallowing that error and producing the above output. So unfortunately, I can't really help until you get to the bottom of what's causing the above exception. I just did a quick search on Google and very little showed up which makes me thing it may something specific to your organization.

Do you have any custom WebApi handlers and/or OWIN middleware configured for your application?
