### ISSUE TITLE
swagger UI page not rendering properly.

### ISSUE THREAD

**Issue by sstrange** [domaindrivendev/Swashbuckle#685]
I've followed the instructions in the readme.md and am able to get my raw swagger JSON at "http://localhost:16715/swagger/docs/v1" with all my routes and XML comments. I can copy/paste this into editor.swagger.io and it displays ok.

But "http://localhost:16715/swagger/" is not rendering. This is the screenshot with javascript console. Can anyone point me in the right direction?

![image](https://cloud.githubusercontent.com/assets/7025212/13828820/dd8b686c-eb80-11e5-8a2c-55105c8e9caa.png)

**Comment by langdonx** [comment]
Either jQuery fails to load or your iisexpress is hosed.  What's the first error?  It's not included in the screenshot.  What does the Network tab look like?

**Comment by sstrange** [comment]
The screenshot below has the first error and the network tab. 
If I add the entire /dist folder from the Swagger UI repo to the project as static files and point the index.html to /swagger/docs/v1, that will work.  I don't understand why /swagger/ui/index isn't working.

![image](https://cloud.githubusercontent.com/assets/7025212/13859336/3cd707ee-ec40-11e5-93ad-cc63bf0044c5.png)

**Comment by langdonx** [comment]
Looks like IIS or Chrome is not able to download your scripts.  What does jquery-1-8-0-min-js look like when you open it in a new tab?

**Comment by sstrange** [comment]
jquery-1-8-0-min-js in a new tab. 
Looks like it's getting cut off somehow.

![image](https://cloud.githubusercontent.com/assets/7025212/13860027/94a98c14-ec43-11e5-84a2-4036ec97795d.png)

**Comment by JT-Bruch** [comment]
@sstrange Were you able to get this resolved?  I am having the same issue except it can't find any of the referenced resources in the index.html.  I've tried a number of different combinations, but nothing seems to be working.  

I can inject JS & CSS just fine, but when I try custom content and replacing the included index.html I get the same result.

**Comment by sstrange** [comment]
No. I ultimately commented out .EnableSwaggerUi() in SwaggerConfig and added the /dist folder as static files. I've been using it like that. 

Strangely I found it only had the issue on localhost. When deployed /swagger was working.

**Comment by rbonestell** [comment]
I, too, am experiencing this issue when injecting a custom index.html file. We use Swagger for both testing and publishing so we need this to work locally too. Subscribing in hope for a solution!

**Comment by domaindrivendev** [comment]
Are people still experiencing an issue here? Will go ahead and close if no response in the next couple of days

**Comment by JT-Bruch** [comment]
Actually! I was able to get it fixed @sstrange.  Basically you need to replace the periods with dashes in the various script and stylesheet includes.

**Comment by bys-wallance-zhang** [comment]
the root cause is the "Swashbuckle.core" source code we build to dll not include "css\" "lib\" "images\",these are different Swashbuckle.core.dll get from nuget.

**Comment by MurtuzaTravadi** [comment]
i am facing same issue

**Comment by laura-mi** [comment]
I am also having this issue. The css/js files are not loaded, but it doesn't work neither locally, neither on server. I think using the static files in the dist folder is just an workaround, not a solution. If Swashbuckle.core does not include those files, shouldn't it be fixed so far?

**Comment by erivics** [comment]
I install Swashbuckle.AspNetCore 6.2.3. Configuration properly done but the display is this. Please I need help
![swagger](https://user-images.githubusercontent.com/75021908/158629381-848ab27f-c00f-44af-bce5-752838bc8a22.PNG)
