### ISSUE TITLE
6.0.0-final-rc1, ASPNET5, and replacing index.html

### ISSUE THREAD

**Issue by galmok** [domaindrivendev/Swashbuckle#686]
In 5.3x it was fairly easy to substitute a new index.html to use, but how do we do it with 6.0?

UseSwaggerUI seems to have this hardwired.

Related, the reason for the replacement need is the seemingly fixed nature of "api_key". Is it possible to modify it using config now?

**Comment by domaindrivendev** [comment]
As I'm sure you're aware 6.x is next-gen and still in pre-release. I'm trying hard to clean up critical bugs in the 5.x line before re-shifting my focus back to next-gen. So, in the meantime you'll have to bare with the lack of next-gen documentation.

In the meantime, you should look at the various exampled I've provided in the next-gen repo - https://github.com/domaindrivendev/Ahoy/tree/master/test/WebSites. There's an example there for CustomizedUi and if you take a quick look you'll see that it's as simple as dropping your custom index.html under wwwroot/swagger/ui
