### ISSUE TITLE
native support for KeyValuePair<TKey, TValue>

### ISSUE THREAD

**Issue by langdonx** [domaindrivendev/Swashbuckle#687]
Is it possible with the current build to get `KeyValuePair<string, string>` working with `swagger-codegen`?  Currently this class:

    public class Employee
    {
        public List<KeyValuePair<string, string>> Test { get; set; }
    }

Ends up looking like this with its own generated type:

    public List<KeyValuePairStringString> Roles1 { get; set; }

I [filed this last week](https://github.com/swagger-api/swagger-codegen/issues/2355), but it seems more of an issue with how Swashbuckle generates the spec file.

**Comment by domaindrivendev** [comment]
Why are you defining your property as a List of KeyValuePairs as opposed to a Dictionary? For example, if you use the following:

    public IDictionary<string, string> Test { get; set; }

then SB will generate the following description:

    {
        "type": "object"
        "additionalProperties": {
            "type": "string"
        }
    }

which, from a quick browse over the referenced issue, is what swagger-codegen is looking for

**Comment by langdonx** [comment]
I was generating from an existing API written by someone who didn't know what they were doing at the time.  It's a bit too ingrained and can't be easily refactored. =/

**Comment by domaindrivendev** [comment]
When it comes to JSON serialization, there's a substantial difference between a "dictionary" and a "list of key-value pairs" and given that your API uses the latter, I think the description that Swashbuckle generates is accurate.

**Comment by domaindrivendev** [comment]
OK - something's just clicked and now I understand your issue better. I don't think there's any issue with this being described as a list of key-value-pairs - it's just the SchemaId that SB generates for generic types is not friendly for client generators.

I'm looking into a fix ...

**Comment by domaindrivendev** [comment]
Or maybe not ... as I read on it seems the generator creates the following:

    public List<KeyValuePairStringString> Roles1 { get; set; }

Why do you think this is wrong?

**Comment by langdonx** [comment]
Nothing necessarily wrong, it just seems odd that it generates a new type called "KeyValuePairStringString" instead of just using the native `KeyValuePair` generic.  Perhaps that's all you can get with the OAI standard?

**Comment by domaindrivendev** [comment]
Swagger/OpenAPI, or more specifically JSONSchema, doesn't support the notion of "generics" and so the name is the only way in which the specific types for the generic can be expressed.

**Comment by janseris** [comment]
The `List<KeyValuePair<TKey, TValue>>` must be used when TKey is not a primitive type in `Dictionary<TKey, TValue>` which is fine possible in C#.
Why is the client generated with new made up class and how to disable this behavior?
Btw a large issue with this is as well that if models are linked, this new auto-generated model class (`XxxYyyKeyValuePair`) cannot be linked because it does not exist in my linked models.
It is invented by the generator and not included in the generated code when the option for not including models is selected.

The mapping would be as simple as this if `List<KeyValuePair<TKey, TValue>>` was preserved.

```
public static Dictionary<TKey, TValue> FromRestApiModel<TKey, TValue>(this List<KeyValuePair<TKey, TValue>> kvps)
{
    return kvps.ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
}

public static List<KeyValuePair<TKey, TValue>> ToRestApiModel<TKey, TValue>(this Dictionary<TKey, TValue> dictionary)
{
    return dictionary.ToList();
}
```
