### ISSUE TITLE
"Run in Postman" button on swagger index.html?

### ISSUE THREAD

**Issue by L0G1C** [domaindrivendev/Swashbuckle#688]
Has anyone figured out, or can think of a way to incorporate Postman's new "Run it button" onto swagger's index.html page? here's the button info:

https://www.getpostman.com/integrations/run-button?source=chrome_app

I've created a custom index.html page and i inject it into swagger through the configuration. I'm able to see the button momentarily when I have placed the code for it under the "swagger-ui-wrap" div. But it quickly is removed as the API data is dynamically generated. =/

**Comment by VisualBean** [comment]
have you tried injecting it through javascript instead? - maybe replacing 'try it out' buttons with the 'Run in Postman' button

**Comment by L0G1C** [comment]
Oh I forgot to close the issue. yeah I ended up using javascript to inject the html. It was the only way I could do it because even if I put the html in the index page directly, it was "disappearing" as swagger added all of the other documentation over it.
