### ISSUE TITLE
Can I set showRequestHeaders for SwaggerUI to true?

### ISSUE THREAD

**Issue by sebekz** [domaindrivendev/Swashbuckle#689]
I was trying to enable request headers in Swagger, but in the code ```showRequestHeaders``` parameter is hardcoded to false. Is it  possible to flip it to true?

**Comment by VisualBean** [comment]
You can, but you need to "override" the index file to instantiate swagger with` showRequestHeaders = true`

**Comment by sebekz** [comment]
That might seem like a silly question, but how do I do that? Do I need to build my own private Swashbuckle package from the source to do that? Perhaps this could be made a configuration setting instead?

**Comment by VisualBean** [comment]
You can inject a html page to replace the index file. ([link to docs](https://github.com/domaindrivendev/Swashbuckle#customizing-the-swagger-ui)).

What you do is;

1. You copy the index.html file from the repo.
2. Change what you need (show request headers = true)
3. Set the Build Action to "Embedded Resource"
4. Inject it in through your swaggerconfig (c.CustomAsset("index", thisAssembly, "ProjectName.Folder.index.html");
5. Et voila.

**Comment by sebekz** [comment]
That partially worked, thanks. I now can see request headers section, but it always comes up empty {}.

**Comment by VisualBean** [comment]
Hmm that is odd, it should be handled by swagger-ui.js

**Comment by kpgeek** [comment]
Hi @VisualBean 
I need to set the multiple request headers in swagger. I tried to reset showRequestHeaders = true, and Set the Build Action to "Embedded Resource".

But I don't find any suitable method for c.CustomAsset as you see here.

How do we enable multiple headers in swagger? Any help would be appreciated. 

![image](https://cloud.githubusercontent.com/assets/12850067/14400668/8fe0be4a-fdb0-11e5-99c8-6fc362d59321.png)

**Comment by sebekz** [comment]
@kpgeek it's on

```
GlobalConfiguration.Configuration   
    .EnableSwaggerUi(c =>
    {
        c.CustomAsset(
```

**Comment by VisualBean** [comment]
@kpgeek in the third parameter of the CustomAsset method, you need to provide it with the fully qualified folder path to the index file with dots instead of slashes (ProjectName.Folder.index.html)

**Comment by kpgeek** [comment]
Thanks @VisualBean and @sebekz, my project name is **Test.Web.UI ** and I tried as follows. But its not showing me any option to set the headers. 

.EnableSwaggerUi(c =>
                    {
                        c.CustomAsset("index", thisAssembly, "Test.Web.UI.swagger.dist.index.html");

**Comment by VisualBean** [comment]
There are no header options in the customasset method. But in the javascript of the index page :)

**Comment by domaindrivendev** [comment]
Closing as the issue is stale and the proposed solution is correct
