### ISSUE TITLE
Different response model examples based on HttpStatusCode

### ISSUE THREAD

**Issue by VisualBean** [domaindrivendev/Swashbuckle#690]
I have an API where all non-success responses returns typeof(IApiException).
the exception changes based on the status code (duh)...

What I want to do is create different examples based on the httpStatusCode.

I tried creating an operationFilter and then overriding the schema examples, but the examples are not shown at all.

I've created a StackOverflow question that might be more fulfilling [here](http://stackoverflow.com/questions/36128739/different-response-model-examples-based-on-httpstatuscode)

**Comment by domaindrivendev** [comment]
Have you tried decorating your actions with SwaggerResponseAttribute's? You can create one for each status code and also specify the corresponding return type

**Comment by VisualBean** [comment]
I guess that could work, just for the sake of documentation.- I use a generic exception model, so it wouldn't work with that specifically, but I could just add derived specific errors as responses
