### ISSUE TITLE
DescribeAllEnumsAsStrings not considered for examples

### ISSUE THREAD

**Issue by Eleasar** [domaindrivendev/Swashbuckle#694]
[Version 5.3.2]

When calling DescribeAllEnumsAsStrings it will nicely convert all enumerations to the string values in the definitions. In the examples on the other hand they are still using the integer representations though.

And there is a typo in the documentation (i think) e.g. on https://github.com/domaindrivendev/Swashbuckle but on few other places as well:

"configuring the StringToEnumConverter globally"

Should be StringEnumConverter and to be more precise the json.net one. Maybe add an example on how to do this.

Workaround is described (add this "StringEnumConverter" per enum or globally) so i think this has low priority.

[JsonConverter(typeof(StringEnumConverter))]

**Comment by bryan-c-oconnell** [comment]
Thanks @Eleasar - this workaround worked for me. Just needed to the Attribute you listed to the enum property in my Swagger example ViewModel.

**Comment by VisualBean** [comment]
:+1:  I also ran into this problem, I fixed it by defining anonymous examples instead :)

**Comment by domaindrivendev** [comment]
For this SB project (i.e. for WebAPI), you'll have to resort to the described workarounds. For [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore), the ASP.NET Core-specific project, examples will automatically be deserialized according to your application's serialization settings:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v1.0.0/src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerContractResolver.cs#L22
