### ISSUE TITLE
Define which controllers to use in documentation generation

### ISSUE THREAD

**Issue by couellet** [domaindrivendev/Swashbuckle#695]
Is it possible to specify explicitely which controllers should be used to generated the JSON schema? 

We have a bunch of API that we don't want to be available in our documentation, it would be easier to specify which controllers should be documented instead of adding the `[ApiExplorer(Ignore()]` flag

**Comment by srebella** [comment]
Hi @couellet 

I have the same trouble as you. What i did is to create a new class that implements the IDocumentFilter. See this on the SwaggerConfig File:
`
                        // Post-modify the entire Swagger document by wiring up one or more Document filters.
                        // This gives full control to modify the final SwaggerDocument. You should have a good understanding of
                        // the Swagger 2.0 spec. - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md
                        // before using this option.
                        //`

check this ticket, it actually helped me [https://github.com/domaindrivendev/Swashbuckle/issues/228](url)

**Comment by domaindrivendev** [comment]
If you don't want to use the ApiExplorerAttribute on your controllers, then the DocumentFilter approach described above is the best alternative at the moment.
