### ISSUE TITLE
Combining JWT with swashbuckle api_key and Auth0, security requirements set at Authorized controllers?

### ISSUE THREAD

**Issue by AlFranco** [domaindrivendev/Swashbuckle#697]
Hi!

I'm trying to use an apikey to inject a bearer token ONLY on controllers in my WebAPI that have the Authorize attribute. I'm using Auth0 as the STS, I've injected some JS in order to fill the api_key input. 

```
        $('#input_apiKey').val(token);
        var key = "Bearer " + token;
        swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("Authorization", key, "header"));
        console.log("Added key: " + key);
```

However it turns out that it's injecting the key to all the actions in the API... How can I set a security requirement stating that it's only used in those controllers? I think this could be achieved using an operation filter.

I know I could do something like:

```
public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            var actFilters = apiDescription.ActionDescriptor.GetFilterPipeline();
            var isAuthorizedController = actFilters.Select(f => f.Instance).OfType<AuthorizeAttribute>().Any();
            if(isAuthorizedController)
                operation.security.Add(asecurityrequirement);
```

But I don't know which is the attribute I have to fill in and how to link it with a value that will be resolved in the injected javascript.

Thanks!

**Comment by VisualBean** [comment]
The name of the apikey you've set in swaggerconfig has to be exactly the same as in the OperationsFilter
I have the following in my swaggerConfig.cs  ```
c.ApiKey("Authorization")
                                .Description("Standard Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"")
                                .Name("Authorization")
                                .In("header");
```
My operationsFilter looks like the following: ```
public class AuthorizationSecurityObjectOperationsFilter : IOperationFilter
    {
        public string Name { get; private set; }

        public AuthorizationSecurityObjectOperationsFilter()
        {
            Name = "Authorization";
        }
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            if (operation.parameters == null)
                operation.parameters = new List<Parameter>();
            var tokenAuthDict = new Dictionary<string, IEnumerable<string>>();
            tokenAuthDict.Add(Name, new List<string>());
            operation.security = new IDictionary<string, IEnumerable<string>>[] { tokenAuthDict };
         
        }
    }
```
This works for me (I have bearer on all actions except an authorize one which has another scheme, but annoted with
```
  [AllowAnonymous]
  [BasicAuthentication()]     
```

instead

**Comment by domaindrivendev** [comment]
Closing as it appears the solution has been provided - thanks for your contributions @VisualBean :)
