### ISSUE TITLE
Swagger port mapping error.

### ISSUE THREAD

**Issue by LambertW** [domaindrivendev/Swashbuckle#699]
I am trying to use swagger in the wepapi project, and add setting in the Initialize() function like this
`Configuration.Modules.AbpWebApi().HttpConfiguration.EnableSwagger(
c => { c.SingleApiVersion("v1", "Abp.Test.WebApi"); c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First()); 
c.IncludeXmlComments(GetXmlCommentsPath()); })
.EnableSwaggerUi(c => c.DisableValidator());
`
While I debug in my computer, it seems that nothing wrong with swagger.
Swagger can list all apis correctly.

But when i published it into iis with port 8083(url:**http://localhost:8083/swagger/ui/index**),
and use route to set port mapping like **internal: 8083 -> external:8112**,
and visit the url with** http://183.234.**.**:8112/swagger/ui/index**,
it will return "Can't read from server. It may not have the appropriate access-control-origin settings.", and we can see swagger visit url with the wrong port(8083), **http://183.234..:8083/swagger/docs/v1**.

![qq 20160328111722](https://cloud.githubusercontent.com/assets/12291760/14073385/2382712a-f4fb-11e5-855d-c249f5ac5dcd.png)

Only when we change the port from 8083 to 8112(**http://183.234..:8112/swagger/docs/v1**), we can see the apis list.

Am I miss some setting in the project?

**Comment by domaindrivendev** [comment]
Closing as this is a dup of #352 

There's a couple of workarounds suggested there. In addition, you could try injecting a custom RootUrl resolver:

    // SwaggerConfig.cs
    c.RootUrl(request => // your implementation goes here)

You can look at the default implementation for reference: https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Application/SwaggerDocsConfig.cs#L277

If the "port mapping" you've described above injects any additional headers to identify the original (external) port you could use that to construct the correct URL. If not, then I think you'll have to hardcode the external port.
