### ISSUE TITLE
ComplexType on GET Method using [FromUri]

### ISSUE THREAD

**Issue by alexvance89** [domaindrivendev/Swashbuckle#70]
In order for swagger to allow me to call a GET with a complex type specified as my parameter, I had to do some custom modification using the OperationFilter.

Here is what the WebAPI controller action method looks like:

![image](https://cloud.githubusercontent.com/assets/7396996/4050951/1e64e4aa-2d5d-11e4-97e4-073b0b85affc.png)

The URL should look like the following examples: 

/api/blah?Id=1&secondaryid=blah
or
/api/blah?id=1&secondaryid=blah&fieldone=blah&fieldtwo=blah

Here's what happens without the operation filter:

![image](https://cloud.githubusercontent.com/assets/7396996/4050922/ea76b3b2-2d5c-11e4-8121-eb1df45d5a08.png)

Here's what I need it to do (or something similar):

![image](https://cloud.githubusercontent.com/assets/7396996/4050965/4b180bbc-2d5d-11e4-8334-26752490d62a.png)

And Here's how I got it to do that:

![image](https://cloud.githubusercontent.com/assets/7396996/4050979/70f83668-2d5d-11e4-900d-a0c5ecde1283.png)

I don't want to have to do this for every single method that I have this sort of issue on. I did get this to work using that operation filter, but I already know there will be other methods similar to this same one. Is this a bug, or is there a better way to do this?

Thanks,

Alex

**Comment by domaindrivendev** [comment]
Just released version 4.2.0 with these changes. Please try it out and provide feedback if you get a chance.

FYI, bar any serious bugs, this will be the last release of the 4.x line. All future development and features will be targeted to the next major version 5.x, which makes the transition from Swagger 1.2 to Swagger 2.0.
