### ISSUE TITLE
How set host in swagger.json?

### ISSUE THREAD

**Issue by poma-prs** [domaindrivendev/Swashbuckle#701]
I want to set host (rooturl) in swagger.json
How i can do it in aspnet5 (with swashbuckle 6.0.0-rc1-final)?

It is right? Or is there another way?

```
public class HostDocumentFilter : IDocumentFilter
{
    public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
    {
        swaggerDoc.Host = "localhost:5272";
        swaggerDoc.Schemes = new List<string>() {"http"};
    }
}

services.ConfigureSwaggerDocument(options =>
        {
            options.DocumentFilter(new HostDocumentFilter());
        });
```

**Comment by domaindrivendev** [comment]
There's a separate SB project for ASP.NET Core and here's the corresponding issue:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/235
