### ISSUE TITLE
201-created shows up as a response with status 200 in swagger-ui

### ISSUE THREAD

**Issue by VisualBean** [domaindrivendev/Swashbuckle#702]
I have a post endpoint where i would like to return a 201, If i use `<response code="201"> Created</response>` with `[ResponseType(typeof(mytype))]` with the addition of [SwaggerResponses] - it doesn't show my swaggerresponses, but shows the correct return code and type.
![2016-03-31_11-35-44](https://cloud.githubusercontent.com/assets/5294032/14171736/cac9ffbc-f734-11e5-8723-3e0a7ff3f6c1.png)

If I on the other hand, only use SwaggerResponses and not the xml responses, it shows an empty 200 and all of my swaggerresponses.

![2016-03-31_11-31-47](https://cloud.githubusercontent.com/assets/5294032/14171623/3175d930-f734-11e5-9e34-d7a3013cfd67.png)

**Comment by domaindrivendev** [comment]
I'm going to close this issue and refer you to a thread toward the end of a previous issue that should answer your question:

https://github.com/domaindrivendev/Swashbuckle/pull/259#issuecomment-87715485

**Comment by VisualBean** [comment]
` [SwaggerResponseRemoveDefaults]` fixed it
