### ISSUE TITLE
ApplyXmlTypeComments throws exception when manually adding properties to schema via a SchemaFilter

### ISSUE THREAD

**Issue by guillaume86** [domaindrivendev/Swashbuckle#706]
Looks like the fix is simple, use `Contains(key) ? [key] : null` in that line:

https://github.com/domaindrivendev/Swashbuckle/blob/953f9803bdf4a5051dd4ad90f8a6bc0ad8b6af3b/Swashbuckle.Core/Swagger/XmlComments/ApplyXmlTypeComments.cs#L38

**Comment by long-greg-c** [comment]
+1

**Comment by domaindrivendev** [comment]
I'm not sure exactly when this happened but now the XML filters are always executed prior to any custom filters and so this issue should be resolved if you use the latest version. Please reopen if you're still having issues.
