### ISSUE TITLE
Configuring Swashbuckle in ASP.NET Core

### ISSUE THREAD

**Issue by brentarias** [domaindrivendev/Swashbuckle#708]
I added Swashbuckle to my ASP.NET Core project (`install-package swashbuckle -pre`), and its default behavior is working correctly.  Now I would like to try a custom [`GroupActionsBy` as shown in this example](http://stackoverflow.com/questions/34175018/grouping-of-api-methods-in-documentation-is-there-some-custom-attribute).

Unfortunately, I can't figure how to access the configuration API.  Is customization / configuration not yet available for the ASP.NET Core version of Swashbuckle?  All the documentation examples show syntax like this:

```
httpConfiguration
   .EnableSwagger(c => ...
```

Unless I'm mistaken, there is no "httpConfiguration" object in ASP.NET Core.  The only Swashbuckle API surface area I have discovered for ASP.NET Core looks like this:

```
    public void ConfigureServices(IServiceCollection services)
    {
        // Add framework services.
        services.AddSwaggerGen();
        services.AddMvc();
```

The `AddSwaggerGen` method takes no parameters, and so there is nothing to configure. Likewise I have this:

```
    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        app.UseIISPlatformHandler();

        app.UseStaticFiles();

        app.UseMvc();
        app.UseSwaggerGen();
        app.UseSwaggerUi();
```

Neither `UseSwaggerGen` nor `UseSwaggerUI` take any parameters related to configuration.  So again, there is nothing I can configure.  

Is this ability not yet available for Swashbuckle in ASP.NET Core, or am I simply overlooking something?

**Comment by GZidar** [comment]
I too am interested in this. I have followed the steps outlined here: https://damienbod.com/2015/12/13/asp-net-5-mvc-6-api-documentation-using-swagger/ 

I think I have the service installed (and configured?) correctly since the page loads when I navigate to http://localhost:(port)/swagger/ui/index.html but the swagger.json file is not being generated.

**Comment by jordanwallwork** [comment]
Configuration happens in the Startup `ConfigureServices` method:

    services.ConfigureSwaggerDocument(options => options.GroupActionsBy(...));

**Comment by domaindrivendev** [comment]
To use Swashbuckle with ASP.NET Core, see the separate project - https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by Brighty28** [comment]
Running dotnet core 2.1 and installed Nuget package from here: https://www.nuget.org/packages/Swashbuckle.AspNetCore.Cli/3.0.0-beta1 and can not get the dotnet swagger tofile --help command to work returns : No executable found matching command "dotnet-swagger"
At line:1 char:1
dotnet swagger tofile --help
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (No executable f...dotnet-swagger":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by AndreCastilhoFilho** [comment]
> Running dotnet core 2.1 and installed Nuget package from here: https://www.nuget.org/packages/Swashbuckle.AspNetCore.Cli/3.0.0-beta1 and can not get the dotnet swagger tofile --help command to work returns : No executable found matching command "dotnet-swagger"
> At line:1 char:1
> dotnet swagger tofile --help
> 
> ```
>    + CategoryInfo          : NotSpecified: (No executable f...dotnet-swagger":String) [], RemoteException
>    + FullyQualifiedErrorId : NativeCommandError
> ```

Same problem but with v4.01
