### ISSUE TITLE
Swagger/Docs/V1 is showing "Paths" to be an Empty Array -- but shouldn't be.

### ISSUE THREAD

**Issue by EdLichtman** [domaindrivendev/Swashbuckle#710]
in swagger/docs/v1 on a working project I don't seem to be getting any paths. My docs JSON is ending with= "schemes":["http"],"paths":{},"definitions":{}}

I've done some googling and I can't seem to find the proper issue, or if it has to do with BeanConfig, like I'm seeing in many places, I can't seem to find good instructions on how to apply it. Does anyone have any experience with this?

**Comment by domaindrivendev** [comment]
Are you per chance using a custom controller selector? If so, take a look at #51 and #144

**Comment by EdLichtman** [comment]
This looks right, but because of other issues I'm putting this on delay until I can start adding Swagger again. I should be able to within a few days

**Comment by EdLichtman** [comment]
Found the issue. It didn't have to do with Versioning or Custom Api Versions. It had to do with the particular project I was working on didn't have WebApiConfig configured, so it couldn't find an "{id}" to find a path. There were no paths for /localhost/api/, because I was supposed to find paths for /localhost/api/{id}
