### ISSUE TITLE
Need a xml document attribute to specify request model, similar to the response /// <response ...

### ISSUE THREAD

**Issue by liushuping** [domaindrivendev/Swashbuckle#711]
I have an ASP.NET Web API (lets say A) controller, actually it is a "proxy": it forwards all the requests to an internal Web API (lets say B). So the API A accepts any request and just forward it to API B and let API B do validation check and respond. 

My solution is to use a parameter-less controller action and inside the action to use HttpClient to forward the request to API B. code like below:
```
        /// <response code="200" cref="ReturnModel"></response>
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(ReturnModel))]
        public async Task<HttpResponseMessage> Post()
        {
            var client = new HttpClient();
            Request.RequestUri = Uri_Of_B;
            return await client.SendAsync(Request);
        }
```

The code works well. But unfortunately, the generated Swagger page does not show the input box to let user input request body and try.

So, I request to support an xml document attribute like /// <request cref="InputModel"></request> to specify request input model.

I do not want put the InputModel as parameter in the Post action/method for two reasons:
* I want the action accept any input message even invalid model, but if I put the InputModel in Post parameter, I will loose the input from forwarding to API B.
* Request.content will be empty if I put any parameter in Post method.

**Comment by domaindrivendev** [comment]
Going forward, I want to limit the use of XML comments to just populate free-text fields, like "description" and "summary", in the generated Swagger. For the structured metadata like parameter and response schema's, which are more tightly-bound to the implementation code, the provided Swagger attributes or the built-in .Net attributes (e.g. ResponseType) should be used.

Yours seems like a pretty special case and so I'm reluctant to make exceptions within the library to support it. However, you can achieve what you're trying to do very easily with an Operation filter (see readme). Here's an example to get you started:

    public class AddDefaultPostParameter : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            if (apiDescription.HttpMethod == HttpMethod.Post
                && apiDescription.ParameterDescriptions.Count == 0)
            {
                operation.parameters = new List<Parameter>
                {
                    new Parameter
                    {
                        name = "body",
                        schema = schemaRegistry.GetOrRegister(typeof(InputModel))
                    }
                };
            }
        }
    }
