### ISSUE TITLE
Conflicting between /// <response ...> document and [SwaggerResponse] attribute

### ISSUE THREAD

**Issue by liushuping** [domaindrivendev/Swashbuckle#712]
I put multiple `[SwaggerResponse]` attributes to my Web API controller actions to enumerate all possible responses, it's good I can see they are all listed in swagger page. However, I noticed in the top part of the swagger page for a API, it still displays "Response Class (Status 200)", but I want the response code to be 201. Then I learned I should put  ` /// <response code="201"></response>`

code like this:
```
/// <response code="201" cref="DeviceViewModel"></response>
[SwaggerResponse(HttpStatusCode.Created)]
[SwaggerResponse(HttpStatusCode.BadRequest)]
[SwaggerResponse(HttpStatusCode.InteralServerError)]
public async Task<HttpResponseMessage> Post()
{
     //
}
```
Then I see the document is changed to "Response Class (Status 201)", but unfortunately, I found the 400 and 500 return types are loss from the API document bottom. seems `/// <response>` and `[SwaggerResponse]` attributes are conflicting.

**Comment by domaindrivendev** [comment]
You can only use one strategy or the other - not a hybrid.

In your case, you should stick with the annotations as this is the preferred approach. In fact the XML approach won't be supported in the next major version. To resolve your issue, you'll need an additional attribute to tell Swashbuckle your explicitly providing "all"  response codes and don't want to infer anything from the action signature.

    [SwaggerResponseRemoveDefaults]
    [SwaggerResponse(HttpStatusCode.Created)]
    [SwaggerResponse(HttpStatusCode.BadRequest)]
    [SwaggerResponse(HttpStatusCode.InteralServerError)]
    public async Task<HttpResponseMessage> Post()
    {
         //
    }

**Comment by liushuping** [comment]
Oh! Sorry, I did not notice this attributed. Thanks!
