### ISSUE TITLE
Show/Hide Operations based on the User

### ISSUE THREAD

**Issue by lolekjohn** [domaindrivendev/Swashbuckle#713]
Hi Team,

I am building a Web API service and I use swash buckle for showing the documentation. We use OAuth 2.0 authenticaion. Is there a way to show/hide operations in the swagger ui based on the logged in user's access level so that the user will not see documentation for the methods not relevant to him.

Thanks,
Lolek

**Comment by domaindrivendev** [comment]
Closing as this is a dup of #601

**Comment by lolekjohn** [comment]
But, using this method will it be possible to hide the methods in the swagger ui? Are there any samples?
