### ISSUE TITLE
Change model name in request/response json

### ISSUE THREAD

**Issue by protoze** [domaindrivendev/Swashbuckle#714]
My  external models are suffixed with Dto, for example PersonDto.

Is it possible to make Swagger just render "Person" for all references to the PersonDto type?  It would make my documentation a lot cleaner for external parties.

Thanks.

**Comment by domaindrivendev** [comment]
Have you looked at the SchemaId config option?
https://github.com/domaindrivendev/Swashbuckle#schemaid

Something along the following lines should do it:

    c.SchemaId(t => t.Name.Replace("Dto", ""));

**Comment by protoze** [comment]
Great!  That works for the right hand side where the model | model schema are listed, but how do I make this change propagate to the left hand side where the parameters are listed also?

![screen shot 2016-04-14 at 10 46 01 am](https://cloud.githubusercontent.com/assets/4617626/14537953/3b99ee10-022e-11e6-9750-914a61299bfa.png)

**Comment by protoze** [comment]
I'm guessing I can get that to work with an OperationFilter.

**Comment by protoze** [comment]
I was able to get this to work with an OperationFilter.  Please close this issue if this is the intended approach.
