### ISSUE TITLE
Show/Hide Operations based on the User #713

### ISSUE THREAD

**Issue by lolekjohn** [domaindrivendev/Swashbuckle#715]
Hi Team,

I had raised an issue yesterday titled - "Show/Hide Operations based on the User #713"

This was closed telling that its duplicate of #601 

But, in #601, it is told that we can use delegate handlers. But using this, we canrestrict access to the swagger ui page. But is there any way to restrict the methods that gets displayed in the swagger ui based on the user logged in?

If its possible, can you please give some samples on how to do it?

Regards,
Lolek

**Comment by domaindrivendev** [comment]
Although I have some plans for the next major version that might help, I've no plans to support this as a first class option.

Your best bet for now would be to experiment a little more with the DelegatingHandler. Theoretically, although I haven't done it, it should be possible to intercept the response before it's returned and modify the Content stream of JSON based on user information available on the request.

**Comment by lolekjohn** [comment]
I have tried using the delgate handler and the operation and document filter for protecting the methods that is not supposed to be displayed for the user (referred #601 )

But, how can we configure the Swagger UI to protect it and ask for the Login as soon as the user try to access the swagger ui page.

We use OAuth 2.0

Any help is really appreciated

**Comment by lolekjohn** [comment]
I figured out the way to do this. Use the latest swashbuckle version and add the below div tag in the injected index.html

`<div id='auth_container'></div>`

This will show an Authorize button in the swagger UI which can be used for authentication and once Authenticated, for all the requests to the API, the JWT token will be passed from the swagger UI
