### ISSUE TITLE
Customise - Right Schema Block

### ISSUE THREAD

**Issue by wpitallo** [domaindrivendev/Swashbuckle#720]
Hi,

Great Job well done!

I want to find out tho if it is possible to create a schema for the right block (see below)? I have managed to create one for the schema in the top block but can seem to get it working in the right block. I have tried the operation and schema filter but both only seem to work on the top block. 

Where in the source code does this block actually created? 

![image](https://cloud.githubusercontent.com/assets/12214559/14590383/26870a3a-04f9-11e6-878d-765900d82b7c.png)

Thanks very much for the help, greatly appreciate it!

**Comment by domaindrivendev** [comment]
When you say a "schema for the right block" I'm not sure what you're referring to? There's already a schema in place for your operation response type (top block) and parameter type (right block). That's what's causing the sample JSON to be displayed.

It looks like maybe you're referring to the default values that get displayed in the sample JSON. Can you confirm this is what you mean?

If so, the easiest way to do this is by applying a custom Schema Filter to the corresponding C# type. For example, if you had the following action:

    public int Create(Product product)
    {
        ...
    }

You can provide sample values for the input model by implementing a custom Schema Filter:

    public class AddProductDefault : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaRegistry schemaRegistry, System.Type type)
        {
            schema.@default = new { description = "A Swashbuckling product", price = 10.0 };
        }
    }

And applying it to the corresponding class:

    [SwaggerSchemaFilter(typeof(AddProduceDefault))]
    public class Product
    {
        ...
    }
