### ISSUE TITLE
Merging XML code comments with Swagger docs in ASP.NET Core 1.0

### ISSUE THREAD

**Issue by gzak** [domaindrivendev/Swashbuckle#722]
We've been following [this blog post](https://damienbod.com/2015/12/13/asp-net-5-mvc-6-api-documentation-using-swagger/) on how to set up Swagger docs on our APIs in ASP.NET Core while also including the `/// xml comments` from the code. It seems there's no way to set this up without a static path to the generated xml file, which is quite unfriendly in a team development environment where the paths differ from dev to dev.

Is there any better way to setup docs with xml comments that doesn't involve hard-coding paths?

**Comment by domaindrivendev** [comment]
I have a couple of sample WebSites in the next-gen working repo. Take a look a the following - it's my best attempt for this so far:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/Basic/Startup.cs#L56

**Comment by damienbod** [comment]
I moved this to a code config file:

https://github.com/damienbod/AspNet5GeoElasticsearch/blob/master/src/AspNet5GeoElasticsearch/Startup.cs

This could be mixed with @domaindrivendev solution with per env settings in the config and user settings

Greetings Damien
