### ISSUE TITLE
Ignore actions with an attribute

### ISSUE THREAD

**Issue by dariusdamalakas** [domaindrivendev/Swashbuckle#723]
Hi,

It hope it's really simple, but I don't see an easy way to exclude any operations that have a specific custom attribute placed on them. The extra bit here is that we want to serve 2 types of swagger documentation - one is private, which includes all API operations, the other is public, and this is where we want to have control on what API operations are included in swagger doc.

Documentation lists several options, but none of them allow to control whether API operation should be included or excluded. I'll examine one by one:

 1. 'IgnoreObsoleteActions' property - that is not implemented as a filter so we can't use this. This is hard-coded in the project. (IMO, this should be changed, but that's a separate issue and out of scope) 
 1. `ApiExplorerSettingsAttribute` - we can't really use this because `IApiExplorer` is configured once per `httpConfiguration`. Again, we want to serve 2 different types of swagger docs from same service. This would work if we'd just want to serve single.
 1. Third suggested option is to use `IDocumentFilter`, but I don't see how I can get to the custom attributes on the specific operation. We can loop through all `Operation`s in the document, but once we have that, there is nothing that links back to controller and method which was used to construct this `Operation`

Any other options out there?

Given that this is a missing piece, I can think of several options how to implement this:
 1. Extend `IOperationFilter` by allowing to tell whether operation should be included, or excluded. 
Cons - changing interface is a breaking change. There are several options, such as change return type from `void` to `bool`. Returning `false` would mean operation is excluded. or add extra parameter `IncludeOperation`, or add extra method `bool IsOperationIncluded()`.

 I like none of these, as they are all breaking changes, and the impact is huge because of existing filters - the area of impact is wide, each operation filter should be updated.
 1. Add some context to `Operation` class, which would allow to trace back to controller/method. 
 We can add `Context IDictionary<string, object>`, which would allow to add any type of context for this operation. Surely, this should be marked with `JsonIgnore` attribute so as not to be included in the schema. Then use `IDocumentFilter` as intended.
 1. Write custom `ISwaggerProvider`, but since `GetSwagger` is not virtual, that means i'd have to copy-paste that method. This will be a disaster to maintain in the long run. Another option is to have `GetApiDescriptionsFor` protected, so we could override this.  Slightly better option.
 1.  Add a new filter `IOperationIncludeFilter`.  Apply filters when [creating `PathItem` objects](https://github.com/domaindrivendev/Swashbuckle/blob/953f9803bdf4a5051dd4ad90f8a6bc0ad8b6af3b/Swashbuckle.Core/Swagger/SwaggerGenerator.cs#L49).

None of these are non-intrusive changes. I like 2nd option of adding operation context most, but I am also keen to hear some opinions on this.

I could submit a PR for the change (whatever option we will chose).

**Comment by domaindrivendev** [comment]
This definitely warrants further discussion and is something that I'd like to simplify in the next major version (which will include breaking changes anyway). However, there is a pretty reasonable workaround that's available today - actually not that dissimilar to option 2. above.

It involves a combination of an Operation and a Document filter. The Operation filter simply adds additional metadata to each Operation and then the Document filter iterates all  PathItems and nullifies it's operations based on the additional metadata. This may be better explained with an example:

    // SwaggerConfig.cs
    c.OperationFilter<TagPrivateOperations>();
    c.DocumentFilter<OmitPrivateOperations>()

    // TagPrivateOperations.cs
    public class TagPrivateOperations : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            // I'm using the Authorize attribute to distinguish between public/private but
            // you could update this to use whatever you want
            var authAttributes = apiDescription.ActionDescriptor.GetFilterPipeline()
                .Select(filterInfo => filterInfo.Instance)
                .OfType<AuthorizeAttribute>();

            if (authAttributes.Any())
                operation.tags = operation.tags.Concat(new[] { "PrivateApi" }).ToList();
        }
    }

    // OmitPrivateOperations.cs
    public class OmitPrivateOperations : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
        {
            foreach (var pathItem in swaggerDoc.paths.Values)
            {
                pathItem.get = NullifyIfPrivateApi(pathItem.get);
                pathItem.put = NullifyIfPrivateApi(pathItem.put);
                pathItem.post = NullifyIfPrivateApi(pathItem.post);
                pathItem.delete = NullifyIfPrivateApi(pathItem.delete);
                pathItem.options = NullifyIfPrivateApi(pathItem.options);
                pathItem.head = NullifyIfPrivateApi(pathItem.head);
                pathItem.patch = NullifyIfPrivateApi(pathItem.patch);
            }
        }

        private Operation NullifyIfPrivateApi(Operation operation)
        {
            if (operation == null) return null;
            return operation.tags.Contains("PrivateApi") ? null : operation;
        }
    }

It's also worth noting that there's several existing Operation properties, already part of the [swagger-spec](http://swagger.io/specification/#operationObject), which you could leverage. In this case I'm just adding an additional "tag". But, perhaps specific "security" requirements might have more semantic meaning. Or, you even have the "vendorExtensions" dictionary for adding whatever additional metadata you'd like (essentially your Context dictionary above) - in this case to be spec-compliant you should prefix the extension name with "X-".

**Comment by dariusdamalakas** [comment]
@domaindrivendev , thanks, that is actually the easiest approach, i'll go ahead with this option. Perhaps with verndor extensions, or maybe a custom as you suggested. I really like this solution - the best that can be achieved with current state.

**Comment by dariusdamalakas** [comment]
Just to add, HTTP verb is missing in `IOperationFilter` as well, i.e. you can't know what verb operation goes with in the filer. Have to revert to workaround as well - have 2 filters to pass through information from operation filter to document filter.

**Comment by domaindrivendev** [comment]
In the op filter you have access to the corresponding ApiDescription, which has the "HttpMethod" property.
