### ISSUE TITLE
Unable to mark a model property as Required in portable class library

### ISSUE THREAD

**Issue by lmjwheeler** [domaindrivendev/Swashbuckle#724]
Hi,

I have just configured Swashbuckle for the first time and everything works very well except for trying to specify "Required" properties. I know that you can do this with annotations but my models are stored in a portable class library meaning I cannot actually reference the required attribute. I cannot move the models into a standard class library because the consumers of the API are mobile devices and having a portable project enables easy export/import.

I have tried using a portable version of data annotations (https://github.com/ryanhorath/PortableDataAnnotations) to try and get around this but as I kind of expected this did not work (the properties marked by the portable required attribute still showed as optional in the Swagger documentation).

Is there any workaround I could use to mark properties of a portable model as required?

Thanks,
Luke

**Comment by Barre14** [comment]
Hi, I'm having the same issue here. Any work arounds? thanks !

**Comment by domaindrivendev** [comment]
Your best option here would be to create a custom ISchemaFilter (see readme) that get's applied to every  complex Schema that's generated. In that filter, you can reflect over the type for properties that are annotated with the PortableDataAnnotation and then update the Schema's "required" property accordingly. Here's an example to get started with:

    public class PortableAnnotationsSchemaFilter : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
        {
            var publicProperties = type.GetProperties(BindingFlags.Instance | BindingFlags.Public);

            schema.required = publicProperties
                .Where(p => p.GetCustomAttribute<RequiredAttribute>() != null) // this would be the portable attribute version
                .Select(p => p.Name)
                .ToList();

            // NOTE: If you're serializing property names to camel case, you'll need to reflect that here
            // in the list of required properties
        }
    }
