### ISSUE TITLE
OAuth2: Server error when no scopes were selected

### ISSUE THREAD

**Issue by iouri-s** [domaindrivendev/Swashbuckle#727]
Using packages Swashbuckle v6.0.0.-rc1-final and Swashbuckle.Core v5.3.2

Repro:

1. Follow the steps in https://github.com/domaindrivendev/Swashbuckle/issues/671 to add AAD OAuth to your app.
2. Uncomment the c.OperationFilter(); 
 line in SwaggerConfig.cs and implement it as described here (scroll down to "Second, create the OperationFilter class").
3. Navigate to your Swagger UI page and click on On/Off switch to initiate the OAuth flow
4. In the dialog that comes up, do not select any scopes and click on "Authorize"

Expected
Some error message or that "Authorize" be disabled and/or that there be a way to specify a default scope in Swagger config that would be selected by default in the UI.

Actual
Browser navigates to this URL:
http://localhost:28506//swagger/ui/null&redirect_uri=http%3A%2F%2Flocalhost%3A28506%2F%2Fswagger%2Fui%2Fo2c-html&realm=%2Fswagger%2Fui%2Fo2c-html%20&client_id=d805a127-8cd3-462d-94fd-6dee3d0ea7c5&scope=&state=undefined&resource=https%3A%2F%2Fmanagement.azure.com%2F

Note that the query string starts with  "&" instead of "?"
Server Error in '/' Application.

A potentially dangerous Request.Path value was detected from the client (&). 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Web.HttpException: A potentially dangerous Request.Path value was detected from the client (&).

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[HttpException (0x80004005): A potentially dangerous Request.Path value was detected from the client (&).]
   System.Web.HttpRequest.ValidateInputIfRequiredByConfig() +9807804
   System.Web.PipelineStepManager.ValidateHelper(HttpContext context) +53

  

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1073.0

**Comment by domaindrivendev** [comment]
This seems more related to [swagger-ui](https://github.com/swagger-api/swagger-ui) as opposed to Swashbuckle. You may have better luck posting this issue over at that repo
