### ISSUE TITLE
Swashbuckle outputs "deprecated": false for all operations

### ISSUE THREAD

**Issue by iouri-s** [domaindrivendev/Swashbuckle#728]
This creates too much noise in the spec.

Swashbuckle should either only output deprecated when it is true  or make Operation.deprecated a Nullable<Boolean>.

**Comment by domaindrivendev** [comment]
The audience of the spec is more likely to be machine than human so I'm not overly concerned about the "extra noise". I probably need some more convincing to go ahead and change this - can you think of a practical example where this presents itself as a pain point?

**Comment by iouri-s** [comment]
This was the feedback on my pull request https://github.com/Azure/azure-rest-api-specs/pull/260#issuecomment-213027795. I think it clutters the output, but tend to agree that this is not really essential.

**Comment by dragonfly91** [comment]
@iouri-s Even I got a similar feedback (https://github.com/Azure/azure-rest-api-specs/pull/495#discussion_r77040605). Any workaround you found for this issue?

**Comment by iouri-s** [comment]
Search-and-replace is the workaround.

**Comment by domaindrivendev** [comment]
See PR #866 which resolves this. Will be available in the upcoming v5.5.0 release
