### ISSUE TITLE
DataAnnotations

### ISSUE THREAD

**Issue by harley333** [domaindrivendev/Swashbuckle#729]
Can Swashbuckler examine model classes for the .Net validation DataAnnotations?  Specifically, StringLengthAttribute, RequiredAttribute, and RangeAttribute.  I believe the Swagger spec already supports these concepts.  It'd be nice to be able to author your .Net model appropriately, and have the generated API reflect these validation attributes.

**Comment by domaindrivendev** [comment]
Have you tried? I believe these are all currently supported

**Comment by harley333** [comment]
I see.  I'm using the MetadataTypeAttribute to add my DataAnnotations.  Any chance support for this can be added?

**Comment by domaindrivendev** [comment]
Wow - I never even knew about that attribute, perhaps because I've worked mainly with NHibernate as opposed to EF. When I have used EF it's always been with code first approach.

I'd imagine support for this would be pretty involved - requiring a lot of reflection. There's soooo much other stuff on the todo list that it's unlikely I'd ever get to this any time soon. I wonder if it's even going to be supported in AspNetCore (i.e. next gen)?

**Comment by harley333** [comment]
Well, I can't speak for AspNetCore, but MetadataTypeAttribute has been around for almost a decade.  I'm guessing they're not going to deprecate it because of a new web framework.  In my opinion, swagger (and swashbuckler) are a little broader in scope than a single framework.

In any case, the following code will add support for MetadataTypeAttribute.  The code assumes a single object is either using meta-data or it's not.  In other words, it does not attempt to merge CustomAttributes from meta-data with the CustomAttributes with the original object.  This is inline with the original intent of the MetadataTypeAttribute.

You can probably better encapsulate the code changes that I've made, but here it is:

\Swashbuckle.Core\Swagger\SchemaExtensions.cs
``` c#
namespace Swashbuckle.Swagger {
    public static class SchemaExtensions {
        public static Schema WithValidationProperties(this Schema schema, JsonProperty jsonProperty) {
            var propInfo = jsonProperty.PropertyInfo();
            if (propInfo == null)
                return schema;

            var metadata = propInfo.DeclaringType.GetCustomAttributes(typeof(MetadataTypeAttribute), true).OfType<MetadataTypeAttribute>().ToArray().FirstOrDefault();
            if (metadata != null) {
                propInfo = metadata.MetadataClassType.GetProperties().SingleOrDefault(x => x.Name == propInfo.Name);
                if (propInfo == null)
                    return schema;
            }
            ...
        }
    }
}
```

\Swashbuckle.Core\Swagger\JsonPropertyExtensions.cs
``` c#
namespace Swashbuckle.Swagger {
    public static class JsonPropertyExtensions {
        public static bool HasAttribute<T>(this JsonProperty jsonProperty) {
            var propInfo = jsonProperty.PropertyInfo();
            var metadata = propInfo.DeclaringType.GetCustomAttributes(typeof(MetadataTypeAttribute), true).OfType<MetadataTypeAttribute>().ToArray().FirstOrDefault();
            if (metadata != null) {
                propInfo = metadata.MetadataClassType.GetProperties().SingleOrDefault(x => x.Name == propInfo.Name);
            }
            return propInfo != null && Attribute.IsDefined(propInfo, typeof(T));
        }
    }
}
```

**Comment by harley333** [comment]
I don't want to be the guy who's bugging the single owner of an after-hours, open-source project.  But, is anyone looking at these pull requests?  Is the project dead?

**Comment by arielcloud** [comment]
I'm not sure what is going with this issue. I saw that I can see [StringLength(100)] dataAnnotation in swaggerUI (by hover the property).
but i can't see EmailAddress dataAnnotation in swagger-UI. 
where can i find in docs the list of annotation that can be displayed in swagger?
is it work in progress? thanks!

**Comment by vitalyobukhov** [comment]
Currently, it's possible to work-around this via custom IDocumentFilter which inspects & modified related Schema required array, but it should be implemented for each needed attribute type.

**Comment by domaindrivendev** [comment]
See ebeddcae9b3cabc1a9f6a04aa558a74dc63f52a0 for the fix. Will release Nuget shortly
