### ISSUE TITLE
JsonProperty and JsonIgnore

### ISSUE THREAD

**Issue by Hainesy** [domaindrivendev/Swashbuckle#73]
I'm using the JsonProperty("PropertyName") attribute to change my JSON property names, and the JsonIgnore attribute to ignore certain properties.

However Swashbuckle seems to be ignoring these when generating documentation.

Would it be a big job to implement this?

**Comment by mattfrear** [comment]
How do we ignore Model properties? I couldn't see it in the documentation.

**Comment by GeorgeTsaplin** [comment]
For Swashbuckle starts using JsonProperty and JsonIgnore you must:
1. use package _Swashbuckle.AspNetCore.Newtonsoft_;
1. at `Startup.ConfigureServices()` add `services.AddSwaggerGenNewtonsoftSupport()`.

**Comment by mattfrear** [comment]
@GeorgeTsaplin your comment is in the wrong repo - this is Swashbuckle (the .NET Framework version). Swashbuckle.AspNetCore is a different GitHub repo.
