### ISSUE TITLE
EnableSwagger throws error when custom root is same as EnableSwaggerUI 

### ISSUE THREAD

**Issue by shibut12** [domaindrivendev/Swashbuckle#731]
EDIT: I have misunderstood that the error was throwing because of word "specification", later realized that the error is because of routes for EnableSwagger and EnableSwaggerUI are same.

I'm using following code to enable swagger ui in my WebAPI OData web application.

```
httpConfiguration
.EnableSwagger("sdk/webapi/specification/{apiVersion}", c =>
{
c.SingleApiVersion(apiVersion, apiDescription);
c.IncludeXmlComments(xmlDocumentationFilePath);
c.DescribeAllEnumsAsStrings();
c.CustomProvider(defaultProvider => 
new ODataSwaggerProvider(defaultProvider, c, httpConfiguration)
.Configure(oDataConfig =>
{
    oDataConfig.IncludeNavigationProperties();
}));
c.OperationFilter<SwaggerMultiLineCommentFilter>();
})
.EnableSwaggerUi("sdk/webapi/specification/{*assetPath}",
c => { }
);
```

Enable swagger is throwing following error when swaggerUI is loading in my browser.

```
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>Unknown API version - index</ExceptionMessage>
<ExceptionType>Swashbuckle.Swagger.UnknownApiVersion</ExceptionType>
<StackTrace>
at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion) at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
</StackTrace>
</Error>
```

I have verified that the error is only occurs when custom route for EnableSwagger and EnableSwaggerUI are same. Is this type of custom route not allowed? is there a work around for this issue?.
For now I have managed to fix this issue by using following routes.
Enableswagger   : sdk/webapi/specification/docs/{apiVersion}
EnableswaggerUI: sdk/webapi/specification/{*assetPath}

**Comment by domaindrivendev** [comment]
There is now a separate project specifically for ASP.NET Core and this gives you more control around the ordering of Swagger/SwaggerUI routes.

Of course this is only available if you've moved your application to ASP.NET Core. I don't plan on implementing it in this, WebAPI-specific. I don't plan on adding this capability for this project so really you're stuck with the workaround suggested above.
