### ISSUE TITLE
IApiExplorer is not reading in any of my ApiControllers -- Swagger Displays No Routes

### ISSUE THREAD

**Issue by EdLichtman** [domaindrivendev/Swashbuckle#737]
I have been having an issue in which Swagger has been displaying no routes after StructureMap Dependency Resolver is applied. I've narrowed down the problem to what I think is the root: When I use Default Conventions, and Scan in System.Web.Http.Descriptions.IApiExplorer, the StructureMap holds an empty IApiExplorer -- as in the IApiExplorer isn't recognizing any of the ApiControllers.

![swagger](https://cloud.githubusercontent.com/assets/13857969/14896953/00b3b6ca-0d4e-11e6-8b98-1db956534e3a.PNG)

First, does this sound like accurate reasoning? I'm not even sure if structuremap reference to IApiExplorer could contain anything, because it's in Interface.

Second, does anyone have any way to do this

 besides just not scanning IApiExplorer?

**Comment by domaindrivendev** [comment]
It sounds like this may not be a Swashbuckle issue. SB depends on IApiExplorer and expects it to be populated but if StructureMap is causing it to be empty, then it's really an issue with StructureMap and not SB.

I'm not ruling out the fact that it could be related to SB but it sounds unlikely. It would be really useful to confirm this. Could you uninstall Swashbuckle and then try inspect ApiExplorer elsewhere - perhaps create a test controller for this purpose. If it's still empty, then this really isn't a SB issue and should be posted elsewhere.

**Comment by EdLichtman** [comment]
Hi! sorry I forgot to close/notify you, I was able to finally solve it with my Senior after I got down to the root of the issue. It was not a swashbuckle issue. That was exactly the problem, it's because we needed to create a registry for IApiExplorers.

I will be closing this issue now. Thanks, and I hope this helps whomever may have the same issues in the future.
