### ISSUE TITLE
Remove Default HTTP 200 as a Response?

### ISSUE THREAD

**Issue by Fabio-Marini** [domaindrivendev/Swashbuckle#742]
Is there a way to tell SB not to generate an HTTP 200? I'm doing a POST and only want to return either 201 or 400, but I can't seem to find a way to do that...

Thanks.

**Comment by parvezah** [comment]
Have you tried the "SwaggerResponseRemoveDefaults" attribute?

**Comment by Fabio-Marini** [comment]
I have now! Thank you very very much - I was hoping it would be straightforward...
