### ISSUE TITLE
Is there a way to mark query parameters as optional?

### ISSUE THREAD

**Issue by WayneHiller** [domaindrivendev/Swashbuckle#746]
Is there a way to mark query parameters as optional?

For example this action:

public IEnumerable<PartData> GetPartsList( string criteria, int? page ) {

in the swagger-ui the page value is required. The criteria is also required when in reality the action might ignore it if it is null or empty.
 
I did not see anything in the XML documentation to mark it optional either?

**Comment by WayneHiller** [comment]
Never mind I figured it out. Need to assign a default value like this:

public IEnumerable GetPartsList( string criteria = null, int? page = null ) {

**Comment by EricSch** [comment]
Didn't work for me. What version did you have?

**Comment by WayneHiller** [comment]
Product version says 5.3.2
