### ISSUE TITLE
Does Swashbuckle support .Net 4.5?

### ISSUE THREAD

**Issue by PeterZong** [domaindrivendev/Swashbuckle#75]
I created a WebAPI with .Net 4.5, then installed Swashbuckle. I attempt to run the application, but got the following error:
Could not load file or assembly 'System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 

Does that mean Swashbuckle doesn't support .Net 4.5?

If I use .Net 4.0, it works.

**Comment by mattlangis** [comment]
Hi Peter,

I know it's a pretty old thread now, but I just create a Pull Request for Swashbuckle to add support for .NET 4.5 - 4.5.2.
See: https://github.com/mattlangis/Swashbuckle/tree/MultiTarget_Net45-452

Note: It's stable, but I did it a way that all the targeted project are built at the same time. It requires Caitlyn extensions to use all the features.

Cheers,
Matt

**Comment by jayoungers** [comment]
I'm running into this issue now as well on the current 5.1.5 version.  I already have those two lines in my web.config (with the current assembly versions I'm using):

      <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>

However, I still get the file not found exception:

A first chance exception of type 'System.IO.FileNotFoundException' occurred in Swashbuckle.Core.dll

Additional information: Could not load file or assembly 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Do I need an entry to match this `PublicKeyToken=b03f5f7f11d50a3a` version?
