### ISSUE TITLE
adding custom header

### ISSUE THREAD

**Issue by sysout0** [domaindrivendev/Swashbuckle#755]
Our API implementation has a required API header and without it the API is just returning 406 Not acceptable. Is there a way to plug a custom header to the requests?

**Comment by alfhv** [comment]
did you check the IOperationFilter ?

**Comment by domaindrivendev** [comment]
@alfhv - an Operation Filter (see readme) is likely what you want here.

Also, this issue is actually a dup of #501. Look there for more info.
