### ISSUE TITLE
Specifying Base Url in ASP.NET Core

### ISSUE THREAD

**Issue by jordanwallwork** [domaindrivendev/Swashbuckle#760]
I can't seem to see how to set the base url? I want to select only actions in a area at /api but it's picking up actions throughout the rest of my application.

I've looked at the `ConfigureSwaggerDocument` and `ConfigureSwaggerSchema` methods but can't seem to see any kinda of setter. Can anyone advise how this can be set?

**Comment by domaindrivendev** [comment]
So, just so I understand your issue fully - do you want to a) set the baseUrl (this tells the swagger-ui the host and port where it can access your API) or do you want to b) limit the operation descriptions that are displayed in your docs. Despite the issue name, I think you might be looking for the latter.

If so, there's a couple of different ways to do this. Probably the easiest would be to restrict the operations that are described by WebAPI's built-in metadata layer - ApiExplorer. The "ApiDescriptions" from there are used by Swashbuckle to generate a corresponding list of Swagger "Operations".

You can use an ApplicationConvention (a framework concept, not SB) to do this and control which controllers or actions should be described through ApiExplorer and hence Swashbuckle:

_Startup.cs_ ...

    services.AddSwaggerGen(c =>
    {
        ...   
    });

    services.Configure<MvcOptions>(c =>
        c.Conventions.Add(new ApiExplorerVisibilityConvention()));

_ApiExplorerVisibilityConvention_

    public class ApiExplorerConvention : IApplicationModelConvention
    {
        public void Apply(ApplicationModel application)
        {
            foreach (var controller in application.Controllers)
            {
                controller.ApiExplorer.IsVisible = (controller.ControllerName == "CrudActions");
                // in this trivial example I'm using controllername, you'll want to look at the metadata available on "controller" and use something more appropriate
            }
        }

**Comment by jordanwallwork** [comment]
Ah ok thanks for clearing that up, you were right I was looking to limit the descriptions that appeared. I had thought that the way to achieve that was to set the baseUrl to mydomain.com/api rather than just mydomain.com; I'll have a crack at restricting the ApiDescriptions as described. Cheers
