### ISSUE TITLE
Add non 200 "default" response in Swagger Doc

### ISSUE THREAD

**Issue by OzBob** [domaindrivendev/Swashbuckle#761]
How to add a "default" handler for non "Success" responses, if the type is known.

To add this to the swagger file with a "default" response like:

        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ProfileListResult"
            }
          },
          **"default": {**
            "description": "response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },

Would I role my own IOperationFilter or is there one already? like: https://github.com/domaindrivendev/Swashbuckle/blob/953f9803bdf4a5051dd4ad90f8a6bc0ad8b6af3b/Swashbuckle.Dummy.Core/SwaggerExtensions/AddDefaultResponse.cs

**Comment by OzBob** [comment]
Self Answer for posterity and the community.

## Controller:

		[SwaggerDefaultResponse(typeof(Models.DetailedErrorListResponse))]

## Attribute

	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false)]
	public sealed class SwaggerDefaultResponseAttribute : Attribute
	{

		public SwaggerDefaultResponseAttribute(Type type)
		{
		}

		public Type Type { get; set; }
	}

## Extension

public class UpdateFileResponseTypeFilter : IOperationFilter
	{
		public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
		{
			if (apiDescription.GetControllerAndActionAttributes<SwaggerResponseRemoveDefaultsAttribute>().Any())
				operation.responses.Clear();

			var defaultResponseAttributes = apiDescription.GetControllerAndActionAttributes<SwaggerDefaultResponseAttribute>();

			foreach (var attr in defaultResponseAttributes)
			{
				var defaultResponse = new Response
				{
					description = "default",
					schema = (attr.Type != null) ? schemaRegistry.GetOrRegister(attr.Type) : null
				};

				if (!operation.responses.ContainsKey("default"))
					operation.responses["default"] = defaultResponse;
				else
					operation.responses.Add(new System.Collections.Generic.KeyValuePair<string, Response>("default", defaultResponse));
			}
		}

		private string InferDescriptionFrom(string statusCode)
		{
			HttpStatusCode enumValue;
			if (Enum.TryParse(statusCode, true, out enumValue))
			{
				return enumValue.ToString();
			}
			return null;
		}
	}

## SwaggerConfig

	c.OperationFilter<UpdateFileResponseTypeFilter>();

**Comment by OzBob** [comment]
@domaindrivendev should this (and some other neat ones I've written) go in SO or pullrequest on 'Swashbuckly.Dummy.Core/SwaggerExtensions' ?

**Comment by koolraap** [comment]
@OzBob FWIW I also posted my solution the other day in #757. Mostly the same, I also made my attribute work so it uses the first attribute it finds in Action, Controller, Assembly order.  I believe your version will prefer the Controller attribute to the Action attribute which is not quite right.

The generic KVP list is genius though, I'm going to steal that, thanks :-)

**Comment by martinRocks** [comment]
I don't know if there is a better fix to this, but I basically used the code above from OzBob except the interface IOperationFilter has changed in the last 6 years.

I needed to add this because my IA tool said the swagger file needed the default response.

`public class UpdateFileResponseTypeFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var customAttributes = ((ControllerActionDescriptor)context.ApiDescription.ActionDescriptor).MethodInfo.CustomAttributes;
            var customAttributeArray = customAttributes as CustomAttributeData[] ?? customAttributes.ToArray();
            if (customAttributeArray.Any())
            {
                operation.Responses.Clear();
            }

            var defaultResponseAttributes = customAttributeArray.FirstOrDefault(x => x.AttributeType == typeof(SwaggerDefaultResponseAttribute));
            if (defaultResponseAttributes != null)
            {
                var swaggerType = (Type)defaultResponseAttributes.ConstructorArguments.FirstOrDefault().Value;

                var defaultResponse = new OpenApiResponse
                {
                    Description = "default",
                    Content = new Dictionary<string, OpenApiMediaType>()
                    {
                        {
                            "application/json", new OpenApiMediaType()
                            {
                                Schema = new OpenApiSchema
                                {
                                    Reference = new OpenApiReference()
                                    {
                                        Id = swaggerType.Name,
                                        Type = ReferenceType.Schema
                                    }
                                }
                            }
                        }
                    }
                };

                if (!operation.Responses.ContainsKey("default"))
                {
                    operation.Responses["default"] = defaultResponse;
                }
                else
                {
                    operation.Responses.Add("default", defaultResponse);
                }
            }
        }`
