### ISSUE TITLE
Support for `id_token` in with `OAuth2SchemeBuilder`

### ISSUE THREAD

**Issue by ilivewithian** [domaindrivendev/Swashbuckle#763]
I am in the process of wiring up the oauth2 config for an api, I can see how to use an `implicit` flow with a `response_type` of token, but not how to request a response type of `token id_token`. Is this a supported behaviour in Swashbuckle?

**Comment by domaindrivendev** [comment]
@ilivewithian - I think this question may be better directed to the swagger-ui folks over here https://github.com/swagger-api/swagger-ui. At it's core, Swashbuckle is a "Swagger Generator". It's the combination of this and an embedded version of the excellent swagger-ui tool that provides the complete documentation package but other than leveraging it, SB has little to do with the UI features, including OAuth support.
