### ISSUE TITLE
Create swagger file for different controllers

### ISSUE THREAD

**Issue by vdecristofaro** [domaindrivendev/Swashbuckle#764]
Is there any way to create a single swagger file for every controller?

**Comment by keg7271** [comment]
Exactly my question.  I would like to expose different controller action methods through different prefixes in Azure API Management.  Therefore, each prefix in Azure API Management requires a separate swagger file.  There may be a better way of doing this using filters, but how?

**Comment by domaindrivendev** [comment]
Currently, the only way to split your API description across multiple Swagger documents is with the use of __MultipleApiVersions__ (as described in readme). With this approach you could probably achieve what you want by specifying a document version for each controller. Of course, this wan't really the intended use for that feature so may confuse some people looking at your code.

As a matter of interest, have you considered implementing a simple post-processing step (using a scripting technology of your choice) that takes the full Swagger description and splits into multiple files based on the value found in each the tags attribute for each Operation?

**Comment by keg7271** [comment]
Thank you for the suggestions.  No I hadn't considered the post-processing step.  That is a simple idea that could yield an appropriate result.  As it turns out, scoping our APIs to APIM prefixes has been moved up to the project level, so single swagger doc per project is working well for us at the moment. Your suggestions provide us additional flexibility if needed.

**Comment by ViacomVMSCore** [comment]
My Web API has multiple controllers and

How can i generate separate swagger for each controller.
How can i generate one swagger for all the controllers.

I have some information on use of multipleApiVersion in swagger config but i am not sure how can i implement for controllers.
