### ISSUE TITLE
update to FLURL breaks Swashbukle

### ISSUE THREAD

**Issue by figuerres** [domaindrivendev/Swashbuckle#765]
I did a package update and found that taking the now current FLUrl package breaks Swashbuckle at runtime with a "Missing Method" Exception, roll back to the old version and it works.

**Comment by domaindrivendev** [comment]
I'm not familiar with FLUrl so you'll have to provide more details - e.g. exact repo steps, full stack trace etc.

**Comment by figuerres** [comment]
Sorry this is in the wrong project, my bad!
I need to post this in the SwashBuckle.Odata Project that is what uses it.
