### ISSUE TITLE
Upgrade to RC 2?

### ISSUE THREAD

**Issue by ivan-prodanov** [domaindrivendev/Swashbuckle#770]
Hello,

When are the dependencies expected to be updated to asp.net core rc2?

**Comment by ilessa** [comment]
~Possibly a duplicate of Issue 768?

**Comment by domaindrivendev** [comment]
This is available with the 6.0.0-beta9 Nuget package. NOTE: The source code for 6.0.0 currently resides at https://github.com/domaindrivendev/Ahoy
