### ISSUE TITLE
swagger-ui.js contains huge commented out lines

### ISSUE THREAD

**Issue by artem-dudarev** [domaindrivendev/Swashbuckle#773]
The swagger-ui.js contains two commented out lines which take 700KB of 1.5MB.
```JS
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJza...
//zY29wZXMgPSBleGlzdGluZ0F1dGhvcml6YXRpb25zW2tleV07XG4gICAg...
```
Is there any reason?

**Comment by domaindrivendev** [comment]
@jondavis-ineight is correct - this is a swagger-ui (a dependency of Swashbuckle) concern and should be posted in that repo
