### ISSUE TITLE
Swashbuckler UI - not showing

### ISSUE THREAD

**Issue by c2793096trbvncom** [domaindrivendev/Swashbuckle#777]
Hi all,

First of all thanks for the great project as Swashbuckle really is. Unfortunately I have a problem with swashbuckle which is really strange.

I used this project in my custom Web API project in C#. I added Swashbuckle via nuget packages I properly configured it and it is working on some group of computers (IE 11 or the newest Chrome version).

But one user which has got the same configuration (IE 11 and Chrome webbrowsers) is unable to view swagger UI...

I extracted the "error" response via Debug in user webbrowser and I received below errors : 

-object.keys not found
-can't find "prototype" property (or null reference exception)
-Not "JSON" definition found

It is very strange because this swagger ui works perfectly on another machines except this one. I noted that this error occurs because IE incompatibility with object.keys keyword, but it does not work on IE 11 (with full updates) and Chrome webbrowsers as well.

Could you help me how can I resolve this problem (swagger ui not showing) ?

I am lookinf forward to mailing from you.

**Comment by domaindrivendev** [comment]
I think this issue would be better directed to the [swagger-ui project](https://github.com/swagger-api/swagger-ui). Swashbuckle embeds this tool but doesn't implement it.
