### ISSUE TITLE
RC2 & RTM Updates

### ISSUE THREAD

**Issue by bradygaster** [domaindrivendev/Swashbuckle#778]
Is there any ETA on when the NuGets will be available to support ASP.NET developers who have started using RC2? Same question for RTM - is there work ongoing to make sure the RTM release will be supported shortly after its release? 

Thanks for continuing to keep this project up! It has made **such** a difference!

**Comment by domaindrivendev** [comment]
Re RC1 - see beta2 milestone here https://github.com/domaindrivendev/Ahoy/milestones

Re RTM - 1 step at a time, I have a day job which is insane at the moment :)

**Comment by bradygaster** [comment]
Understood! Will look forward to RC2 and offer to help with testing if you need it. Let me know if I can be of assistance, sir!

**Comment by JorritSalverda** [comment]
Where can the code for the most recent beta nuget packages be found? It doesn't seem to live in this github repo.

**Comment by wpostma** [comment]
Will try to be of help. Thanks so much for making this project.

**Comment by johnkwaters** [comment]
Can I join the enthusiastic crowd looking for an RC2 compatible release? Anything I can test in beta, or do to help?

**Comment by domaindrivendev** [comment]
This is available with the 6.0.0-beta9 Nuget package. NOTE: The source code for 6.0.0 currently resides at https://github.com/domaindrivendev/Ahoy

**Comment by bradygaster** [comment]
So this package is RC2-capable? Verifying before i tweet. :) https://www.nuget.org/packages/Swashbuckle/6.0.0-beta9

**Comment by johnkwaters** [comment]
Works well!
