### ISSUE TITLE
XmlComments fail to generate comments when models used from external class library

### ISSUE THREAD

**Issue by kmmacgill** [domaindrivendev/Swashbuckle#779]
just got swagger generated and i'm pumped! love this project! but i noticed an issue that i'm hoping to find the answer to but the more i search for it there's no luck, so if anyone has any insight on this i'd love to know what i'm lacking right now.

i'm keeping the models in a business layer and just including them in the controller through a using reference. the main issue is that the summary xmlcomments aren't being recognized in the generated swagger. 

so here's the commented code:

![commented code](https://cloud.githubusercontent.com/assets/16615546/15591066/32fc982a-2358-11e6-9042-83e6590b0efa.PNG)

and the generated swagger:

![uncommented swagger](https://cloud.githubusercontent.com/assets/16615546/15591071/3ef84b2e-2358-11e6-8171-498a87082f4d.PNG)

this confused me. looking into it i recognized that swashbuckle was included in the api project within the solution, but the business project layer does not have it included (this is my prime suspicion for this issue however adding swashbuckle to business layer is an issue as that would create xml file conflictions) so i went to the models folder of api: models->add->existing item->and navigated to the models from my isbnbusiness project: (sorry for long verticle picture)

![structure of solution](https://cloud.githubusercontent.com/assets/16615546/15591455/8018be2a-235a-11e6-8e74-35989d32985f.PNG)

once i did so i changed the namespace and set this up within the controller:

![using statements](https://cloud.githubusercontent.com/assets/16615546/15591516/cd1dad02-235a-11e6-83aa-e1368c5a27a1.PNG)

so its not the prettiest (possibly a buggy patch waiting to burst) solution but when i did this the swagger generated this: 

![commented swagger](https://cloud.githubusercontent.com/assets/16615546/15591301/69649eb6-2359-11e6-94ee-b73f51eca4d7.PNG)

so a fix? maybe. but i'd really rather only be using isbnbusiness' and not the api's models

how can i fix this so that swashbuckle will recognize the comments of the models of the business layer project and generate the <summary> comments i need in swagger?

**Comment by VisualBean** [comment]
There is a very simple solution this.
You need to generate the xmldocumentation for the project where the models reside
in project properties/Build
![windows_10](https://cloud.githubusercontent.com/assets/5294032/16042053/03314812-3239-11e6-9c16-24f5531d832b.png)

Then in swagger.config create a static string that returns the xml file location
```
protected static string GetXmlCommentsForDTO()
        {
            return System.String.Format(@"{0}\bin\MyProject.DTO.XML", System.AppDomain.CurrentDomain.BaseDirectory);
        }

```
And then in the swaggerconfiguration c.IncludeXmlComments(GetXmlCommentsForDTO()); and you are all set :)

**Comment by VisualBean** [comment]
I think this can be closed

**Comment by zeshan-xeesoft** [comment]
@domaindrivendev thank you, I just want to add that we can get comments from multiple files in swashbuckle 

```
c.IncludeXmlComments(GetXmlCommentsPath());
c.IncludeXmlComments(GetXmlCommentsPathCommon());'

private static string GetXmlCommentsPath()
{
   return AppDomain.CurrentDomain.BaseDirectory + @"bin\ReportingAPI.xml";
}

private static string GetXmlCommentsPathCommon()
{
	return AppDomain.CurrentDomain.BaseDirectory + @"bin\ReportingAPI.Common.xml";
}

```

**Comment by sdepouw** [comment]
Chiming in from the future (2025). I've included my XML documentation from my other class library. I've confirmed that the file exists on run (Swashbuckle throws an error if it's missing). But my models are not showing their documentation anyway.

Models within the web project show up fine, as expected.
