### ISSUE TITLE
Core, with net452 framework?

### ISSUE THREAD

**Issue by eshorgan** [domaindrivendev/Swashbuckle#780]
I'm not seeing a way to install Swashbuckle on an Asp.Net Core application using the net452 framework.

Swashbuckle 6.0 will only install on dnx framework.

Swashbuckle 5.0 is set up for OWIN

Is it possible to get Swashbuckle on a Core/net452 application?

**Comment by ritcoder** [comment]
Having the same issue. Any way around it?

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Ahoy/issues/143
