### ISSUE TITLE
'IServiceCollection' does not contain a definition for 'ConfigureSwaggerDocument' since 6.0.0-beta9

### ISSUE THREAD

**Issue by JorritSalverda** [domaindrivendev/Swashbuckle#785]
In package 6.0.0-beta9 I can no longer run the following initialization in Startup.cs.

```
using Swashbuckle.SwaggerGen;

public void ConfigureServices(IServiceCollection services)
{
  services.AddSwaggerGen();

  services.ConfigureSwaggerDocument(options =>
  {
     ...
  });

  services.ConfigureSwaggerSchema(options =>
  {
    ...
  }); 
```

The AddSwaggerGen method works fine, but both Configure methods result in the following type of compile errors:

> 'IServiceCollection' does not contain a definition for 'ConfigureSwaggerDocument'
> 'IServiceCollection' does not contain a definition for 'ConfigureSwaggerSchema'

I'm referencing the following packages in project.json

```
"Swashbuckle.SwaggerGen": "6.0.0-beta9",
"Swashbuckle.SwaggerUi": "6.0.0-beta9"
```
Any idea what causes this? Missing a using?

**Comment by automatonic** [comment]
In my setup, I request the "6.0.0-beta9" versions in my project.json, but get a warning that the restore "falls back": 
![swagger-beta9](https://cloud.githubusercontent.com/assets/139759/15685110/1f2187aa-271f-11e6-993f-99d1e847650e.PNG)

Note, too, that the nuget page also things the -beta9 is the olderversion, even though its publish date is newer:
![image](https://cloud.githubusercontent.com/assets/139759/15685181/77ee0f3e-271f-11e6-81a7-f70382c6f660.png)

I am guessing this is a semver issue and "beta" vs "rc" alphabetical sorting. I think a "6.0.1-beta9" version would solve it?

**Comment by automatonic** [comment]
Note, too, that using "6.0.0-beta9" instead of "6.0.0-beta9-*" yielded the same result. I am sure there are ways to get this configured locally, but setting this up for a "dotnet restore" command for a team/ci looks like it needs a new nuget version pushed?

**Comment by automatonic** [comment]
@domaindrivendev - is it possible to get a .NET core beta package with a revved version number to indicate it is the "newest" pre package? Or am I way off track on this?

**Comment by JorritSalverda** [comment]
It turns out that the following new syntax fixes the issue:

```
using Swashbuckle.SwaggerGen.Generator;

...

public void ConfigureServices(IServiceCollection services)
{
    services.AddSwaggerGen(options =>
    {
        options.SingleApiVersion(new Info
        {
            Version = "v1",
            Title = "Title",
            Description = "Description",
            TermsOfService = "None"
        });

        options.DescribeAllEnumsAsStrings();

        var xmlDocPath = GetPathToXmlDoc();

        if (File.Exists(xmlDocPath))
        {
            options.IncludeXmlComments(xmlDocPath);
        }
    });
```

**Comment by domaindrivendev** [comment]
6.0.0 is still in beta and it's likely the config API will undergo further breaking changes before reaching a more stable release.

It's worth noting that the source code for 6.0.0 currently resides in a separate repo - https://github.com/domaindrivendev/Ahoy. I've added some more up-to-date documentation there but it's still a little light. Your best bet for understanding the current config syntax is to look at the various sample applications in that repo - https://github.com/domaindrivendev/Ahoy/tree/master/test/WebSites
