### ISSUE TITLE
limiting access to swagger ui and json to authenticated users needed

### ISSUE THREAD

**Issue by figuerres** [domaindrivendev/Swashbuckle#786]
I found two closed threads but no actual answer that will work for most users.
the json and html need to be protected from unauthenticated users.
it needs to work with OWIN 
I have oauth / identity server working to pass tokens to the api calls and it seems like a small change would finish the work.
the user needs a key or a token *before* they can access the json doc
if they do not have one then redirect to a login page.   this is happening now but at too late of a stage to block access.
I would offer to do the code but I just do not know this code to even start. wish I could help but only so much time to spend.

**Comment by domaindrivendev** [comment]
This is not something that I'm going to support out-of-the-box.

As described in other threads, this can be done by injecting your own middleware earlier in the pipeline that checks if a Swagger resource (JSON or HTML) is being accessed and then redirecting or delegating to the next middleware as appropriate.

**Comment by lolekjohn** [comment]
I figured out the way to do this. Use the latest swashbuckle version and add the below div tag in the injected index.html

`<div id='auth_container'></div>`

This will show an Authorize button in the swagger UI which can be used for authentication and once Authenticated, for all the requests to the API, the JWT token will be passed from the swagger UI
