### ISSUE TITLE
Customize the same schema in both respone and request.

### ISSUE THREAD

**Issue by maperr** [domaindrivendev/Swashbuckle#787]
Not too sure if this is the right place to ask this question but hi!

I currently use the same schema for both the request parameter and the response but I need to modify the two in different ways (removing certain properties).
Is there a way to apply a schema filter to only request parameters and not have the filter apply itself to responses even though both are the same type?

**Comment by domaindrivendev** [comment]
This is really a dup of #479.

Swagger Schema's are created per Type - they have no knowledge of where the type is being used (i.e. request/response). If you need to be that explicit, then you need to create two types - e.g. OrderRequest, OrderResponse.

Alternatively, Swagger does support the notion of readOnly properties and these can be used to indicate fields that are not applicable (e.g. an Id that gets auto-generated) in say a request to create something.

However, as of now the swagger-ui doesn't hide these so your still a little snookered until that's addressed in the swagger-ui project.
