### ISSUE TITLE
Swashbuckle and certificates

### ISSUE THREAD

**Issue by msclements2003** [domaindrivendev/Swashbuckle#789]
Hello!

We use certificates to call our REST API's.  I would love to use swashbuckle to describe my API's but it seems as though when certificates are involved, it is not supported.

Has anyone does this with swashbuckle or do you know if it's an option or coming in the future?

Thanks in advance!

Sarah

**Comment by domaindrivendev** [comment]
I assume you mean SSL certificates? If so, it should work, so long as you access the UI over https

**Comment by msclements2003** [comment]
I'm sorry for the confusion. We have to pass a client certificate for authentication to our Rest API's and without, you cannot run any of the calls. The SSL is for the transport encryption.

Because our REST API's are expecting a client certificate to be passed, we cannot seem to even get swagger to document our API's.

**Comment by VisualBean** [comment]
I think the problem here is that swagger calls itself through http, but is probably blocked by, it not sending the certificate.

You should remove the need for the certificate, for requests made to anything swagger related.
