### ISSUE TITLE
Add custom JSON Schemas to schema registry

### ISSUE THREAD

**Issue by maperr** [domaindrivendev/Swashbuckle#791]
Hi,

Is there a way to directly add a JSON schema from a file in the solution to the list of schemas in the schema registry, without going through a model class?

Thanks

**Comment by VisualBean** [comment]
ISchemaFilter

**Comment by domaindrivendev** [comment]
I think a Document Filter (see readme) would be more appropriate here because Schema Filters are associated with both a generated Schema and an underlying model class. The entire SwaggerDocument is passed to a Document Filter so here you could add to the Definitions dictionary manually
