### ISSUE TITLE
Error - Conflicting schemaIds: Duplicate schemaIds detected for types and

### ISSUE THREAD

**Issue by msclements2003** [domaindrivendev/Swashbuckle#795]
I am using swagger to decorate my WEB API's.  It works for one set of API's but not for another.  I receive this error:

500 : {"Message":"An error has occurred.","ExceptionMessage":"Conflicting schemaIds: Duplicate schemaIds detected for types and . See the config setting - \"UseFullTypeNameInSchemaIds\" for a potential workaround","ExceptionType":"System.InvalidOperationException","StackTrace":" at Swashbuckle.Swagger.SchemaRegistry.CreateRefSchema..

I have tried adding "c.UseFullTypeNameInSchemaIds();" and that does not seem to resolve my issues.  Any help would be appreciated.

**Comment by domaindrivendev** [comment]
dup of #738

**Comment by msclements2003** [comment]
I finally resolved my issue last week. We have Controllers that inherit from a base class and I had to mark several methods in the base class with the attribute [ApiExplorerSettings(IgnoreApi = true)] with so it did not try and document those.
