### ISSUE TITLE
Model schema for multipart header

### ISSUE THREAD

**Issue by griggsrl** [domaindrivendev/Swashbuckle#796]
Hi, is there a way to specify a model schema when using a multipart POST/PUT request? We're sending both a file and a JSON string mapped to one of our classes and currently no model schema shows up in the generated documentation. What we'd like to add is minimally a model schema for the custom class object (in the example below a Document). I don't see a way to do this currently, at least through the documentation and what I could find on the web.

Our methods are pretty straight forward and not sure if it's helpful but here's what we have:

    [ValidateModel]
    [HttpPost]
    [ValidateMimeMultipartContent]
    [Route(Name = "CreateNewDocument")]
    [SwaggerResponse(HttpStatusCode.Created, null, typeof(Document))]
    [SwaggerResponse(HttpStatusCode.InternalServerError)]
    [SwaggerResponse(HttpStatusCode.BadRequest)]
    [SwaggerResponse(HttpStatusCode.Unauthorized)]
    public async Task<HttpResponseMessage> Post()
    {
            ...
            Document value = null;
            ...
            var provider = new MultipartFormDataStreamProvider(tempPath);

            // Read the form data.
            var allData = await Request.Content.ReadAsMultipartAsync(provider);

            string documentJson = allData.FormData["DocumentModel"].NormalizeJson();

            // get document data
            value = JsonConvert.DeserializeObject<Document>(documentJson);
            ...
    }

**Comment by griggsrl** [comment]
Hi, just following up on this to see if there is any feedback or suggestion for how to proceed.

**Comment by HarelM** [comment]
I had the exact same scenario.
Here is the backwards engineering I made to make it work:
controller action (which receives multi-part data):
```
[SwaggerOperationFilter(typeof(ReportProblemOperationFilter))]
public async Task<IHttpActionResult> PostProblem()
{
    ...
```
The object to specify the schema for is ```ReportProblem```:
The code for the filter referenced above:
```
    public class ReportProblemOperationFilter : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            operation.consumes.Add("application/form-data");
            var reportProblemSchema = schemaRegistry.GetOrRegister(typeof (ReportProblem));
            operation.parameters = new[]
            {
                new Parameter
                {
                    name = "file",
                    @in = "formData",
                    required = true,
                    type = "file",
                    description = "The screenshot to upload"
                },
                new Parameter
                {
                    name = "info",
                    @in = "body",
                    required = true,
                    type = "object",
                    schema = reportProblemSchema,
                    description = "Other related data"
                }
            };
        }
    }
```

Hope this will help you guys, I've search this issue through about 5 different swashbuckle issue to get it going in the right direction.

Final screenshot:
![swagger](https://cloud.githubusercontent.com/assets/3269297/17273011/63bba52a-56af-11e6-9d81-7b53d09df6fb.png)


Here are some related issues:
#283, #638.

**Comment by griggsrl** [comment]
@HarelM Thanks for sharing your solution. I'll give it a shot on our end.

**Comment by domaindrivendev** [comment]
The Operation Filter looks like a good approach to me. @HarelM - will close for now but feel free to re-open if you're still experiencing issues.

**Comment by rvhuang** [comment]
HI all. Is there any way to specify acceptable content type of each part in multi-part request? For example, an API that allows user to upload one or more image files. Thanks.
