### ISSUE TITLE
CustomAsset with IsTemplate enabled

### ISSUE THREAD

**Issue by timhoekstra** [domaindrivendev/Swashbuckle#797]
Our application is configured to disallow inline scripts and styles which leads to a problem in the index.

I was thinking to move the inline javascript to a separate  custom asset and use a custom asset for the index without the inline javascript part. However the templates are not applied on the separate js because it is coded to only apply on the index asset.
Is it possible to get an overload of the CustomAsset method where I can specify if the asset should use templating?

**Comment by domaindrivendev** [comment]
See f71c4fce64bd160bb7853da4561ccaf162bab7a2. Will be available with v5.5.0
