### ISSUE TITLE
display Basic Authentication popup

### ISSUE THREAD

**Issue by alfhv** [domaindrivendev/Swashbuckle#798]
I have some actions/controller with Authorize attribute. I want to display a popup to ask for user/passw when I click "Try it out" swagger button (just first time could be good)
Then this user/passw should be put on Authorization header and be passed to server for validation.
I have already went into issues #326 and #290 but can't make this work. I dont want to display an extra field on each action like #290 suggest with an IOperationFilter.

please advice

**Comment by VisualBean** [comment]
See my blogpost on this matter exactly: http://visualbean.io/blog/adding-basic-authentication-to-swashbuckle

**Comment by VisualBean** [comment]
But Basically, if you add Basic Authentication as an attribute on a given webapi endpoint - most browsers will show you the login popup.
