### ISSUE TITLE
.NET Core RTM?

### ISSUE THREAD

**Issue by bradygaster** [domaindrivendev/Swashbuckle#802]
It's me again. :) Any chance @domaindrivendev has a plan for the release of the RTM-supported version? Or an ETA on when?

**Comment by VisualBean** [comment]
There is a separate project see https://github.com/domaindrivendev/Ahoy

**Comment by bradygaster** [comment]
So - same question. Is there an ETA on the availability of a NuGet package supporting the 1.0 Core release?

**Comment by VisualBean** [comment]
Install-Package Swashbuckle -Pre - you should probably ask over on the other project :)
