### ISSUE TITLE
The latest beta does not work with the .netcore RTM

### ISSUE THREAD

**Issue by johnkwaters** [domaindrivendev/Swashbuckle#805]
Any ETA?

**Comment by johnkwaters** [comment]
And by the way thanks for such an awesome framework! It has become so essential to our devs that I can't even publish our new .net core RTM version of our project until I get swagger support in :-)

**Comment by domaindrivendev** [comment]
As per @christiannagel 's comment, code for the ASP.NET Core version (available as pre-release package 6.0.0-beta901) is currently living in a separate repo.

P.S. Thanks for the support, always nice to hear!
