### ISSUE TITLE
Types are not used for arrays

### ISSUE THREAD

**Issue by Vaccano** [domaindrivendev/Swashbuckle#806]
I have a Web Api 2 service that has a HttpGet method.  One of the parameters looks like this:

`List<ContainerContract> containers`

The json for that parameter that is generated for swagger looks like this:

    {
        "name" : "containerContracts",
        "in" : "query",
        "required" : true,
        "type" : "array",
        "items" : {},
        "collectionFormat" : "multi"
    }

It bothered me that the swagger ui did not show the properties for my contract (it just shows a free text area where I guess I am supposed to enter json).

So I looked at some examples online.  One I found [here](http://petstore.swagger.io/v2/swagger.json) has an example that looks like this:

    {
        "name" : "status",
        "in" : "query",
        "description" : "Status values that need to be considered for filter",
        "required" : true,
        "type" : "array",
        "items" : {
            "type" : "string",
            "enum" : ["available", "pending", "sold"],
            "default" : "available"
        },
        "collectionFormat" : "multi"
    }

The difference here is that the `items` object has a definition in it.  I am imagining that it should have my type (`ContainerContract`) listed in there.

Not sure if this is a bug or a "as yet to be developed feature".  Either way, I thought I would report it.

**Comment by domaindrivendev** [comment]
For parameters that are not in the request body (e.g. "in": "query"), Swagger only supports a subset of the JSONSchema properties:

See http://swagger.io/specification/#itemsObject
"_A limited subset of JSON-Schema's items object. It is used by parameter definitions that are not located in "body"_"

If you read the spec, you'll notice this subset doesn't include the "properties" field. This means Swagger does not support arrays of complex types (i.e. types with properties) in the "query" string.

The example you gave is in the query but it's an array of primitive type (e.g. a string) whereas yours is  an array of complex type (e.g. ContainerContract). If you disagree with this constraint imposed by Swagger, you should open a ticket here: https://github.com/OAI/OpenAPI-Specification.
