### ISSUE TITLE
Parameterless Actions

### ISSUE THREAD

**Issue by Kotemu** [domaindrivendev/Swashbuckle#811]
Hi,

I just had a situation where I implemented parameter-less action which based on odata documentation is perfectly fine. On the other had Swashbuckle assumes that there have to be some:
internal class MapToODataActionParameter line 20:
Contract.Assume(odataActionParametersDescriptor != null);

I get NullReferenceExeption here which according to the code is just as expected. Don't you guys think it should be allowed to provide actions without parameters? 

For my purposes I did allow it and despite the fact I can provide request body from everything work just fine.

**Comment by domaindrivendev** [comment]
The code you're referring to is from a different project, albeit one that extends this one. You'll need to post this issue there https://github.com/rbeauchamp/Swashbuckle.OData
