### ISSUE TITLE
Error 500 : https://localhost:443/Cufx/swagger/docs/v1 when attempting to view the documentation

### ISSUE THREAD

**Issue by komilp13** [domaindrivendev/Swashbuckle#812]
I get the following error when navigating to the documentation url.

`500 : https://localhost:443/Cufx/swagger/docs/v1`

I checked that the xml file is created and is in the proper destination path.  I also confirmed that the app is also looking for the file in the same path.  I looked at the xml file and made sure that it is properly formatted.

I am not sure why else the documentation would not show.  How can I get the actual error that swagger is encountering?

**Comment by domaindrivendev** [comment]
Did you navigate directly to the above URL? It's the one (as opposed to the UI page) that's actually returning the 500 and so is likely to give you more information about the exception.

**Comment by komilp13** [comment]
I did try that.  That is giving me a the 500 error as well.  I think IIS has no idea how to handle that request.  Unfortunately, I get no additional details regarding the error.

**Comment by keith9820** [comment]
I'm having the same issue.  Is there any way to get more information about the 500 error?

**Comment by komilp13** [comment]
Sorry for the late response.  I turned on .net profiling to figure out what the exact issue was.  It was the fact that I had overloaded methods in my controllers which is not supported by swagger.  Hope that helps.
