### ISSUE TITLE
Custom headers for requests without displaying in UI

### ISSUE THREAD

**Issue by AndreyCarter** [domaindrivendev/Swashbuckle#813]
Now I can add custom headers using IOperationFilter and they displays in parameters. But I need to add that headers without displaying in UI (or disable editing).

**Comment by domaindrivendev** [comment]
The swagger-ui does expose an interface for doing. You can see an example here: https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html#L116

SB doesn't expose this directly through it's C# config but it does provide a way to inject some custom JavaScript that runs when the page has loaded. See __InjectJavaScript__ in the readme.
