### ISSUE TITLE
Host Swashbuckle on other Web site

### ISSUE THREAD

**Issue by Jcomper** [domaindrivendev/Swashbuckle#817]
I have Web-API enabled application hosted under IIS. I've added Swashbuckle to it and everything seems to work well. Is it possible to host Swashbuckle on another Web site like API is running on api.cooldomain.com and Swashbuckle documentation is available on docs.cooldomain.com?

**Comment by shashinh** [comment]
Yes - if you have the Swagger coming up already, just pick up the link to the underlying json (you'll find that in the text box at the top of the swagger page - will look similar to xxxxx/swagger/docs/v1) and set up your own swagger site wherever you need and point to that link. This second site will be a pure Swagger UI and have nothing to do with Swashbuckle. Head over to the Swagger UI documentation to understand that set up. In a nutshell:

1. fetch the url to the swagger json for your application as described earlier.
2. download the swagger-ui assets from github - host it as a site at your desired location.
3. modify the url parameter in index.html to point to the url in 1, above. Details [here](https://github.com/swagger-api/swagger-ui#swaggerui).

**Comment by domaindrivendev** [comment]
closing as per @shashinh 's answer
