### ISSUE TITLE
Update swagger-ui - Request CURL output XSS issue

### ISSUE THREAD

**Issue by yngndrw-sage** [domaindrivendev/Swashbuckle#818]
Swashbuckle currently uses an old version of swagger-ui which has an XSS issue when displaying the CURL output.

The corrected line can be seen here:
https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/OperationView.js#L777

The [Swashbuckle Ahoy](https://github.com/domaindrivendev/Ahoy/) repository also has this issue so I've [raised a separate issue there](https://github.com/domaindrivendev/Ahoy/issues/135).

**Issue Reproduction**
Enter ```<script>alert(document.domain);</script>``` into a body parameter of an operation and click "Try it out!", the parameter is output without escaping into the CURL output and an alert box is shown.

**Comment by domaindrivendev** [comment]
According to this - https://github.com/swagger-api/swagger-ui/releases, Swashbuckle/Ahoy is up-to-date with the latest stable release.

I've no plans to start pulling in non-stable dependencies. This doesn't invalidate the issue but it does mean it won't be resolved until the next release of swagger-ui.

It's also worth noting that the swagger-ui is just a folder of static web assets. If you need to use an edge version of the UI, you can use SB to generate and expose your Swagger JSON and then serve up the swagger-ui yourself, using whichever version you want.

**Comment by yngndrw-sage** [comment]
Sorry I looked through the swagger-ui tags and thought there were out-standing releases but didn't realise that the later tags were *-M1/2 version - I should have looked at the releases page instead !

We already have some Javascript overrides to replace the API key with our authentication method so I've just overridden the method in question in there for the time being:
```window.SwaggerUi.Views.OperationView.prototype.showStatus = function (response) { ... };```

Thanks.

**Comment by yngndrw-sage** [comment]
Closing - This looks to be fixed in the latest Swashbuckle.Core NuGet package. (v5.4.0)
