### ISSUE TITLE
How to add newline in note

### ISSUE THREAD

**Issue by luuvthanh87** [domaindrivendev/Swashbuckle#82]
HI all,

I want to add new line in action note. I tried add tag < br /> in note, but it generate \n to client. 
Can I add new line in note?

Thanks.

**Comment by NoUserNames** [comment]
\n\r

**Comment by michael-freidgeim-webjet** [comment]
In SwashBuckle.AspNetCore  `&lt;br /&gt `doesn't work, however for remarks specifying backslash [at the end of line does work](https://gist.github.com/shaunlebron/746476e6e7a4d698b373#gistcomment-2555534),
