### ISSUE TITLE
Add content-security-policy headers

### ISSUE THREAD

**Issue by danderson00** [domaindrivendev/Swashbuckle#826]
This is required to mitigate the security vulnerability described at https://nodesecurity.io/advisories/126 and https://github.com/swagger-api/swagger-ui/issues/1865, and any potential future vulnerabilities.

**Comment by domaindrivendev** [comment]
v5.5.0 upgrades swagger-ui to 2.2.4 which I believe fixes all known XSS vulnerabilities

**Comment by domaindrivendev** [comment]
Will be available with the upcoming v5.5.0 release
