### ISSUE TITLE
Swagger Doc does not generate If I remove "/api" from Asp.Net Web API routing

### ISSUE THREAD

**Issue by deepumi** [domaindrivendev/Swashbuckle#829]
Hi,

I have got a problem with swagger doc.  I was trying to remove the "api" from web api config routing and from controller as well like below.

**Expected**
https://api.mydomain.com/v1/{controller} should go.. 

**Actual :** 
https://api.mydomain.com/api/v1/{controller}  

**WebApiConfig Register method**
```
 config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
```
**SampleApiController class**
  ```
    [RoutePrefix("v1/search")]
    public class SampleApiController : ApiController
    {
        [Route("{userid}/{keyword}/", Name = "", Order = 1)]
        [ResponseType(typeof(MyModel))]
        public IHttpActionResult Get(string userId, string keyword)
        {
            try
            {
                return Ok(GetSearchResult(userId,keyword));
            }
            catch{}
             return BadRequest();
        }
     }
```
Since we are hosting the API service as a sub sub-site (virtual directory) and we don't want to see another URL pattern inside API service.  (**/subsite/api/controller/**)

Note: Web API still works if I add / remove the "api" prefix from routing, However, swagger does not generate and no error. Also, once I revert back to 'api/{controller/{id} every thing works fine..

**Comment by domaindrivendev** [comment]
This is odd - SB should be completely agnostic of the route contents, prefix or no prefix. When you say "swagger does not generate" what exactly do you mean? Can you access the Swagger JSON at "swagger/docs/v1" and it just returns no path items? Is the UI loading with an empty contents? Have you checked the JavaScript console?

If you can provide me with more specifics around what your observing that may help a bit. Thanks

**Comment by deepumi** [comment]
@domaindrivendev Thank you for getting back to me. 

I am able to access the swagger doc. And the path is not generated, its empty. Below, please find the following steps to reproduce the issue. 

1) Created Asp.net WebApi Empty project template with .Net 4.6.1 framework
2) Installed Swashbuckle via nuget latest
3) Swagger.config file code below

```
 public class SwaggerConfig
    {
        public static void Register()
        {
            GlobalConfiguration.Configuration
                .EnableSwagger(c =>
                {
                    c.MultipleApiVersions(
                        (apiDesc, version) =>
                        {
                            var path = apiDesc.RelativePath.Split('/');
                            var pathVersion = path[1];
                            return CultureInfo.InvariantCulture.CompareInfo.IndexOf(pathVersion, version, CompareOptions.IgnoreCase) >= 0;
                        },
                        vc =>
                        {
                            vc.Version("v2", "API info")
                               .Description("A sample API for testing and prototyping Swashbuckle features")
                               .TermsOfService("Some terms")
                               .Contact(cc => cc
                                    .Name("Some contact")
                                    .Url("http://tempuri.org/contact")
                                    .Email("api@careeronestop.org"))
                                .License(lc => lc
                                    .Name("Some License")
                                    .Url("http://tempuri.org/license"));

                            vc.Version("v1", "API info");
                        });

                    c.ApiKey("apiKey")
                        .Description("API Key Authentication")
                        .Name("apiKey")
                        .In("header");

                    c.IncludeXmlComments(GetXmlCommentsPath());

                    //c.OperationFilter<AddDefaultResponse>();

                    c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());

                })
                .EnableSwaggerUi(c =>
                {

                });
        }

        private static string GetXmlCommentsPath()
        {
            return string.Format(@"{0}\bin\SwashbuckleWebApiDemo.XML", AppDomain.CurrentDomain.BaseDirectory);
        }
``` 
4) No route change in the WebApiConfig class.
5) Added homecontroller.cs file inside controller/v1 folder.
  ```
namespace SwashbuckleWebApiDemo.Controllers.v1
{
    [RoutePrefix("v1/home")]
    public class HomeController : ApiController
    {
        /// <summary>
        /// Hello world
        /// </summary>
        /// <remarks>Get data</remarks>
        /// <response code="400">Bad request</response>
        /// <response code="500">Internal Server Error</response>
        [Route("")]
        [ResponseType(typeof(string))]
        public IHttpActionResult Get()
        {
            return Ok("Hello world");
        }
    }
}
```
 6) Swagger Json file 
```
{
	"swagger": "2.0",
	"info": {
		"version": "v1",
		"title": "API info"
	},
	"host": "localhost:55670",
	"schemes": [
		"http"
	],
	"paths": {},
	"definitions": {},
	"securityDefinitions": {
		"apiKey": {
			"type": "apiKey",
			"description": "API Key Authentication",
			"name": "apiKey",
			"in": "header"
		}
	}
}
```
7) I am able to browse the service via URL **http://localhost:55670/v1/home** works fine.. Swagger path does not generate.

**Comment by deepumi** [comment]
@domaindrivendev Got a chance to check this?

**Comment by domaindrivendev** [comment]
OK - I think I see what the problem is here. The function your provide for determining which ApiDescription's belong to a given version needs to be updated to reflect the changes to your routes:

    (apiDesc, version) =>
    {
        var path = apiDesc.RelativePath.Split('/');
        var pathVersion = path[1]; // if you remove "api" from the route this should be path[0]
        return CultureInfo.InvariantCulture.CompareInfo.IndexOf(pathVersion, version, CompareOptions.IgnoreCase) >= 0;
    }
