### ISSUE TITLE
SwaggerUI failing due to faulty generated schema definition

### ISSUE THREAD

**Issue by dneimke** [domaindrivendev/Swashbuckle#833]
I have a custom object as an input parameter to an Api method and I'm using a custom model binder to bind to URI params:

```
[HttpGet("foo")]
public IActionResult GetFoo([MyCustomRequestBinder]MyMvcRequest requestModel)
```

The SwaggerDoc that is getting generated reports @in as 'custom' as seen below but doesn't generate a type for it - even though the Type is getting picked up correctly in the Definitions section of the document:

**Method Parameter Definition (minus type attribute):**
```
"parameters": [{
    "name": "requestModel",
    "in": "custom",
    "required": false
}],
```

**Definition Section:**
```
"definitions": {
    "MyMvcRequest": {
        "type": "object",
```

The lack of a type attribute causes the SwaggerUI to fail with a javascript error.

Is there something I need to do to get this parameter picked up correctly?

**Comment by dneimke** [comment]
FYI... this *may* be related to .NET Core RTM upgrade.

**Comment by domaindrivendev** [comment]
When you use a custom model binder, Swashbuckle has no way of knowing how to describe the parameter and it's attempt in this case is clearly wrong - "custom" is not a valid value and hence the generated spec is invalid.

You can write a custom IOperationFilter (see readme) which inspects the ApiDescription for parameters that are decorated with your custom binding attribute and if so, update the Parameter description accordingly.

Another alternative is to write your custom bindings in a way that still lets Swashbuckle know how they should be bound - check out #518 as that was resolved with a similar approach

**Comment by dneimke** [comment]
Thanks @domaindrivendev.  I've since implemented the solution that you have recommended - apologies for not updating this Issue... I forgot that I had raised it.

I appreciate you following this up!

Cheers.
