### ISSUE TITLE
Generate url in documentation with lower case

### ISSUE THREAD

**Issue by rafalkasa** [domaindrivendev/Swashbuckle#834]
Hello

I would like to know if it's any switch or option to generate documentation by Swashbuckle using lower case instead only default .NET PascalCase.

In my documentation, I would like to have **/api/clients** istead of **/api/Clients**

Thank you in advance for any help

**Comment by smaglio81** [comment]
Hi @rafalkasa,

I've only started using Swashbuckle a few days ago, but I wanted the same thing. I think I came up with a pseudo-solution, but it's not exactly what I wanted.

The work-around makes the operations within a "controller" definition lowercase. This makes operation definitions, the generated url and generated .json file also use lowercase. The UI still shows the controller name with Upper case. I figure you can fix that with the UI css, but I would rather it be done with the "schema document" information.

This [`LowercaseDocumentFilter.cs` gist](https://gist.github.com/smaglio81/e57a8bdf0541933d7004665a85a7b198) looks through the "paths" and lowercases their keys. That seems to do it.

You can add it into your `SwaggerConfig.cs` with:
```
c.DocumentFilter<LowercaseDocumentFilter>();
````

![image](https://cloud.githubusercontent.com/assets/169953/18407619/b5283b9a-76ca-11e6-8a36-0290e9b220f4.png)

**Comment by rafalkasa** [comment]
Hi @smaglio81 

Your LowercaseDocumentFilter is working amazing :-) Thank you for your work! Maybe you can create Pull  Request and add this to Swashbuckle project.

Instead of changing c.DocumentFilter<LowercaseDocumentFilter>(); inside SwaggerConfig.cs Swashbuckle has very nice interface to do this:

- version 5.*
```
httpConfiguration
    .EnableSwagger(c =>
	{
		c.DocumentFilter<LowercaseDocumentFilter>();
	});
```
- version 6.* - .NET Core
```
	services.AddSwaggerGen(c =>
	{
		c.DocumentFilter<LowercaseDocumentFilter>();
	});
```
Here [LowercaseDocumentFilter gist](https://gist.github.com/rafalkasa/01d5e3b265e5aa075678e0adfd54e23f) you will find changed your class for version 6.* Swashbuckle and .NET Core
because Swashbuckle team change IDocumentFilter interface and also SwaggerDocument class.

**Comment by jonorogers** [comment]
Hi guys, this can break some swagger-codegen solutions because it lower-cases the parameter names, and some of the codegen's are case sensitive. Add this method to the LowerCaseDocumentFilter:

```
private string LowercaseEverythingButParameters(string key) {
            return String.Join('/', key.Split('/').Select(x => x.Contains("{") ? x : x.ToLower()));
        }
```

And change line 21 to:
         `       var newKey = LowercaseEverythingButParameters(path.Key);`

**Comment by hanssens** [comment]
Great addition, @jonorogers! For everyone here is an [updated gist](https://gist.github.com/hanssens/3a0a398bbf0969afb40360a7e6371396) to reflect those changes as well.

**Comment by wickdninja** [comment]
I was running into the same issue using dotnetcore 2.1.
 
I wouldn't doubt that there is a better way, but this worked for me.

```
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger(c =>
            {
                c.PreSerializeFilters.Add((document, request) =>
                {
                    var paths = document.Paths.ToDictionary(item => item.Key.ToLowerInvariant(), item => item.Value);
                    document.Paths.Clear();
                    foreach (var pathItem in paths)
                    {
                        document.Paths.Add(pathItem.Key, pathItem.Value);
                    }
                });
            });
         }
```

**Comment by yann510** [comment]
Here is a simplified version of the above gists for everyone consulting this issue as reference: [LowercaseDocumentFilter](https://gist.github.com/yann510/76a2fc61605811f4e95720c2d405ca00)

**Comment by elAndyG** [comment]
@yann510 can do a lower camel case. if you like `someRestWord `instead of `somerestword`.

`return string.Join('/', key.Split('/').Select(x => x.Contains("{") || x.Length < 2 ? x : char.ToLowerInvariant(x[0]) + x.Substring(1)));`

only thing that stinks of you have `ABCName`, it will convert it to `aBCName`.

**Comment by ka-bezmaternykh** [comment]
Run into same question, but use another solution:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    // Must be before AddMvc
    services.AddRouting(options => options.LowercaseUrls = true);
}
```

**Comment by hanssens** [comment]
@ka-bezmaternykh Unfortunately, that alone didn't work for me for the generated Swagger documentation. But agreed it is mandatory for the ASP.NET routes to be lowercased by default.

**Comment by mesh7s** [comment]
all of the above give errors on .net core 3.1 for some reason, so I mixed some answers to the following:
```
public class LowerCaseDocumentFilter : IDocumentFilter
{
     public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
     {
            var paths = swaggerDoc.Paths.ToDictionary(entry => LowercaseEverythingButParameters(entry.Key),
                entry => entry.Value);
            swaggerDoc.Paths = new OpenApiPaths();
            foreach (var (key, value) in paths)
            {
                swaggerDoc.Paths.Add(key, value);
            }
      }

        private static string LowercaseEverythingButParameters(string key) => string.Join('/', key.Split('/').Select(x => x.Contains("{") ? x : x.ToLower()));
}
```

**Comment by VILLAN3LL3** [comment]
If you want the parameters to be lowercase, too, you can do the following (tested with .NET 5):

```
public class LowerCaseDocumentFilter : IDocumentFilter
    {
        public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
        {
            var paths = swaggerDoc.Paths.ToDictionary(
                entry => string.Join('/', entry.Key.Split('/').Select(x => x.ToLower())),
                entry => entry.Value);

            swaggerDoc.Paths = new OpenApiPaths();

            foreach ((string key, OpenApiPathItem value) in paths)
            {
                foreach (OpenApiParameter param in value.Operations.SelectMany(o => o.Value.Parameters))
                {
                    param.Name = param.Name.ToLower();
                }

                swaggerDoc.Paths.Add(key, value);
            }
        }
    }
```

**Comment by mmsaffari** [comment]
When building `paths` Dictionary, couldn't you just use `entry => entry.Key.ToLower()` instead of `entry => string.Join('/', entry.Key.Split('/').Select(x => x.ToLower()))` ?
