### ISSUE TITLE
IOperationFilter.Apply Method not found(OWIN)

### ISSUE THREAD

**Issue by CindyHuang-cn** [domaindrivendev/Swashbuckle#836]
I'm currently use Swashbuckle.Core 5.3.2 to enable a ASP.NET project for OWIN, and enable oAuth2 for swagger.
In SwaggerConfig.cs, I enable an IOperationFilter to add the appropriate security definition like this:
  _c.OperationFilter<SwaggerOperationTest>();_
Then I define a test operation filter like this: 
    _using Swashbuckle.Swagger;
    using System.Web.Http.Description;

    public class SwaggerOperationTest : IOperationFilter
    {
        void IOperationFilter.Apply(
            Operation operation,
            SchemaRegistry schemaRegistry,
            ApiDescription apiDescription)
        {
        }
    }_

However, when I compile the project I get the following error, it seems that the Apply method is not found. I tried to add full namespace path for each class in this file, but it doesn't work.

_1>EXEC : error : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
1>  LoaderException:
1>  System.MissingMethodException: Method not found: 'Void Swashbuckle.Swagger.IOperationFilter.Apply(Swashbuckle.Swagger.Operation, Swashbuckle.Swagger.SchemaRegistry, System.Web.Http.Description.ApiDescription)'.
1>F:\Job\MSEG\ProfileService\AP-git\NugetPackages\Microsoft.Diagnostics.Tracing.EventRegister.1.0.26\build\Microsoft.Diagnostics.Tracing.EventRegister.targets(132,5): error MSB3073: The command ""F:\Job\MSEG\ProfileService\AP-git\NugetPackages\Microsoft.Diagnostics.Tracing.EventRegister.1.0.26\build\eventRegister.exe" -DumpRegDlls @"F:\Job\MSEG\ProfileService\AP-git\MSEG.CMC.AgentService\Product\Common\AgentService.Common\bin\Debug\AgentService.Common.eventRegister.rsp" "F:\Job\MSEG\ProfileService\AP-git\MSEG.CMC.AgentService\Product\Common\AgentService.Common\bin\Debug\AgentService.Common.dll" " exited with code 1._

I also tried to create a empty project with just a operation filter class, and call it by SwaggerConfig.cs in my project, it actually works fine, and AAD auth works perfect.

My question is: why is that happen? What can I do if I don't want to add a project just for swagger operation filter?

**Comment by Valchris** [comment]
The issue is root caused by #133.
