### ISSUE TITLE
Model documentation is empty when using SwaggerResponseAttribute with List, IList type

### ISSUE THREAD

**Issue by tenbits** [domaindrivendev/Swashbuckle#839]
Hello Team,

we having here an issue with the webapi documentation when using diverse `List` types in `SwaggerResponseAttribte`. The documentation is not generated and the response model cell is empty.

Consider this example:
```c#
[SwaggerResponse(HttpStatusCode.Conflict, Description = "Foo", Type = typeof(List<Bar>))]
```

But when we wrap the List into a container class, the docmentation is rendered as expected.

```c#
class Errors { public List<Bar> Errors {get;set;}  }
[SwaggerResponse(HttpStatusCode.Conflict, Description = "Foo", Type = typeof(Errors))]
```

Is there some workarounds to use the List types directly as a response type?

Thank you for your time, 
Alex

:pencil2: (1)

Just looked into the generated api json, and the response model **is in** there

```json
"409":{"description":"Foo","schema":{"type":"array","items":{"$ref":"#/definitions/Bar"}}}
```

_And definitions have also the model `Bar`._

So it must be the UI bug, should I open a new issue in `swagger-ui` repo?

**Comment by domaindrivendev** [comment]
@tenbits - wondering if you ever got this resolved? I think swagger-ui repo is the correct place for bugs like this. SB bundles in a version of swagger-ui to make it easy to get up and running with API docs. But, first and foremost it's a Swagger generator - so if the generated JSON looks correct it's most likely an issue with the swagger-ui
