### ISSUE TITLE
How to add my token to the header of my request?

### ISSUE THREAD

**Issue by zh-wowtv** [domaindrivendev/Swashbuckle#841]
I know this is a swagger-ui issue. But I don't know where is the code or configuration for swagger-ui in Swashbuckle. What I want is to add a token to every request after I got the token. What should I do? Thanks.

**Comment by zh-wowtv** [comment]
Here is my complete question. 

http://stackoverflow.com/questions/39009758/enable-bearer-token-in-swashbuckle-swagger-document

**Comment by urig** [comment]
@domaindrivendev I've encountered the same issue and opened an identical (albeit more detailed) issue for it: https://github.com/domaindrivendev/Swashbuckle/issues/851.   
I have a PR with a resolution for it ready for review here: https://github.com/domaindrivendev/Swashbuckle/pull/853. Tx.

**Comment by domaindrivendev** [comment]
Closing in favor of #851
