### ISSUE TITLE
Adding securityField is breaking API GET call with parameters

### ISSUE THREAD

**Issue by amitkhese** [domaindrivendev/Swashbuckle#843]
var securityField = new Dictionary<string, IEnumerable<string>>();
  securityField.Add("Authorization", new List<string>());
  operation.security.Add(securityField);

Adding securityField is breaking API GET call with parameters. Given 401 error.
But Post and Get without parameter are working getting proper result.
Please suggest

**Comment by domaindrivendev** [comment]
Can you provide some more detail please - ideally an exact set of repro steps. Thanks
