### ISSUE TITLE
How to map a c# dictionary<int, string> swagger

### ISSUE THREAD

**Issue by daxu7509** [domaindrivendev/Swashbuckle#844]
I have a web api which returns a object that contains dictionary property

public Dictionary<int, string> Roles { get; set; }

I use swashbuckle to publish it into swagger format and this is what I get:

"Roles":{"type":"object","additionalProperties":{"type":"string"}}

I am not really sure this is correct? As I thought at least it should be something like

"Roles":{"type":"object","additionalProperties":{"type":"int", "type":"string"}}
How can represent my dictionary correctly in swagger format?

**Comment by domaindrivendev** [comment]
This is the correct description. Remember that Swagger is describing JSON structures and not C# types. In JSON, there's no equivalent of Dictionary&lt;int, string&gt;. The closest representation would be the following:

```json
{
  "1": "foo",
  "2": "bar"
}
```

And sure enough if you return an object of this type from a WebAPI action, it will be serialized exactly like this - try for yourself. Furthermore, the JSON Schema that Swashbuckle is generating describes this structure accurately:

```
{"type":"object","additionalProperties":{"type":"string"}}
```
