### ISSUE TITLE
Get 404 error when trying to customize the UI

### ISSUE THREAD

**Issue by zh-wowtv** [domaindrivendev/Swashbuckle#846]
I'm using the sample index.html and change the url to my url. But got the following errors:

> Failed to load resource: the server responded with a status of 404 (Not Found)

For all the files in **lib**. What could be the reason? Thanks.

**Comment by zh-wowtv** [comment]
The full error message is:

> Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:53670/swagger/ui/lib/underscore-min-js
> 
> Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:53670/swagger/ui/lib/handlebars-2-0-0-js
> 
> Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:53670/swagger/ui/lib/underscore-min-js
> 
> Failed to load resource: the server responded with a status of 404 (Not Found) backbone-min-js:3 Uncaught TypeError: Cannot read property 'each' of undefined swagger-ui-js:9
> 
> Uncaught ReferenceError: Handlebars is not defined http://localhost:53670/swagger/ui/lib/highlight-7-3-pack-js Failed to load resource: the server responded with a status of 404 (Not Found) index:54
> 
> Uncaught ReferenceError: SwaggerUi is not defined

**Comment by zh-wowtv** [comment]
Look through the source code. I'm wondering where all the js files are?

**Comment by domaindrivendev** [comment]
swagger-ui is a git submodule. You need to run "git submodule update" from solution root

**Comment by domaindrivendev** [comment]
Are u using a custom index.html? If so, you'll need to base it off this one (note the dots in the names replaced by dashes) - https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html

**Comment by zh-wowtv** [comment]
Yes, I'm using this one.

**Comment by zh-wowtv** [comment]
@domaindrivendev This index.html works. The one I used is:

https://github.com/domaindrivendev/Swashbuckle/blob/v5.2.1/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html

So please change the document.

**Comment by zh-wowtv** [comment]
How can I add an asset file and referred by my index.html? For example, I add a logo.png to the same folder as the index.html. But it doesn't work when I refer to it loke **<img src="logo.png">**.

**Comment by drightchao** [comment]
I think you can try inject stylesheet or javascript to make the change.

**Comment by zh-wowtv** [comment]
Solved the issue already.

**Comment by Marusyk** [comment]
What is solution for that?

**Comment by dwasyluk** [comment]
@zh-wowtv what was the solution?

**Comment by dozieogbo** [comment]
The custom index.html i still causing issues till date. I think the link should be changed.
