### ISSUE TITLE
Route custom parameter attribute causes the Swashbuckle to ignore this route

### ISSUE THREAD

**Issue by reflash** [domaindrivendev/Swashbuckle#847]
Hello,

I just have a problem with some routes, where we use custom attributes.
The idea that we get an id and then use a ModelBinderAttribute to load the entity by its id.
Unfortunately this causes problems with documentation generation and I couldn't figure out how this could be fixed or workaround-ed.

```c#
[Route( "controller/param1/{param1Id:int}/param2/{param2Id:int}" )]
public Result GetSomething(
[Load( Param="param1Id" )] Param1 param1,
[Load( Param="param2Id" )] Param2 param2)
```

I've just seen similar issues with FromUri attribute, but couldn't understand how to map this solution for my case.
#518

**Comment by domaindrivendev** [comment]
Have you tried using a custom IOperationFilter (see readme)? You would need to inspect the individual parameters on the provided ApiDescription and check to see if they're decorated with the LoadAttribute. If so, then you would have to update the Parameter description accordingly. A little involved but probably your best bet at this point
