### ISSUE TITLE
Optional routeTemplate parameters is tagged as required in spec

### ISSUE THREAD

**Issue by moander** [domaindrivendev/Swashbuckle#849]
```csharp
config.Routes.MapHttpRoute(
    name: "DefaultApi",
    routeTemplate: "api/{controller}/{id}",
    defaults: new { id = RouteParameter.Optional }
);
```

```csharp
public class ValuesController : ApiController
{
    // GET api/<controller>
    public IEnumerable<string> Get()
    {
        return new string[] { "value1", "value2" };
    }

    // GET api/<controller>/5
    public string Get(int id)
    {
        return "value";
    }
}
```

The path parameter gets documented as required in swagger.json:
```json
{
  "/api/Values": {
    "get": {
      "operationId": "Values_Get"
    }
  },
  "/api/Values/{id}": {
    "get": {
      "operationId": "Values_Get",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "type": "integer",
          "format": "int32"
        }
      ]
    }
  }
}
```

Same result using a nullable int
```csharp
public class ValuesController : ApiController
{
    public string Get(int? id)
    {
        return "value";
    }
}
```

Or optional string
```csharp
public class ValuesController : ApiController
{
    public string Get(string id = null)
    {
        return "value";
    }
}
```

**Comment by moander** [comment]
I did some more testing on how things are handled by asp.net:

/{id} is required
```csharp
    public string Get(int id)

    public string Get(int? id)

    public string Get(string id)
```

/{id} is optional (but documented as required by Swashbuckle)
```csharp
    public string Get(int? id = null)

    public string Get(string id = null)
```

**Comment by EricSch** [comment]
Same here, it is annoying

**Comment by domaindrivendev** [comment]
Swagger doesn't support optional "path" parameters because the path (less query string) uniquely identifies an operation. It's opinionated on this matter - if you want to describe it via Swagger you'll need to split into separate operations.

NOTE: this is a Swagger constraint, not a Swashbuckle constraint

**Comment by moander** [comment]
What if we look at the optional parameters as overloads instead?

This
```csharp
 public string Get() {}
 public string Get(string id) {}
```
and this
```csharp
 public string Get(string id = null) {}
```
could both be described in swagger as
```json
{
  "/api/Values": {
    "get": {
      "operationId": "Values_Get"
    }
  },
  "/api/Values/{id}": {
    "get": {
      "operationId": "Values_Get_id",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "type": "integer",
          "format": "int32"
        }
      ]
    }
  }
}
```

**Comment by domaindrivendev** [comment]
@moander - that's exactly the approach I would recommend. It keeps your contract intact and minimizes code changes because the new overloads can delegate to your existing method - which should be made private

**Comment by hidegh** [comment]
IMO the v1.0 swagger/swaschbuckle version was better on it. *It simply treated that optional parameter as a mandatory and at least the rest of the UI was working.* For the given optional param. the generated command was not working, yet...

**Now with v2.0 we simply get an error when hit swagger URL.** The advice above also stinks, since it forces us to bypass exiting coding practices.

**How to revert to v1.0 behaviour and add a big WARNING to the desc.?**

**Comment by domaindrivendev** [comment]
@hidegh - please read the [contribution guidelines](https://github.com/domaindrivendev/Swashbuckle/blob/master/CONTRIBUTING.md) and consider how you articulate your opinions, keeping in mind that SB is a free and open source project provided to you at no financial gain to its authors.

A more constructive and understanding argument is always more likely to be actioned. With that said, I agree that defaulting to required and not raising an error is a better experience for SB consumers. I will revert that change in the [AspNetCore implementation](https://github.com/domaindrivendev/Swashbuckle.AspNetCore)

I'll also add that I have no plans to support optional path parameters by generating multiple operation descriptions within SB. I don't want to take on the additional complexity to support what I believe to be an anti-pattern.

**Comment by bobwah** [comment]
[Route("attributes/{someValue:alpha}")]
[Route("attributes/{someDecimal:decimal}")]
public ActionResult SetAttribute(decimal? someDecimal = null, string someValue = null)

For the above do I have to use two operations then :(
