### ISSUE TITLE
Issue with VB.NET

### ISSUE THREAD

**Issue by guidoffm** [domaindrivendev/Swashbuckle#85]
The package can be installe within a VB.NET project and it inserts a C# file which does not work at all.

**Comment by jbencina** [comment]
If anyone comes across this on Google for help with VB.NET.

1. Create a SwaggerConfig.vb class file in the App_Start of your Web API project
2. Modify the file as such
```
Imports System.Web.Http
Imports WebActivatorEx
Imports Swashbuckle.Application
<Assembly: PreApplicationStartMethod(GetType(SwaggerConfig), "Register")> 

Public Class SwaggerConfig
    Public Shared Sub Register()
        Dim thisAssembly = GetType(SwaggerConfig).Assembly

        GlobalConfiguration.Configuration.EnableSwagger(Function(c) c.SingleApiVersion("v1", "Your API Name")).EnableSwaggerUi()
    End Sub

End Class
```

This is the bare minimum. You can follow the annotations in the SwaggerConfig.cs file as well as the readme for any additional options you may want to configure.

**Comment by tomatdaysmart** [comment]
I've added that file to my project, however I am getting this error: 

Method not found: 'Swashbuckle.Application.SwaggerEnabledConfiguration Swashbuckle.Application.HttpConfigurationExtensions.EnableSwagger(System.Web.Http.HttpConfiguration, System.Action`1<Swashbuckle.Application.SwaggerDocsConfig>)'.

I'm referencing this this library version: Swashbuckle.Core.5.0.0\lib\net40\Swashbuckle.Core.dll 

Any Ideas?

**Comment by vbjay** [comment]
Please just detect language and place this file renamed to .vb in project instead of the cs file.  
[SwaggerConfig.txt](https://github.com/domaindrivendev/Swashbuckle/files/397143/SwaggerConfig.txt)
