### ISSUE TITLE
How to use customized Swagger-ui?

### ISSUE THREAD

**Issue by zh-wowtv** [domaindrivendev/Swashbuckle#854]
There is a very nice fork for Swagger-ui, please refer to https://github.com/jensoleg/swagger-ui.

My question is how to use it in Swashbuckle? Show I build Swashbuckle from scratch?

**Comment by domaindrivendev** [comment]
First and foremost, SB is a Swagger generator. It does bundle in a version of the swagger-ui for convenience, to help get up and running quickly. But, at the end of the day, the swagger-ui is just a set of static assets which could be easily added to any ASP.NET project independent of SB.

If I were you, I would just use SB to provide the generated Swagger JSON and then serve the forked version of swagger-ui independently as a set of static assets. You'll just need to make sure the forked index.html points to the Swagger endpoints generated by SB.

**Comment by domaindrivendev** [comment]
FYI - this would mean your omit the call to __EnableSwaggerUi__ in _SwaggerConfig.cs_
