### ISSUE TITLE
OAuth setting redirect URL with hash query

### ISSUE THREAD

**Issue by PhillipZada** [domaindrivendev/Swashbuckle#857]
After 5.4 update, OAuth2 setting redirect URL with hash query on refresh.

**Comment by osemyonov** [comment]
I came across the same issue after updating to 5.4
Swagger schema is correct

**Comment by lolekjohn** [comment]
Are you using Injected index.html? then in that case, you need to update the index.html to have the latest code

**Comment by osemyonov** [comment]
No, I don't use injected index.html. I use nuget package 'Swashbuckle.Core'

**Comment by johannesvaltonen** [comment]
I am having the same problem after updating to 5.4. It seems that this is fixed in #842 but the fix has not made into a release yet. Could we get a hotfix for this issue? Authentication is not currently working according to specs.

**Comment by domaindrivendev** [comment]
Planned release for 10/29
