### ISSUE TITLE
<summary> xml annotation not working for properties in nested objects

### ISSUE THREAD

**Issue by maniacally** [domaindrivendev/Swashbuckle#86]
Assuming we have a model called Group that looks like this:

``` csharp
    public class Group{
      ///<summary>
      /// Some description of GroupName
      ///</summary>
      public string GroupName{get;set;}
      public List<Person> People {get;set;} 
    }
```

and a Person class that looks like this:

``` csharp
    public class Person{
      ///<summary>
      /// Some description of Name
      ///</summary>
      public string Name{get;set;}
    }
```

If we then use the ResponeType attribute for an API action and set it to typeof(Group) the resulting documentation for the action will only show the descriptions in the <summary>

 element for the top level properties (GroupName, for ex).  The description in the <summary>

 element of the nested Person class (for Name) is not reflected in the generated documentation.

**Comment by radduri** [comment]
I am using 6.0 but still facing the same issue. Any help?

**Comment by Magic73** [comment]
Me too. With the lastest version...

**Comment by luboshl** [comment]
I am using version 5.6.0 and multiple XML docs works for me:

```
var dir = new DirectoryInfo(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "bin"));
foreach (var fi in dir.EnumerateFiles("*.xml"))
{
    c.IncludeXmlComments(fi.FullName);
}
```

**Comment by raffaeu** [comment]
@luboshl that worked for me, Swagger on asp.net core 2.1

**Comment by andyliutyme** [comment]
3 years later, @luboshl 's solution still works 👍

**Comment by lonix1** [comment]
@luboshl's solution works in aspnet core 5:
````cs
var dir = AppContext.BaseDirectory;
var paths = Directory.GetFiles(dir, "*.xml", SearchOption.TopDirectoryOnly);
foreach (var path in paths) o.IncludeXmlComments(path);
````

@domaindrivendev Should be added to the [docs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/a66864f65bac06ad326b4f2ec8fddcc91012a4e8#include-descriptions-from-xml-comments), this issue is the only place it's discussed.
