### ISSUE TITLE
c.BooleanValues(new[] { "0", "1" });

### ISSUE THREAD

**Issue by chenzhikang** [domaindrivendev/Swashbuckle#864]
i review the SwaggerConfig.cs file .and want to enable [c.BooleanValues(new[] { "0", "1" });] to work .but the  boolean input still  rendering as true/false.not expected value :0/1. here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/9971827/18377893/603c23ae-769c-11e6-858f-0a78686f2770.png)

**Comment by domaindrivendev** [comment]
Hmmm - looks like this feature was dropped from the swagger-ui project:

https://github.com/swagger-api/swagger-ui/issues/1272

As it's now redundant, I've removed the option from Swashbuckle.

**Comment by chenzhikang** [comment]
thanks
