### ISSUE TITLE
where does the js and css files?

### ISSUE THREAD

**Issue by chenzhikang** [domaindrivendev/Swashbuckle#865]
![image](https://cloud.githubusercontent.com/assets/9971827/18379035/ec6a45bc-76a2-11e6-87a0-1f13115ebf20.png)

i reflector the dll ,and saw the files of js\css.but i can`t find them in the sourcefile download from github,
coult u tell me why?

**Comment by chenzhikang** [comment]
i am in order to custom myself page of index.html.

**Comment by chenzhikang** [comment]
<EmbeddedResource Include="..\swagger-ui\dist\**\*.*"> i think the file should in directory \Swashbuckle\swagger-ui.but the repository of this dir is empty

**Comment by domaindrivendev** [comment]
It's a git submodule. Run "git submodule update" from your project root to pull the assets down from the swagger-ui repo.
