### ISSUE TITLE
"Response Headers" section is different on local and prod

### ISSUE THREAD

**Issue by Jcomper** [domaindrivendev/Swashbuckle#871]
Hi,

I'm having an issue: "Response Headers" section is different on local and prod computers. I'm adding "x-pagination" and "link" attributes to header and it's displayed on local computer, on prod the only 
`{
  "content-type": "application/json; charset=utf-8"
}`
is displayed, although using Fiddler (or other HTTP debugging tool) I can see that server returns my attributes in response header.   

Any ideas why is it so?

**Comment by domaindrivendev** [comment]
I really have no idea why this would be the case - if you've confirmed that the server is returning all expected headers, but they're just not being displayed in the UI, then it's more likely to be an issue with the the [swagger-ui](https://github.com/swagger-api/swagger-ui) and not Swashbuckle.
