### ISSUE TITLE
How to get swagger-ui is set to home page

### ISSUE THREAD

**Issue by eightHundreds** [domaindrivendev/Swashbuckle#873]
if my website host is abc.com,then how can i see swagger by http://abc.com
now the url always need "/index" ,eg. abc.com/index. @ #

**Comment by CoolDadTx** [comment]
I use a redirect rule in the config file. Refer to the blog article I posted here - http://www.michaeltaylorp3.net/creating-a-rest-api-project-template/ 
Jump to the Setting a Default Document section.

**Comment by v-karbovnichy** [comment]
@eightHundreds there are several ways to do it, however.

To all who will come here from Google, go look here:
https://stackoverflow.com/a/41282115/1875339

@domaindrivendev please include this topic in README.md because of so much frustration and common use-case.

**Comment by domaindrivendev** [comment]
I'm going to close this as there's several approaches described above. Adding a simple redirect to a web application is a pretty standard practice and is extremely well document. I don't think it's necessary to add specific documentation to Swashbuckle. But, if anyone here feels strongly about adding to the docs, feel free to submit a PR.

**Comment by mbarmettler** [comment]
this worked for me:
```
app.Run(async context => { 
    context.Response.Redirect("swagger/ui/index"); 
}); 
```
