### ISSUE TITLE
XML comments from dependent Assemblies

### ISSUE THREAD

**Issue by patricknolan** [domaindrivendev/Swashbuckle#874]
Hi,

I have an asp.net project with some controllers that exist in dependent assemblies. How can I get swashbuckle to pickup the XML comments from these dependent assemblies? Is the suggestion in this [post ](https://github.com/domaindrivendev/Swashbuckle/issues/93) still the only approach? And if so, does this approach still work?

**Comment by cbird** [comment]
I guess you can use suggested approach in the docs https://github.com/domaindrivendev/Swashbuckle#including-xml-comments

**Comment by domaindrivendev** [comment]
@cbird is correct. If you take a look at the docs, you can see that multiple XML comment files are supported. So long as you have the XML files for those assemblies, or know where they get generated, you can tell Swashbuckle about them and it should pick them up.
