### ISSUE TITLE
Default Request Data in Model Schema on Swagger UI using Swagger 6.0.0-rc1-final

### ISSUE THREAD

**Issue by urao123** [domaindrivendev/Swashbuckle#875]
Hi All,
Please help me out in implementing default request data to the controller action of the model schema on the Swagger UI with Swagger 6.0.0-rc1-final with C#. 

i found relevant answer for this  but not the exact answer at https://mattfrear.com/2016/01/25/generating-swagger-example-requests-with-swashbuckle.

 Above link works for Swagger 5.0, As i'm using Swagger 6.0.0-rc1-final,  the functions which are used at above link are not found in this swagger which i’m using.

Anyone worked with Swagger 6.0.0-rc1-final, Please post your answer?

**Comment by domaindrivendev** [comment]
For that version, the config settings you need are available via a separate calls __ConfigureSwaggerSchema__ and __ConfigureSwaggerDocument__ on IServiceCollection.

It's also worth noting that despite the names, 6.0.0-rc1-final is actually a couple of versions behind. The latest version is 6.0.0-beta902. Let's just say naming got a little messed up while ASP.NET Core was stabilizing itself. I'm trying to get a stable release of SB 6 out real soon and that should clear up all the confusion.
