### ISSUE TITLE
ResolvingConflictingActions return type is different from readme.

### ISSUE THREAD

**Issue by Head-Strong** [domaindrivendev/Swashbuckle#876]
Hi All, 

ResolvingConflictingActions return type is "Func<IEnumerable<ApiDescription>, ApiDescription>". But in readme it is mentioned as : 
[c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());].

Actual implementation : 

c.ResolveConflictingActions(ResolveConflictByDescription());

private static Func<IEnumerable<ApiDescription>, ApiDescription> ResolveConflictByDescription()
{
        return null;
}

I am using SwashBuckle Version 5.4.0. Could you please let me know how to resolve it ?

**Comment by domaindrivendev** [comment]
ResolveConflictingActions doesn't have a return type at all - it's a void:

    public void ResolveConflictingActions(Func<IEnumerable<ApiDescription>, ApiDescription> conflictingActionsResolver)

You have to give it a function that accepts a enumerable of ApiDescriptions's and returns 1 ApiDescription - i.e. the winner of the conflict or a merged version. This is exactly what the lambda described in the readme does. As in ... it receives __apiDescriptions__ and returns the first one.

The function you've shown above has an incorrect signature. It should be as follows:

    public static ApiDescription ResolveConflictByDescription(IEnumerable<ApiDescription> apiDescriptions)
    {
        ...
    }
