### ISSUE TITLE
Modelbinding parameters not being sent to the server

### ISSUE THREAD

**Issue by cable729** [domaindrivendev/Swashbuckle#882]
I was suggested to post this here. The original posted issue is https://github.com/domaindrivendev/Ahoy/issues/182
# Reproduction
1. Run `dotnet new -t Web`
2. Create controller with the following code:
   
   ```
   using Microsoft.AspNetCore.Mvc;
   
   namespace WebApplication.Controllers
   {
   public class Test
   {
       public string Name { get; set; }
       public bool IsPassing { get; set; }
   }
   
   [Route("api/[controller]")]
   public class TestController : Controller
   {
       [HttpPost]
       public Test CreateTest(Test test)
       {
           return test;
       }
   }
   }
   ```
3. Add Swashbuckle according to readme
4. Navigate to /swagger/ui and execute the POST request like so:
   ![image](https://cloud.githubusercontent.com/assets/1524578/18923138/6ee372a6-8568-11e6-8576-45e128efee58.png)
5. I expect to see `{ "name": "some name", "passing": true }`, but instead I see `{ "name": null, "passing": false }`.
# Other tried solutions

I have tried attaching a `[FromForm]`, and it doesn't work (apparently, the parameter type is being generated as `form`, but it should be generated as `formBody`).

**Comment by mkeymolen** [comment]
i have the same issue

**Comment by raphi011** [comment]
same problem

**Comment by heldersepu** [comment]
The parameter type should be Body...
That is very strange, I do not get this issue with this code:
```c#
using System.Web.Http;

namespace Swagger_Test.Controllers
{
    public class MyTest
    {
        public string Name { get; set; }
        public bool IsPassing { get; set; }
    }

    public class TestPostController : ApiController
    {
        [HttpPost]
        public MyTest CreateTest(MyTest test)
        {
            return test;
        }
    }
}
```

**Comment by heldersepu** [comment]
Here is my code:
https://github.com/heldersepu/csharp-proj/commit/368dd50afa3c6de9b80e9e7155ac0bae45b739d5

And here is the SwaggerUI:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#!/TestPost/TestPost_CreateTest
