### ISSUE TITLE
A route named 'swagger_docsswagger/docs/{apiVersion}' is already in the route collection. Route names must be unique. Parameter name: name

### ISSUE THREAD

**Issue by BenPowerProfessional** [domaindrivendev/Swashbuckle#884]
OK, so this is with Swashbuckle 5.4.0 - the latest stable version currently.

When I host my Web API in IIS, Swagger works just fine, but when I publish it to Azure as an API App, it fails with:

Server Error in '/' Application.

> A route named 'swagger_docsswagger/docs/{apiVersion}' is already in the route collection. Route names must be unique.
> Parameter name: name

Swagger.Config:
```
using System.Web.Http;
using WebActivatorEx;
using Services.VirtualAssistant.Fake;
using Swashbuckle.Application;

[assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]

namespace Services.VirtualAssistant.Fake
{
    public class SwaggerConfig
    {
        public static void Register()
        {
            var thisAssembly = typeof(SwaggerConfig).Assembly;

            GlobalConfiguration.Configuration 
                .EnableSwagger(c =>
                    {
                        c.SingleApiVersion("v1", "Services.MyTestService");

//snipped default comments 
                    })
                .EnableSwaggerUi(c =>
                    {
//snipped default comments 
                   });
        }
    }
}
```

I've searched the whole repo for the string 'docsswagger' and there's nothing. Any clues as to what I might be missing here?

**Comment by adamvanvliet** [comment]
Hi @BenPowerProfessional, did you see #364?

**Comment by domaindrivendev** [comment]
Closing as this is a dup of #364

**Comment by aligenc** [comment]
You got conflict dll files. So delete your bin folder and re-build your solution. If you get this error on development, clean solution and try again.
