### ISSUE TITLE
Swagger Swashbuckly option to generate NodeJS Api Mock Server?

### ISSUE THREAD

**Issue by masaanli** [domaindrivendev/Swashbuckle#885]
Sorry for asking, but could not find a website, or chat or something simulair to ask this question.

Is there a Swagger Swashbuckly option to generate NodeJS Api Mock Server?

So the C# dev's can use Swashbuckle, and the Front-End dev's can use a generated thing from Swashbuckle as api mock in there NodeJS project?

**Comment by domaindrivendev** [comment]
It's outside the scope of this project and there's nothing else out there that I'm aware of. Your open source calling has arrived :)
