### ISSUE TITLE
Excluding certain assemblies from being analyzed for endpoints

### ISSUE THREAD

**Issue by andreygarmash** [domaindrivendev/Swashbuckle#886]
We are building an api on top of Sitecore CMS and Sitecore has dlls with its own admin api endpoints, Swashbuckle seems to try and explore those endpoints but it takes enormous amount of time and ends with a fail. We`d like swashbuckle to only look at one particular assembly.

**Comment by domaindrivendev** [comment]
Hmmm - there'll be better support for arbitrary selection of API descriptions for a target Swagger document in the next version (6.0). Of course that requires an upgrade to ASP.NET Core so may not be an option.

However, one potential approach you could try is to use the __MultipleVersions__ option in your _SwaggerConfig.cs_. This method accepts a Func for indicating which ApiDescriptions are relevant to each specified version. You could still just specify one version but also provide the Func which only includes the ApiDescriptions you're interested in. I think this should get you what you need - let me know how it goes?
