### ISSUE TITLE
Specify a parameter type for a custom parsed body

### ISSUE THREAD

**Issue by zidad** [domaindrivendev/Swashbuckle#887]
Hi,

Is there a way (attribute or documentation) that would allow me to do custom parsing of the request body, but still generate documentation for a specific (JSON) type?

like this:
```
        public async Task Product()
        {
            using (var postStream = await Request.Content.ReadAsStreamAsync())
            using (var postStreamReader = new StreamReader(postStream))
                var body = await postStreamReader.ReadToEndAsync();
                var list = body.Deserialize<ProductQuery>();

```
I tried to look but all documentation seems to be about response types, not request/model types.
I found an ApiModelAttribute somewhere but that seem an unofficial/outdated package.

Sorry I'm a bit new to this and there's obvious attributes to do this.

**Comment by domaindrivendev** [comment]
Your best bet would be to introduce you're own custom attribute that you can decorate these kinds of actions with and then a corresponding IOperationFilter (see readme) that inspects ApiDescription's for the attribute and adds the corresponding operation.Parameters where applicable:

    [RequestType(typeof(ProductQuery))]
    public async Task Product()
    {
    ...

**Comment by zidad** [comment]
ok I will try that, thanks!
