### ISSUE TITLE
Where's DescendingAlphabeticComparer?

### ISSUE THREAD

**Issue by MB34** [domaindrivendev/Swashbuckle#892]
Just installed 5.4.0. I cannot find the class DescendingAlphabeticComparer which is needed when attempting to sort the documentation. Is this supposed to com in the package?

**Comment by MB34** [comment]
Also, in attempting enabling XMLComments, I included this code:
`c.IncludeXmlComments(GetXmlCommentsPathForControllers());`
But cannot find the GetXmlCommentsPathForControllers function...

**Comment by paul3291** [comment]
just try searching the repo for anything like this.

https://github.com/domaindrivendev/Swashbuckle/search?utf8=%E2%9C%93&q=DescendingAlphabeticComparer+

**Comment by MB34** [comment]
The Swagger.Extensions class is NOT in the SwashBuckle.Core. This is what I have in the Object Inspector:
![swashbuckle](https://cloud.githubusercontent.com/assets/377196/19274324/5926c9c2-8f95-11e6-94a8-c721fa3cb9e8.png)

**Comment by MB34** [comment]
Ok, I added it to the SwaggerConfig and it seems to work, however, I want to sort the Actions not just the groups. Is there a way to do that?

**Comment by paul3291** [comment]
not sure if this is the right way to do it or not, but the following works for us with SB 5.4.0.

we have a custom attribute (GroupByNameAttribute) we apply to the controller to provide a friendly 'group name' which we invoke with
`swaggerDocsConfig.GroupActionsBy(ExtractControllerGroupingValue);`

which is basically used to provide a different name to what is auto picked up
```
private static string ExtractControllerGroupingValue(ApiDescription apiDescription)
{
	// see if we have an attribute to provide our name
	var controllerGroupName = apiDescription.ActionDescriptor.ControllerDescriptor.GetCustomAttributes<GroupByNameAttribute>().FirstOrDefault();

	if (controllerGroupName != null)
	{
	return controllerGroupName.Name;
	}

	// revert to the old logic
	return apiDescription.ActionDescriptor.ControllerDescriptor.ControllerName;
}
```

the we finish off with a Document Filter
`swaggerDocsConfig.DocumentFilter<SortOperationsByPathDocumentFilter>();`

which is basically
```
public class SortOperationsByPathDocumentFilter : IDocumentFilter
{
/// <summary>
/// Applies an ordering to the operations based on the path name of the operation.
/// </summary>
public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
{
    // make operations a-z based on the controller name, then the path details
    var paths = swaggerDoc.paths.OrderBy(e => this.GetOperationFilterString(e.Key, e.Value)).ToList();

    swaggerDoc.paths = paths.ToDictionary(e => e.Key, e => e.Value);
}

/// <summary>
/// Gets a string value that represents the name of an operation filter based on logic we will use for sorting.
///     All operations should be sorted by the group by name/controller name, then by the operation path (which is the
///     default)
/// </summary>
private string GetOperationFilterString(string key, PathItem value)
{
    var groupByName = string.Empty;

    // grab the controller name or group by name from the first tag, if we have one
    if (value.get?.tags != null)
    {
        groupByName = value.get.tags[0];
    }
    else if (value.delete?.tags != null)
    {
        groupByName = value.delete.tags[0];
    }
    else if (value.patch?.tags != null)
    {
        groupByName = value.patch.tags[0];
    }
    else if (value.post?.tags != null)
    {
        groupByName = value.post.tags[0];
    }
    else if (value.put?.tags != null)
    {
        groupByName = value.put.tags[0];
    }

    // check if we have anything
    if (!string.IsNullOrWhiteSpace(groupByName))
    {
        return groupByName + '-' + key;
    }

    // we reach here if we have nothing, which we shouldn't, unless there is another http verb we need to catch above..
    return value.ToString();
}
}
```

**Comment by domaindrivendev** [comment]
DescendingAlphabeticComparer is just an example name provided with the documentation - it's not part of Swashbuckle.

For sorting by operation, the solution from @paul3291 seems like a reasonable workaround. Admittedly, this should be a little easier to achieve. Unfortunately, it's just lower on the list of priorities. I'm closing this issues as there already one to track the sort order feature - #840
