### ISSUE TITLE
Host the generated HTML, Javascript and CSS on a different machine

### ISSUE THREAD

**Issue by joshirushabh** [domaindrivendev/Swashbuckle#893]
We have an _internal_ Web API project which is hosted inside our company's network. 
The swashbuckle works great and shows the documentation nicely when i change the URL to

internal project url/swagger

We also have an _external_ project available on the internet which is a wrapper for the internal project. 
It has one controller which redirects all the calls to internal project.

We would like to make the _internal_ project's documentation available on the internet. 

Is it possible to pull out the HTML, Javascript and CSS from the _internal_ project?

Can someone please point me to the correct way to do this?

**Comment by domaindrivendev** [comment]
Take a look at [swagger-ui](https://github.com/swagger-api/swagger-ui). It's a dependency free set of static assets (HTML, CSS, JS) that should be fairly trivial to host independently of SB. With this setup, you would only use SB for generating and exposing the Swagger JSON endpoints. Then, you just modify you're independenty hosted swagger-ui (see index.html) to point to those endpoints.

**Comment by joshirushabh** [comment]
@domaindrivendev - This is exactly what I ended up doing! Thanks again for this great library and support!
