### ISSUE TITLE
Thank You!!

### ISSUE THREAD

**Issue by paul3291** [domaindrivendev/Swashbuckle#895]
Just want to give you a big thanks @domaindrivendev for putting in all the unpaid hours that you have. I would go insane doing my normal paid work duties and then try to keep a popular open source library moving and it's consumers happy. Open source gives everyone the ability to debug and test themselves, it's not a black box. Keep up the good work!

**Comment by domaindrivendev** [comment]
Thank dude - the attitude of some open source consumers never ceases to amaze me so it's great to hear from people who "get it" and appreciate all the hard work that goes into it
