### ISSUE TITLE
OAuth2SchemeBuilder.AuthorizationUrl() incorrectly parses OAuth2 auth url with Azure AD B2C signin policy

### ISSUE THREAD

**Issue by leoogh** [domaindrivendev/Swashbuckle#896]
when using Azure AD B2C, the OAuth2 authorization url is something like:

`https://login.microsoftonline.com/mytenant.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_mysigninpolicy`

note that this authorization url has a query parameter that indicates the B2C policy to use

when using this url with OAuth2SchemeBuilder.AuthorizationUrl() then in Swagger UI the completed authorization url becomes:

`https://login.microsoftonline.com/mytenant.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_mysigninpolicy?response_type=token&redirect_uri=....
`

notice the double appearance of a question mark: apparently the code doesn't properly parse the provided authorization url, but just blindly appends a new question mark and further querystring parameters

this breaks authentication with a 404 not found

the correct composed url should instead be:
`https://login.microsoftonline.com/mytenant.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_mysigninpolicy&response_type=token&redirect_uri=....`

**Comment by MelvinVermeer** [comment]
Hi I'm walking through this documentation for a Asp.Net 4.6 Web App and I'm having the same issue as you do.
https://azure.microsoft.com/nl-nl/documentation/articles/active-directory-b2c-devquickstarts-web-dotnet/

**Comment by MelvinVermeer** [comment]
This fixed it for me: http://stackoverflow.com/questions/39775299/trying-to-implement-azure-active-directory-b2c-gives-me-a-404-error

I updated **microsoft.identitymodel.protocol.extensions**.

**Comment by leoogh** [comment]
Hi, yes I encountered that issue too.  However, the Swashbuckle/Swagger issue (which is very similar) is not dependent on that nuget (I think).  Seems more like a problem with the generated javascript.  Btw I'm now using a workaround by omitting the ?p=... parameter from the auth url in Swashbuckle configuration and adding it later again via 
```
c.EnableOAuth2Support(
  //  ...
additionalQueryStringParams: new Dictionary<string, string>() { { "p", "B2C_1_mypolicy" }}
);
```

**Comment by domaindrivendev** [comment]
Sounds like there's some workarounds here so going to close. If you're still having issues, feel free to re-open and provide any additional details. Exact repro steps on a fresh WebAPI project would be very helpful

**Comment by markti** [comment]
is there an example for setting up Azure AD B2C with swashbuckle on .NET core?

**Comment by ChiefWiggum** [comment]
@markti I just found this [article ](https://blogs.msdn.microsoft.com/isgupt/2017/09/04/swagger-authentication-against-azure-ad-b2c/)which helped my out.
