### ISSUE TITLE
Is there a way to customize input elements in Swagger-UI?

### ISSUE THREAD

**Issue by xtrmstep** [domaindrivendev/Swashbuckle#899]
Hi,

I'd like to use jQuery widgets for editing specific types on UI. For example, DateTime picker instead of text editor. How can I achieve that?

Another case. 
I've got complex type which can be posted via URI to the action. By default UI will create several parameters for each of the type properties. I want to substitute that by providing one textarea element where I could input JSON text. Is it possible to implement by means of Swashbuckle configuration?

Thanks

**Comment by domaindrivendev** [comment]
These questions are specific the the Swagger UI, which is actually pulled in from a completely separate project - https://github.com/swagger-api/swagger-ui. Swashbuckle does expose the config options from that project, and even allows a custom index.html to be injected (see readme), but doesn't implement any of the actual UI code. You should submit these questions to the swagger-ui folks instead.
