### ISSUE TITLE
Backslashes added to curl snippet

### ISSUE THREAD

**Issue by Shimii** [domaindrivendev/Swashbuckle#902]
Hi!

After having upgraded Swashbuckle.Core from version 5.3.2 to 5.4.0 I got an unwanted behavior in the swagger UI curl snippet. 

![image](https://cloud.githubusercontent.com/assets/9336354/19485274/ec25d590-955a-11e6-9799-384598fd7b3c.png)

Where backslashes is added for every row in the body expression.  This was not the behaviour of version 5.3.2. 

Is this a wanted behaviour? If so, how can I edit my solution to suit my needs? (Having a model class being mapped to curl snippet without the backslashes added to it)

**Comment by domaindrivendev** [comment]
Swashbuckle is a Swagger generator which ships with an embedded version of swagger-ui. The Curl generation is provided by swagger-ui and not Swashbuckle, so you should direct this query to that repo - https://github.com/swagger-api/swagger-ui. Thanks
