### ISSUE TITLE
Cannot access version in OperationFilter

### ISSUE THREAD

**Issue by Yackob94** [domaindrivendev/Swashbuckle#905]
I want to be able to modify the Response Content Type on the UI to include my version number parameter. I have implemented IOperationFilter to modify the "produces" field on the Operation object and include my version parameter. I can't seem to be able to access it.

**Comment by domaindrivendev** [comment]
This is a dup of #408

**Comment by davetransom** [comment]
You can work around this with am `IDocumentFilter` instead, something along the lines of:
```
class MyDocumentFilter : IDocumentFilter
{
	void ApplyOperation(SwaggerDocument swaggerDoc, Operation operation, SchemaRegistry schemaRegistry)
	{
		// your implementation here
		//var version = swaggerDoc.info.version; .. etc
	}

	public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
	{
		foreach (PathItem path in swaggerDoc.paths.Values)
		{
			foreach (Operation operation in DefinedOperationsIn(path))
			{
				ApplyOperation(swaggerDoc, operation, schemaRegistry);
			}
		}
	}

	static IEnumerable<Operation> DefinedOperationsIn(PathItem path)
	{
		return new Operation[]
		{
			path.delete,
			path.get,
			path.head,
			path.options,
			path.patch,
			path.post,
			path.put
		}.Where(operation => operation != null);
	}
}
```
NB: I haven't included the `ApiDescription` parameter normally found in the `IOperationFilter.Apply` signature, if you want it you'll need to look it up from `IApiExplorer` instance and pass that along to `ApplyOperation`.
