### ISSUE TITLE
When object inherits from IEnumerable model doesn't show up.

### ISSUE THREAD

**Issue by bhw7** [domaindrivendev/Swashbuckle#911]
Have applied a custom schema in: `c.SchemaFilter<ApplySchemaVendorExtensions>();`

When trying to show a model that has inherited from IEnumerable the model didn't show up correctly in Swagger-UI. Instead it showed:

```
[
   "string"
]
```

`ReminderGroupBatch : IReminderGroupBatch` inherited from its interface of `IReminderGroupBatch : ICloneable, IEnumerable<Uri>`

Schema code was:

```
public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
{
             if (type == typeof(IReminderGroupBatch) || type == typeof(ReminderGroupBatch))
            {
                schema.example = new ReminderGroupBatch
                {
                    BatchGuid = Guid.NewGuid(),
                    PatientReminderUris = new List<Uri>()
                    {
                        new Uri("http://localhost:56003/api/v1/reminders/" + Guid.NewGuid())
                    }
                };
            }
}
```

After removing the `IEnumerable<Uri>` the model showed correctly as:

```
{
  "PatientReminderUris": [
    "http://localhost:56003/api/v1/reminders/4c847cd1-f328-4692-a0ad-1dfa3b87989f"
  ],
  "BatchGuid": "d23a5282-8554-417e-9a5b-9110945826aa"
}
```

**Comment by domaindrivendev** [comment]
Independent of Swashbuckle, the default JSON serializer for WebAPI will serialize/deserialize an instance of your complex type as a JSON array and not an object. But, it sounds like you expect it to be represented as an object instead of an array (it can't be both in JSON). Have you applied some custom serialization rules to make it behave this way at runtime?

**Comment by domaindrivendev** [comment]
Furthermore, if you do explicitly tell the serializer to treat the type as a JSON object instead of a JSON array as follows, then Swashbuckle will honor this and describe it as an object:

```csharp
[JsonObject]
public class ReminderGroupBatch : IEnumerable<Uri>
{
  ...
}
```

**Comment by bhw7** [comment]
@domaindrivendev thanks for the response!
