### ISSUE TITLE
ApplyXmlActionComments clears responses from other filters

### ISSUE THREAD

**Issue by gislikonrad** [domaindrivendev/Swashbuckle#913]
Now that ApplyXmlActionComments is last in the operation filter pipeline, anything that is done to responses in any other operation filter gets cleared. In the ApplyResponseComments method, operation.responses.clear() is being called.

This bug was introduced in checkin bdb4f4705e09faa1964b9a81840ca8795208c60e on Sept 27. The change that causes it is the change in how the filters are added to the pipeline in SwaggerDocsConfig (specifically the foreach in lines 242-247) as opposed to the former way of doing this which was adding these filters to the pipeline when IncludeXmlComments is called on SwaggerDocsConfig.

**Comment by domaindrivendev** [comment]
Should be resolved in v5.5.2
