### ISSUE TITLE
Not supported by Swagger 2.0: Multiple operations with path 'v1/api/Admin/' and method 'POST'.

### ISSUE THREAD

**Issue by stricq** [domaindrivendev/Swashbuckle#916]
I installed Swashbuckle v5.5.2 in a new Web.API project that is .Net 4.6.1.  With no controllers, it worked with no errors.  However, after I added a controller with a Get and a Put method, I get the following error in Swashbuckle:

500 : {
    "Message": "An error has occurred.",
    "ExceptionMessage": "Not supported by Swagger 2.0: Multiple operations with path 'v1/api/Admin/' and method 'POST'. See the config setting - \"ResolveConflictingActions\" for a potential workaround",
    "ExceptionType": "System.NotSupportedException",
    "StackTrace": " at Swashbuckle.Swagger.SwaggerGeneratorOptions.DefaultConflictingActionsResolver(IEnumerable`1 apiDescriptions)\r\n at Swashbuckle.Swagger.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)\r\n at Swashbuckle.Swagger.SwaggerGenerator.<>c__DisplayClass7.<GetSwagger>b__4(IGrouping`2 group)\r\n at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n at Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
}
http://localhost:20923/swagger/docs/v1

The problem is, there is no Admin controller anywhere in the project.  The controller I added does not have any POST methods at all.

**Comment by stricq** [comment]
I found the controller.  It was coming from RavenDB DLLs.

**Comment by kdcllc** [comment]
@stricq  How did you filter the RavenDB DLls?  I am experiencing the same kind of issue.

Thanks, kdcllc

**Comment by stricq** [comment]
I uncommented the ResolveConflictingActions line in the config.
