### ISSUE TITLE
Generated swagger for assembly

### ISSUE THREAD

**Issue by fleed** [domaindrivendev/Swashbuckle#919]
Is it possible to generate a Swagger file for an external assembly?

The problem: I have a `.net core` web api project, and with Swashbuckle I can dynamically create the swagger description. I'd like to generate that swagger file within my build pipeline (using `cake build` / `VSTS`) so that I can automate the documentation process and additionally create client code.

I'd like to have a reusable component, so I should be able to read external assemblies containing the REST API.

**Comment by djandh** [comment]
Ran into the same problem. Unfortunately I don't know of a way to do this, as swashbuckle uses ApiExplorer to get the descriptions, and that uses HttpConfiguration, which is setup at runtime. If there is a way around this I would love to hear it though :)

**Comment by asrikantan80** [comment]
We are also looking for something similar. NSwag has this functionality. But i am not able to generate a successful swagger.json there. https://github.com/NSwag/NSwag/wiki/CommandLine

**Comment by fleed** [comment]
I was able to achieve my goal using [cakebuild](https://cakebuild.net):

- create an asp.net "integration test", requesting the swagger content and storing as a file
- using Cake.AutoRest package I've generated the clients
- built the project containing the clients
- packed and pushed to NuGet

That's a complete pipeline that works quite well for me.  
Anyway, the unit test generating the swagger file looks ugly... I think that this is a must-have feature for devops and CI pipelines.

**Comment by domaindrivendev** [comment]
Agreed that this is a massively important feature and so I'll definitely be adding this as a first class feature in the Core-specific project:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore

For continued WebAPI users, I'll refer you the #783 which describes a fairly clean workaround.
