### ISSUE TITLE
Getting a 404 on IIS for the swagger json route, but swagger-ui page loads

### ISSUE THREAD

**Issue by novabe** [domaindrivendev/Swashbuckle#921]
In IIS Express both endpoints work fine. When I deploy to IIS however, the swagger json route (/swagger/1.0) gives a 404, and the swagger UI page (/swagger AKA /swagger/ui/index) loads but the request it makes to the json endpoint also gives the 404.

Swashbuckle version: 5.4.0
IIS version: 6.2

Can anyone suggest how I can debug this further on my end?

**Comment by dariusdamalakas** [comment]
We use owin self hosting, works fine. When things get sour, there is always an options to download source and include swashbuckle project into your solution, and debug. Though that will require to upgrade to latest version.

**Comment by novabe** [comment]
This turned out to be environment-specific; the load balancer was applying https whereas IIS was serving http. Fixed by using a custom GetRootUrl() in SwaggerConfig.cs that checks the RequestUri host, and manually builds the root URL based on that.

**Comment by AndrewBragdon** [comment]
My problem was that I enabled XML Comments support, but only enabled comment generate on Debug and not Release.  I wish that the swashbuckle app had better logging.
