### ISSUE TITLE
Where can we find release notes?

### ISSUE THREAD

**Issue by dariusdamalakas** [domaindrivendev/Swashbuckle#922]
Hi, 

I want to understand what has changed between `5.3.1` and `5.5.3` versions.   There is a difference how Dictionary<string, string> is serialized, so am keen to understand the reasons behind this, whether this is intentional or this is a regression  #issue.

Version `5.5.3`  produces this swagger.  Note the `AdditionalProperties` object.
````
"responses": {
          "200": {
            "description": "Preference was found",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "object",
              },
            },
           }
         },
````
Version `5.3.1`, Note that `additionalProperties` has a property `$ref`, which is not produced in `5.5.3`
````
 "responses": {
          "200": {
            "description": "Preference was found",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "$ref": "#/definitions/Object"
              }
            },
          },
````

Controller, note that response object is a `Dictionary<string, object>`.
````
    public class PortfolioPreferenceDocument : Dictionary<string, object>
    {
    }

    [RoutePrefix("v1/clients/me")]
    public class PortfolioPreferenceController : ApiController
    {
        [Route]
        [HttpGet]
        public IHttpActionResult<PortfolioPreferenceDocument> Get()
        {....    }
    }
`````

**Comment by paulclarkin** [comment]
https://github.com/domaindrivendev/Swashbuckle/releases ?

**Comment by dariusdamalakas** [comment]
Thanks. Closing this.
