### ISSUE TITLE
Format swagger json output with pretty print?

### ISSUE THREAD

**Issue by dariusdamalakas** [domaindrivendev/Swashbuckle#929]
Is there an option to pretty print swagger output?    

If not, I would propose to add support for querystring parameter pretty to turn this on

`docs/v1/swagger?pretty=true`

Happy to provide a PR for this.

**Comment by Southen** [comment]
Looks from https://github.com/domaindrivendev/Swashbuckle/issues/541 like this got implemented in PR https://github.com/domaindrivendev/Swashbuckle/pull/577
I'm using it with v5.5.3 like `GlobalConfiguration.Configuration.EnableSwagger(c => {.PrettyPrint(); })`

**Comment by domaindrivendev** [comment]
Fixed by #577
