### ISSUE TITLE
XML comments from dependent Assemblies

### ISSUE THREAD

**Issue by Zaphod99** [domaindrivendev/Swashbuckle#93]
I may be missing something obvious here but I can't seem to figure out how to include XML comment documentation from more than one assembly.  I have a web project that produces file a.xml in the app_data directory.  I also have a DTO project that contains the objects the web project returns.  It produces an xml file, b.xml.  I have been able to include one file or the other, and Swashbuckle picks up either set of comments.  However, I don't know how to ask it to look at both files at once.  Is that supported?

string path = AppDomain.CurrentDomain.GetData("DataDirectory").ToString() + "\a.xml";
            SwaggerSpecConfig.Customize(
                c => c.IncludeXmlComments(path));

Great project, btw!

**Comment by gbotros** [comment]
Does this issue has a formal fix now?

**Comment by viku85** [comment]
This issue still haunts in 2018.
My solution for the same.

Function to get a of XML doc:
`private static string GetXmlCommentPath(string assemblyName) =>
      Path.Combine(AppContext.BaseDirectory, assemblyName + ".xml");`

Register XML files with help of C# `nameof` without using any reflection.
`
options.IncludeXmlComments(GetXmlCommentPath($"{nameof(MyProject)}.{nameof(Db)}"));
options.IncludeXmlComments(GetXmlCommentPath(nameof(SomeOtherNamespace)));
options.IncludeXmlComments(GetXmlCommentPath($"{nameof(MyProject)}.{nameof(Core)}"));
`

**Comment by akalcik** [comment]
It can be a option to add all xml files from _bin_ directory. 
```csharp
List<string> xmlFiles = Directory.GetFiles(AppContext.BaseDirectory,"*.xml",SearchOption.TopDirectoryOnly).ToList();
xmlFiles.ForEach(xmlFile => swaggerGenOptions.IncludeXmlComments(xmlFile));
```

**Comment by Rozzemak** [comment]
> 
> 
> It can be a option to add all xml files from _bin_ directory.
> 
> ```cs
> List<string> xmlFiles = Directory.GetFiles(AppContext.BaseDirectory,"*.xml",SearchOption.TopDirectoryOnly).ToList();
> xmlFiles.ForEach(xmlFile => swaggerGenOptions.IncludeXmlComments(xmlFile));
> ```

Elegant solution. Highly configurable and simple.

**Comment by gerbenvl** [comment]
> It can be a option to add all xml files from _bin_ directory.

Nice solution. You never know what kind of files there are in the bin directory though. So would alter this a bit to grab them from the AppDomain instead:

```cs
var assemblies = AppDomain.CurrentDomain.GetAssemblies().Where(
    x => x.GetName().Name!.StartsWith(ThisAssembly.AssemblyName, StringComparison.OrdinalIgnoreCase));

foreach (var assembly in assemblies)
{
    options.IncludeXmlComments(assembly);
}
```
