### ISSUE TITLE
when using a custom IHttpControllerTypeResolver, swagger-ui stops working

### ISSUE THREAD

**Issue by stombeur** [domaindrivendev/Swashbuckle#936]
I need to deploy the same web api in two modes, limiting the number of exposed controllers in one case.
To do this, I implemented an IHttpControllerTypeResolver, extended DefaultHttpControllerTypeResolver and excluded all controllers in my own assembly except one.

When I replace the controllertyperesolver service with mine, the swagger ui does not load correctly anymore because it cannot resolve the route /api/settings/swagger. 

any ideas why this happens?

**Comment by stombeur** [comment]
never mind, this was probably something todo with customassets in a folder named swagger

**Comment by heldersepu** [comment]
Please close this issue if there is nothing to do
