### ISSUE TITLE
SwaggerUI generating documentation for System.Guid

### ISSUE THREAD

**Issue by JustinJohnWilliams** [domaindrivendev/Swashbuckle#943]
We're using Swashbuckle latest (v 6.0.0-beta90) and everything seems to be working perfectly fine for us, except for the swagger ui generation for GUID parameters.  They show up in the generated documentation as strings. I understand that GUIDs are pretty much a .NET only kind of thing, so I'd be okay with showing them in the UI as a UUID. Does anyone know how to do this?

example code:

```CSharp
/// <summary>
/// Returns a customer from the id provided
/// </summary>
/// <param name="id">UUID v4</param>
/// <returns></returns>
[HttpGet("{id:guid}")]
public IActionResult Get(Guid id)
{
      return Ok(Factory.Customers[id]);
}
```

If you notice the data type is "String" for Id: 
<img width="970" alt="screen shot 2016-11-28 at 1 53 37 pm" src="https://cloud.githubusercontent.com/assets/517113/20683578/2db5d280-b572-11e6-86ed-73bf980513dd.png">

https://github.com/domaindrivendev/Ahoy/pull/65 has a code snippet for the following in the configuration which we've implemented, and still no luck:

```CSharp
config.EnableSwagger(x =>
{
    x.MapType<Guid>(() => new Schema { type = "string", format = "uuid" });
});
```

**Comment by SJ28** [comment]
I am also looking for the very same resolution for System.GUID. It would be great if it gets incorporated soon! Desperately looking for it.

**Comment by domaindrivendev** [comment]
I think Data Type "string" is correct in this case. As far as JSON / JSON Schema is concerned "Data Type" MUST be one of the six defined types (http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2). So, it's still a "string", just with specific formatting which you've correctly included in the "format" field via _MapType_.

It's worth noting however, that "uuid" is not a supported value for "format" in the [swagger spec](http://swagger.io/specification/). So, it's not surprising that the swagger-ui tool doesn't do anything with it.

You could argue that the swagger-ui should include an additional column where it displays "format" in addition to data type, but that's an issue for the swagger-ui repo (https://github.com/swagger-api/swagger-ui) and not Swashbuckle.

**Comment by JustinJohnWilliams** [comment]
Thank you for the information, that's super helpful. I was not aware UUID was not a supported type (as well as date/time). It makes total sense to have them represented as strings in this case.
