### ISSUE TITLE
Model Property Names using Custom Json Contract Resolver

### ISSUE THREAD

**Issue by jondunning** [domaindrivendev/Swashbuckle#95]
Hi,

Cant find a way to use a custom json contract resolver with swashbuckle.

My stripped down example below;

var config = new HttpConfiguration();
config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new LowercaseUnderscoreContractResolver();
Swashbuckle.Bootstrapper.Init(config);
app.UseWebApi(config);

public class LowercaseUnderscoreContractResolver : DefaultContractResolver 
{
    protected override string ResolvePropertyName(string propertyName)
    {
        var regex = new Regex("(?!(^[A-Z]))([A-Z])");
        return regex.Replace(input, "_$2").ToLower();
    }
}

**Comment by OzBob** [comment]
Please help me decide which Interface to use, IModelFilter or ISchemaFilter

https://github.com/domaindrivendev/Swashbuckle/blob/f5f3a187e1648e818778eddbdb4e1b6e35b6d83d/Swashbuckle.Core/Application/SwaggerDocsConfig.cs#L147
says 
// NOTE: In next major version, ModelFilter will completely replace SchemaFilter

but

https://github.com/domaindrivendev/Swashbuckle/blob/07a7a247ef33ef9ba3afcd70b4e4c34937839427/README.md#transitioning-to-swashbuckle-50
says
v5
IModelFilter is now ISchemaFilter

and trying to figure out how to write a IModelFilter and looking at 
https://github.com/domaindrivendev/Swashbuckle/blob/953f9803bdf4a5051dd4ad90f8a6bc0ad8b6af3b/Swashbuckle.Core/Swagger/XmlComments/ApplyXmlTypeComments.cs
as it doesn't use ISchemaFilter yet ....

Any suggestions on how to update it's JsonSerialisationConfiguration for this type as the JsonObjectContract isn't accessible?
