### ISSUE TITLE
A simple method added to a base controller class causes 500 error

### ISSUE THREAD

**Issue by butterfieldcons** [domaindrivendev/Swashbuckle#972]
Windows 10
VS 2015 update 3
dot net core 1.1 etc.

I have a much more complex application, but simplicity is good!

I created a simple dot net core 1.1 web api.  I then create the "BaseController" class below and have the "ValuesConroller" derive from that.  This, I feel, is a fairly common practice.  All works fine until I add the simple Init() method.  this causes a 500 internal error when I try to run the application.  Remove the Init() method() and all is good.

This is nothing more than a very basic "project/new/asp net core/webapi" application.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2
{
    /// <summary>
    /// 
    /// </summary>
    public class BaseController : Controller
    {
        private int i;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="i"></param>
        public BaseController(int i)
        {
            this.i = i;
        }

        /// <summary>
        /// 
        /// </summary>
        public int init(int y)
        {
            return y;
        }
    }   
}

//////////////

    [Route("api/[controller]")]
    public class ValuesController : BaseController
    {

        public ValuesController() : base(5)
              { }

        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

**Comment by domaindrivendev** [comment]
Need more info to troubleshoot. Could you provide full details of the exception behind the 500 by navigating directly to the Swagger JSON endpoint. You may need to add the ASP.Net Core developer exception page.

**Comment by butterfieldcons** [comment]
Its fairly simple to replicate.  Create a new .net core/ASP.net Web application.  use the following base class for the 'ValuesController'.  So it should look like this.

******** change for ValuesController ********
    [Route("api/[controller]")]
    public class ValuesController : BaseController

Add this file.  Comment out the Init() method.  Just the presence of the method causes the 500 error in swashbuckle.  Expected behavior would be to see the routes exposed.  This is a fairly common coding practice.  This is the entire example.

**********  The BaseController class ***************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2
{
    /// <summary>
    /// 
    /// </summary>
    public class BaseController : Controller
    {
        private int i;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="i"></param>
        public BaseController(int i)
        {
            this.i = i;
        }

        /// <summary>
        /// 
        /// </summary>
        public int init(int y)
        {
            return y;
        }
    }   
}

******************

I was able to setup the error handling.  It produced the following

500 :
An unhandled exception occurred while processing the request.

NotSupportedException: Unbounded HTTP verbs for path 'api/Values'. Are you missing an HttpMethodAttribute?
Swashbuckle.SwaggerGen.Generator.SwaggerGenerator.CreatePathItem(IEnumerable<ApiDescription> apiDescriptions, ISchemaRegistry schemaRegistry)

Stack Query Cookies Headers
NotSupportedException: Unbounded HTTP verbs for path 'api/Values'. Are you missing an HttpMethodAttribute?

******************

Ok, so a work around is you can add [Route("bla")] and [HttpGet] to the init method above, but surely this should not be required and is quite awkward.

**Comment by domaindrivendev** [comment]
In general, you should avoid having public methods inside controller classes unless you want to expose them as an endpoints. Regardless of Swashbuckle, ASP.NET Core will discover all public controller methods and attempt to expose them over HTTP. In fact, you can demonstrate this by commenting out the "Get" method in your derived class above. Spin up your app, navigate to "/api/Values" and note how your "init" method is getting invoked over the wire - pretty dangerous if this isn't your intention!

What's the purpose of your "init" method anyway - is it part of your public API or something that just get's called internally. If it's the latter, just mark it private/protected or internal depending on how it's getting called

This is a much better practice as it prevents the possibility of accidentally exposing it and it will prevent Swashbuckle from trying to document it.

**Comment by butterfieldcons** [comment]
Thanks domain; I put on the Computer Science hat and fixed the problem.  To answer your question the randomly named init() method was an actionfilter being used to inject some context into the the controller call.  I had to make this "internal", but the other's were marked as private.

I kind of inherited this code and I was not really familiar with swashbuckle.  I'm mostly an Angular/open source programmer.   anyway, thank again; problem resolved.
