### ISSUE TITLE
Method not found: 'Swashbuckle.Application.SwaggerEnabledConfiguration 

### ISSUE THREAD

**Issue by krishnamhn009** [domaindrivendev/Swashbuckle#973]
When i am deploying on server below exception is coming
Method not found: 'Swashbuckle.Application.SwaggerEnabledConfiguration Swashbuckle.Application.HttpConfigurationExtensions.EnableSwagger(System.Web.Http.HttpConfiguration, System.Action`1<Swashbuckle.Application.SwaggerDocsConfig>)'. 

Meanwhile it is working good in local IIS.

**Comment by bootv2** [comment]
Maybe this can help you: https://github.com/domaindrivendev/Swashbuckle/issues/451

**Comment by phhlho** [comment]
I ran into this same issue. I just posted a comment on #451 on what I did to resolve it.

**Comment by rudyscoggins** [comment]
My fix for this issue came from this thread:
#781 
Different problem, but same fix

**Comment by krishnamhn009** [comment]
This is what I did to resolve it [#451](https://github.com/domaindrivendev/Swashbuckle/issues/451)

**Comment by MeltdownInteractive** [comment]
I fixed this on my local IIS by adding a binding redirect for System.Net.Http in web.config.
Just make sure the 4.2.0.0 below matches the version of the DLL in your references folder. 

```
<dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0"/>
</dependentAssembly>
```

**Comment by Cloudmersive** [comment]
That worked
