### ISSUE TITLE
Method documentation not working

### ISSUE THREAD

**Issue by Joyel** [domaindrivendev/Swashbuckle#98]
I have been having an issue where none of the method xml comments appear. When I look at the raw format, those areas are blank. However all of the model information appears! 

The api has its models and methods split into separate projects. I am using two xml files to build the documentation (one for models and one for methods). When tested with just one xml file at a time, only the model documentation works. 
Am I missing something with the method documentation? 

This is method documentation:
/// <summary> 
/// Lots of somethings going on here
/// </summary>
/// <param name="request"> Model Something</param>
/// <response code="400"> Invalid stuff</response>
[ActionName("Something")]
public SomeResponse GetSomething([FromUri] SomeRequest request)

And this is a property documentation which appears:
 /// <summary>
/// The list of somethings used to create something. 
/// </summary>
[Name("Something")]
public List<Something> Somethings { get; set; }

**Comment by tillig** [comment]
Not sure if this helps, but I found I needed to add all of the XML documentation files individually. With one of the more recent updates the docs stopped using `ApiExplorer` and switched to manual inclusion.

    var binDirectory = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, AppDomain.CurrentDomain.RelativeSearchPath);
    var xmlDocs = Directory.GetFiles(binDirectory, "*.xml", SearchOption.AllDirectories)
    SwaggerSpecConfig.Customize(c =>
    {
      foreach (var path in xmlDocs)
      {
        c.IncludeXmlComments(path);
      }
    });

**Comment by domaindrivendev** [comment]
@tillig is correct - Swashbuckle needs to be told about all XML files that contain relevant comments. Closing as this should solve the issue
