### ISSUE TITLE
Setting the API version to include a dot "." causes a 404 in IIS on the JSON

### ISSUE THREAD

**Issue by novabe** [domaindrivendev/Swashbuckle#980]
Specifically, in SwaggerConfig.cs:

```csharp
// This works fine in IIS Express and in IIS, is also the default
c.SingleApiVersion("v1", "MyApplication");

// Also works fine IIS Express + IIS
c.SingleApiVersion("1", "MyApplication");

// Works in IIS Express, but not in IIS!
c.SingleApiVersion("1.0", "MyApplication");
```
The error I get is a 404 on the XHR request that tries to read the JSON:

> Can't read swagger JSON from http://localhost:80/swagger/1.0

This issue was encountered in Swashbuckle 5.4.0 and 5.5.3. IIS 8.5.9600.16384.

**Comment by brazabr** [comment]
This is not a Swashbuckle bug, it is an IIS bug.
http://stackoverflow.com/questions/11728846/dots-in-url-causes-404-with-asp-net-mvc-and-iis

**Comment by novabe** [comment]
@brazabr Good catch, that was indeed it.
