### ISSUE TITLE
incorrect long number in swagger ui

### ISSUE THREAD

**Issue by arielcloud** [domaindrivendev/Swashbuckle#981]
I'm using swashbuckle 6.0.0beta902 in my asp.net core 1.1 project (didn't succeeded to upgrade to Swashbuckle.AspNetCore (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/278) )

when I excute get for account object with contractId field (type long) I can see that my app return correct json, but in your UI - the number isn't correct. screenshot attached.

![image](https://cloud.githubusercontent.com/assets/12379498/22107221/48a86a7e-de55-11e6-8951-6a0bdde2bf19.png)

**Comment by arielcloud** [comment]
now, I succeeded switch to Swashbuckle.AspNetCore and the problem still exists.

**Comment by domaindrivendev** [comment]
Swashbuckle is a Swagger generator with an external UI project bundled in for convenience. You need to log this issue with the swagger-ui folks - https://github.com/swagger-api/swagger-ui. Although, they may well point you to this being a JavaScript precision problem - http://stackoverflow.com/questions/15869275/json-not-converting-long-numbers-appropriately.. Either way, it's no a SB issue.

**Comment by arielcloud** [comment]
very helpful! thanks!
