### ISSUE TITLE
Microsoft API Versioning Support

### ISSUE THREAD

**Issue by cecilphillip** [domaindrivendev/Swashbuckle#984]
I dug around for a little while but couldn't find an answer to this question anywhere.

Does Swashbuckle support getting API versions from the Microsoft.AspNet.WebApi.Versioning package?

**Comment by marazt** [comment]
Hi. I think it is not possible.

In case of **Swashbuckle.AspNetCore**, the combination with **Microsoft.AspNet.WebApi.Versioning** can be possible via definition of custom IControllerModelConvention (https://github.com/domaindrivendev/Swashbuckle.AspNetCore#generate-multiple-swagger-documents) and use of **ApiVersion** attribute. But this solution will not work when you use multiple ApiVersion attributes on a single action.

**Comment by cecilphillip** [comment]
There's an existing issue on the API versioning repo. I'll continue to track it [there](https://github.com/Microsoft/aspnet-api-versioning/issues/60)
