### ISSUE TITLE
Update to newest version of Swagger UI to support Password Flow

### ISSUE THREAD

**Issue by pdusen** [domaindrivendev/Swashbuckle#986]
Since https://github.com/domaindrivendev/Swashbuckle/issues/202 is closed and is not receiving any responses from @domaindrivendev, I'm trying to draw attention to this by opening a new issue.

Password Flow support has landed in swagger-ui Master: https://github.com/swagger-api/swagger-ui/pull/2397

Please update Swashbuckle to make use of the newest version of swagger-ui.

**Comment by UnrealKazu** [comment]
Pull request #974 could be of interest for this issue. This essentially updates Swagger UI to 2.2.10, which has the new password flow functionality. I too am eager for this to be supported in Swashbuckle.

Though, I am not sure to what extend Swashbuckle itself would need some tinkering in order for password flow to function properly. This, as Swashbuckle provides config settings for the grant type which should be used in Swagger UI.

**Comment by aposashenko-distillery** [comment]
We're also interested in the password flow.

P.S. thank you guys for your work implementing so cool tool!

**Comment by VenomAV** [comment]
I have just compiled the latest commit of master and I verified that OAuth2 password flow works correctly. Does anyone know when the new version of the NuGet package will be released?
The parameters of EnableOAuth2Support method are useless since the new version of Swagger UI does not use those configurations any more (at least for the password flow).

**Comment by heldersepu** [comment]
It seem that the owner is busy with other projects...
But there is a call out for maintainers, see: #1053

**Comment by VenomAV** [comment]
@heldersepu I saw the call for maintainers and I would like to be helpful. However, at the moment, I do not have enough insights on the inner workings of the library and the overall design to be of any real help.

**Comment by clabnet** [comment]
I am very interested to this update.

**Comment by Astimus** [comment]
I am very interested too. Authorization works great. But after there is no authorization header in requests to api. Is this will be solved after upgrade?

**Comment by heldersepu** [comment]
All we need is a new version of the NuGet package...
Anyone in a rush I will recommend the solution from VenomAV: https://github.com/domaindrivendev/Swashbuckle/issues/986#issuecomment-299022132

**Comment by heldersepu** [comment]
I've been working on my fork, I updated to the latest Swagger-UI (3.x), here is how it looks on one of my projects:
http://turoapi.azurewebsites.net/swagger/ui/index

If you have time I could use your help testing it, you can get my version from MyGet:
https://www.myget.org/gallery/swashbuckle

**Comment by domaindrivendev** [comment]
SB v5.6.0 ships with swagger-ui 2.2.10 and is now available on Nuget. I believe this resolves the issue. @pdusen - please let me know if this isn't the case. Thanks

**Comment by UnrealKazu** [comment]
@domaindrivendev It seems like the way authorization settings are configured in Swagger UI have been changed. This means that the corresponding `EnableOAuth2Support` method is no longer working, like @VenomAV already mentioned.

So this isn't a clear-cut 'upgrade Swagger-UI and everything is fixed'-solution, unfortunately. It does seem that there isn't too much needed to make Swashbuckle work with those new settings, though.

**Comment by ai-fwd** [comment]
@UnrealKazu if possible can you elaborate on the changes required to make Swashbuckle work with the new settings so it's a little more turnkey for the rest of us?
