### ISSUE TITLE
How to to display response subtypes description in Model/Schema view

### ISSUE THREAD

**Issue by Medii** [domaindrivendev/Swashbuckle#987]
The return type of one my GET APIs is List<baseclass>.
Is it possible to display description of all possible subclass types of response list items in the swagger UI?
(https://github.com/swagger-api/swagger-ui/issues/300)

**Comment by heldersepu** [comment]
Here is a GET that the return is a List:
http://offleaseonly.azurewebsites.net/swagger/ui/index#!/Cars/Cars_GetNew

I do see everything in the description ...
Do you have a sample project to reproduce your issue?

**Comment by Medii** [comment]
:-) It was already fix by swagger-ui team.

https://github.com/swagger-api/swagger-ui/issues/1430#issuecomment-287913124
