### ISSUE TITLE
Specify https in ASP.NET Core

### ISSUE THREAD

**Issue by siberianguy** [domaindrivendev/Swashbuckle#989]
How can I specify https schema in the Core version of Swashbuckle? In old ASP.NET I could do 

```
.EnableSwagger(c =>
{
c.Schemes(new[] { "https" });
}
```
but I don't see anything similar as part of AddSwaggerGen

**Comment by heldersepu** [comment]
You are posting on the wrong project, please close this issue and reopen it here:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore
