### ISSUE TITLE
application/x-www-form-urlencoded is ignored in ASP.NET Core

### ISSUE THREAD

**Issue by alexidsa** [domaindrivendev/Swashbuckle#990]
I have an Action that consumes application/x-www-form-urlencoded:

```
[HttpPost("~/connect/token"), Consumes("application/x-www-form-urlencoded")]
public async Task<IActionResult> Exchange([FromBody]OpenIdConnectRequest request)
{
   ..
}
```

But Swashbuckle generates empty array for Consumes property. If I change it to application/json, consumes array is generated properly.

Is it a bug related to application/x-www-form-urlencoded or I need to configure Swashbuckle additionally to support this application type?

**Comment by alexidsa** [comment]
There was a similar issue reported long time ago. I'm working on fixing it in this PR: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/292

**Comment by Thuran** [comment]
just replace FromBody with FromForm
