### ISSUE TITLE
apiVersion required even for single api

### ISSUE THREAD

**Issue by scovel** [domaindrivendev/Swashbuckle#992]
We don't version our APIs, we version at the service level.  We also need to integrate with an internal portal that aggregates all the services.  It expects the swagger json endpoint to be:

http://myservice/swagger.json  or it could be http://myservice/swagger

I have been able to (fight) swashbuckle into delivering the json by using the following:

            configuration
                .EnableSwagger("{apiVersion}", c =>
                {
                    c.RootUrl(req => ResolveBasePath(req)); //fix path resolution behind the load balance point

                    c.SingleApiVersion("swagger.json", apiName);  //change to swagger
                })

The json is delivered. To get the UI to work I did the following:

            .EnableSwaggerUi(c =>
                {
                    c.DisableValidator();//disable validator tag
                });

The UI comes up, the json is delivered, looks good.  When I go to "Try It out!", the call fails with the following exception:

{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Unknown API version - values",
  "ExceptionType": "Swashbuckle.Swagger.UnknownApiVersion",
  "StackTrace": "   at Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)\r\n   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)"
}

Seems that the UI depends on that version, while the json doesn't really care.  Is there a way to disable the need for ApiVersion when you are using SingleApiVersion?

BTW, I love Swagger/Swashbuckle.  I'm unhappy with our internal portal....

Thanks,

Sean

**Comment by MikeFH** [comment]
It could be nice if the `{apiVersion}` wasn't necessary at all in the urlTemplate parameter of `EnableSwagger()`. Maybe this can be done in specifying a default in the call to `MapHttpRoute` during setup. This way we could specify the real version in the call to `SingleApiVersion()` and use a constant url template (like "swagger") to download the schema.

**Comment by domaindrivendev** [comment]
Whether you use versioning or not, it's a required field in a Swagger document (as per the spec). Hence, SB uses version as part of the document resource identifier URL. I don't have a strong desire to make this optional.

If you're goal is to serve the V1 document at an alias URL to support tooling, then I would use a "URL Rewrite Rule" - supported by all modern web servers incl. IIS
